function [X2C] = update_t2c_proj2(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys,shift)
   
    % H(CCS) intermediates          
    h1B_ov = sys.fb_ov...
             +einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me')...
             +einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me');
         
    h1B_oo = sys.fb_oo...
             +einsum_kg(h1B_ov,t1b,'me,ei->mi')...
             +einsum_kg(sys.vB_oovo,t1a,'nmfi,fn->mi')...
             +einsum_kg(sys.vC_ooov,t1b,'mnif,fn->mi');
         
    h1B_vv = sys.fb_vv...
             -einsum_kg(h1B_ov,t1b,'me,am->ae')...
             +einsum_kg(sys.vB_ovvv,t1a,'nafe,fn->ae')...
             +einsum_kg(sys.vC_vovv,t1b,'anef,fn->ae');
          
    h2C_oooo = sys.vC_oooo...
                +einsum_kg(sys.vC_ooov,t1b,'mnie,ej->mnij')...
	    			-einsum_kg(sys.vC_ooov,t1b,'mnje,ei->mnij')...
                +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,ei->mnif'),t1b,'mnif,fj->mnij'); 
            
    h2C_vvvv = sys.vC_vvvv...
                -einsum_kg(sys.vC_ovvv,t1b,'mbef,am->abef')...
	     			+einsum_kg(sys.vC_ovvv,t1b,'maef,bm->abef')...
                +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,bn->mbef'),t1b,'mbef,am->abef');
                
    h2B_ovvo = sys.vB_ovvo ...
               +einsum_kg(sys.vB_ovvv,t1b,'maef,fi->maei')...
               -einsum_kg(sys.vB_oovo,t1b,'mnei,an->maei')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->maei');
           
    h2C_voov = sys.vC_voov ...
               -einsum_kg(sys.vC_oovo,t1b,'mnei,an->amie')...
               +einsum_kg(sys.vC_vovv,t1b,'amfe,fi->amie')...
               -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->amie');
           
    % <ijab|H(CCS)|0> intermediates - need weights of 0.5 to compensate diagrams that do not have A(ij) or A(ab)
    I2C_ovoo = sys.vC_ovoo ...
               -0.5*einsum_kg(sys.vC_oooo,t1b,'mnij,bn->mbij')...
               +einsum_kg(einsum_kg(sys.vC_ovvv,t1b,'mbef,ei->mbif'),t1b,'mbif,fj->mbij')...
               -0.5*einsum_kg(einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fj->mnej'),t1b,'mnej,ei->mnij'),t1b,'mnij,bn->mbij')...
               +einsum_kg(sys.vC_ovov,t1b,'mbif,fj->mbij')...
                    -einsum_kg(sys.vC_ovov,t1b,'mbjf,fi->mbij');
                
    I2C_vvvo = sys.vC_vvvo...
               +0.5*einsum_kg(sys.vC_vvvv,t1b,'abef,fj->abej')...
               +einsum_kg(einsum_kg(sys.vC_oovo,t1b,'mnej,am->anej'),t1b,'anej,bn->abej');
             
    % VT2 intermediates - need weights of 0.5 to compensate diagrams that do not have A(ij) or A(ab)
    VT2_1B_oo = 0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,efin->mi') + einsum_kg(sys.vB_oovv,t2b,'nmfe,feni->mi');
    VT2_1B_vv = -0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,afmn->ae') - einsum_kg(sys.vB_oovv,t2b,'nmfe,fanm->ae');
    VT2_2C_oooo = 0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,efij->mnij');
    VT2_2B_ovvo = einsum_kg(sys.vB_oovv,t2c,'mnef,afin->maei') + 0.5*einsum_kg(sys.vA_oovv,t2b,'mnef,fani->maei');
    VT2_2C_voov = 0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,afin->amie');
    
    % contraction intermdiates
    I1B_oo = h1B_oo + VT2_1B_oo;
    I1B_vv = h1B_vv + VT2_1B_vv;
    I2C_voov = h2C_voov + VT2_2C_voov;
    I2B_ovvo = h2B_ovvo + VT2_2B_ovvo;
    I2C_oooo = h2C_oooo + VT2_2C_oooo;
    
    % <ijab| H(CCS) | 0> + <ijab| (H(CCS)T2)_C |0> + <ijab| 0.5*(H(CCS)T2^2)_C |0>
    D1 = -einsum_kg(I2C_ovoo,t1b,'mbij,am->abij'); 
    
    D2 = einsum_kg(I2C_vvvo,t1b,'abej,ei->abij');
    
    D3 = einsum_kg(I1B_vv,t2c,'ae,ebij->abij');
    
    D4 = -einsum_kg(I1B_oo,t2c,'mi,abmj->abij');
    
    D5 = einsum_kg(I2C_voov,t2c,'amie,ebmj->abij');
    
    D6 = einsum_kg(I2B_ovvo,t2b,'maei,ebmj->abij');
    
    D7 = 0.5*einsum_kg(h2C_vvvv,t2c,'abef,efij->abij');
    
    D8 = 0.5*einsum_kg(I2C_oooo,t2c,'mnij,abmn->abij');
    
    % diagrams that have A(ab)
    D13 = D1 + D3;
    D13 = D13 - permute(D13,[2,1,3,4]);
    
    % diagrams that have A(ij)
    D24 = D2 + D4;
    D24 = D24 - permute(D24,[1,2,4,3]);
        
    % diagrams that have A(ab)A(ij)
    D56 = D5 + D6;
    D56 = D56 - permute(D56,[2,1,3,4]) - permute(D56,[1,2,4,3]) + permute(D56,[2,1,4,3]);
    
    % total contribution
    X2C = sys.vC_vvoo + D13 + D24 + D56 + D7 + D8;
    
    % CCSDT part
    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;

    H1B.ov = h1B_ov;
    H1A.ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');
    H2C.vovv = sys.vC_vovv - einsum_kg(sys.vC_oovv,t1b,'mnfe,an->amef');
    H2C.ooov = sys.vC_ooov + einsum_kg(sys.vC_oovv,t1b,'mnfe,fi->mnie');
    H2B.ovvv = sys.vB_ovvv - einsum_kg(sys.vB_oovv,t1b,'mnfe,an->mafe');
    H2B.oovo = sys.vB_oovo + einsum_kg(sys.vB_oovv,t1b,'nmef,fi->nmei');
    

D1 = +einsum_kg(H1A.ov(hA,pA),T3C.pPphHH,'me,eAbmIJ->AbIJ')...
+einsum_kg(H1A.ov(hA,PA),T3C.PPphHH,'mE,EAbmIJ->AbIJ')...
+einsum_kg(H1A.ov(HA,pA),T3C.pPpHHH,'Me,eAbMIJ->AbIJ')...
+einsum_kg(H1A.ov(HA,PA),T3C.PPpHHH,'ME,EAbMIJ->AbIJ');

D2 = +einsum_kg(H1B.ov(hB,pB),T3D.PpphHH,'me,AbemIJ->AbIJ')...
-einsum_kg(H1B.ov(hB,PB),T3D.PPphHH,'mE,AEbmIJ->AbIJ')...
+einsum_kg(H1B.ov(HB,pB),T3D.PppHHH,'Me,AbeIJM->AbIJ')...
-einsum_kg(H1B.ov(HB,PB),T3D.PPpHHH,'ME,AEbIJM->AbIJ');

D3 = +0.5*einsum_kg(H2C.vovv(PB,hB,pB,pB),T3D.ppphHH,'Anef,ebfnIJ->AbIJ')...
+einsum_kg(H2C.vovv(PB,hB,PB,pB),T3D.PpphHH,'AnEf,EbfnIJ->AbIJ')...
-0.5*einsum_kg(H2C.vovv(PB,hB,PB,PB),T3D.PPphHH,'AnEF,EFbnIJ->AbIJ')...
+0.5*einsum_kg(H2C.vovv(PB,HB,pB,pB),T3D.pppHHH,'ANef,ebfIJN->AbIJ')...
+einsum_kg(H2C.vovv(PB,HB,PB,pB),T3D.PppHHH,'ANEf,EbfIJN->AbIJ')...
-0.5*einsum_kg(H2C.vovv(PB,HB,PB,PB),T3D.PPpHHH,'ANEF,EFbIJN->AbIJ')...
+0.5*einsum_kg(H2C.vovv(pB,hB,pB,pB),T3D.PpphHH,'bnef,AefnIJ->AbIJ')...
-einsum_kg(H2C.vovv(pB,hB,PB,pB),T3D.PPphHH,'bnEf,EAfnIJ->AbIJ')...
-0.5*einsum_kg(H2C.vovv(pB,hB,PB,PB),T3D.PPPhHH,'bnEF,EAFnIJ->AbIJ')...
+0.5*einsum_kg(H2C.vovv(pB,HB,pB,pB),T3D.PppHHH,'bNef,AefIJN->AbIJ')...
-einsum_kg(H2C.vovv(pB,HB,PB,pB),T3D.PPpHHH,'bNEf,EAfIJN->AbIJ')...
-0.5*einsum_kg(H2C.vovv(pB,HB,PB,PB),T3D.PPPHHH,'bNEF,EAFIJN->AbIJ');

D4 = +einsum_kg(H2B.ovvv(hA,PB,pA,pB),T3C.ppphHH,'nAfe,febnIJ->AbIJ')...
+einsum_kg(H2B.ovvv(hA,PB,pA,PB),T3C.pPphHH,'nAfE,fEbnIJ->AbIJ')...
+einsum_kg(H2B.ovvv(hA,PB,PA,pB),T3C.PpphHH,'nAFe,FebnIJ->AbIJ')...
+einsum_kg(H2B.ovvv(hA,PB,PA,PB),T3C.PPphHH,'nAFE,FEbnIJ->AbIJ')...
+einsum_kg(H2B.ovvv(HA,PB,pA,pB),T3C.pppHHH,'NAfe,febNIJ->AbIJ')...
+einsum_kg(H2B.ovvv(HA,PB,pA,PB),T3C.pPpHHH,'NAfE,fEbNIJ->AbIJ')...
+einsum_kg(H2B.ovvv(HA,PB,PA,pB),T3C.PppHHH,'NAFe,FebNIJ->AbIJ')...
+einsum_kg(H2B.ovvv(HA,PB,PA,PB),T3C.PPpHHH,'NAFE,FEbNIJ->AbIJ')...
+einsum_kg(H2B.ovvv(hA,pB,pA,pB),T3C.pPphHH,'nbfe,fAenIJ->AbIJ')...
-einsum_kg(H2B.ovvv(hA,pB,pA,PB),T3C.pPPhHH,'nbfE,fEAnIJ->AbIJ')...
+einsum_kg(H2B.ovvv(hA,pB,PA,pB),T3C.PPphHH,'nbFe,FAenIJ->AbIJ')...
-einsum_kg(H2B.ovvv(hA,pB,PA,PB),T3C.PPPhHH,'nbFE,FEAnIJ->AbIJ')...
+einsum_kg(H2B.ovvv(HA,pB,pA,pB),T3C.pPpHHH,'Nbfe,fAeNIJ->AbIJ')...
-einsum_kg(H2B.ovvv(HA,pB,pA,PB),T3C.pPPHHH,'NbfE,fEANIJ->AbIJ')...
+einsum_kg(H2B.ovvv(HA,pB,PA,pB),T3C.PPpHHH,'NbFe,FAeNIJ->AbIJ')...
-einsum_kg(H2B.ovvv(HA,pB,PA,PB),T3C.PPPHHH,'NbFE,FEANIJ->AbIJ');

D5 = +0.5*einsum_kg(H2C.ooov(hB,hB,HB,pB),T3D.PpphhH,'mnIf,AbfmnJ->AbIJ')...
-0.5*einsum_kg(H2C.ooov(hB,hB,HB,PB),T3D.PPphhH,'mnIF,AFbmnJ->AbIJ')...
-einsum_kg(H2C.ooov(HB,hB,HB,pB),T3D.PpphHH,'MnIf,AbfnMJ->AbIJ')...
+einsum_kg(H2C.ooov(HB,hB,HB,PB),T3D.PPphHH,'MnIF,AFbnMJ->AbIJ')...
-0.5*einsum_kg(H2C.ooov(HB,HB,HB,pB),T3D.PppHHH,'MNIf,AbfMJN->AbIJ')...
+0.5*einsum_kg(H2C.ooov(HB,HB,HB,PB),T3D.PPpHHH,'MNIF,AFbMJN->AbIJ');
D5 = D5 - permute(D5,[1,2,4,3]);

D6 = -einsum_kg(H2B.oovo(hA,hB,pA,HB),T3C.pPphhH,'nmfI,fAbnmJ->AbIJ')...
-einsum_kg(H2B.oovo(hA,hB,PA,HB),T3C.PPphhH,'nmFI,FAbnmJ->AbIJ')...
-einsum_kg(H2B.oovo(hA,HB,pA,HB),T3C.pPphHH,'nMfI,fAbnMJ->AbIJ')...
-einsum_kg(H2B.oovo(hA,HB,PA,HB),T3C.PPphHH,'nMFI,FAbnMJ->AbIJ')...
-einsum_kg(H2B.oovo(HA,hB,pA,HB),T3C.pPpHhH,'NmfI,fAbNmJ->AbIJ')...
-einsum_kg(H2B.oovo(HA,hB,PA,HB),T3C.PPpHhH,'NmFI,FAbNmJ->AbIJ')...
-einsum_kg(H2B.oovo(HA,HB,pA,HB),T3C.pPpHHH,'NMfI,fAbNMJ->AbIJ')...
-einsum_kg(H2B.oovo(HA,HB,PA,HB),T3C.PPpHHH,'NMFI,FAbNMJ->AbIJ');
D6 = D6 - permute(D6,[1,2,4,3]);
    
    X2C_PpHH = (D1 + D2 + D3 + D4 + D5 + D6);
    X2C(PB,pB,HB,HB) = X2C(PB,pB,HB,HB) + X2C_PpHH;


end