function [X2C] = update_t2c_proj8(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys,shift)
   
    % H(CCS) intermediates          
    h1B_ov = sys.fb_ov...
             +einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me')...
             +einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me');
         
    h1B_oo = sys.fb_oo...
             +einsum_kg(h1B_ov,t1b,'me,ei->mi')...
             +einsum_kg(sys.vB_oovo,t1a,'nmfi,fn->mi')...
             +einsum_kg(sys.vC_ooov,t1b,'mnif,fn->mi');
         
    h1B_vv = sys.fb_vv...
             -einsum_kg(h1B_ov,t1b,'me,am->ae')...
             +einsum_kg(sys.vB_ovvv,t1a,'nafe,fn->ae')...
             +einsum_kg(sys.vC_vovv,t1b,'anef,fn->ae');
          
    h2C_oooo = sys.vC_oooo...
                +einsum_kg(sys.vC_ooov,t1b,'mnie,ej->mnij')...
	    			-einsum_kg(sys.vC_ooov,t1b,'mnje,ei->mnij')...
                +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,ei->mnif'),t1b,'mnif,fj->mnij'); 
            
    h2C_vvvv = sys.vC_vvvv...
                -einsum_kg(sys.vC_ovvv,t1b,'mbef,am->abef')...
	     			+einsum_kg(sys.vC_ovvv,t1b,'maef,bm->abef')...
                +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,bn->mbef'),t1b,'mbef,am->abef');
                
    h2B_ovvo = sys.vB_ovvo ...
               +einsum_kg(sys.vB_ovvv,t1b,'maef,fi->maei')...
               -einsum_kg(sys.vB_oovo,t1b,'mnei,an->maei')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->maei');
           
    h2C_voov = sys.vC_voov ...
               -einsum_kg(sys.vC_oovo,t1b,'mnei,an->amie')...
               +einsum_kg(sys.vC_vovv,t1b,'amfe,fi->amie')...
               -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->amie');
           
    % <ijab|H(CCS)|0> intermediates - need weights of 0.5 to compensate diagrams that do not have A(ij) or A(ab)
    I2C_ovoo = sys.vC_ovoo ...
               -0.5*einsum_kg(sys.vC_oooo,t1b,'mnij,bn->mbij')...
               +einsum_kg(einsum_kg(sys.vC_ovvv,t1b,'mbef,ei->mbif'),t1b,'mbif,fj->mbij')...
               -0.5*einsum_kg(einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fj->mnej'),t1b,'mnej,ei->mnij'),t1b,'mnij,bn->mbij')...
               +einsum_kg(sys.vC_ovov,t1b,'mbif,fj->mbij')...
                    -einsum_kg(sys.vC_ovov,t1b,'mbjf,fi->mbij');
                
    I2C_vvvo = sys.vC_vvvo...
               +0.5*einsum_kg(sys.vC_vvvv,t1b,'abef,fj->abej')...
               +einsum_kg(einsum_kg(sys.vC_oovo,t1b,'mnej,am->anej'),t1b,'anej,bn->abej');
             
    % VT2 intermediates - need weights of 0.5 to compensate diagrams that do not have A(ij) or A(ab)
    VT2_1B_oo = 0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,efin->mi') + einsum_kg(sys.vB_oovv,t2b,'nmfe,feni->mi');
    VT2_1B_vv = -0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,afmn->ae') - einsum_kg(sys.vB_oovv,t2b,'nmfe,fanm->ae');
    VT2_2C_oooo = 0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,efij->mnij');
    VT2_2B_ovvo = einsum_kg(sys.vB_oovv,t2c,'mnef,afin->maei') + 0.5*einsum_kg(sys.vA_oovv,t2b,'mnef,fani->maei');
    VT2_2C_voov = 0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,afin->amie');
    
    % contraction intermdiates
    I1B_oo = h1B_oo + VT2_1B_oo;
    I1B_vv = h1B_vv + VT2_1B_vv;
    I2C_voov = h2C_voov + VT2_2C_voov;
    I2B_ovvo = h2B_ovvo + VT2_2B_ovvo;
    I2C_oooo = h2C_oooo + VT2_2C_oooo;
    
    % <ijab| H(CCS) | 0> + <ijab| (H(CCS)T2)_C |0> + <ijab| 0.5*(H(CCS)T2^2)_C |0>
    D1 = -einsum_kg(I2C_ovoo,t1b,'mbij,am->abij'); 
    
    D2 = einsum_kg(I2C_vvvo,t1b,'abej,ei->abij');
    
    D3 = einsum_kg(I1B_vv,t2c,'ae,ebij->abij');
    
    D4 = -einsum_kg(I1B_oo,t2c,'mi,abmj->abij');
    
    D5 = einsum_kg(I2C_voov,t2c,'amie,ebmj->abij');
    
    D6 = einsum_kg(I2B_ovvo,t2b,'maei,ebmj->abij');
    
    D7 = 0.5*einsum_kg(h2C_vvvv,t2c,'abef,efij->abij');
    
    D8 = 0.5*einsum_kg(I2C_oooo,t2c,'mnij,abmn->abij');
    
    % diagrams that have A(ab)
    D13 = D1 + D3;
    D13 = D13 - permute(D13,[2,1,3,4]);
    
    % diagrams that have A(ij)
    D24 = D2 + D4;
    D24 = D24 - permute(D24,[1,2,4,3]);
        
    % diagrams that have A(ab)A(ij)
    D56 = D5 + D6;
    D56 = D56 - permute(D56,[2,1,3,4]) - permute(D56,[1,2,4,3]) + permute(D56,[2,1,4,3]);
    
    % total contribution
    X2C = sys.vC_vvoo + D13 + D24 + D56 + D7 + D8;
    
    % CCSDT part
    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;

    H1B.ov = h1B_ov;
    H1A.ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');
    H2C.vovv = sys.vC_vovv - einsum_kg(sys.vC_oovv,t1b,'mnfe,an->amef');
    H2C.ooov = sys.vC_ooov + einsum_kg(sys.vC_oovv,t1b,'mnfe,fi->mnie');
    H2B.ovvv = sys.vB_ovvv - einsum_kg(sys.vB_oovv,t1b,'mnfe,an->mafe');
    H2B.oovo = sys.vB_oovo + einsum_kg(sys.vB_oovv,t1b,'nmef,fi->nmei');
    

D1 = +einsum_kg(H1A.ov(hA,pA),T3C.ppphhH,'me,eabmiJ->abiJ')...
+einsum_kg(H1A.ov(hA,PA),T3C.PpphhH,'mE,EabmiJ->abiJ')...
+einsum_kg(H1A.ov(HA,pA),T3C.pppHhH,'Me,eabMiJ->abiJ')...
+einsum_kg(H1A.ov(HA,PA),T3C.PppHhH,'ME,EabMiJ->abiJ');

D2 = -einsum_kg(H1B.ov(hB,pB),T3D.ppphhH,'me,abeimJ->abiJ')...
-einsum_kg(H1B.ov(hB,PB),T3D.PpphhH,'mE,EabimJ->abiJ')...
+einsum_kg(H1B.ov(HB,pB),T3D.ppphHH,'Me,abeiJM->abiJ')...
+einsum_kg(H1B.ov(HB,PB),T3D.PpphHH,'ME,EabiJM->abiJ');

D3 = -0.5*einsum_kg(H2C.vovv(pB,hB,pB,pB),T3D.ppphhH,'anef,ebfinJ->abiJ')...
-einsum_kg(H2C.vovv(pB,hB,PB,pB),T3D.PpphhH,'anEf,EbfinJ->abiJ')...
+0.5*einsum_kg(H2C.vovv(pB,hB,PB,PB),T3D.PPphhH,'anEF,EFbinJ->abiJ')...
+0.5*einsum_kg(H2C.vovv(pB,HB,pB,pB),T3D.ppphHH,'aNef,ebfiJN->abiJ')...
+einsum_kg(H2C.vovv(pB,HB,PB,pB),T3D.PpphHH,'aNEf,EbfiJN->abiJ')...
-0.5*einsum_kg(H2C.vovv(pB,HB,PB,PB),T3D.PPphHH,'aNEF,EFbiJN->abiJ');
D3 = D3 - permute(D3,[2,1,3,4]);

D4 = +einsum_kg(H2B.ovvv(hA,pB,pA,pB),T3C.ppphhH,'nafe,febniJ->abiJ')...
+einsum_kg(H2B.ovvv(hA,pB,pA,PB),T3C.pPphhH,'nafE,fEbniJ->abiJ')...
+einsum_kg(H2B.ovvv(hA,pB,PA,pB),T3C.PpphhH,'naFe,FebniJ->abiJ')...
+einsum_kg(H2B.ovvv(hA,pB,PA,PB),T3C.PPphhH,'naFE,FEbniJ->abiJ')...
+einsum_kg(H2B.ovvv(HA,pB,pA,pB),T3C.pppHhH,'Nafe,febNiJ->abiJ')...
+einsum_kg(H2B.ovvv(HA,pB,pA,PB),T3C.pPpHhH,'NafE,fEbNiJ->abiJ')...
+einsum_kg(H2B.ovvv(HA,pB,PA,pB),T3C.PppHhH,'NaFe,FebNiJ->abiJ')...
+einsum_kg(H2B.ovvv(HA,pB,PA,PB),T3C.PPpHhH,'NaFE,FEbNiJ->abiJ');
D4 = D4 - permute(D4,[2,1,3,4]);

D5 = +0.5*einsum_kg(H2C.ooov(hB,hB,hB,pB),T3D.ppphhH,'mnif,abfmnJ->abiJ')...
+0.5*einsum_kg(H2C.ooov(hB,hB,hB,PB),T3D.PpphhH,'mniF,FabmnJ->abiJ')...
-einsum_kg(H2C.ooov(HB,hB,hB,pB),T3D.ppphHH,'Mnif,abfnMJ->abiJ')...
-einsum_kg(H2C.ooov(HB,hB,hB,PB),T3D.PpphHH,'MniF,FabnMJ->abiJ')...
-0.5*einsum_kg(H2C.ooov(HB,HB,hB,pB),T3D.pppHHH,'MNif,abfMJN->abiJ')...
-0.5*einsum_kg(H2C.ooov(HB,HB,hB,PB),T3D.PppHHH,'MNiF,FabMJN->abiJ')...
+0.5*einsum_kg(H2C.ooov(hB,hB,HB,pB),T3D.ppphhh,'mnJf,abfmin->abiJ')...
+0.5*einsum_kg(H2C.ooov(hB,hB,HB,PB),T3D.Ppphhh,'mnJF,Fabmin->abiJ')...
+einsum_kg(H2C.ooov(HB,hB,HB,pB),T3D.ppphhH,'MnJf,abfinM->abiJ')...
+einsum_kg(H2C.ooov(HB,hB,HB,PB),T3D.PpphhH,'MnJF,FabinM->abiJ')...
-0.5*einsum_kg(H2C.ooov(HB,HB,HB,pB),T3D.ppphHH,'MNJf,abfiMN->abiJ')...
-0.5*einsum_kg(H2C.ooov(HB,HB,HB,PB),T3D.PpphHH,'MNJF,FabiMN->abiJ');

D6 = -einsum_kg(H2B.oovo(hA,hB,pA,hB),T3C.ppphhH,'nmfi,fabnmJ->abiJ')...
-einsum_kg(H2B.oovo(hA,hB,PA,hB),T3C.PpphhH,'nmFi,FabnmJ->abiJ')...
-einsum_kg(H2B.oovo(hA,HB,pA,hB),T3C.ppphHH,'nMfi,fabnMJ->abiJ')...
-einsum_kg(H2B.oovo(hA,HB,PA,hB),T3C.PpphHH,'nMFi,FabnMJ->abiJ')...
-einsum_kg(H2B.oovo(HA,hB,pA,hB),T3C.pppHhH,'Nmfi,fabNmJ->abiJ')...
-einsum_kg(H2B.oovo(HA,hB,PA,hB),T3C.PppHhH,'NmFi,FabNmJ->abiJ')...
-einsum_kg(H2B.oovo(HA,HB,pA,hB),T3C.pppHHH,'NMfi,fabNMJ->abiJ')...
-einsum_kg(H2B.oovo(HA,HB,PA,hB),T3C.PppHHH,'NMFi,FabNMJ->abiJ')...
+einsum_kg(H2B.oovo(hA,hB,pA,HB),T3C.ppphhh,'nmfJ,fabnmi->abiJ')...
+einsum_kg(H2B.oovo(hA,hB,PA,HB),T3C.Ppphhh,'nmFJ,Fabnmi->abiJ')...
-einsum_kg(H2B.oovo(hA,HB,pA,HB),T3C.ppphhH,'nMfJ,fabniM->abiJ')...
-einsum_kg(H2B.oovo(hA,HB,PA,HB),T3C.PpphhH,'nMFJ,FabniM->abiJ')...
+einsum_kg(H2B.oovo(HA,hB,pA,HB),T3C.pppHhh,'NmfJ,fabNmi->abiJ')...
+einsum_kg(H2B.oovo(HA,hB,PA,HB),T3C.PppHhh,'NmFJ,FabNmi->abiJ')...
-einsum_kg(H2B.oovo(HA,HB,pA,HB),T3C.pppHhH,'NMfJ,fabNiM->abiJ')...
-einsum_kg(H2B.oovo(HA,HB,PA,HB),T3C.PppHhH,'NMFJ,FabNiM->abiJ');
    
    X2C_pphH = (D1 + D2 + D3 + D4 + D5 + D6);
    X2C(pB,pB,hB,HB) = X2C(pB,pB,hB,HB) + X2C_pphH;


end