function [X1B] = update_t1b_proj2(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys,shift)

    chi1B_vv = sys.fb_vv + einsum_kg(sys.vC_vovv,t1b,'anef,fn->ae') + einsum_kg(sys.vB_ovvv,t1a,'nafe,fn->ae');
    chi1B_oo = sys.fb_oo + einsum_kg(sys.vC_ooov,t1b,'mnif,fn->mi') + einsum_kg(sys.vB_oovo,t1b,'nmfi,fn->mi');
    h1A_ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');
    h1B_ov = sys.fb_ov + einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me') + einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me');
    h1B_oo = chi1B_oo + einsum_kg(h1B_ov,t1b,'me,ei->mi');
       
    M11 = sys.fb_vo - einsum_kg(h1B_oo,t1b,'mi,am->ai') + einsum_kg(chi1B_vv,t1b,'ae,ei->ai')...
          +einsum_kg(sys.vC_voov,t1b,'anif,fn->ai') + einsum_kg(sys.vB_ovvo,t1a,'nafi,fn->ai');
      
    h2C_ooov = sys.vC_ooov + einsum_kg(sys.vC_oovv,t1b,'mnfe,fi->mnie'); 
    h2B_oovo = sys.vB_oovo + einsum_kg(sys.vB_oovv,t1b,'nmef,fi->nmei');
    h2C_vovv = sys.vC_vovv - einsum_kg(sys.vC_oovv,t1b,'mnfe,an->amef');
    h2B_ovvv = sys.vB_ovvv - einsum_kg(sys.vB_oovv,t1b,'mnfe,an->mafe');
      
    CCS_T2 = +einsum_kg(h1A_ov,t2b,'me,eami->ai') + einsum_kg(h1B_ov,t2c,'me,aeim->ai')...
             -0.5*einsum_kg(h2C_ooov,t2c,'mnif,afmn->ai') - einsum_kg(h2B_oovo,t2b,'nmfi,fanm->ai')...
             +0.5*einsum_kg(h2C_vovv,t2c,'anef,efin->ai') + einsum_kg(h2B_ovvv,t2b,'nafe,feni->ai');
       
    X1B = M11 + CCS_T2; 
    
    % CCSDT part
    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;


D1 = +0.25*einsum_kg(sys.vC_oovv(hB,hB,pB,pB),T3D.ppphhH,'mnef,aefmnI->aI')...
-0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,pB),T3D.PpphhH,'mnEf,EafmnI->aI')...
+0.25*einsum_kg(sys.vC_oovv(hB,hB,PB,PB),T3D.PPphhH,'mnEF,EFamnI->aI')...
+0.5*einsum_kg(sys.vC_oovv(HB,hB,pB,pB),T3D.ppphHH,'Mnef,aefnIM->aI')...
-1*einsum_kg(sys.vC_oovv(HB,hB,PB,pB),T3D.PpphHH,'MnEf,EafnIM->aI')...
+0.5*einsum_kg(sys.vC_oovv(HB,hB,PB,PB),T3D.PPphHH,'MnEF,EFanIM->aI')...
+0.25*einsum_kg(sys.vC_oovv(HB,HB,pB,pB),T3D.pppHHH,'MNef,aefIMN->aI')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,pB),T3D.PppHHH,'MNEf,EafIMN->aI')...
+0.25*einsum_kg(sys.vC_oovv(HB,HB,PB,PB),T3D.PPpHHH,'MNEF,EFaIMN->aI');

D2 = +1*einsum_kg(sys.vB_oovv(hA,hB,pA,pB),T3C.ppphhH,'mnef,efamnI->aI')...
+1*einsum_kg(sys.vB_oovv(hA,hB,pA,PB),T3C.pPphhH,'mneF,eFamnI->aI')...
+1*einsum_kg(sys.vB_oovv(hA,hB,PA,pB),T3C.PpphhH,'mnEf,EfamnI->aI')...
+1*einsum_kg(sys.vB_oovv(hA,hB,PA,PB),T3C.PPphhH,'mnEF,EFamnI->aI')...
+1*einsum_kg(sys.vB_oovv(hA,HB,pA,pB),T3C.ppphHH,'mNef,efamNI->aI')...
+1*einsum_kg(sys.vB_oovv(hA,HB,pA,PB),T3C.pPphHH,'mNeF,eFamNI->aI')...
+1*einsum_kg(sys.vB_oovv(hA,HB,PA,pB),T3C.PpphHH,'mNEf,EfamNI->aI')...
+1*einsum_kg(sys.vB_oovv(hA,HB,PA,PB),T3C.PPphHH,'mNEF,EFamNI->aI')...
+1*einsum_kg(sys.vB_oovv(HA,hB,pA,pB),T3C.pppHhH,'Mnef,efaMnI->aI')...
+1*einsum_kg(sys.vB_oovv(HA,hB,pA,PB),T3C.pPpHhH,'MneF,eFaMnI->aI')...
+1*einsum_kg(sys.vB_oovv(HA,hB,PA,pB),T3C.PppHhH,'MnEf,EfaMnI->aI')...
+1*einsum_kg(sys.vB_oovv(HA,hB,PA,PB),T3C.PPpHhH,'MnEF,EFaMnI->aI')...
+1*einsum_kg(sys.vB_oovv(HA,HB,pA,pB),T3C.pppHHH,'MNef,efaMNI->aI')...
+1*einsum_kg(sys.vB_oovv(HA,HB,pA,PB),T3C.pPpHHH,'MNeF,eFaMNI->aI')...
+1*einsum_kg(sys.vB_oovv(HA,HB,PA,pB),T3C.PppHHH,'MNEf,EfaMNI->aI')...
+1*einsum_kg(sys.vB_oovv(HA,HB,PA,PB),T3C.PPpHHH,'MNEF,EFaMNI->aI');

D3 = +0.25*einsum_kg(sys.vA_oovv(hA,hA,pA,pA),T3B.ppphhH,'mnef,efamnI->aI')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,PA,pA),T3B.PpphhH,'mnEf,EfamnI->aI')...
+0.25*einsum_kg(sys.vA_oovv(hA,hA,PA,PA),T3B.PPphhH,'mnEF,EFamnI->aI')...
-0.5*einsum_kg(sys.vA_oovv(HA,hA,pA,pA),T3B.ppphHH,'Mnef,efanMI->aI')...
-1*einsum_kg(sys.vA_oovv(HA,hA,PA,pA),T3B.PpphHH,'MnEf,EfanMI->aI')...
-0.5*einsum_kg(sys.vA_oovv(HA,hA,PA,PA),T3B.PPphHH,'MnEF,EFanMI->aI')...
+0.25*einsum_kg(sys.vA_oovv(HA,HA,pA,pA),T3B.pppHHH,'MNef,efaMNI->aI')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,PA,pA),T3B.PppHHH,'MNEf,EfaMNI->aI')...
+0.25*einsum_kg(sys.vA_oovv(HA,HA,PA,PA),T3B.PPpHHH,'MNEF,EFaMNI->aI');
    
    X1B_pH = D1 + D2 + D3;
    X1B(pB,HB) = X1B(pB,HB) + X1B_pH;

end