function [X1B] = update_t1b_proj1(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys,shift)

    chi1B_vv = sys.fb_vv + einsum_kg(sys.vC_vovv,t1b,'anef,fn->ae') + einsum_kg(sys.vB_ovvv,t1a,'nafe,fn->ae');
    chi1B_oo = sys.fb_oo + einsum_kg(sys.vC_ooov,t1b,'mnif,fn->mi') + einsum_kg(sys.vB_oovo,t1b,'nmfi,fn->mi');
    h1A_ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');
    h1B_ov = sys.fb_ov + einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me') + einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me');
    h1B_oo = chi1B_oo + einsum_kg(h1B_ov,t1b,'me,ei->mi');
       
    M11 = sys.fb_vo - einsum_kg(h1B_oo,t1b,'mi,am->ai') + einsum_kg(chi1B_vv,t1b,'ae,ei->ai')...
          +einsum_kg(sys.vC_voov,t1b,'anif,fn->ai') + einsum_kg(sys.vB_ovvo,t1a,'nafi,fn->ai');
      
    h2C_ooov = sys.vC_ooov + einsum_kg(sys.vC_oovv,t1b,'mnfe,fi->mnie'); 
    h2B_oovo = sys.vB_oovo + einsum_kg(sys.vB_oovv,t1b,'nmef,fi->nmei');
    h2C_vovv = sys.vC_vovv - einsum_kg(sys.vC_oovv,t1b,'mnfe,an->amef');
    h2B_ovvv = sys.vB_ovvv - einsum_kg(sys.vB_oovv,t1b,'mnfe,an->mafe');
      
    CCS_T2 = +einsum_kg(h1A_ov,t2b,'me,eami->ai') + einsum_kg(h1B_ov,t2c,'me,aeim->ai')...
             -0.5*einsum_kg(h2C_ooov,t2c,'mnif,afmn->ai') - einsum_kg(h2B_oovo,t2b,'nmfi,fanm->ai')...
             +0.5*einsum_kg(h2C_vovv,t2c,'anef,efin->ai') + einsum_kg(h2B_ovvv,t2b,'nafe,feni->ai');
       
    X1B = M11 + CCS_T2; 
    
    % CCSDT part
    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;

D1 = +0.25*einsum_kg(sys.vC_oovv(hB,hB,pB,pB),T3D.PpphhH,'mnef,AefmnI->AI')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,pB),T3D.PPphhH,'mnEf,AEfmnI->AI')...
+0.25*einsum_kg(sys.vC_oovv(hB,hB,PB,PB),T3D.PPPhhH,'mnEF,AEFmnI->AI')...
+0.5*einsum_kg(sys.vC_oovv(HB,hB,pB,pB),T3D.PpphHH,'Mnef,AefnIM->AI')...
+1*einsum_kg(sys.vC_oovv(HB,hB,PB,pB),T3D.PPphHH,'MnEf,AEfnIM->AI')...
+0.5*einsum_kg(sys.vC_oovv(HB,hB,PB,PB),T3D.PPPhHH,'MnEF,AEFnIM->AI')...
+0.25*einsum_kg(sys.vC_oovv(HB,HB,pB,pB),T3D.PppHHH,'MNef,AefIMN->AI')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,pB),T3D.PPpHHH,'MNEf,AEfIMN->AI')...
+0.25*einsum_kg(sys.vC_oovv(HB,HB,PB,PB),T3D.PPPHHH,'MNEF,AEFIMN->AI');

D2 = -1*einsum_kg(sys.vB_oovv(hA,hB,pA,pB),T3C.pPphhH,'mnef,eAfmnI->AI')...
+1*einsum_kg(sys.vB_oovv(hA,hB,pA,PB),T3C.pPPhhH,'mneF,eFAmnI->AI')...
-1*einsum_kg(sys.vB_oovv(hA,hB,PA,pB),T3C.PPphhH,'mnEf,EAfmnI->AI')...
+1*einsum_kg(sys.vB_oovv(hA,hB,PA,PB),T3C.PPPhhH,'mnEF,EFAmnI->AI')...
-1*einsum_kg(sys.vB_oovv(hA,HB,pA,pB),T3C.pPphHH,'mNef,eAfmNI->AI')...
+1*einsum_kg(sys.vB_oovv(hA,HB,pA,PB),T3C.pPPhHH,'mNeF,eFAmNI->AI')...
-1*einsum_kg(sys.vB_oovv(hA,HB,PA,pB),T3C.PPphHH,'mNEf,EAfmNI->AI')...
+1*einsum_kg(sys.vB_oovv(hA,HB,PA,PB),T3C.PPPhHH,'mNEF,EFAmNI->AI')...
-1*einsum_kg(sys.vB_oovv(HA,hB,pA,pB),T3C.pPpHhH,'Mnef,eAfMnI->AI')...
+1*einsum_kg(sys.vB_oovv(HA,hB,pA,PB),T3C.pPPHhH,'MneF,eFAMnI->AI')...
-1*einsum_kg(sys.vB_oovv(HA,hB,PA,pB),T3C.PPpHhH,'MnEf,EAfMnI->AI')...
+1*einsum_kg(sys.vB_oovv(HA,hB,PA,PB),T3C.PPPHhH,'MnEF,EFAMnI->AI')...
-1*einsum_kg(sys.vB_oovv(HA,HB,pA,pB),T3C.pPpHHH,'MNef,eAfMNI->AI')...
+1*einsum_kg(sys.vB_oovv(HA,HB,pA,PB),T3C.pPPHHH,'MNeF,eFAMNI->AI')...
-1*einsum_kg(sys.vB_oovv(HA,HB,PA,pB),T3C.PPpHHH,'MNEf,EAfMNI->AI')...
+1*einsum_kg(sys.vB_oovv(HA,HB,PA,PB),T3C.PPPHHH,'MNEF,EFAMNI->AI');

D3 = +0.25*einsum_kg(sys.vA_oovv(hA,hA,pA,pA),T3B.ppPhhH,'mnef,efAmnI->AI')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,PA,pA),T3B.PpPhhH,'mnEf,EfAmnI->AI')...
+0.25*einsum_kg(sys.vA_oovv(hA,hA,PA,PA),T3B.PPPhhH,'mnEF,EFAmnI->AI')...
-0.5*einsum_kg(sys.vA_oovv(HA,hA,pA,pA),T3B.ppPhHH,'Mnef,efAnMI->AI')...
-1*einsum_kg(sys.vA_oovv(HA,hA,PA,pA),T3B.PpPhHH,'MnEf,EfAnMI->AI')...
-0.5*einsum_kg(sys.vA_oovv(HA,hA,PA,PA),T3B.PPPhHH,'MnEF,EFAnMI->AI')...
+0.25*einsum_kg(sys.vA_oovv(HA,HA,pA,pA),T3B.ppPHHH,'MNef,efAMNI->AI')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,PA,pA),T3B.PpPHHH,'MNEf,EfAMNI->AI')...
+0.25*einsum_kg(sys.vA_oovv(HA,HA,PA,PA),T3B.PPPHHH,'MNEF,EFAMNI->AI');
    
    X1B_PH = D1 + D2 + D3;
    X1B(PB,HB) = X1B(PB,HB) + X1B_PH;

end