function [X2C] = build_HR_2C(r1a,r1b,r2a,r2b,r2c,HBar_t,cc_t,sys)


    Nunocc_a = sys.Nvir_alpha; Nocc_a = sys.Nocc_alpha;
    Nunocc_b = sys.Nvir_beta; Nocc_b = sys.Nocc_beta;

    H1B = HBar_t.H1B; H2B = HBar_t.H2B; H2C = HBar_t.H2C;

    t2c = cc_t.t2c;

    X2C = zeros(Nunocc_b, Nunocc_b, Nocc_a, Nocc_b);

    X2C = X2C - einsum_kg(H1B.oo,r2c,'mi,abmj->abij')...
              + einsum_kg(H1B.oo,r2c,'mj,abmi->abij');
    X2C = X2C + einsum_kg(H1B.vv,r2c,'ae,ebij->abij')...
              - einsum_kg(H1B.vv,r2c,'be,eaij->abij');

    X2C = X2C + 0.5*einsum_kg(H2C.oooo,r2c,'mnij,abmn->abij');
    X2C = X2C + 0.5*einsum_kg(H2C.vvvv,r2c,'abef,efij->abij');

    X2C = X2C + einsum_kg(H2C.voov,r2c,'amie,ebmj->abij')...
              - einsum_kg(H2C.voov,r2c,'amje,ebmi->abij')...
              - einsum_kg(H2C.voov,r2c,'bmie,eamj->abij')...
              + einsum_kg(H2C.voov,r2c,'bmje,eami->abij');

    X2C = X2C + einsum_kg(H2B.ovvo,r2b,'maei,ebmj->abij')...
              - einsum_kg(H2B.ovvo,r2b,'maej,ebmi->abij')...
              - einsum_kg(H2B.ovvo,r2b,'mbei,eamj->abij')...
              + einsum_kg(H2B.ovvo,r2b,'mbej,eami->abij');

    X2C = X2C - einsum_kg(H2C.ovoo,r1b,'mbij,am->abij')...
              + einsum_kg(H2C.ovoo,r1b,'maij,bm->abij');

    X2C = X2C + einsum_kg(H2C.vvvo,r1b,'abej,ei->abij')...
              - einsum_kg(H2C.vvvo,r1b,'abei,ej->abij');

%     X2C = X2C - einsum_kg(H3C.ovovoo,r2b,'nbmfji,fanm->abij')...
%               + einsum_kg(H3C.ovovoo,r2b,'namfji,fbnm->abij');
%     X2C = X2C - 0.5*einsum_kg(H3D.voooov,r2c,'bmnjif,afmn->abij')...
%               + 0.5*einsum_kg(H3D.voooov,r2c,'amnjif,bfmn->abij');

%     X2C = X2C + einsum_kg(H3C.ovvvov,r2b,'nbafje,feni->abij')...
%               - einsum_kg(H3C.ovvvov,r2b,'nbafie,fenj->abij');
%     X2C = X2C + 0.5*einsum_kg(H3D.vvoovv,r2c,'banjef,efin->abij')...
%               - 0.5*einsum_kg(H3D.vvoovv,r2c,'banief,efjn->abij');

    X2C = X2C - einsum_kg(einsum_kg(sys.vB_oovv,r2b,'nmfe,fbnm->be'),t2c,'be,aeij->abij')...
              + einsum_kg(einsum_kg(sys.vB_oovv,r2b,'nmfe,fanm->ae'),t2c,'ae,beij->abij');

    X2C = X2C - einsum_kg(einsum_kg(sys.vB_oovv,r2b,'nmfe,fenj->mj'),t2c,'mj,abim->abij')...
              + einsum_kg(einsum_kg(sys.vB_oovv,r2b,'nmfe,feni->mi'),t2c,'mi,abjm->abij');

    X2C = X2C - 0.5*einsum_kg(einsum_kg(sys.vC_oovv,r2c,'mnef,bfmn->be'),t2c,'be,aeij->abij')...
              + 0.5*einsum_kg(einsum_kg(sys.vC_oovv,r2c,'mnef,afmn->ae'),t2c,'ae,beij->abij');

    X2C = X2C - 0.5*einsum_kg(einsum_kg(sys.vC_oovv,r2c,'mnef,efjn->mj'),t2c,'mj,abim->abij')...
              + 0.5*einsum_kg(einsum_kg(sys.vC_oovv,r2c,'mnef,efin->mi'),t2c,'mi,abjm->abij');

 
%     X2C = X2C + einsum_kg(H3C.ovvvoo,r1a,'mabeij,em->abij');
%     X2C = X2C + einsum_kg(H3D.vvooov,r1b,'abmije,em->abij');

    X2C = X2C + einsum_kg(einsum_kg(H2B.ovvv,r1a,'maef,em->af'),t2c,'af,fbij->abij')...
              - einsum_kg(einsum_kg(H2B.ovvv,r1a,'mbef,em->bf'),t2c,'bf,faij->abij')...
              - einsum_kg(einsum_kg(H2B.oovo,r1a,'mnei,em->ni'),t2c,'ni,abnj->abij')...
              + einsum_kg(einsum_kg(H2B.oovo,r1a,'mnej,em->nj'),t2c,'nj,abni->abij');

    X2C = X2C + einsum_kg(einsum_kg(H2C.vovv,r1b,'amfe,em->af'),t2c,'af,fbij->abij')...
              - einsum_kg(einsum_kg(H2C.vovv,r1b,'bmfe,em->bf'),t2c,'bf,faij->abij')...
              + einsum_kg(einsum_kg(H2C.ooov,r1b,'mnie,em->ni'),t2c,'ni,abnj->abij')...
              - einsum_kg(einsum_kg(H2C.ooov,r1b,'mnje,em->nj'),t2c,'nj,abni->abij');
end

