function [X2A] = build_HR_2A(r1a,r1b,r2a,r2b,r2c,HBar_t,cc_t,sys)

    Nunocc_a = sys.Nvir_alpha; Nocc_a = sys.Nocc_alpha;

    H1A = HBar_t.H1A; 
    H2A = HBar_t.H2A; H2B = HBar_t.H2B; 

    t2a = cc_t.t2a; 

    X2A = zeros(Nunocc_a, Nunocc_a, Nocc_a, Nocc_a);

    X2A = X2A - einsum_kg(H1A.oo,r2a,'mi,abmj->abij')...
              + einsum_kg(H1A.oo,r2a,'mj,abmi->abij');
    X2A = X2A + einsum_kg(H1A.vv,r2a,'ae,ebij->abij')...
              - einsum_kg(H1A.vv,r2a,'be,eaij->abij');

    X2A = X2A + 0.5*einsum_kg(H2A.oooo,r2a,'mnij,abmn->abij');
    X2A = X2A + 0.5*einsum_kg(H2A.vvvv,r2a,'abef,efij->abij');

    X2A = X2A + einsum_kg(H2A.voov,r2a,'amie,ebmj->abij')...
              - einsum_kg(H2A.voov,r2a,'amje,ebmi->abij')...
              - einsum_kg(H2A.voov,r2a,'bmie,eamj->abij')...
              + einsum_kg(H2A.voov,r2a,'bmje,eami->abij');

    X2A = X2A + einsum_kg(H2B.voov,r2b,'amie,bejm->abij')...
              - einsum_kg(H2B.voov,r2b,'amje,beim->abij')...
              - einsum_kg(H2B.voov,r2b,'bmie,aejm->abij')...
              + einsum_kg(H2B.voov,r2b,'bmje,aeim->abij');
% 
    X2A = X2A - einsum_kg(H2A.ovoo,r1a,'mbij,am->abij')...
              + einsum_kg(H2A.ovoo,r1a,'maij,bm->abij');

    X2A = X2A + einsum_kg(H2A.vvvo,r1a,'abej,ei->abij')...
              - einsum_kg(H2A.vvvo,r1a,'abei,ej->abij');

%     X2A = X2A - 0.5*einsum_kg(H3A.voooov,r2a,'bmnjif,afmn->abij')...
%               + 0.5*einsum_kg(H3A.voooov,r2a,'amnjif,bfmn->abij');
%     X2A = X2A - einsum_kg(H3B.voooov,r2b,'bmnjif,afmn->abij')...
%               + einsum_kg(H3B.voooov,r2b,'amnjif,bfmn->abij');

    X2A = X2A - 0.5*einsum_kg(einsum_kg(sys.vA_oovv,r2a,'mnef,bfmn->eb'),t2a,'eb,aeij->abij')...
              + 0.5*einsum_kg(einsum_kg(sys.vA_oovv,r2a,'mnef,afmn->ea'),t2a,'ea,beij->abij')...  
              - einsum_kg(einsum_kg(sys.vB_oovv,r2b,'mnef,bfmn->eb'),t2a,'eb,aeij->abij')...
              + einsum_kg(einsum_kg(sys.vB_oovv,r2b,'mnef,afmn->ea'),t2a,'ea,beij->abij');

%     X2A = X2A + 0.5*einsum_kg(H3A.vvoovv,r2a,'banjef,efin->abij')...
%               - 0.5*einsum_kg(H3A.vvoovv,r2a,'banief,efjn->abij');
%     X2A = X2A + einsum_kg(H3B.vvoovv,r2b,'banjef,efin->abij')...
%               - einsum_kg(H3B.vvoovv,r2b,'banief,efjn->abij');

    X2A = X2A - 0.5*einsum_kg(einsum_kg(sys.vA_oovv,r2a,'mnef,efjn->mj'),t2a,'mj,abim->abij')...
              + 0.5*einsum_kg(einsum_kg(sys.vA_oovv,r2a,'mnef,efin->mi'),t2a,'mi,abjm->abij')...
              - einsum_kg(einsum_kg(sys.vB_oovv,r2b,'mnef,efjn->mj'),t2a,'mj,abim->abij')...
              + einsum_kg(einsum_kg(sys.vB_oovv,r2b,'mnef,efin->mi'),t2a,'mi,abjm->abij');

% 
%     X2A = X2A + einsum_kg(H3B.vvooov,r1b,'abmije,em->abij');
%     X2A = X2A + einsum_kg(H3A.vvooov,r1a,'abmije,em->abij');

    X2A = X2A + einsum_kg(einsum_kg(H2A.vovv,r1a,'amfe,em->af'),t2a,'af,fbij->abij')...
              - einsum_kg(einsum_kg(H2A.vovv,r1a,'bmfe,em->bf'),t2a,'bf,faij->abij')...
              - einsum_kg(einsum_kg(H2A.ooov,r1a,'nmie,em->ni'),t2a,'ni,abnj->abij')...
              + einsum_kg(einsum_kg(H2A.ooov,r1a,'nmje,em->nj'),t2a,'nj,abni->abij');

    X2A = X2A + einsum_kg(einsum_kg(H2B.vovv,r1b,'amfe,em->af'),t2a,'af,fbij->abij')...
              - einsum_kg(einsum_kg(H2B.vovv,r1b,'bmfe,em->bf'),t2a,'bf,faij->abij')...
              - einsum_kg(einsum_kg(H2B.ooov,r1b,'nmie,em->ni'),t2a,'ni,abnj->abij')...
              + einsum_kg(einsum_kg(H2B.ooov,r1b,'nmje,em->nj'),t2a,'nj,abni->abij');


end

