function [t1, t2, t3] = build_t1_t2_t3(t1,t2,t3,VM,FM,occ,vir)

    addpath(genpath('/Users/harellab/Dropbox/Hartree Fock/hartree_fock/v4/utils'));

    Nocc = length(occ); Nunocc = length(vir);

    Zocc = ones(Nocc)-eye(Nocc);
    Zunocc = ones(Nunocc)-eye(Nunocc);
    
    foo = FM(occ,occ);
    fov = FM(occ,vir);
    fvv = FM(vir,vir);
    fvo = FM(vir,occ);
    
    Vooov = VM(occ,occ,occ,vir);
    Voovv = VM(occ,occ,vir,vir);
    Vovov = VM(occ,vir,occ,vir);
    Vvovv = VM(vir,occ,vir,vir);
    Vvovo = VM(vir,occ,vir,occ);
    Voovo = VM(occ,occ,vir,occ);
    Vovoo = VM(occ,vir,occ,occ);
    Voooo = VM(occ,occ,occ,occ);
    Vvvvv = VM(vir,vir,vir,vir);
    Vvvvo = VM(vir,vir,vir,occ);
    Vvvoo = VM(vir,vir,occ,occ);
    Vovvv = VM(occ,vir,vir,vir);
    Vovvo = VM(occ,vir,vir,occ);
    Vvoov = VM(vir,occ,occ,vir);
    Vvvov = VM(vir,vir,occ,vir);
    Vvooo = VM(vir,occ,occ,occ);

    % Intermediates
    
    chi_mi = foo.*Zocc + ...
             einsum_kg(Vooov,t1,'mnif,fn->mi') + ...
             0.5*einsum_kg(Voovv,t2,'mnef,efin->mi');
    
    chi_me = fov + einsum_kg(Voovv,t1,'mnef,fn->me');
    
    chi_ae = fvv.*Zunocc + ...
             einsum_kg(Vvovv,t1,'anef,fn->ae') - ...
             0.5*einsum_kg(Voovv,t2,'mnef,afmn->ae') - ...
             einsum_kg(chi_me,t1,'me,am->ae');
    
    chit_mi = chi_mi + einsum_kg(chi_me,t1,'me,ei->mi');
    
    chit_anef = Vvovv - 0.5*einsum_kg(Voovv,t1,'mnef,am->anef');
    
    chi_anej = Vvovo - ... 
               0.5*einsum_kg(Voovo,t1,'mnej,am->anej') + ...
               0.5*einsum_kg(chit_anef,t1,'anef,fj->anej');
    
    chi_mnif = Vooov + 0.5*einsum_kg(Voovv,t1,'mnef,ei->mnif');
    
    chi_mbij = Vovoo - ...
                0.5*einsum_kg(Voooo,t1,'mnij,bn->mbij') - ...
                0.5*einsum_kg(chit_anef,t2,'bmef,efij->mbij');
    
    chi_abej = 0.5*Vvvvo - einsum_kg(chi_anej,t1,'anej,bn->abej');
    
    chi_mnij = 0.5*Voooo + ...
               0.25*einsum_kg(Voovv,t2,'mnef,efij->mnij') + ...
               einsum_kg(chi_mnif,t1,'mnif,fj->mnij');
    
    chi_anef = chit_anef - 0.5*einsum_kg(Voovv,t1,'mnef,am->anef');
    
    chit_anej = Vvovo - ... 
                einsum_kg(Voovo,t1,'mnej,am->anej') - ...
                0.5*einsum_kg(Voovv,t2,'mnef,afmj->anej') + ...
                einsum_kg(chi_anef,t1,'anef,fj->anej');
    
    chi_efij = einsum_kg(t1,t1,'ei,fj->efij') + 0.5*t2;
    
    % I8 = chi_me
    
    I9 = Vooov + einsum_kg(Voovv,t1,'mnef,ei->mnif');
    
    I10 = Vvovv - einsum_kg(Voovv,t1,'mnef,am->anef');
    
    I11 = Voovv;
    
    % Intermediates for triples
    
    tau = t2 + 0.5*(einsum_kg(t1,t1,'ai,bj->abij') - ...
                    einsum_kg(t1,t1,'aj,bi->abij') - ...
                    einsum_kg(t1,t1,'bi,aj->abij') + ...
                    einsum_kg(t1,t1,'bj,ai->abij')); 
                
    Wbar_mnij = Voooo + ...
                einsum_kg(Vooov,t1,'mnie,ej->mnij') - einsum_kg(Vooov,t1,'mnje,ei->mnij') + ...
                0.25*einsum_kg(Voovv,tau,'mnef,efij->mnij');
            
    Wbar_abef = Vvvvv - ...
                einsum_kg(Vvovv,t1,'amef,bm->abef') + einsum_kg(Vvovv,t1,'bmef,am->abef') + ...
                0.25*einsum_kg(Voovv,tau,'mnef,abmn->abef');
    
    h_mnij = Wbar_mnij + 0.25*einsum_kg(Voovv,tau,'mnef,efij->mnij'); 
    
    h_abef = Wbar_abef + 0.25*einsum_kg(Voovv,tau,'mnef,abmn->abef'); 
    
    h_mbij =   Vovoo - einsum_kg(chi_me,t2,'me,beij->mbij') - einsum_kg(h_mnij,t1,'mnij,bn->mbij') + ...
                    0.5*einsum_kg(Vovvv,tau,'mbef,efij->mbij') + ...
                    einsum_kg(Vooov,t2,'mnie,bejn->mbij') - einsum_kg(Vooov,t2,'mnje,bein->mbij') + ...
                    einsum_kg(Vovvo,t1,'mbej,ei->mbij') - einsum_kg(Vovvo,t1,'mbei,ej->mbij') - ...
                    einsum_kg(einsum_kg(Voovv,t2,'mnef,bfnj->mbej'),t1,'mbej,ei->mbij') + ...
                    einsum_kg(einsum_kg(Voovv,t2,'mnef,bfni->mbei'),t1,'mbei,ej->mbij'); % 
                
    h_amij_2 = -permute(h_mbij,[2,1,3,4]);
                
    h_abej =   Vvvvo - einsum_kg(chi_me,t2,'me,abmi->abei') + einsum_kg(h_abef,t1,'abef,fi->abei') + ...
                    0.5*einsum_kg(Voovo,tau,'mnei,abmn->abei') - ...
                    einsum_kg(Vovvv,t2,'mbef,afmi->abei') + einsum_kg(Vovvv,t2,'maef,bfmi->abei') - ...
                    einsum_kg(Vovvo,t1,'mbei,am->abei') + einsum_kg(Vovvo,t1,'maei,bm->abei') + ...
                    einsum_kg(einsum_kg(Voovv,t2,'mnef,bfni->mbei'),t1,'mbei,am->abei') - ...
                    einsum_kg(einsum_kg(Voovv,t2,'mnef,afni->maei'),t1,'maei,bm->abei'); 
                
    h_abie = -permute(h_abej,[1,2,4,3]);

    
%  h_abie  MATCHES WITH THE CODE TAKEN FROM build_HBar
%     h_abie = Vvvov ...
%              + einsum_kg(Vvvvv,t1,'abfe,fi->abie') ...
%              - einsum_kg(Vovov,t1,'mbie,am->abie') + einsum_kg(Vovov,t1,'maie,bm->abie') ...
%              - einsum_kg(fov,t2,'me,abim->abie') ...
%              + einsum_kg(Vovvv,t2,'mbfe,afim->abie') - einsum_kg(Vovvv,t2,'mafe,bfim->abie') ...
%              + 0.5*einsum_kg(Vooov,t2,'mnie,abmn->abie') ...
%              + einsum_kg(einsum_kg(Vooov,t1,'nmie,an->amie'),t1,'amie,bm->abie') ...
%              - einsum_kg(einsum_kg(Vovvv,t1,'mbfe,am->abfe'),t1,'abfe,fi->abie') + einsum_kg(einsum_kg(Vovvv,t1,'mafe,bm->abfe'),t1,'abfe,fi->abie') ...
%              + 0.5*einsum_kg(einsum_kg(Voovv,t1,'mnfe,fi->mnie'),t2,'mnie,abmn->abie') ...
%              - einsum_kg(einsum_kg(Voovv,t1,'mnfe,bn->mbfe'),t2,'mbfe,afim->abie') + einsum_kg(einsum_kg(Voovv,t1,'mnfe,an->mafe'),t2,'mafe,bfim->abie') ...
%              - einsum_kg(einsum_kg(Voovv,t1,'nmfe,fn->me'),t2,'me,abim->abie') ...
%              + einsum_kg(einsum_kg(einsum_kg(Voovv,t1,'nmfe,bm->nbfe'),t1,'nbfe,fi->nbie'),t1,'nbie,an->abie');
         
% h_amij MATCHES WITH CODE TAKEN FROM build_HBar
%        h_amij = sys.Vvooo ...
%              + einsum_kg(sys.Vvovo,t1,'amej,ei->amij') - einsum_kg(sys.Vvovo,t1,'amei,ej->amij') ...
%              - einsum_kg(sys.Voooo,t1,'nmij,an->amij') ...
%              + einsum_kg(sys.fov,t2,'me,aeij->amij') ...
%              + 0.5*einsum_kg(sys.Vvovv,t2,'amfe,feij->amij') ...
%              + einsum_kg(sys.Voovo,t2,'nmej,aein->amij') - einsum_kg(sys.Voovo,t2,'nmei,aejn->amij') ...
%              - einsum_kg(einsum_kg(sys.Voovo,t1,'nmej,an->amej'),t1,'amej,ei->amij') + einsum_kg(einsum_kg(sys.Voovo,t1,'nmei,an->amei'),t1,'amei,ej->amij') ...
%              + einsum_kg(einsum_kg(sys.Vvovv,t1,'amfe,fi->amie'),t1,'amie,ej->amij') ...
%              - 0.5*einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,an->amef'),t2,'amef,feij->amij') ...
%              + einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,ej->nmfj'),t2,'nmfj,afin->amij') - einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,ei->nmfi'),t2,'nmfi,afjn->amij') ...
%              + einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,fn->me'),t2,'me,aeij->amij') ...
%              - einsum_kg(einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,an->amfe'),t1,'amfe,fi->amie'),t1,'amie,ej->amij');           
    
         
    I1 = Vvoov ...
         - einsum_kg(Voovo,t1,'mnei,an->amie') ...
         + einsum_kg(Vvovv,t1,'amfe,fi->amie') ...
         + einsum_kg(Voovv,t2,'mnef,afin->amie') ...
         - einsum_kg(einsum_kg(Voovv,t1,'mnef,fi->mnei'),t1,'mnei,an->amie');
    
    I2 = Voooo ...
         + einsum_kg(Vooov,t1,'mnie,ej->mnij') - einsum_kg(Vooov,t1,'mnje,ei->mnij') ...
         + 0.5*einsum_kg(Voovv,t2,'mnef,efij->mnij') ...
         + einsum_kg(einsum_kg(Voovv,t1,'mnef,ei->mnif'),t1,'mnif,fj->mnij');
     
    I3 = Vvvvv ...
         + einsum_kg(einsum_kg(Voovv,t1,'mnef,am->anef'),t1,'anef,bn->abef') ...
         + 0.5*einsum_kg(Voovv,t2,'mnef,abmn->abef') ...
         - einsum_kg(Vvovv,t1,'amef,bm->abef') + einsum_kg(Vvovv,t1,'bmef,am->abef');
     
    I4 = einsum_kg(Voovv,t2,'mnfe,afij->amnije'); % W_amnije
    
    I5 = -einsum_kg(Voovv,t2,'mnfe,abin->abmief'); % W_abmief
    
    I6 = foo.*Zocc ...
         + einsum_kg(fov,t1,'me,ei->mi') ...
         + einsum_kg(einsum_kg(Voovv,t1,'mnef,fn->me'),t1,'me,ei->mi') ...
         + 0.5*einsum_kg(Voovv,t2,'mnef,efin->mi') ...
         + einsum_kg(Vooov,t1,'mnif,fn->mi');
    
    I7 = fvv.*Zunocc ...
         - einsum_kg(fov,t1,'me,am->ae') ...
         - einsum_kg(einsum_kg(Voovv,t1,'mnef,fn->me'),t1,'me,am->ae') ...
         - 0.5*einsum_kg(Voovv,t2,'mnef,afmn->ae') ...
         + einsum_kg(Vvovv,t1,'amef,fm->ae');
     
    I12 = h_abie-einsum_kg(chi_me,t2,'me,abim->abie');
    
    % build T1
    
    TEMP1 = einsum_kg(chi_me,t2,'me,aeim->ai') - ...
            einsum_kg(Vovov,t1,'maie,em->ai') - ...
            einsum_kg(chi_mi,t1,'mi,am->ai') + ...
            einsum_kg(chi_ae,t1,'ae,ei->ai') - ...
            0.5*einsum_kg(Vooov,t2,'mnif,afmn->ai') + ...
            0.5*einsum_kg(Vvovv,t2,'anef,efin->ai');
        
    TEMP1_3 = 0.25*einsum_kg(I11,t3,'mnef,aefimn->ai');
        
    % build T2

    % standard order
    TEMP2_abij = einsum_kg(chi_abej,t1,'abej,ei->abij') - ...
            einsum_kg(chit_anej,t2,'anej,ebin->abij') - ...
            0.5*einsum_kg(chi_mbij,t1,'mbij,am->abij') + ...
            0.5*einsum_kg(chi_ae,t2,'ae,ebij->abij') - ...
            0.5*einsum_kg(chit_mi,t2,'mi,abmj->abij') + ...
            0.25*einsum_kg(chi_mnij,t2,'mnij,abmn->abij') + ...
            0.25*einsum_kg(Vvvvv,chi_efij,'abef,efij->abij');
    % (ij)    
    TEMP2_abji = einsum_kg(chi_abej,t1,'abei,ej->abij') - ...
            einsum_kg(chit_anej,t2,'anei,ebjn->abij') - ...
            0.5*einsum_kg(chi_mbij,t1,'mbji,am->abij') + ...
            0.5*einsum_kg(chi_ae,t2,'ae,ebji->abij') - ...
            0.5*einsum_kg(chit_mi,t2,'mj,abmi->abij') + ...
            0.25*einsum_kg(chi_mnij,t2,'mnji,abmn->abij') + ...
            0.25*einsum_kg(Vvvvv,chi_efij,'abef,efji->abij');
    % (ab)    
    TEMP2_baij = einsum_kg(chi_abej,t1,'baej,ei->abij') - ...
            einsum_kg(chit_anej,t2,'bnej,eain->abij') - ...
            0.5*einsum_kg(chi_mbij,t1,'maij,bm->abij') + ...
            0.5*einsum_kg(chi_ae,t2,'be,eaij->abij') - ...
            0.5*einsum_kg(chit_mi,t2,'mi,bamj->abij') + ...
            0.25*einsum_kg(chi_mnij,t2,'mnij,bamn->abij') + ...
            0.25*einsum_kg(Vvvvv,chi_efij,'baef,efij->abij');
    
    % (ab)(ij)    
    TEMP2_baji = einsum_kg(chi_abej,t1,'baei,ej->abij') - ...
            einsum_kg(chit_anej,t2,'bnei,eajn->abij') - ...
            0.5*einsum_kg(chi_mbij,t1,'maji,bm->abij') + ...
            0.5*einsum_kg(chi_ae,t2,'be,eaji->abij') - ...
            0.5*einsum_kg(chit_mi,t2,'mj,bami->abij') + ...
            0.25*einsum_kg(chi_mnij,t2,'mnji,bamn->abij') + ...
            0.25*einsum_kg(Vvvvv,chi_efij,'baef,efji->abij');
        
        
    TEMP2_3 = einsum_kg(chi_me,t3,'me,abeijm->abij') ...
              -0.5*einsum_kg(I9,t3,'mnif,abfmjn->abij') + 0.5*einsum_kg(I9,t3,'mnjf,abfmin->abij') ...
              +0.5*einsum_kg(I10,t3,'anef,ebfijn->abij') - 0.5*einsum_kg(I10,t3,'bnef,eafijn->abij');
        
        
    % build T3
    
    MM23_1 = -einsum_kg(h_amij,t2,'amij,bcmk->abcijk') ...
             +einsum_kg(h_amij,t2,'amkj,bcmi->abcijk') ...
             +einsum_kg(h_amij,t2,'amik,bcmj->abcijk') ...
             +einsum_kg(h_amij,t2,'cmij,bamk->abcijk') ...
             +einsum_kg(h_amij,t2,'bmij,acmk->abcijk') ...
             -einsum_kg(h_amij,t2,'bmkj,acmi->abcijk') ...
             -einsum_kg(h_amij,t2,'cmkj,bami->abcijk') ...
             -einsum_kg(h_amij,t2,'bmik,acmj->abcijk') ...
             -einsum_kg(h_amij,t2,'cmik,bamj->abcijk');
         
    MM23_2 =  einsum_kg(I12,t2,'abie,ecjk->abcijk') ...
             -einsum_kg(I12,t2,'abje,ecik->abcijk') ...
             -einsum_kg(I12,t2,'abke,ecji->abcijk') ...
             -einsum_kg(I12,t2,'cbie,eajk->abcijk') ...
             -einsum_kg(I12,t2,'acie,ebjk->abcijk') ...
             +einsum_kg(I12,t2,'cbje,eaik->abcijk') ...
             +einsum_kg(I12,t2,'acje,ebik->abcijk') ...
             +einsum_kg(I12,t2,'cbke,eaji->abcijk') ...
             +einsum_kg(I12,t2,'acke,ebji->abcijk');
    
    TEMP3_abc = einsum_kg(I1,t3,'cmke,abeijm->abcijk') - einsum_kg(I1,t3,'cmie,abekjm->abcijk') - einsum_kg(I1,t3,'cmje,abeikm->abcijk') ...
                + einsum_kg(I3,t3,'abef,efcijk->abcijk') ...
                + 0.5*einsum_kg(I5,t3,'abmife,efcmjk->abcijk') - 0.5*einsum_kg(I5,t3,'abmjfe,efcmik->abcijk') - 0.5*einsum_kg(I5,t3,'abmkfe,efcmji->abcijk') ...
                + einsum_kg(I7,t3,'ce,abeijk->abcijk');
            
    TEMP3_cab = einsum_kg(I1,t3,'amke,cbeijm->abcijk') - einsum_kg(I1,t3,'amie,cbekjm->abcijk') - einsum_kg(I1,t3,'amje,cbeikm->abcijk') ...
                + einsum_kg(I3,t3,'cbef,efaijk->abcijk') ...
                + 0.5*einsum_kg(I5,t3,'cbmife,efamjk->abcijk') - 0.5*einsum_kg(I5,t3,'cbmjfe,efamik->abcijk') - 0.5*einsum_kg(I5,t3,'cbmkfe,efamji->abcijk') ...
                + einsum_kg(I7,t3,'ae,cbeijk->abcijk');
    
    TEMP3_acb = einsum_kg(I1,t3,'bmke,aceijm->abcijk') - einsum_kg(I1,t3,'bmie,acekjm->abcijk') - einsum_kg(I1,t3,'bmje,aceikm->abcijk') ...
                + einsum_kg(I3,t3,'acef,efbijk->abcijk') ...
                + 0.5*einsum_kg(I5,t3,'acmife,efbmjk->abcijk') - 0.5*einsum_kg(I5,t3,'acmjfe,efbmik->abcijk') - 0.5*einsum_kg(I5,t3,'acmkfe,efbmji->abcijk') ...
                + einsum_kg(I7,t3,'be,aceijk->abcijk');
            
    TEMP3_ijk = einsum_kg(I2,t3,'mnij,abcmnk->abcijk') ...
                - 0.5*einsum_kg(I4,t3,'amnije,ebcmnk->abcijk') + 0.5*einsum_kg(I4,t3,'bmnije,eacmnk->abcijk') + 0.5*einsum_kg(I4,t3,'cmnije,ebamnk->abcijk') ... 
                - einsum_kg(I6,t3,'mk,abcijm->abcijk');
            
    TEMP3_kji = einsum_kg(I2,t3,'mnkj,abcmni->abcijk') ...
                - 0.5*einsum_kg(I4,t3,'amnkje,ebcmni->abcijk') + 0.5*einsum_kg(I4,t3,'bmnkje,eacmni->abcijk') + 0.5*einsum_kg(I4,t3,'cmnkje,ebamni->abcijk') ... 
                - einsum_kg(I6,t3,'mi,abckjm->abcijk');
            
    TEMP3_ikj = einsum_kg(I2,t3,'mnik,abcmni->abcijk') ...
                - 0.5*einsum_kg(I4,t3,'amnike,ebcmni->abcijk') + 0.5*einsum_kg(I4,t3,'bmnike,eacmni->abcijk') + 0.5*einsum_kg(I4,t3,'cmnike,ebamni->abcijk') ... 
                - einsum_kg(I6,t3,'mj,abcikm->abcijk');
        
        
    t1 = fvo + TEMP1 + TEMP1_3;
    t2 = Vvvoo + TEMP2_abij - TEMP2_abji - TEMP2_baij + TEMP2_baji + TEMP2_3;
    t3 = MM23_1 + MM23_2 + TEMP3_abc - TEMP3_cab - TEMP3_acb + TEMP3_ijk - TEMP3_kji - TEMP3_ikj;
            

            
end