function [t3a] = update_t3a_proj4_ccsdt2(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys,shift)

PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;

[H1A, H2A, H2B, Vt3A] = get_t3a_intermediates(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys);

% MM23A + (V*T2*T3)_C
I2A_vvov = H2A.vvov+einsum_kg(H1A.ov,t2a,'me,abim->abie');

M23_D1 = -einsum_kg(H2A.vooo(PA,:,hA,HA) + Vt3A.PohH,t2a(PA,pA,:,HA),'AmiJ,BcmK->ABciJK');
M23_D1 = M23_D1 - permute(M23_D1,[1,2,3,4,6,5]) - permute(M23_D1,[2,1,3,4,5,6]) + permute(M23_D1,[2,1,3,4,6,5]);
M23_D2 = einsum_kg(H2A.vooo(pA,:,hA,HA) + Vt3A.pohH,t2a(PA,PA,:,HA),'cmiJ,BAmK->ABciJK');
M23_D2 = M23_D2 - permute(M23_D2,[1,2,3,4,6,5]);
M23_D3 = einsum_kg(H2A.vooo(PA,:,HA,HA) + Vt3A.PoHH,t2a(PA,pA,:,hA),'AmKJ,Bcmi->ABciJK');
M23_D3 = M23_D3 - permute(M23_D3,[2,1,3,4,5,6]);
M23_D4 = -einsum_kg(H2A.vooo(pA,:,HA,HA) + Vt3A.poHH,t2a(PA,PA,:,hA),'cmKJ,BAmi->ABciJK');

M23_D1234 = M23_D1 + M23_D2 + M23_D3 + M23_D4;

M23_D5 = +einsum_kg(I2A_vvov(PA,PA,hA,:) + Vt3A.PPhv,t2a(:,pA,HA,HA),'ABie,ecJK->ABciJK');
M23_D6 = -einsum_kg(I2A_vvov(PA,PA,HA,:) + Vt3A.PPHv,t2a(:,pA,hA,HA),'ABJe,eciK->ABciJK');
M23_D6 = M23_D6 - permute(M23_D6,[1,2,3,4,6,5]);
M23_D7 = -einsum_kg(I2A_vvov(PA,pA,hA,:) + Vt3A.Pphv,t2a(:,PA,HA,HA),'Acie,eBJK->ABciJK');
M23_D7 = M23_D7 - permute(M23_D7,[2,1,3,4,5,6]);
M23_D8 = +einsum_kg(I2A_vvov(PA,pA,HA,:) + Vt3A.PpHv,t2a(:,PA,hA,HA),'AcJe,eBiK->ABciJK');
M23_D8 = M23_D8 - permute(M23_D8,[2,1,3,4,5,6]) - permute(M23_D8,[1,2,3,4,6,5]) + permute(M23_D8,[2,1,3,4,6,5]);

M23_D5678 = M23_D5 + M23_D6 + M23_D7 + M23_D8;

MM23A = M23_D1234 + M23_D5678;


% (HBar*T3)_C
D1 =-einsum_kg(H1A.oo(HA,HA),T3A.PPphHH,'MK,ABciJM->ABciJK');
D1 = D1 - permute(D1,[1,2,3,4,6,5]);

D2 = +einsum_kg(H1A.oo(hA,hA),T3A.PPphHH,'mi,ABcmKJ->ABciJK')...
+einsum_kg(H1A.oo(HA,hA),T3A.PPpHHH,'Mi,ABcKJM->ABciJK');

D3 = +einsum_kg(H1A.vv(pA,pA),T3A.PPphHH,'ce,ABeiJK->ABciJK')...
+einsum_kg(H1A.vv(pA,PA),T3A.PPPhHH,'cE,ABEiJK->ABciJK');

D4 =+einsum_kg(H1A.vv(PA,PA),T3A.PPphHH,'BE,AEciJK->ABciJK');
D4 = D4 - permute(D4,[2,1,3,4,5,6]);

D5 =-einsum_kg(H2A.oooo(HA,hA,hA,HA),T3A.PPphHH,'MniJ,ABcnMK->ABciJK')...
+0.5*einsum_kg(H2A.oooo(HA,HA,hA,HA),T3A.PPpHHH,'MNiJ,ABcMNK->ABciJK');
D5 = D5 - permute(D5,[1,2,3,4,6,5]);

D6 =-0.5*einsum_kg(H2A.oooo(HA,HA,HA,HA),T3A.PPphHH,'MNKJ,ABciMN->ABciJK');

D7 =+0.5*einsum_kg(H2A.vvvv(PA,PA,PA,PA),T3A.PPphHH,'ABEF,EFciJK->ABciJK');

D8 =+einsum_kg(H2A.vvvv(PA,pA,PA,pA),T3A.PPphHH,'AcEf,EBfiJK->ABciJK')...
-0.5*einsum_kg(H2A.vvvv(PA,pA,PA,PA),T3A.PPPhHH,'AcEF,EFBiJK->ABciJK');
D8 = D8 - permute(D8,[2,1,3,4,5,6]);

D9 =+einsum_kg(H2A.voov(pA,HA,HA,pA),T3A.PPphHH,'cMKe,ABeiJM->ABciJK')...
+einsum_kg(H2A.voov(pA,HA,HA,PA),T3A.PPPhHH,'cMKE,ABEiJM->ABciJK');
D9 = D9 - permute(D9,[1,2,3,4,6,5]);

D10 =+einsum_kg(H2A.voov(PA,HA,HA,PA),T3A.PPphHH,'BMKE,AEciJM->ABciJK');
D10 = D10 - permute(D10,[2,1,3,4,5,6]) - permute(D10,[1,2,3,4,6,5]) + permute(D10,[2,1,3,4,6,5]);

D11 = -einsum_kg(H2A.voov(pA,hA,hA,pA),T3A.PPphHH,'cmie,ABemKJ->ABciJK')...
-einsum_kg(H2A.voov(pA,hA,hA,PA),T3A.PPPhHH,'cmiE,ABEmKJ->ABciJK')...
-einsum_kg(H2A.voov(pA,HA,hA,pA),T3A.PPpHHH,'cMie,ABeKJM->ABciJK')...
-einsum_kg(H2A.voov(pA,HA,hA,PA),T3A.PPPHHH,'cMiE,ABEKJM->ABciJK');

D12 =-einsum_kg(H2A.voov(PA,hA,hA,PA),T3A.PPphHH,'BmiE,AEcmKJ->ABciJK')...
-einsum_kg(H2A.voov(PA,HA,hA,PA),T3A.PPpHHH,'BMiE,AEcKJM->ABciJK');
D12 = D12 - permute(D12,[2,1,3,4,5,6]);

D13 =+einsum_kg(H2B.voov(pA,HB,HA,pB),T3B.PPphHH,'cMKe,ABeiJM->ABciJK')...
+einsum_kg(H2B.voov(pA,HB,HA,PB),T3B.PPPhHH,'cMKE,ABEiJM->ABciJK');
D13 = D13 - permute(D13,[1,2,3,4,6,5]);

D14 =-einsum_kg(H2B.voov(PA,HB,HA,PB),T3B.PpPhHH,'BMKE,AcEiJM->ABciJK');
D14 = D14 - permute(D14,[2,1,3,4,5,6]) - permute(D14,[1,2,3,4,6,5]) + permute(D14,[2,1,3,4,6,5]);

D15 = -einsum_kg(H2B.voov(pA,hB,hA,pB),T3B.PPpHHh,'cmie,ABeKJm->ABciJK')...
-einsum_kg(H2B.voov(pA,hB,hA,PB),T3B.PPPHHh,'cmiE,ABEKJm->ABciJK')...
-einsum_kg(H2B.voov(pA,HB,hA,pB),T3B.PPpHHH,'cMie,ABeKJM->ABciJK')...
-einsum_kg(H2B.voov(pA,HB,hA,PB),T3B.PPPHHH,'cMiE,ABEKJM->ABciJK');

D16 =+einsum_kg(H2B.voov(PA,hB,hA,PB),T3B.PpPHHh,'BmiE,AcEKJm->ABciJK')...
+einsum_kg(H2B.voov(PA,HB,hA,PB),T3B.PpPHHH,'BMiE,AcEKJM->ABciJK');
D16 = D16 - permute(D16,[2,1,3,4,5,6]);


X3A_PPphHH = D1 + D2 + D3 + D4 + D5 + D6 + D7 + D8 + D9 + D10 + D11 + D12 + D13 + D14 + D15 + D16 + MM23A;

    t3a = T3A.PPphHH;
    
    for a = 1:sys.Nact_p_alpha
        for b = a+1:sys.Nact_p_alpha
            for c = 1:sys.Nunact_p_alpha
                for i = 1:sys.Nunact_h_alpha
                    for j = 1:sys.Nact_h_alpha
                        for k = j+1:sys.Nact_h_alpha
                            
                            denom = sys.fa_hh(i,i) + sys.fa_HH(j,j) + sys.fa_HH(k,k) - sys.fa_PP(a,a) - sys.fa_PP(b,b) - sys.fa_pp(c,c);
                            
                            t3a(a,b,c,i,j,k) = t3a(a,b,c,i,j,k) + X3A_PPphHH(a,b,c,i,j,k)/(denom-shift);
                            t3a(b,a,c,i,j,k) = -t3a(a,b,c,i,j,k);
                            t3a(a,b,c,i,k,j) = -t3a(a,b,c,i,j,k);
                            t3a(b,a,c,i,j,k) = t3a(a,b,c,i,j,k);

                        end
                    end
                end
            end
        end
    end
    %T3A.PPphHH = t3a;


end

function [H1A,H2A,H2B,Vt3A] = get_t3a_intermediates(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys)

% h1A(me)
H1A.ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');

% h1A(mi)
H1A.oo = sys.fa_oo ...
+einsum_kg(sys.fa_ov,t1a,'me,ei->mi')...
+einsum_kg(sys.vA_ooov,t1a,'mnif,fn->mi')...
+einsum_kg(sys.vB_ooov,t1b,'mnif,fn->mi')...
+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efin->mi')...
+einsum_kg(sys.vB_oovv,t2b,'mnef,efin->mi')...
+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,ei->mi')...
+einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,ei->mi');

% h1A(ae)
H1A.vv = sys.fa_vv ...
-einsum_kg(sys.fa_ov,t1a,'me,am->ae')...
+einsum_kg(sys.vA_vovv,t1a,'amef,fm->ae')...
+einsum_kg(sys.vB_vovv,t1b,'anef,fn->ae')...
-0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,afmn->ae')...
-einsum_kg(sys.vB_oovv,t2b,'mnef,afmn->ae')...
-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,am->ae')...
-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,am->ae');

% h2A(amij)
H2A.vooo = sys.vA_vooo ...
+einsum_kg(sys.vA_voov,t1a,'amie,ej->amij')...
-einsum_kg(sys.vA_voov,t1a,'amje,ei->amij')...
-einsum_kg(sys.vA_oooo,t1a,'nmij,an->amij')...
+einsum_kg(sys.fa_ov,t2a,'me,aeij->amij')...
+0.5*einsum_kg(sys.vA_vovv,t2a,'amef,efij->amij')...
+einsum_kg(sys.vA_oovo,t2a,'nmej,aein->amij')...
-einsum_kg(sys.vA_oovo,t2a,'nmei,aejn->amij')...
+einsum_kg(sys.vB_ooov,t2b,'mnje,aein->amij')...
-einsum_kg(sys.vB_ooov,t2b,'mnie,aejn->amij')...
-einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmej,ei->nmij'),t1a,'nmij,an->amij')...
+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmei,ej->nmij'),t1a,'nmij,an->amij')...
+einsum_kg(einsum_kg(sys.vA_vovv,t1a,'amef,ei->amif'),t1a,'amif,fj->amij')...
-0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,an->amef'),t2a,'amef,efij->amij')...
+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ej->mnjf'),t2a,'mnjf,afin->amij')...
-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t2a,'mnif,afjn->amij')...
+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,aeij->amij')...
+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t2b,'mnjf,afin->amij')...
-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ei->mnif'),t2b,'mnif,afjn->amij')...
+einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,aeij->amij')...
-einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,fj->nmej'),t1a,'nmej,an->amej'),t1a,'amej,ei->amij');

% h(abie)
H2A.vvov = sys.vA_vvov ...
+einsum_kg(sys.vA_vvvv,t1a,'abfe,fi->abie')...
-einsum_kg(sys.vA_ovov,t1a,'nbie,an->abie')...
+einsum_kg(sys.vA_ovov,t1a,'naie,bn->abie')...
-einsum_kg(sys.fa_ov,t2a,'me,abim->abie')...
+einsum_kg(sys.vA_ovvv,t2a,'nbfe,afin->abie')...
-einsum_kg(sys.vA_ovvv,t2a,'nafe,bfin->abie')...
+0.5*einsum_kg(sys.vA_oovo,t2a,'mnei,abnm->abie')...
+einsum_kg(sys.vB_vovv,t2b,'bnef,afin->abie')...
-einsum_kg(sys.vB_vovv,t2b,'anef,bfin->abie')...
+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'mnei,an->maei'),t1a,'maei,bm->abie')...
-einsum_kg(einsum_kg(sys.vA_vovv,t1a,'bnef,fi->bnei'),t1a,'bnei,an->abie')...
+einsum_kg(einsum_kg(sys.vA_vovv,t1a,'anef,fi->anei'),t1a,'anei,bn->abie')...
+0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fi->mnei'),t2a,'mnei,abnm->abie')...
-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t2a,'bnef,afin->abie')...
+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,am->anef'),t2a,'anef,bfin->abie')...
-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,abim->abie')...
-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,bm->bnef'),t2b,'bnef,afin->abie')...
+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,am->anef'),t2b,'anef,bfin->abie')...
-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,abim->abie')...
+einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t1a,'bnef,an->baef'),t1a,'baef,fi->abie');

% h2A(mnij)
H2A.oooo = sys.vA_oooo...
+einsum_kg(sys.vA_oovo,t1a,'mnej,ei->mnij')...
-einsum_kg(sys.vA_oovo,t1a,'mnei,ej->mnij')...
+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efij->mnij')...
+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t1a,'mnif,fj->mnij');

% h2A(abef)
H2A.vvvv = sys.vA_vvvv...
-einsum_kg(sys.vA_ovvv,t1a,'mbef,am->abef')...
+einsum_kg(sys.vA_ovvv,t1a,'maef,bm->abef')...
+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,abmn->abef')...
+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bn->mbef'),t1a,'mbef,am->abef');

% h2A(amie)
H2A.voov = sys.vA_voov ...
-einsum_kg(sys.vA_ooov,t1a,'nmie,an->amie')...
+einsum_kg(sys.vA_vovv,t1a,'amfe,fi->amie')...
-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
+einsum_kg(sys.vA_oovv,t2a,'nmfe,afin->amie')...
+einsum_kg(sys.vB_oovv,t2b,'mnef,afin->amie');

% h2B(amie)
H2B.voov = sys.vB_voov ...
-einsum_kg(sys.vB_ooov,t1a,'nmie,an->amie')...
+einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie')...
-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
+einsum_kg(sys.vB_oovv,t2a,'nmfe,afin->amie')...
+einsum_kg(sys.vC_oovv,t2b,'mnef,afin->amie');

% (VT3)_C
PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;

d1 =-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PPphHH,'mNef,ABfmIN->ABIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PPPhHH,'mNeF,ABFmIN->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PPpHHh,'Mnef,ABfIMn->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PPPHHh,'MneF,ABFIMn->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PPpHHH,'MNef,ABfIMN->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PPPHHH,'MNeF,ABFIMN->ABIe');

d2 =+einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PPphHH,'Mnef,ABfnIM->ABIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPPhHH,'MneF,ABFnIM->ABIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PPpHHH,'MNef,ABfIMN->ABIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPPHHH,'MNeF,ABFIMN->ABIe');

Vt3A.PPHv = -d1 - d2;

d1 =+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPhHH,'MNeF,AbFiMN->Abie');

d2 =-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPphHH,'MNeF,AFbiMN->Abie');

Vt3A.Pphv = -d1 - d2;


d1 =-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhHH,'mNeF,AbFmIN->AbIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPHHh,'MneF,AbFIMn->AbIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPHHH,'MNeF,AbFIMN->AbIe');

d2 =-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphHH,'MneF,AFbnIM->AbIe')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPpHHH,'MNeF,AFbIMN->AbIe');

Vt3A.PpHv = -d1 - d2;


d1 =+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PPphHH,'MNef,ABfiMN->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PPPhHH,'MNeF,ABFiMN->ABie');

d2 =+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PPphHH,'MNef,ABfiMN->ABie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPPhHH,'MNeF,ABFiMN->ABie');

Vt3A.PPhv = -d1 - d2;

d1 =+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PPpHHh,'mnEf,AEfIJn->AmIJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.PpPHHh,'mneF,AeFIJn->AmIJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PPPHHh,'mnEF,AEFIJn->AmIJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PPpHHH,'mNEf,AEfIJN->AmIJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.PpPHHH,'mNeF,AeFIJN->AmIJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PPPHHH,'mNEF,AEFIJN->AmIJ');

d2 =-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PPphHH,'mneF,AFenIJ->AmIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPPhHH,'mnEF,AEFnIJ->AmIJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PPpHHH,'mNeF,AFeIJN->AmIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPPHHH,'mNEF,AEFIJN->AmIJ');

Vt3A.PoHH = d1 + d2;

d1 =+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PPphHH,'mNEf,AEfiJN->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.PpPhHH,'mNeF,AeFiJN->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PPPhHH,'mNEF,AEFiJN->AmiJ');

d2 =-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PPphHH,'mNeF,AFeiJN->AmiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPPhHH,'mNEF,AEFiJN->AmiJ');

Vt3A.PohH = d1 + d2;

d1 =-einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PpPHHh,'mnEF,EaFIJn->amIJ')...
-einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PpPHHH,'mNEF,EaFIJN->amIJ');

d2 =+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPphHH,'mnEF,EFanIJ->amIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPpHHH,'mNEF,EFaIJN->amIJ');

Vt3A.poHH = d1 + d2;

d1 =-einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PpPhHH,'mNEF,EaFiJN->amiJ');

d2 =+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPphHH,'mNEF,EFaiJN->amiJ');

Vt3A.pohH = d1 + d2;
end
