function [HBar] = build_HBar_debug(t1,t2,sys)

    fprintf('\n==============================================\n')
    fprintf('Building CCSD HBar...')

    H1 = cell(2,2);
    H2 = cell(2,2,2,2);
    H3 = cell(2,2,2,2,2,2);

    tic
    %%%%%%%%%%%%%%%%%%%%%%% One-Body HBar %%%%%%%%%%%%%%%%%%%%%%%

    % h_me
    H1{1,2} = sys.fov ...
              + einsum_kg(sys.Voovv,t1,'mnef,fn->me');

    % h_mi
    H1{1,1} = sys.foo ...
              + einsum_kg(sys.fov,t1,'me,ei->mi') ...
              + einsum_kg(sys.Vooov,t1,'mnif,fn->mi') ...
              + 0.5*einsum_kg(sys.Voovv,t2,'mnef,efin->mi') ...
              + einsum_kg(einsum_kg(sys.Voovv,t1,'mnef,fn->me'),t1,'me,ei->mi');

    % h_ae
    H1{2,2} = sys.fvv ...
              - einsum_kg(sys.fov,t1,'me,am->ae') ...
              + einsum_kg(sys.Vvovv,t1,'anef,fn->ae') ...
              - 0.5*einsum_kg(sys.Voovv,t2,'mnef,afmn->ae') ...
              - einsum_kg(einsum_kg(sys.Voovv,t1,'mnef,fn->me'),t1,'me,am->ae');

    %%%%%%%%%%%%%%%%%%%%%%% Two-Body HBar %%%%%%%%%%%%%%%%%%%%%%%

    % h_mnef
    H2{1,1,2,2} = sys.Voovv;

    % h_amef
    H2{2,1,2,2} = sys.Vvovv ...
                  - einsum_kg(sys.Voovv,t1,'nmef,an->amef');
    H2{1,2,2,2} = -permute(H2{2,1,2,2},[2,1,3,4]);

    % h_mnie
    H2{1,1,1,2} = sys.Vooov ...
                  + einsum_kg(sys.Voovv,t1,'mnfe,fi->mnie');
    H2{1,1,2,1} = -permute(H2{1,1,1,2},[1,2,4,3]);

    % h_mnij
    H2{1,1,1,1} = sys.Voooo ...
                  + einsum_kg(sys.Voovo,t1,'mnej,ei->mnij') - einsum_kg(sys.Voovo,t1,'mnei,ej->mnij') ...
                  + 0.5*einsum_kg(sys.Voovv,t2,'mnef,efij->mnij') ...
                  + einsum_kg(einsum_kg(sys.Voovv,t1,'mnef,ei->mnif'),t1,'mnif,fj->mnij');

    % h_abef
    H2{2,2,2,2} = sys.Vvvvv ...
                  - einsum_kg(sys.Vovvv,t1,'mbef,am->abef') + einsum_kg(sys.Vovvv,t1,'maef,bm->abef') ...
                  + 0.5*einsum_kg(sys.Voovv,t2,'mnef,abmn->abef') ...
                  + einsum_kg(einsum_kg(sys.Voovv,t1,'mnef,am->anef'),t1,'anef,bn->abef');

    % h_amie
    H2{2,1,1,2} = sys.Vvoov ...
                  - einsum_kg(sys.Vooov,t1,'nmie,an->amie') ...
                  + einsum_kg(sys.Vvovv,t1,'amfe,fi->amie') ...
                  - einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,an->amfe'),t1,'amfe,fi->amie') ...
                  + einsum_kg(sys.Voovv,t2,'nmfe,afin->amie');
    H2{1,2,1,2} = -permute(H2{2,1,1,2},[2,1,3,4]);
    H2{2,1,2,1} = -permute(H2{2,1,1,2},[1,2,4,3]);
    H2{1,2,2,1} = permute(H2{2,1,1,2},[2,1,4,3]);

    % h_abie
    H2{2,2,1,2} = sys.Vvvov ...
                     + einsum_kg(sys.Vvvvv,t1,'abfe,fi->abie') ...
                     - einsum_kg(sys.Vovov,t1,'mbie,am->abie') + einsum_kg(sys.Vovov,t1,'maie,bm->abie') ...
                     - einsum_kg(sys.fov,t2,'me,abim->abie') ...
                     + einsum_kg(sys.Vovvv,t2,'mbfe,afim->abie') - einsum_kg(sys.Vovvv,t2,'mafe,bfim->abie') ...
                     + 0.5*einsum_kg(sys.Vooov,t2,'mnie,abmn->abie') ...
                     + einsum_kg(einsum_kg(sys.Vooov,t1,'nmie,an->amie'),t1,'amie,bm->abie') ...
                     - einsum_kg(einsum_kg(sys.Vovvv,t1,'mbfe,am->abfe'),t1,'abfe,fi->abie') + einsum_kg(einsum_kg(sys.Vovvv,t1,'mafe,bm->abfe'),t1,'abfe,fi->abie') ...
                     + 0.5*einsum_kg(einsum_kg(sys.Voovv,t1,'mnfe,fi->mnie'),t2,'mnie,abmn->abie') ...
                     - einsum_kg(einsum_kg(sys.Voovv,t1,'mnfe,bn->mbfe'),t2,'mbfe,afim->abie') + einsum_kg(einsum_kg(sys.Voovv,t1,'mnfe,an->mafe'),t2,'mafe,bfim->abie') ...
                     - einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,fn->me'),t2,'me,abim->abie') ...
                     + einsum_kg(einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,bm->nbfe'),t1,'nbfe,fi->nbie'),t1,'nbie,an->abie');
    H2{2,2,2,1} = -permute(H2{2,2,1,2},[1,2,4,3]);

   % h_amij
   H2{2,1,1,1} = sys.Vvooo ...
                 + einsum_kg(sys.Vvovo,t1,'amej,ei->amij') - einsum_kg(sys.Vvovo,t1,'amei,ej->amij') ...
                 - einsum_kg(sys.Voooo,t1,'nmij,an->amij') ...
                 + einsum_kg(sys.fov,t2,'me,aeij->amij') ...
                 + 0.5*einsum_kg(sys.Vvovv,t2,'amfe,feij->amij') ...
                 + einsum_kg(sys.Voovo,t2,'nmej,aein->amij') - einsum_kg(sys.Voovo,t2,'nmei,aejn->amij') ...
                 - einsum_kg(einsum_kg(sys.Voovo,t1,'nmej,an->amej'),t1,'amej,ei->amij') + einsum_kg(einsum_kg(sys.Voovo,t1,'nmei,an->amei'),t1,'amei,ej->amij') ...
                 + einsum_kg(einsum_kg(sys.Vvovv,t1,'amfe,fi->amie'),t1,'amie,ej->amij') ...
                 - 0.5*einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,an->amef'),t2,'amef,feij->amij') ...
                 + einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,ej->nmfj'),t2,'nmfj,afin->amij') - einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,ei->nmfi'),t2,'nmfi,afjn->amij') ...
                 + einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,fn->me'),t2,'me,aeij->amij') ...
                 - einsum_kg(einsum_kg(einsum_kg(sys.Voovv,t1,'nmfe,an->amfe'),t1,'amfe,fi->amie'),t1,'amie,ej->amij'); 
    H2{1,2,1,1} = -permute(H2{2,1,1,1},[2,1,3,4]);

    % h_abij -> 0 by CCSD equations
    H2{2,2,1,1} = zeros(sys.Nunocc,sys.Nunocc,sys.Nocc,sys.Nocc);

    %%%%%%%%%%%%%%%%%%%%%%% Three-Body HBar %%%%%%%%%%%%%%%%%%%%%%%

    H3{2,2,1,1,1,2} =  -einsum_kg(sys.Voovo,t2,'mnej,abin->abmije') +...
                        einsum_kg(sys.Voovo,t2,'mnei,abjn->abmije') - ...
                        einsum_kg(einsum_kg(sys.Voovv,t1,'mnef,fi->mnei'),t2,'mnei,abnj->abmije') + ...
                        einsum_kg(einsum_kg(sys.Voovv,t1,'mnef,fj->mnej'),t2,'mnej,abni->abmije') + ...
                        einsum_kg(sys.Vovvv,t2,'mbef,afij->abmije') - ...
                        einsum_kg(sys.Vovvv,t2,'maef,bfij->abmije') - ...
                        einsum_kg(einsum_kg(sys.Voovv,t1,'mnef,an->maef'),t2,'maef,fbij->abmije') + ...
                        einsum_kg(einsum_kg(sys.Voovv,t1,'mnef,bn->mbef'),t2,'mbef,faij->abmije'); % W_abmije
    H3{2,1,2,1,2,1} = permute(H3{2,2,1,1,1,2},[1,3,2,4,6,5]);       
    H3{1,2,2,2,1,1} = permute(H3{2,2,1,1,1,2},[3,1,2,6,4,5]);
                   
    H3{1,1,2,1,1,1} = einsum_kg(H2{1,1,1,2},t2,'mnie,ecjk->mncijk')...
                       -einsum_kg(H2{1,1,1,2},t2,'mnje,ecik->mncijk')...
                       -einsum_kg(H2{1,1,1,2},t2,'mnke,ecji->mncijk');
%     H3{1,1,2,1,1,1} = einsum_kg(H2{1,1,1,2},t2,'nmje,ecik->mncijk')...
%                       -einsum_kg(H2{1,1,1,2},t2,'nmie,ecjk->mncijk')...
%                       -einsum_kg(H2{1,1,1,2},t2,'nmke,ecij->mncijk');
    H3{2,1,1,1,1,1} = permute(H3{1,1,2,1,1,1},[3,1,2,4,5,6]);
    H3{1,2,1,1,1,1} = -permute(H3{1,1,2,1,1,1},[1,3,2,4,5,6]);

    H3{2,2,2,2,2,1} = -einsum_kg(H2{2,1,2,2},t2,'amef,bcmk->abcefk')...
                      +einsum_kg(H2{2,1,2,2},t2,'bmef,acmk->abcefk')...
                      +einsum_kg(H2{2,1,2,2},t2,'cmef,bamk->abcefk');
    H3{2,2,2,2,1,2} = -permute(H3{2,2,2,2,2,1},[1,2,3,4,6,5]);
    H3{2,2,2,1,2,2} = permute(H3{2,2,2,2,2,1},[1,2,3,6,4,5]);

    H3{2,1,1,1,1,2} = einsum_kg(sys.Voovv,t2,'mnfe,afij->amnije'); % W_amnije
    H3{2,1,1,1,2,1} = -permute(H3{2,1,1,1,1,2},[1,2,3,4,6,5]);
    
    H3{2,2,1,1,2,2} = -einsum_kg(sys.Voovv,t2,'mnfe,abin->abmief'); % W_abmief
    H3{2,1,2,1,2,2} = -permute(H3{2,2,1,1,2,2},[1,3,2,4,5,6]);
    
    H3{2,2,2,1,1,2} = -einsum_kg(H2{2,1,1,2},t2,'amie,bcjm->abcije')...
                      +einsum_kg(H2{2,1,1,2},t2,'amje,bcim->abcije')... %(ij)
                      +einsum_kg(H2{2,1,1,2},t2,'bmie,acjm->abcije')... %(ab)
                      +einsum_kg(H2{2,1,1,2},t2,'cmie,bajm->abcije')... %(ac)
                      -einsum_kg(H2{2,1,1,2},t2,'bmje,acim->abcije')... %(ij)(ab)
                      -einsum_kg(H2{2,1,1,2},t2,'cmje,baim->abcije')... %(ij)(ac)
                      +einsum_kg(H2{2,2,2,2},t2,'acfe,fbij->abcije')... 
                      -einsum_kg(H2{2,2,2,2},t2,'bcfe,faij->abcije')... %(ab)
                      -einsum_kg(H2{2,2,2,2},t2,'abfe,fcij->abcije');   %(bc)
    H3{2,2,2,1,2,1} = -permute(H3{2,2,2,1,1,2},[1,2,3,4,6,5]);
    H3{2,2,2,2,1,1} = permute(H3{2,2,2,1,1,2},[1,2,3,6,4,5]);
                  
    H3{2,2,1,1,1,1} = einsum_kg(H2{2,1,1,2},t2,'amie,bejk->abmijk')...
                      -einsum_kg(H2{2,1,1,2},t2,'bmie,aejk->abmijk')... %(ab)
                      -einsum_kg(H2{2,1,1,2},t2,'amje,beik->abmijk')... %(ij)
                      -einsum_kg(H2{2,1,1,2},t2,'amke,beji->abmijk')... %(ik)
                      +einsum_kg(H2{2,1,1,2},t2,'bmje,aeik->abmijk')... %(ab)(ij)
                      +einsum_kg(H2{2,1,1,2},t2,'bmke,aeji->abmijk')... %(ab)(ik)
                      -einsum_kg(H2{1,1,1,1},t2,'mnki,abnj->abmijk')... 
                      +einsum_kg(H2{1,1,1,1},t2,'mnkj,abni->abmijk')... %(ij)
                      +einsum_kg(H2{1,1,1,1},t2,'mnji,abnk->abmijk');   %(jk)
    H3{2,1,2,1,1,1} = -permute(H3{2,2,1,1,1,1},[1,3,2,4,5,6]);
    H3{1,2,2,1,1,1} = permute(H3{2,2,1,1,1,1},[3,1,2,4,5,6]);
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    HBar = {H1,H2,H3};

    fprintf(' completed in %4.2f seconds\n',toc);
    fprintf('==============================================\n')

end


