function [HBar_t] = build_ucc_HBar( cc_t, sys, flag_build_3body)

    addpath(genpath('/Users/harellab/Dropbox/Hartree Fock/hartree_fock/v4/utils'));
    
    %%%% IMPORTANT %%%%
    % Do A and C permutations (for 2-body HBar) need phase factors
    % corresponding to each swap? Maybe not because the A and C tensors are
    % antisymmetric by construction. Only the B tensor needs the minus
    % signs explicitly.

    if nargin < 3
        flag_build_3body = false;
    end

    
    t1a = cc_t.t1a;
    t1b = cc_t.t1b;
    t2a = cc_t.t2a;
    t2b = cc_t.t2b;
    t2c = cc_t.t2c;
    
    Nocc_a = sys.Nocc_alpha; Nocc_b = sys.Nocc_beta;
    Nunocc_a = sys.Nvir_alpha; Nunocc_b = sys.Nvir_beta;
    
    fprintf('\n====================================++Building UCCSD HBar++===================================\n')

    tic_Start = tic;
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%++1-Body HBar++%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    %%%%%%%%%%%%%%%%%%%%% H1A %%%%%%%%%%%%%%%%%%%
    
    fprintf('Building H1A... ')
    tic
    % h1A(mi)
    H1A.oo = sys.fa_oo ...
             +einsum_kg(sys.fa_ov,t1a,'me,ei->mi')...
             +einsum_kg(sys.vA_ooov,t1a,'mnif,fn->mi')...
             +einsum_kg(sys.vB_ooov,t1b,'mnif,fn->mi')...
             +0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efin->mi')...
             +einsum_kg(sys.vB_oovv,t2b,'mnef,efin->mi')...
             +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,ei->mi')...
             +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,ei->mi');
         
    % h1A(ae)
    H1A.vv = sys.fa_vv ...
             -einsum_kg(sys.fa_ov,t1a,'me,am->ae')...
             +einsum_kg(sys.vA_vovv,t1a,'amef,fm->ae')...
             +einsum_kg(sys.vB_vovv,t1b,'anef,fn->ae')...
             -0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,afmn->ae')...
             -einsum_kg(sys.vB_oovv,t2b,'mnef,afmn->ae')...
             -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,am->ae')...
             -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,am->ae');
         
    % h1A(me)
    H1A.ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');

    fprintf('done in %4.8f s\n',toc)

    %%%%%%%%%%%%%%%%%%%%% H1B %%%%%%%%%%%%%%%%%%%

    fprintf('Building H1B... ')
    tic
    % h1B(mi)
    H1B.oo = sys.fb_oo ...
             +einsum_kg(sys.fb_ov,t1b,'me,ei->mi')...
             +einsum_kg(sys.vB_oovo,t1a,'nmfi,fn->mi')...
             +einsum_kg(sys.vC_ooov,t1b,'mnif,fn->mi')...
             +einsum_kg(sys.vB_oovv,t2b,'nmfe,feni->mi')...
             +0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,efin->mi')...
             +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t1b,'me,ei->mi')...
             +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t1b,'me,ei->mi');
         
    % h1B(ae)
    H1B.vv = sys.fb_vv ...
             -einsum_kg(sys.fb_ov,t1b,'me,am->ae')...
             +einsum_kg(sys.vB_ovvv,t1a,'nafe,fn->ae')...
             +einsum_kg(sys.vC_vovv,t1b,'anef,fn->ae')...
             -einsum_kg(sys.vB_oovv,t2b,'nmfe,fanm->ae')...
             -0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,afmn->ae')...
             -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t1b,'me,am->ae')...
             -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t1b,'me,am->ae');
         
    % h1B(me)
    H1B.ov = sys.fb_ov + einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me') + einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me');

    fprintf('done in %4.8f s\n',toc)
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%++2-Body HBar++%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

	
    %%%%%%%%%%%%%%%%%%%%% H2A %%%%%%%%%%%%%%%%%%%
    
    fprintf('Building H2A... ')
    tic
    % h2A(amij)
    H2A.vooo    = sys.vA_vooo ...
                  +einsum_kg(sys.vA_voov,t1a,'amie,ej->amij')...
	    			-einsum_kg(sys.vA_voov,t1a,'amje,ei->amij')...
                  -einsum_kg(sys.vA_oooo,t1a,'nmij,an->amij')...
                  +einsum_kg(sys.fa_ov,t2a,'me,aeij->amij')...
                  +0.5*einsum_kg(sys.vA_vovv,t2a,'amef,efij->amij')...
                  +einsum_kg(sys.vA_oovo,t2a,'nmej,aein->amij')...
	    			-einsum_kg(sys.vA_oovo,t2a,'nmei,aejn->amij')...
                  +einsum_kg(sys.vB_ooov,t2b,'mnje,aein->amij')...
	    			-einsum_kg(sys.vB_ooov,t2b,'mnie,aejn->amij')...
                  -einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmej,ei->nmij'),t1a,'nmij,an->amij')...
	    			+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmei,ej->nmij'),t1a,'nmij,an->amij')...
                  +einsum_kg(einsum_kg(sys.vA_vovv,t1a,'amef,ei->amif'),t1a,'amif,fj->amij')...
                  -0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,an->amef'),t2a,'amef,efij->amij')...
                  +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ej->mnjf'),t2a,'mnjf,afin->amij')...
	    			-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t2a,'mnif,afjn->amij')...
                  +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,aeij->amij')...
                  +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t2b,'mnjf,afin->amij')...
	    			-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ei->mnif'),t2b,'mnif,afjn->amij')...
                  +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,aeij->amij')...
                  -einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,fj->nmej'),t1a,'nmej,an->amej'),t1a,'amej,ei->amij');
    H2A.ovoo =    -permute(H2A.vooo,[2,1,3,4]);

    % h(abie)
    H2A.vvov  = sys.vA_vvov ...
	    	+einsum_kg(sys.vA_vvvv,t1a,'abfe,fi->abie')...
	    	-einsum_kg(sys.vA_ovov,t1a,'nbie,an->abie')...
	    			+einsum_kg(sys.vA_ovov,t1a,'naie,bn->abie')...
	    	-einsum_kg(sys.fa_ov,t2a,'me,abim->abie')...
	    	+einsum_kg(sys.vA_ovvv,t2a,'nbfe,afin->abie')...
	    			-einsum_kg(sys.vA_ovvv,t2a,'nafe,bfin->abie')...
	    	+0.5*einsum_kg(sys.vA_oovo,t2a,'mnei,abnm->abie')...
	    	+einsum_kg(sys.vB_vovv,t2b,'bnef,afin->abie')...
	    			-einsum_kg(sys.vB_vovv,t2b,'anef,bfin->abie')...
	    	+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'mnei,an->maei'),t1a,'maei,bm->abie')...
	    	-einsum_kg(einsum_kg(sys.vA_vovv,t1a,'bnef,fi->bnei'),t1a,'bnei,an->abie')...
	    			+einsum_kg(einsum_kg(sys.vA_vovv,t1a,'anef,fi->anei'),t1a,'anei,bn->abie')...
	    	+0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fi->mnei'),t2a,'mnei,abnm->abie')...
	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t2a,'bnef,afin->abie')...
	    			+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,am->anef'),t2a,'anef,bfin->abie')...
	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,abim->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,bm->bnef'),t2b,'bnef,afin->abie')...
	    			+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,am->anef'),t2b,'anef,bfin->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,abim->abie')...
	    	+einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t1a,'bnef,an->baef'),t1a,'baef,fi->abie');
     H2A.vvvo = -permute(H2A.vvov,[1,2,4,3]);

     % h2A(mnij)
     H2A.oooo = sys.vA_oooo...
	     	+einsum_kg(sys.vA_oovo,t1a,'mnej,ei->mnij')...
	     			-einsum_kg(sys.vA_oovo,t1a,'mnei,ej->mnij')...
	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efij->mnij')...
	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t1a,'mnif,fj->mnij');

     % h2A(abef)
     H2A.vvvv = sys.vA_vvvv...
	     	-einsum_kg(sys.vA_ovvv,t1a,'mbef,am->abef')...
	     			+einsum_kg(sys.vA_ovvv,t1a,'maef,bm->abef')...
	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,abmn->abef')...
	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bn->mbef'),t1a,'mbef,am->abef');
        
     % h2A(amie)
     H2A.voov = sys.vA_voov ...
                -einsum_kg(sys.vA_ooov,t1a,'nmie,an->amie')...
                +einsum_kg(sys.vA_vovv,t1a,'amfe,fi->amie')...
                -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
                +einsum_kg(sys.vA_oovv,t2a,'nmfe,afin->amie')...
                +einsum_kg(sys.vB_oovv,t2b,'mnef,afin->amie');
%      H2A.ovov = -permute(H2A.voov,[2,1,3,4]);
%      H2A.vovo = -permute(H2A.voov,[1,2,4,3]);
%     H2A.ovvo = -permute(H2A.voov,[2,1,4,3]); LCC WORKS WHEN - SIGN???
     
     % h2A(amef)
     H2A.vovv = sys.vA_vovv - einsum_kg(sys.vA_oovv,t1a,'mnfe,an->amef');
     H2A.ovvv = -permute(H2A.vovv,[2,1,3,4]);
     
     % h2A(mnie)
     H2A.ooov = sys.vA_ooov + einsum_kg(sys.vA_oovv,t1a,'mnfe,fi->mnie');
     H2A.oovo = -permute(H2A.ooov,[1,2,4,3]);
     
     % h2A(mnef)
     H2A.oovv = sys.vA_oovv;

    fprintf('done in %4.8f s\n',toc)

    %%%%%%%%%%%%%%%%%%%%% H2B %%%%%%%%%%%%%%%%%%%
        
    fprintf('Building H2B... ')
    tic
    % h2B(amij)
    H2B.vooo = sys.vB_vooo...
               -einsum_kg(sys.vB_oooo,t1a,'nmij,an->amij')...
               +einsum_kg(sys.vB_vovo,t1a,'amej,ei->amij')...
               +einsum_kg(sys.vB_voov,t1b,'amie,ej->amij')...
               +einsum_kg(sys.vB_oovo,t2a,'nmej,aein->amij')...
               +einsum_kg(sys.vC_oovo,t2b,'nmej,aein->amij')...
               +einsum_kg(sys.vB_vovv,t2b,'amef,efij->amij')...
               -einsum_kg(sys.vB_ooov,t2b,'nmif,afnj->amij')...
               +einsum_kg(sys.fb_ov,t2b,'me,aeij->amij')...
               -einsum_kg(einsum_kg(sys.vB_oovo,t1a,'nmej,an->amej'),t1a,'amej,ei->amij')...
               -einsum_kg(einsum_kg(sys.vB_ooov,t1b,'nmie,ej->nmij'),t1a,'nmij,an->amij')...
               +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,ej->mnjf'),t2b,'mnjf,afin->amij')...
               +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t2b,'me,aeij->amij')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,an->amfe'),t2b,'amfe,feij->amij')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t2b,'nmie,aenj->amij')...
               +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t2b,'me,aeij->amij')...
               +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,ej->nmfj'),t2a,'nmfj,afin->amij')...
               -einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,ej->nmfj'),t1a,'nmfj,an->amfj'),t1a,'amfj,fi->amij')...
               +einsum_kg(einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie'),t1b,'amie,ej->amij');

    % h2B(maji)
    H2B.ovoo =  sys.vB_ovoo...
                +einsum_kg(sys.vB_ovvo,t1a,'maei,ej->maji')...
                -einsum_kg(sys.vB_oooo,t1b,'mnji,an->maji')...
                +einsum_kg(sys.vB_ovov,t1b,'majf,fi->maji')...
                +einsum_kg(sys.vB_ooov,t2c,'mnjf,afin->maji')...
                +einsum_kg(sys.vB_ovvv,t2b,'maef,efji->maji')...
                +einsum_kg(sys.vA_ooov,t2b,'mnjf,fani->maji')...
                -einsum_kg(sys.vB_oovo,t2b,'mnei,eajn->maji')...
	        +einsum_kg(sys.fa_ov,t2b,'me,eaji->maji')...
	    	-einsum_kg(einsum_kg(sys.vB_ooov,t1b,'mnjf,an->majf'),t1b,'majf,fi->maji')...
	    	+einsum_kg(einsum_kg(sys.vB_ovvv,t1a,'maef,ej->majf'),t1b,'majf,fi->maji')...
	    	-einsum_kg(einsum_kg(sys.vB_oovo,t1a,'mnei,ej->mnji'),t1b,'mnji,an->maji')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t2c,'mnjf,afin->maji')...
	    	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2b,'me,eaji->maji')...
	    	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ej->mnjf'),t2b,'mnjf,fani->maji')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,an->maef'),t2b,'maef,efji->maji')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2b,'me,eaji->maji')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t2b,'mnei,eajn->maji')...
	    	-einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t1b,'mnjf,an->majf'),t1b,'majf,fi->maji');

    % h2B(abie)
    H2B.vvov =  sys.vB_vvov...
	    	-einsum_kg(sys.vB_ovov,t1a,'nbie,an->abie')...
	    	+einsum_kg(sys.vB_vvvv,t1a,'abfe,fi->abie')...
	    	-einsum_kg(sys.vB_voov,t1b,'amie,bm->abie')...
	    	+einsum_kg(sys.vB_ovvv,t2a,'nbfe,afin->abie')...
	    	+einsum_kg(sys.vC_ovvv,t2b,'nbfe,afin->abie')...
	    	+einsum_kg(sys.vB_ooov,t2b,'nmie,abnm->abie')...
	    	-einsum_kg(sys.vB_vovv,t2b,'amfe,fbim->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_ovvv,t1a,'nbfe,an->abfe'),t1a,'abfe,fi->abie')...
	    	+einsum_kg(einsum_kg(sys.vB_ooov,t1a,'nmie,an->amie'),t1b,'amie,bm->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie'),t1b,'amie,bm->abie')...
	    	-einsum_kg(sys.fb_ov,t2b,'me,abim->abie')...
	    	-einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,bm->bnef'),t2b,'bnef,afin->abie')...
	    	-einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t2b,'me,abim->abie')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t2b,'nmie,abnm->abie')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,an->amfe'),t2b,'amfe,fbim->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t2b,'me,abim->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,bm->nbfe'),t2a,'nbfe,afin->abie')...
	    	+einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,an->amfe'),t1a,'amfe,fi->amie'),t1b,'amie,bm->abie');

    % h2B(baei)
    H2B.vvvo =  sys.vB_vvvo...
	    	+einsum_kg(sys.vB_vvvv,t1b,'baef,fi->baei')...
	    	-einsum_kg(sys.vB_vovo,t1b,'bnei,an->baei')...
	    	-einsum_kg(sys.vB_ovvo,t1a,'maei,bm->baei')...
	    	+einsum_kg(sys.vB_vovv,t2c,'bnef,afin->baei')...
	    	+einsum_kg(sys.vB_oovo,t2b,'mnei,bamn->baei')...
	    	+einsum_kg(sys.vA_vovv,t2b,'bnef,fani->baei')...
	    	-einsum_kg(sys.vB_ovvv,t2b,'maef,bfmi->baei')...
	    	-einsum_kg(sys.fa_ov,t2b,'me,bami->baei')...
	    	-einsum_kg(einsum_kg(sys.vB_vovv,t1b,'bnef,fi->bnei'),t1b,'bnei,an->baei')...
	    	+einsum_kg(einsum_kg(sys.vB_oovo,t1b,'mnei,an->maei'),t1a,'maei,bm->baei')...
	    	-einsum_kg(einsum_kg(sys.vB_ovvv,t1b,'maef,fi->maei'),t1a,'maei,bm->baei')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,bm->bnef'),t2c,'bnef,afin->baei')...
	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2b,'me,bami->baei')...
	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t2b,'bnef,fani->baei')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t2b,'mnei,bamn->baei')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2b,'me,bami->baei')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,an->maef'),t2b,'maef,bfmi->baei')...
	    	+einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,an->maef'),t1b,'maef,fi->maei'),t1a,'maei,bm->baei');

    % h2B(mnij)
    H2B.oooo =  sys.vB_oooo...
	    	+einsum_kg(sys.vB_oovo,t1a,'mnej,ei->mnij')...
	   	+einsum_kg(sys.vB_ooov,t1b,'mnif,fj->mnij')...
	   	+einsum_kg(sys.vB_oovv,t2b,'mnef,efij->mnij')...
	   	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ei->mnif'),t1b,'mnif,fj->mnij'); 

    % h2B(abef)
    H2B.vvvv =  sys.vB_vvvv...
	    	-einsum_kg(sys.vB_ovvv,t1a,'mbef,am->abef')...
	    	-einsum_kg(sys.vB_vovv,t1b,'anef,bn->abef')...
	    	+einsum_kg(sys.vB_oovv,t2b,'mnef,abmn->abef')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,am->anef'),t1b,'anef,bn->abef');
        
    % h2B(amie)
    H2B.voov = sys.vB_voov ...
               -einsum_kg(sys.vB_ooov,t1a,'nmie,an->amie')...
               +einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
               +einsum_kg(sys.vB_oovv,t2a,'nmfe,afin->amie')...
               +einsum_kg(sys.vC_oovv,t2b,'mnef,afin->amie');
          
    % h2B(maie)
    H2B.ovov = sys.vB_ovov ...
               +einsum_kg(sys.vB_ovvv,t1a,'mafe,fi->maie')...
               -einsum_kg(sys.vB_ooov,t1b,'mnie,an->maie')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnfe,an->mafe'),t1a,'mafe,fi->maie')...
               -einsum_kg(sys.vB_oovv,t2b,'mnfe,fain->maie');
           
    % h2B(amei)
    H2B.vovo = sys.vB_vovo ...
               -einsum_kg(sys.vB_oovo,t1a,'nmei,an->amei')...
               +einsum_kg(sys.vB_vovv,t1b,'amef,fi->amei')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmef,fi->nmei'),t1a,'nmei,an->amei')...
               -einsum_kg(sys.vB_oovv,t2b,'nmef,afni->amei');
           
    % h2B(maei)
    H2B.ovvo = sys.vB_ovvo ...
               +einsum_kg(sys.vB_ovvv,t1b,'maef,fi->maei')...
               -einsum_kg(sys.vB_oovo,t1b,'mnei,an->maei')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->maei')...
               +einsum_kg(sys.vB_oovv,t2c,'mnef,afin->maei')...
               +einsum_kg(sys.vA_oovv,t2b,'mnef,fani->maei');
           
    % h2B(amef)
    H2B.vovv = sys.vB_vovv - einsum_kg(sys.vB_oovv,t1a,'nmef,an->amef');
    
    % h2B(mafe)
    H2B.ovvv = sys.vB_ovvv - einsum_kg(sys.vB_oovv,t1b,'mnfe,an->mafe');
    
    % h2B(mnie)
    H2B.ooov = sys.vB_ooov + einsum_kg(sys.vB_oovv,t1a,'mnfe,fi->mnie');
    
    % h2B(nmei)
    H2B.oovo = sys.vB_oovo + einsum_kg(sys.vB_oovv,t1b,'nmef,fi->nmei');
    
    % h2B(mnef)
    H2B.oovv = sys.vB_oovv;
    
    fprintf('done in %4.8f s\n',toc)

    %%%%%%%%%%%%%%%%%%%%% H2C %%%%%%%%%%%%%%%%%%%

    fprintf('Building H2C... ')
    tic
    % h2C(amij)
    H2C.vooo =  sys.vC_vooo ...
	    	+einsum_kg(sys.vC_vovo,t1b,'amej,ei->amij')...
	    			-einsum_kg(sys.vC_vovo,t1b,'amei,ej->amij')...
	    	-einsum_kg(sys.vC_oooo,t1b,'nmij,an->amij')...
	    	+einsum_kg(sys.vB_oovo,t2b,'nmfj,fani->amij')...
	    			-einsum_kg(sys.vB_oovo,t2b,'nmfi,fanj->amij')...
	    	+0.5*einsum_kg(sys.vC_vovv,t2c,'amfe,feij->amij')...
	    	+einsum_kg(sys.vC_ooov,t2c,'mnjf,afin->amij')...
	    			-einsum_kg(sys.vC_ooov,t2c,'mnif,afjn->amij')...
	    	+einsum_kg(sys.fb_ov,t2c,'me,aeij->amij')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t2c,'me,aeij->amij')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,ej->nmfj'),t2b,'nmfj,fani->amij')...
	    			-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,ei->nmfi'),t2b,'nmfi,fanj->amij')...
	    	-einsum_kg(einsum_kg(sys.vC_ooov,t1b,'mnjf,an->majf'),t1b,'majf,fi->amij')...
	    			+einsum_kg(einsum_kg(sys.vC_ooov,t1b,'mnif,an->maif'),t1b,'maif,fj->amij')...
	    	+einsum_kg(einsum_kg(sys.vC_vovv,t1b,'amfe,fi->amie'),t1b,'amie,ej->amij')...
	    	-0.5*einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,an->maef'),t2c,'maef,feij->amij')...
	    	+einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,ej->mnjf'),t2c,'mnjf,afin->amij')...
	    			-einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,ei->mnif'),t2c,'mnif,afjn->amij')...
	    	+einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t2c,'me,aeij->amij')...
	    	-einsum_kg(einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,ej->mnjf'),t1b,'mnjf,fi->mnji'),t1b,'mnji,an->amij');
    H2C.ovoo = -permute(H2C.vooo,[2,1,3,4]);

    % h2C(abie)
    H2C.vvov =  sys.vC_vvov...
	    	+einsum_kg(sys.vC_vvvv,t1b,'abfe,fi->abie')...
	    	-einsum_kg(sys.vC_ovov,t1b,'nbie,an->abie')...
	    			+einsum_kg(sys.vC_ovov,t1b,'naie,bn->abie')...
	    	+einsum_kg(sys.vB_ovvv,t2b,'nbfe,fani->abie')...
	    			-einsum_kg(sys.vB_ovvv,t2b,'nafe,fbni->abie')...
	    	+0.5*einsum_kg(sys.vC_oovo,t2c,'mnei,abnm->abie')...
	    	+einsum_kg(sys.vC_ovvv,t2c,'nbfe,afin->abie')...
	    			-einsum_kg(sys.vC_ovvv,t2c,'nafe,bfin->abie')...
	    	-einsum_kg(sys.fb_ov,t2c,'me,abim->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t2c,'me,abim->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,bm->nbfe'),t2b,'nbfe,fani->abie')...
	    			+einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,am->nafe'),t2b,'nafe,fbni->abie')...
	    	-einsum_kg(einsum_kg(sys.vC_ovvv,t1b,'nbfe,an->abfe'),t1b,'abfe,fi->abie')...
	    			+einsum_kg(einsum_kg(sys.vC_ovvv,t1b,'nafe,bn->bafe'),t1b,'bafe,fi->abie')...
	    	+einsum_kg(einsum_kg(sys.vC_oovo,t1b,'mnei,bm->bnei'),t1b,'bnei,an->abie')...
	    	-einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,bm->bnef'),t2c,'bnef,afin->abie')...
	    			+einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,am->anef'),t2c,'anef,bfin->abie')...
	    	+0.5*einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fi->mnei'),t2c,'mnei,abnm->abie')...
	    	-einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t2c,'me,abim->abie')...
	    	+einsum_kg(einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,bm->bnef'),t1b,'bnef,an->baef'),t1b,'baef,fi->abie');
     H2C.vvvo = -permute(H2C.vvov,[1,2,4,3]);

     % h2C(mnij)
     H2C.oooo = sys.vC_oooo...
	      	+einsum_kg(sys.vC_ooov,t1b,'mnie,ej->mnij')...
	    			-einsum_kg(sys.vC_ooov,t1b,'mnje,ei->mnij')...
	    	+0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,efij->mnij')...
	    	+einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,ei->mnif'),t1b,'mnif,fj->mnij'); 

     % h2C(abef)
     H2C.vvvv = sys.vC_vvvv...
	     	-einsum_kg(sys.vC_ovvv,t1b,'mbef,am->abef')...
	     			+einsum_kg(sys.vC_ovvv,t1b,'maef,bm->abef')...
	     	+0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,abmn->abef')...
	     	+einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,bn->mbef'),t1b,'mbef,am->abef');
	      
     % h2C(amie)
     H2C.voov = sys.vC_voov ...
                -einsum_kg(sys.vC_oovo,t1b,'mnei,an->amie')...
                +einsum_kg(sys.vC_vovv,t1b,'amfe,fi->amie')...
                -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->amie')...
                +einsum_kg(sys.vC_oovv,t2c,'mnef,afin->amie')...
                +einsum_kg(sys.vB_oovv,t2b,'nmfe,fani->amie');
%      H2C.ovov = -permute(H2C.voov,[2,1,3,4]);
%      H2C.vovo = -permute(H2C.voov,[1,2,4,3]);
%      H2C.ovvo = permute(H2C.voov,[2,1,4,3]);
     
     % h2C(amef)
     H2C.vovv = sys.vC_vovv - einsum_kg(sys.vC_oovv,t1b,'mnfe,an->amef');
     H2C.ovvv = -permute(H2C.vovv,[2,1,3,4]);
     
     % h2C(mnie)
     H2C.ooov = sys.vC_ooov + einsum_kg(sys.vC_oovv,t1b,'mnfe,fi->mnie');
     H2C.oovo = -permute(H2C.ooov,[1,2,4,3]);

     % h2C(mnef)
     H2C.oovv = sys.vC_oovv;

    fprintf('done in %4.8f s\n',toc)
    		
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%++3-Body HBar++%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    if flag_build_3body
    
        %%%%%%%%%%%%%%%%%%%%% H3A %%%%%%%%%%%%%%%%%%%

        fprintf('Building H3A... ')
        tic
        % h3A(abmije)
        H3A.vvooov = -einsum_kg(sys.vA_oovo,t2a,'mnei,abnj->abmije') ...
                            +einsum_kg(sys.vA_oovo,t2a,'mnej,abni->abmije') ...
                     +einsum_kg(sys.vA_vovv,t2a,'amfe,fbij->abmije') ...
                            -einsum_kg(sys.vA_vovv,t2a,'bmfe,faij->abmije')...
                     -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmfe,fi->nmie'),t2a,'nmie,abnj->abmije')...
                            +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmfe,fj->nmje'),t2a,'nmje,abni->abmije')...
                     -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmfe,an->amfe'),t2a,'amfe,fbij->abmije')...
                            +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmfe,bn->bmfe'),t2a,'bmfe,faij->abmije');
        H3A.vovovo = permute(H3A.vvooov,[1,3,2,4,6,5]); 
        H3A.ovvvoo = permute(H3A.vvooov,[3,1,2,6,4,5]);
        
        % h3A(mncijk)
        H3A.oovooo = einsum_kg(H2A.ooov,t2a,'mnie,ecjk->mncijk')...
                     -einsum_kg(H2A.ooov,t2a,'mnje,ecik->mncijk')...
                     -einsum_kg(H2A.ooov,t2a,'mnke,ecji->mncijk');

        % h3A(abcefk)
        H3A.vvvvvo = -einsum_kg(H2A.vovv,t2a,'amef,bcmk->abcefk')...
                      +einsum_kg(H2A.vovv,t2a,'bmef,acmk->abcefk')...
                      +einsum_kg(H2A.vovv,t2a,'cmef,bamk->abcefk');

        % h3A(abmief)
        H3A.vvoovv = -einsum_kg(sys.vA_oovv,t2a,'mnfe,abin->abmief');
        H3A.vovovv = -permute(H3A.vvoovv,[1,3,2,4,5,6]);
        H3A.vvovov = -permute(H3A.vvoovv,[1,2,3,5,4,6]);
        H3A.vovvov = permute(H3A.vvoovv,[1,3,2,5,4,6]);

        % h3A(amnije)
        H3A.voooov = einsum_kg(sys.vA_oovv,t2a,'mnfe,afij->amnije');
        H3A.vooovo = -permute(H3A.voooov,[1,2,3,4,6,5]);
        H3A.oovovo = -permute(H3A.voooov,[2,3,1,4,6,5]);
        H3A.ovooov = -permute(H3A.voooov,[2,1,3,4,5,6]);
        
        % h3A(vvvoov)
        H3A.vvvoov =  -einsum_kg(H2A.voov,t2a,'amie,bcjm->abcije')...
                            +einsum_kg(H2A.voov,t2a,'amje,bcim->abcije')... %(ij)
                            +einsum_kg(H2A.voov,t2a,'bmie,acjm->abcije')... %(ab)
                            +einsum_kg(H2A.voov,t2a,'cmie,bajm->abcije')... %(ac)
                            -einsum_kg(H2A.voov,t2a,'bmje,acim->abcije')... %(ij)(ab)
                            -einsum_kg(H2A.voov,t2a,'cmje,baim->abcije')... %(ij)(ac)
                      +einsum_kg(H2A.vvvv,t2a,'acfe,fbij->abcije')... 
                            -einsum_kg(H2A.vvvv,t2a,'bcfe,faij->abcije')... %(ab)
                            -einsum_kg(H2A.vvvv,t2a,'abfe,fcij->abcije');   %(bc)
                  
        % h3A(vvoooo)          
        D1 = einsum_kg(H2A.voov,t2a,'amie,bejk->abmijk');
        D1 = D1 - permute(D1,[1,2,3,6,5,4]) - permute(D1,[1,2,3,5,4,6]);
        D1 = D1 - permute(D1,[2,1,3,4,5,6]);
        D2 = -einsum_kg(H2A.oooo,t2a,'nmjk,abin->abmijk');
        D2 = D2 - permute(D2,[1,2,3,6,5,4]) - permute(D2,[1,2,3,5,4,6]);
        H3A.vvoooo = D1 + D2;
                                    

        fprintf('done in %4.8f s\n',toc)

        %%%%%%%%%%%%%%%%%%%%% H3B %%%%%%%%%%%%%%%%%%%

        fprintf('Building H3B... ')
        tic
        % h3B(abmije)
        H3B.vvooov = -einsum_kg(sys.vB_ooov,t2a,'nmie,abnj->abmije')...
                            +einsum_kg(sys.vB_ooov,t2a,'nmje,abni->abmije')...
                     +einsum_kg(sys.vB_vovv,t2a,'amfe,fbij->abmije')...
                            -einsum_kg(sys.vB_vovv,t2a,'bmfe,faij->abmije')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t2a,'nmie,abnj->abmije')...
                            +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fj->nmje'),t2a,'nmje,abni->abmije')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,an->amfe'),t2a,'amfe,fbij->abmije')...
                            +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,bn->bmfe'),t2a,'bmfe,faij->abmije');

        % h3B(ambiej)                
        H3B.vovovo = einsum_kg(sys.vB_ovvv,t2b,'mbef,afij->ambiej')...
                     -einsum_kg(sys.vB_oovo,t2b,'mnej,abin->ambiej')...
                     -einsum_kg(sys.vA_ooov,t2b,'nmie,abnj->ambiej')...
                     +einsum_kg(sys.vA_vovv,t2b,'amfe,fbij->ambiej')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fj->nmej'),t2b,'nmej,abin->ambiej')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,bn->mbef'),t2b,'mbef,afij->ambiej')...
                     -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fi->mnei'),t2b,'mnei,abnj->ambiej')...
                     -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,an->maef'),t2b,'maef,fbij->ambiej');
        H3B.ovvvoo = permute(H3B.vovovo,[2,1,3,5,4,6]); 

        % h3B(ambije)
        H3B.vovoov = einsum_kg(sys.vB_ovvv,t2a,'mbfe,afij->ambije')...
                     -einsum_kg(sys.vB_ooov,t2b,'mnje,abin->ambije')...
                            +einsum_kg(sys.vB_ooov,t2b,'mnie,abjn->ambije')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnfe,fj->mnje'),t2b,'mnje,abin->ambije')...
                            +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnfe,fi->mnie'),t2b,'mnie,abjn->ambije')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnfe,bn->mbfe'),t2a,'mbfe,afij->ambije');

        % h3B(abmiej)
        H3B.vvoovo = -einsum_kg(sys.vB_oovo,t2a,'nmej,abin->abmiej')...
                     +einsum_kg(sys.vB_vovv,t2b,'bmef,afij->abmiej')...
                            -einsum_kg(sys.vB_vovv,t2b,'amef,bfij->abmiej')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmef,bn->bmef'),t2b,'bmef,afij->abmiej')...
                            +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmef,an->amef'),t2b,'amef,bfij->abmiej')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmef,fj->nmej'),t2a,'nmej,abin->abmiej');
                 
        % h3B(anmijk)
        H3B.vooooo = einsum_kg(H2B.oovo,t2a,'nmfk,afij->anmijk')...
                     +einsum_kg(H2B.ooov,t2b,'nmjf,afik->anmijk')...
                            -einsum_kg(H2B.ooov,t2b,'nmif,afjk->anmijk');
        
        % h3B(mncijk)
        H3B.oovooo = einsum_kg(H2A.ooov,t2b,'mnif,fcjk->mncijk')...
                            -einsum_kg(H2A.ooov,t2b,'mnjf,fcik->mncijk');
                        
        % h3B(abcief)
        H3B.vvvovv = -einsum_kg(H2B.ovvv,t2a,'mcef,abim->abcief')...
                     -einsum_kg(H2B.vovv,t2b,'bmef,acim->abcief')...
                            +einsum_kg(H2B.vovv,t2b,'amef,bcim->abcief');
                        
        % h3B(abcefk)
        H3B.vvvvvo = -einsum_kg(H2A.vovv,t2b,'amef,bcmk->abcefk')...
                            +einsum_kg(H2A.vovv,t2b,'bmef,acmk->abcefk');

        % h3B(abmief)
        H3B.vvoovv = -einsum_kg(sys.vB_oovv,t2a,'nmef,abin->abmief');
        H3B.vvovov = -permute(H3B.vvoovv,[1,2,3,5,4,6]);

        % h3B(bmaefi)
        H3B.vovvvo = -einsum_kg(sys.vA_oovv,t2b,'nmef,bani->bmaefi');

        % h3B(ambife)
        H3B.vovovv = -einsum_kg(sys.vB_oovv,t2b,'mnfe,abin->ambife');
        H3B.ovvvov = permute(H3B.vovovv,[2,1,3,5,4,6]);

        % h3B(abmefi) -> not allowed
        H3B.vvovvo = zeros(Nunocc_a,Nunocc_a,Nocc_b,Nunocc_a,Nunocc_a,Nocc_b);

        % h3B(amnije)
        H3B.voooov = einsum_kg(sys.vB_oovv,t2a,'mnfe,afij->amnije');

        % h3B(mnajei)
        H3B.oovovo = einsum_kg(sys.vA_oovv,t2b,'mnfe,faji->mnajei');
    %    H3B.ovooov = permute(H3B.oovovo,[1,3,2,4,6,5]);

        % h3B(anmiej)
        H3B.vooovo = einsum_kg(sys.vB_oovv,t2b,'nmef,afij->anmiej');
    %    H3B.ovovoo = permute(H3B.vooovo,[2,1,3,5,4,6]);

        % h3B( -> not allowed
        H3B.oovoov = zeros(Nocc_a,Nocc_a,Nunocc_b,Nocc_a,Nocc_a,Nunocc_b);
        
        % h3B(vvvoov)
        H3B.vvvoov = -einsum_kg(H2B.voov,t2b,'amie,bcjm->abcije')...
                     +einsum_kg(H2B.voov,t2b,'bmie,acjm->abcije')...
                     +einsum_kg(H2B.voov,t2b,'amje,bcim->abcije')...
                     -einsum_kg(H2B.voov,t2b,'bmje,acim->abcije')...
                     -einsum_kg(H2B.ovov,t2a,'mcie,abmj->abcije')...
                     +einsum_kg(H2B.ovov,t2a,'mcje,abmi->abcije')...
                     +einsum_kg(H2B.vvvv,t2a,'acfe,fbij->abcije')...
                     -einsum_kg(H2B.vvvv,t2a,'bcfe,faij->abcije');
        
        % h3B(vvvovo)
        H3B.vvvovo = -einsum_kg(H2B.ovvo,t2a,'mbej,acim->acbiej')...
                     -einsum_kg(H2A.voov,t2b,'amie,cbmj->acbiej')...
                     +einsum_kg(H2A.voov,t2b,'cmie,abmj->acbiej')...
                     -einsum_kg(H2B.vovo,t2b,'cmej,abim->acbiej')...
                     +einsum_kg(H2B.vovo,t2b,'amej,cbim->acbiej')...
                     +einsum_kg(H2A.vvvv,t2b,'acfe,fbij->acbiej')...
                     +einsum_kg(H2B.vvvv,t2b,'cbef,afij->acbiej')...
                     -einsum_kg(H2B.vvvv,t2b,'abef,cfij->acbiej');
                 
        % h3B(vovooo)
        H3B.vovooo = einsum_kg(H2B.ovvo,t2a,'mcfk,afij->amcijk')...
                     +einsum_kg(H2A.voov,t2b,'amif,fcjk->amcijk')...
                            -einsum_kg(H2A.voov,t2b,'amjf,fcik->amcijk')...
                     +einsum_kg(H2B.ovov,t2b,'mcjf,afik->amcijk')...
                            -einsum_kg(H2B.ovov,t2b,'mcif,afjk->amcijk')...
                     -einsum_kg(H2A.oooo,t2b,'mnji,acnk->amcijk')...
                     -einsum_kg(H2B.oooo,t2b,'mnjk,acin->amcijk')...
                            +einsum_kg(H2B.oooo,t2b,'mnik,acjn->amcijk');
                        
        % h3B(vvoooo)
        H3B.vvoooo = einsum_kg(H2B.vovo,t2a,'amfk,fbij->abmijk')...
                            -einsum_kg(H2B.vovo,t2a,'bmfk,faij->abmijk')...
                     +einsum_kg(H2B.voov,t2b,'amif,bfjk->abmijk')...
                            -einsum_kg(H2B.voov,t2b,'bmif,afjk->abmijk')...
                            -einsum_kg(H2B.voov,t2b,'amjf,bfik->abmijk')...
                            +einsum_kg(H2B.voov,t2b,'bmjf,afik->abmijk')...
                     -einsum_kg(H2B.oooo,t2a,'nmik,abnj->abmijk')...
                            +einsum_kg(H2B.oooo,t2a,'nmjk,abni->abmijk');

        fprintf('done in %4.8f s\n',toc)

        %%%%%%%%%%%%%%%%%%%%% H3C %%%%%%%%%%%%%%%%%%%

        fprintf('Building H3C... ')
        tic
        % h3C(abmije)
        H3C.vvooov = -einsum_kg(sys.vB_ooov,t2b,'nmie,abnj->abmije')...
                     +einsum_kg(sys.vB_vovv,t2b,'amfe,fbij->abmije')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t2b,'nmie,abnj->abmije')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,an->amfe'),t2b,'amfe,fbij->abmije')...
                     -einsum_kg(sys.vC_oovo,t2b,'mnej,abin->abmije')...
                     +einsum_kg(sys.vC_vovv,t2b,'bmfe,afij->abmije')...
                     -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fj->mnej'),t2b,'mnej,abin->abmije')...
                     -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,bn->mbef'),t2b,'mbef,afij->abmije');
        H3C.vovovo = permute(H3C.vvooov,[1,3,2,4,6,5]);

        % h3C(mabeij)         
        H3C.ovvvoo = -einsum_kg(sys.vB_oovo,t2c,'mnei,abnj->mabeij')...
                            +einsum_kg(sys.vB_oovo,t2c,'mnej,abni->mabeij')...
                     +einsum_kg(sys.vB_ovvv,t2c,'maef,fbij->mabeij')...
                            -einsum_kg(sys.vB_ovvv,t2c,'mbef,faij->mabeij')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t2c,'mnei,abnj->mabeij')...
                            +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fj->mnej'),t2c,'mnej,abni->mabeij')...
                     -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,an->maef'),t2c,'maef,fbij->mabeij')...
                            +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,bn->mbef'),t2c,'mbef,faij->mabeij');

         % h3C(abmeji)
         H3C.vvovoo = einsum_kg(sys.vB_vovv,t2c,'amef,fbij->abmeji')...
                      -einsum_kg(sys.vB_oovo,t2b,'nmei,abnj->abmeji')...
                            +einsum_kg(sys.vB_oovo,t2b,'nmej,abni->abmeji')...
                      -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmef,fi->nmei'),t2b,'nmei,abnj->abmeji')...
                            +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmef,fj->nmej'),t2b,'nmej,abni->abmeji')...
                      -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmef,an->amef'),t2c,'amef,fbij->abmeji');

         % h3C(mabiej)
         H3C.ovvovo = -einsum_kg(sys.vB_ooov,t2c,'mnie,abnj->mabiej')...
                      +einsum_kg(sys.vB_ovvv,t2b,'mafe,fbij->mabiej')...
                            -einsum_kg(sys.vB_ovvv,t2b,'mbfe,faij->mabiej')...
                      -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnfe,fi->mnie'),t2c,'mnie,abnj->mabiej')...
                      -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnfe,an->mafe'),t2b,'mafe,fbij->mabiej')...
                            +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnfe,bn->mbfe'),t2b,'mbfe,faij->mabiej');

         % h3C(abcefk)
         H3C.vvvvvo = -einsum_kg(H2B.vovv,t2c,'amef,bcmk->abcefk')...
                      -einsum_kg(H2B.ovvv,t2b,'mbef,acmk->abcefk')...
                            +einsum_kg(H2B.ovvv,t2b,'mcef,abmk->abcefk');
                        
         % h3C(abcief)
         H3C.vvvovv = -einsum_kg(H2C.vovv,t2b,'cmfe,abim->abcief')...
                            +einsum_kg(H2C.vovv,t2b,'bmfe,acim->abcief');
                        
         % h3C(mnajki)
         H3C.oovooo = einsum_kg(H2B.ooov,t2c,'mnje,aeik->mnajki')...
                      +einsum_kg(H2B.oovo,t2b,'mnek,eaji->mnajki')...
                            -einsum_kg(H2B.oovo,t2b,'mnei,eajk->mnajki');
                        
         % h3C(amnijk)
         H3C.vooooo = einsum_kg(H2C.ooov,t2b,'nmke,aeij->amnijk')...
                            -einsum_kg(H2C.ooov,t2b,'nmje,aeik->amnijk');

         % h3C(abmief)
         H3C.vvoovv = -einsum_kg(sys.vC_oovv,t2b,'mnfe,abin->abmief');

         % h3C(mabfie)
         H3C.ovvvov = -einsum_kg(sys.vB_oovv,t2c,'mnfe,abin->mabfie');

         % h3C(bameif)
         H3C.vvovov = -einsum_kg(sys.vB_oovv,t2b,'nmef,bani->bameif');

         % h3C(
         H3C.ovvovv = zeros(Nocc_a,Nunocc_b,Nunocc_b,Nocc_a,Nunocc_b,Nunocc_b);

         % h3C(amnije)
         H3C.voooov = einsum_kg(sys.vC_oovv,t2b,'mnfe,afij->amnije');

         % h3C(nameij)
         H3C.ovovoo = einsum_kg(sys.vB_oovv,t2c,'nmef,afij->nameij');

         % h3C(manjie)
         H3C.ovooov = einsum_kg(sys.vB_oovv,t2b,'mnfe,faji->manjie');
         
         % h3C(abcije)
         H3C.vvvoov = -einsum_kg(H2B.voov,t2c,'amie,bcjm->abcije')...
                      -einsum_kg(H2C.voov,t2b,'bmje,acim->abcije')...
                      +einsum_kg(H2C.voov,t2b,'cmje,abim->abcije')...
                      -einsum_kg(H2B.ovov,t2b,'mcie,abmj->abcije')...
                      +einsum_kg(H2B.ovov,t2b,'mbie,acmj->abcije')...
                      +einsum_kg(H2B.vvvv,t2b,'acfe,fbij->abcije')...
                      -einsum_kg(H2B.vvvv,t2b,'abfe,fcij->abcije')...
                      +einsum_kg(H2C.vvvv,t2b,'bcfe,afij->abcije');
                  
         % h3C(cabeij)
         H3C.vvvvoo = -einsum_kg(H2B.vovo,t2c,'cmei,abmj->cabeij')...
                      +einsum_kg(H2B.vovo,t2c,'cmej,abmi->cabeij')...
                      -einsum_kg(H2B.ovvo,t2b,'maei,cbmj->cabeij')...
                      +einsum_kg(H2B.ovvo,t2b,'mbei,camj->cabeij')...
                      +einsum_kg(H2B.ovvo,t2b,'maej,cbmi->cabeij')...
                      -einsum_kg(H2B.ovvo,t2b,'mbej,cami->cabeij')...
                      +einsum_kg(H2B.vvvv,t2c,'caef,fbij->cabeij')...
                      -einsum_kg(H2B.vvvv,t2c,'cbef,faij->cabeij');
                  
         % h3C(mbcijk)
         H3C.ovvooo = -einsum_kg(H2B.oooo,t2c,'mnij,bcnk->mbcijk')...
                            +einsum_kg(H2B.oooo,t2c,'mnik,bcnj->mbcijk')...
                      +einsum_kg(H2B.ovvo,t2b,'mbfj,fcik->mbcijk')...
                            -einsum_kg(H2B.ovvo,t2b,'mcfj,fbik->mbcijk')...
                            -einsum_kg(H2B.ovvo,t2b,'mbfk,fcij->mbcijk')...
                            +einsum_kg(H2B.ovvo,t2b,'mcfk,fbij->mbcijk')...
                      +einsum_kg(H2B.ovov,t2c,'mbif,fcjk->mbcijk')...
                            -einsum_kg(H2B.ovov,t2c,'mcif,fbjk->mbcijk');
                        
         % h3C(vvoooo)
         H3C.vvoooo =  einsum_kg(H2B.vovo,t2b,'amfj,fcik->acmikj')...
                            -einsum_kg(H2B.vovo,t2b,'amfk,fcij->acmikj')...
                      +einsum_kg(H2B.voov,t2c,'amif,fcjk->acmikj')...
                      +einsum_kg(H2C.voov,t2b,'cmkf,afij->acmikj')...
                            -einsum_kg(H2C.voov,t2b,'cmjf,afik->acmikj')...
                      -einsum_kg(H2B.oooo,t2b,'nmij,acnk->acmikj')...
                            +einsum_kg(H2B.oooo,t2b,'nmik,acnj->acmikj')...
                      -einsum_kg(H2C.oooo,t2b,'mnjk,acin->acmikj');

         fprintf('done in %4.8f s\n',toc)

         %%%%%%%%%%%%%%%%%%%%% H3D %%%%%%%%%%%%%%%%%%%

        fprintf('Building H3D... ')
        tic                
         % h3D(abmije)
         H3D.vvooov = -einsum_kg(sys.vC_oovo,t2c,'mnei,abnj->abmije')...
                            +einsum_kg(sys.vC_oovo,t2c,'mnej,abni->abmije')...
                      +einsum_kg(sys.vC_vovv,t2c,'amfe,fbij->abmije')...
                            -einsum_kg(sys.vC_vovv,t2c,'bmfe,faij->abmije')...
                      -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fi->mnei'),t2c,'mnei,abnj->abmije')...
                            +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fj->mnej'),t2c,'mnej,abni->abmije')...
                      -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,an->maef'),t2c,'maef,fbij->abmije')...
                            +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,bn->mbef'),t2c,'mbef,faij->abmije');
          H3D.vovovo = permute(H3D.vvooov,[1,3,2,4,6,5]);
          H3D.ovvvoo = permute(H3D.vvooov,[3,1,2,6,4,5]);
          
        % h3D(mncijk)
        H3D.oovooo = einsum_kg(H2C.ooov,t2c,'mnie,ecjk->mncijk')...
                     -einsum_kg(H2C.ooov,t2c,'mnje,ecik->mncijk')...
                     -einsum_kg(H2C.ooov,t2c,'mnke,ecji->mncijk');

        % h3D(abcefk)
        H3D.vvvvvo = -einsum_kg(H2C.vovv,t2c,'amef,bcmk->abcefk')...
                      +einsum_kg(H2C.vovv,t2c,'bmef,acmk->abcefk')...
                      +einsum_kg(H2C.vovv,t2c,'cmef,bamk->abcefk');

          % h3D(abmief)
          H3D.vvoovv = -einsum_kg(sys.vC_oovv,t2c,'mnfe,abin->abmief');
          H3D.vvovov = -permute(H3D.vvoovv,[1,2,3,5,4,6]);

          % h3D(amnije)
          H3D.voooov = einsum_kg(sys.vC_oovv,t2c,'mnfe,afij->amnije');
          H3D.oovovo = -permute(H3D.voooov,[2,3,1,4,6,5]);

          % h3D(vvvoov)
          H3D.vvvoov =  -einsum_kg(H2C.voov,t2c,'amie,bcjm->abcije')...
                          +einsum_kg(H2C.voov,t2c,'amje,bcim->abcije')... %(ij)
                          +einsum_kg(H2C.voov,t2c,'bmie,acjm->abcije')... %(ab)
                          +einsum_kg(H2C.voov,t2c,'cmie,bajm->abcije')... %(ac)
                          -einsum_kg(H2C.voov,t2c,'bmje,acim->abcije')... %(ij)(ab)
                          -einsum_kg(H2C.voov,t2c,'cmje,baim->abcije')... %(ij)(ac)
                          +einsum_kg(H2C.vvvv,t2c,'acfe,fbij->abcije')... 
                          -einsum_kg(H2C.vvvv,t2c,'bcfe,faij->abcije')... %(ab)
                          -einsum_kg(H2C.vvvv,t2c,'abfe,fcij->abcije');   %(bc)

          % h3D(vvoooo)          
          H3D.vvoooo =   einsum_kg(H2C.voov,t2c,'amie,bejk->abmijk')...
                          -einsum_kg(H2C.voov,t2c,'bmie,aejk->abmijk')... %(ab)
                          -einsum_kg(H2C.voov,t2c,'amje,beik->abmijk')... %(ij)
                          -einsum_kg(H2C.voov,t2c,'amke,beji->abmijk')... %(ik)
                          +einsum_kg(H2C.voov,t2c,'bmje,aeik->abmijk')... %(ab)(ij)
                          +einsum_kg(H2C.voov,t2c,'bmke,aeji->abmijk')... %(ab)(ik)
                          -einsum_kg(H2C.oooo,t2c,'mnki,abnj->abmijk')... 
                          +einsum_kg(H2C.oooo,t2c,'mnkj,abni->abmijk')... %(ij)
                          +einsum_kg(H2C.oooo,t2c,'mnji,abnk->abmijk');   %(jk)

        fprintf('done in %4.8f s\n',toc)

        % store 3-body HBar in HBar_t struct
        HBar_t.H3A = H3A;
        HBar_t.H3B = H3B;
        HBar_t.H3C = H3C;
        HBar_t.H3D = H3D;

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    end

        % store 1- and 2-body HBar in HBar_t struct
        HBar_t.H1A = H1A;
        HBar_t.H1B = H1B;
        HBar_t.H2A = H2A;
        HBar_t.H2B = H2B;
        HBar_t.H2C = H2C;


    fprintf('UCCSD HBar completed in %4.8f seconds\n',toc(tic_Start));
    fprintf('===============================================================================================\n')
                 
end

