function [sigma_r1, sigma_r2] = build_HBar_R(r1, r2, HBar)

    addpath(genpath('/Users/harellab/Dropbox/Hartree Fock/hartree_fock/v4/utils'));

    % <ia|HR_1|0>
    TEMP1 = einsum_kg(HBar{1}{2,2},r1,'ae,ei->ai') - einsum_kg(HBar{1}{1,1},r1,'mi,am->ai') + ...
            einsum_kg(HBar{2}{1,2,2,1},r1,'maei,em->ai');
        
    % <ia|HR_2|0>
    TEMP2 = 0.5*einsum_kg(HBar{2}{2,1,2,2},r2,'amfe,feim->ai') - ...
            0.5*einsum_kg(HBar{2}{1,1,1,2},r2,'mnie,aemn->ai') + ...
            einsum_kg(HBar{1}{1,2},r2,'me,aeim->ai');% + ...
            %0.25*einsum_kg(HBar{3}{2,1,1,1,2,2},r2,'amnief,efmn->ai'); <- why
            %does Jun's code have this??? Has 4 lines extending to right
            %and 2 extending to left
        
        
    % <ijab|HR_1|0>
    TEMP3 = einsum_kg(HBar{2}{2,2,2,1},r1,'abej,ei->abij') - ...
            einsum_kg(HBar{2}{2,2,2,1},r1,'abei,ej->abij') - ...
            einsum_kg(HBar{2}{1,2,1,1},r1,'mbij,am->abij') + ...
            einsum_kg(HBar{2}{1,2,1,1},r1,'maij,bm->abij') + ...
            einsum_kg(HBar{3}{2,2,1,1,1,2},r1,'abmije,em->abij');
        
    % <ijab|HR_2|0>    
    TEMP4 = einsum_kg(HBar{1}{2,2},r2,'be,aeij->abij') - ...
            einsum_kg(HBar{1}{2,2},r2,'ae,beij->abij') - ...
            einsum_kg(HBar{1}{1,1},r2,'mj,abim->abij') + ...
            einsum_kg(HBar{1}{1,1},r2,'mi,abjm->abij') + ...
            0.5*einsum_kg(HBar{2}{2,2,2,2},r2,'abef,efij->abij') + ...
            0.5*einsum_kg(HBar{2}{1,1,1,1},r2,'mnij,abmn->abij') + ...
            einsum_kg(HBar{2}{1,2,2,1},r2,'mbej,aeim->abij') - ...
            einsum_kg(HBar{2}{1,2,2,1},r2,'mbei,aejm->abij') - ...
            einsum_kg(HBar{2}{1,2,2,1},r2,'maej,beim->abij') + ...
            einsum_kg(HBar{2}{1,2,2,1},r2,'maei,bejm->abij') - ...
            0.5*einsum_kg(HBar{3}{2,1,1,1,1,2},r2,'amnije,bemn->abij') + ...
            0.5*einsum_kg(HBar{3}{2,1,1,1,1,2},r2,'bmnije,aemn->abij') + ...
            0.5*einsum_kg(HBar{3}{2,2,1,1,2,2},r2,'abmief,efjm->abij') - ...
            0.5*einsum_kg(HBar{3}{2,2,1,1,2,2},r2,'abmjef,efim->abij');
        
        % Construct sigma trial vectors for Davidson iterations
        sigma_r1 = TEMP1 + TEMP2;
        sigma_r2 = TEMP3 + TEMP4;
        


end
