function [] = HBar_triples_diagonal(a,b,c,i,j,k,HBar_t,cc_t,sys)
% 
    t2a = cc_t.t2a; t2b = cc_t.t2b; t2c = cc_t.t2c;

    D3A_V = @(a,i,b) -dot(squeeze(sys.vA_oovv(i,:,b,a)),squeeze(t2a(a,b,i,:)));
    D3A_O = @(a,i,j) dot(squeeze(sys.vA_oovv(i,j,a,:)),squeeze(t2a(a,:,i,j)));
    
    D3B_V = @(a,i,c) -dot(squeeze(sys.vB_oovv(i,:,a,c)),squeeze(t2b(a,c,i,:)));
    D3B_O = @(a,i,k) dot(squeeze(sys.vB_oovv(i,k,a,:)),squeeze(t2b(a,:,i,k)));
    
    D3C_V = @(a,k,c) -dot(squeeze(sys.vB_oovv(:,k,a,c)),squeeze(t2b(a,c,:,k)));
    D3C_O = @(c,i,k) dot(squeeze(sys.vB_oovv(i,k,:,c)),squeeze(t2b(:,c,i,k)));
    
    D3D_V = @(a,i,b) -dot(squeeze(sys.vC_oovv(i,:,b,a)),squeeze(t2c(a,b,i,:)));
    D3D_O = @(a,i,j) dot(squeeze(sys.vC_oovv(i,j,a,:)),squeeze(t2c(a,:,i,j)));
    
    D3A = -D3A_O(a,i,j)-D3A_O(a,i,k)-D3A_O(a,j,k)...
     -D3A_O(b,i,j)-D3A_O(b,i,k)-D3A_O(b,j,k)...
     -D3A_O(c,i,j)-D3A_O(c,i,k)-D3A_O(c,j,k)...
     +D3A_V(a,i,b)+D3A_V(a,i,c)+D3A_V(b,i,c)...
     +D3A_V(a,j,b)+D3A_V(a,j,c)+D3A_V(b,j,c)...
     +D3A_V(a,k,b)+D3A_V(a,k,c)+D3A_V(b,k,c);
 
 
     D3B = -D3A_O(a,i,j)-D3B_O(a,i,k)-D3B_O(a,j,k)...
         -D3A_O(b,i,j)-D3B_O(b,i,k)-D3B_O(b,j,k)...
         -D3C_O(c,i,k)-D3C_O(c,j,k)...
         +D3A_V(a,i,b)+D3B_V(a,i,c)+D3B_V(b,i,c)...
         +D3A_V(a,j,b)+D3B_V(a,j,c)+D3B_V(b,j,c)...
         +D3C_V(a,k,c)+D3C_V(b,k,c);
     
     D3C = -D3B_O(a,i,j)-D3B_O(a,i,k)...
     -D3C_O(b,i,j)-D3C_O(b,i,k)-D3C_O(b,j,k)...
     -D3C_O(c,i,j)-D3C_O(c,i,k)-D3D_O(c,j,k)...
     +D3B_V(a,i,b)+D3B_V(a,i,c)...
     +D3C_V(a,j,b)+D3C_V(a,j,c)+D3D_V(b,j,c)...
     +D3C_V(a,k,b)+D3C_V(a,k,c)+D3D_V(b,k,c);
 
 D3D = -D3D_O(a,i,j)-D3D_O(a,i,k)-D3D_O(a,j,k)...
     -D3D_O(b,i,j)-D3D_O(b,i,k)-D3D_O(b,j,k)...
     -D3D_O(c,i,j)-D3D_O(c,i,k)-D3D_O(c,j,k)...
     +D3D_V(a,i,b)+D3D_V(a,i,c)+D3D_V(b,i,c)...
     +D3D_V(a,j,b)+D3D_V(a,j,c)+D3D_V(b,j,c)...
     +D3D_V(a,k,b)+D3D_V(a,k,c)+D3D_V(b,k,c);
 
 D3A
 
  H3A = HBar_t.H3A; 
  
  H3A_O = H3A.vooovo; H3A_V = H3A.vovovv;
  H3B_O = H3B.vooovo; H3B_V = H3B.vovovv;
  
%   D3Aex = -H3A_O(a,i,j,i,a,j)-H3A_O(a,i,k,i,a,k)-H3A_O(a,j,k,j,a,k)...
%           -H3A_O(b,i,j,i,b,j)-H3A_O(b,i,k,i,b,k)-H3A_O(b,j,k,j,b,k)...
%           -H3A_O(c,i,j,i,c,j)-H3A_O(c,i,k,i,c,k)-H3A_O(c,j,k,j,c,k)...
%           +H3A_V(a,i,b,i,a,b)+H3A_V(a,i,c,i,a,c)+H3A_V(b,i,c,i,b,c)...
%           +H3A_V(a,j,b,j,a,b)+H3A_V(a,j,c,j,a,c)+H3A_V(b,j,c,j,b,c)...
%           +H3A_V(a,k,b,k,a,b)+H3A_V(a,k,c,k,a,c)+H3A_V(b,k,c,k,b,c);
 

  
end

