function [Gamma] = build_partial_L3(i,j,k,L1,L2,HBar)

    DC1 = einsum_kg(L1(k,:),HBar{2}{1,1,2,2}(i,j,:,:),'c,ab->abc') ...
          - einsum_kg(L1(k,:),HBar{2}{1,1,2,2}(i,j,:,:),'a,cb->abc') ...
          - einsum_kg(L1(k,:),HBar{2}{1,1,2,2}(i,j,:,:),'b,ac->abc');

    DC2 = einsum_kg(L2(i,j,:,:),HBar{1}{1,2}(k,:),'ab,c->abc') ...
          - einsum_kg(L2(i,j,:,:),HBar{1}{1,2}(k,:),'cb,a->abc') ...
          - einsum_kg(L2(i,j,:,:),HBar{1}{1,2}(k,:),'ac,b->abc');
    
    D1 = einsum_kg(L2(:,k,:,:),HBar{2}{1,1,2,1}(i,j,:,:),'mbc,am->abc') ...
         - einsum_kg(L2(:,k,:,:),HBar{2}{1,1,2,1}(i,j,:,:),'mac,bm->abc') ...
         - einsum_kg(L2(:,k,:,:),HBar{2}{1,1,2,1}(i,j,:,:),'mba,cm->abc');

    D2 = einsum_kg(L2(i,j,:,:),HBar{2}{2,1,2,2}(:,k,:,:),'ae,ebc->abc') ...
         - einsum_kg(L2(i,j,:,:),HBar{2}{2,1,2,2}(:,k,:,:),'be,eac->abc') ...
         - einsum_kg(L2(i,j,:,:),HBar{2}{2,1,2,2}(:,k,:,:),'ce,eba->abc');

    Gamma = DC1 + DC2 - D1 + D2;
end

