function [t3a] = update_t3a_proj2_ccsdt2(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,HBar_t,sys,shift)

    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;

    H1A = HBar_t.H1A; H2A = HBar_t.H2A; H2B = HBar_t.H2B;
    [Vt3A] = get_t3a_intermediates(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys);

    I2A_vvov = H2A.vvov+einsum_kg(H1A.ov,t2a,'me,abim->abie');
    
    % MM23A + (V*T2*T3)_C
    M23_D1 = -einsum_kg(H2A.vooo(PA,:,HA,HA) + Vt3A.PoHH,t2a(PA,pA,:,HA),'AmIJ,BcmK->ABcIJK');
    M23_D1 = M23_D1 - permute(M23_D1,[2,1,3,4,5,6]);
    M23_D2 = einsum_kg(H2A.vooo(pA,:,HA,HA) + Vt3A.poHH,t2a(PA,PA,:,HA),'cmIJ,BAmK->ABcIJK');
    M23_D12 = M23_D1 + M23_D2;
    M23_D12 = M23_D12 - permute(M23_D12,[1,2,3,6,5,4]) - permute(M23_D12,[1,2,3,4,6,5]);

    M23_D3 = +einsum_kg(I2A_vvov(PA,PA,HA,:) + Vt3A.PPHv,t2a(:,pA,HA,HA),'ABIe,ecJK->ABcIJK');
    M23_D4 = -einsum_kg(I2A_vvov(PA,pA,HA,:) + Vt3A.PpHv,t2a(:,PA,HA,HA),'AcIe,eBJK->ABcIJK');
    M23_D4 = M23_D4 - permute(M23_D4,[2,1,3,4,5,6]);
    M23_D34 = M23_D3 + M23_D4;
    M23_D34 = M23_D34 - permute(M23_D34,[1,2,3,5,4,6]) - permute(M23_D34,[1,2,3,6,5,4]);

    MM23A = M23_D12 + M23_D34;

    % (HBar*T3)_C    
    D1 = -einsum_kg(H1A.oo(hA,HA),T3A.PPphHH,'mK,ABcmIJ->ABcIJK')...
    -einsum_kg(H1A.oo(HA,HA),T3A.PPpHHH,'MK,ABcIJM->ABcIJK');
    D1 = D1 - permute(D1,[1,2,3,6,5,4]) - permute(D1,[1,2,3,4,6,5]);

    D2 = +einsum_kg(H1A.vv(pA,pA),T3A.PPpHHH,'ce,ABeIJK->ABcIJK')...
    +einsum_kg(H1A.vv(pA,PA),T3A.PPPHHH,'cE,ABEIJK->ABcIJK');

    D3 = -einsum_kg(H1A.vv(PA,pA),T3A.PppHHH,'Be,AceIJK->ABcIJK')...
    +einsum_kg(H1A.vv(PA,PA),T3A.PPpHHH,'BE,AEcIJK->ABcIJK');
    D3 = D3 - permute(D3,[2,1,3,4,5,6]);

    D4 = +0.5*einsum_kg(H2A.oooo(hA,hA,HA,HA),T3A.PPphhH,'mnIJ,ABcmnK->ABcIJK')...
    -einsum_kg(H2A.oooo(HA,hA,HA,HA),T3A.PPphHH,'MnIJ,ABcnMK->ABcIJK')...
    +0.5*einsum_kg(H2A.oooo(HA,HA,HA,HA),T3A.PPpHHH,'MNIJ,ABcMNK->ABcIJK');
    D4 = D4 - permute(D4,[1,2,3,6,5,4]) - permute(D4,[1,2,3,4,6,5]);

    D5 = +0.5*einsum_kg(H2A.vvvv(PA,PA,pA,pA),T3A.pppHHH,'ABef,efcIJK->ABcIJK')...
    +einsum_kg(H2A.vvvv(PA,PA,PA,pA),T3A.PppHHH,'ABEf,EfcIJK->ABcIJK')...
    +0.5*einsum_kg(H2A.vvvv(PA,PA,PA,PA),T3A.PPpHHH,'ABEF,EFcIJK->ABcIJK');

    D6 = -0.5*einsum_kg(H2A.vvvv(PA,pA,pA,pA),T3A.PppHHH,'Acef,BefIJK->ABcIJK')...
    +einsum_kg(H2A.vvvv(PA,pA,PA,pA),T3A.PPpHHH,'AcEf,EBfIJK->ABcIJK')...
    -0.5*einsum_kg(H2A.vvvv(PA,pA,PA,PA),T3A.PPPHHH,'AcEF,EFBIJK->ABcIJK');
    D6 = D6 - permute(D6,[2,1,3,4,5,6]);

    D7 = +einsum_kg(H2A.voov(pA,hA,HA,pA),T3A.PPphHH,'cmKe,ABemIJ->ABcIJK')...
    +einsum_kg(H2A.voov(pA,hA,HA,PA),T3A.PPPhHH,'cmKE,ABEmIJ->ABcIJK')...
    +einsum_kg(H2A.voov(pA,HA,HA,pA),T3A.PPpHHH,'cMKe,ABeIJM->ABcIJK')...
    +einsum_kg(H2A.voov(pA,HA,HA,PA),T3A.PPPHHH,'cMKE,ABEIJM->ABcIJK');

    D8 = -einsum_kg(H2A.voov(PA,hA,HA,pA),T3A.PpphHH,'BmKe,AcemIJ->ABcIJK')...
    +einsum_kg(H2A.voov(PA,hA,HA,PA),T3A.PPphHH,'BmKE,AEcmIJ->ABcIJK')...
    -einsum_kg(H2A.voov(PA,HA,HA,pA),T3A.PppHHH,'BMKe,AceIJM->ABcIJK')...
    +einsum_kg(H2A.voov(PA,HA,HA,PA),T3A.PPpHHH,'BMKE,AEcIJM->ABcIJK');
    D8 = D8 - permute(D8,[2,1,3,4,5,6]);

    D78 = D7 + D8;
    D78 = D78 - permute(D78,[1,2,3,6,5,4]) - permute(D78,[1,2,3,4,6,5]);

    D9 = +einsum_kg(H2B.voov(pA,hB,HA,pB),T3B.PPpHHh,'cmKe,ABeIJm->ABcIJK')...
    +einsum_kg(H2B.voov(pA,hB,HA,PB),T3B.PPPHHh,'cmKE,ABEIJm->ABcIJK')...
    +einsum_kg(H2B.voov(pA,HB,HA,pB),T3B.PPpHHH,'cMKe,ABeIJM->ABcIJK')...
    +einsum_kg(H2B.voov(pA,HB,HA,PB),T3B.PPPHHH,'cMKE,ABEIJM->ABcIJK');

    D10 = -einsum_kg(H2B.voov(PA,hB,HA,pB),T3B.PppHHh,'BmKe,AceIJm->ABcIJK')...
    -einsum_kg(H2B.voov(PA,hB,HA,PB),T3B.PpPHHh,'BmKE,AcEIJm->ABcIJK')...
    -einsum_kg(H2B.voov(PA,HB,HA,pB),T3B.PppHHH,'BMKe,AceIJM->ABcIJK')...
    -einsum_kg(H2B.voov(PA,HB,HA,PB),T3B.PpPHHH,'BMKE,AcEIJM->ABcIJK');
    D10 = D10 - permute(D10,[2,1,3,4,5,6]);

    D910 = D9 + D10;
    D910 = D910 - permute(D910,[1,2,3,6,5,4]) - permute(D910,[1,2,3,4,6,5]);
        
    X3A_PPpHHH = D1 + D2 + D3 + D4 + D5 + D6 + D78 + D910 + MM23A;
    
    t3a = T3A.PPpHHH;
    for a = 1:sys.Nact_p_alpha
        for b = a+1:sys.Nact_p_alpha
            for c = 1:sys.Nunact_p_alpha
                for i = 1:sys.Nact_h_alpha
                    for j = i+1:sys.Nact_h_alpha
                        for k =j+1:sys.Nact_h_alpha
                            denom = sys.fa_HH(i,i) + sys.fa_HH(j,j) + sys.fa_HH(k,k) - sys.fa_PP(a,a) - sys.fa_PP(b,b) - sys.fa_pp(c,c);
                            
                            t3a(a,b,c,i,j,k) = t3a(a,b,c,i,j,k) + X3A_PPpHHH(a,b,c,i,j,k)/(denom-shift);     
                            t3a(a,b,c,k,i,j) = t3a(a,b,c,i,j,k);
                            t3a(a,b,c,j,k,i) = t3a(a,b,c,i,j,k);
                            t3a(a,b,c,i,k,j) = -t3a(a,b,c,i,j,k);
                            t3a(a,b,c,j,i,k) = -t3a(a,b,c,i,j,k);
                            t3a(a,b,c,k,j,i) = -t3a(a,b,c,i,j,k);
                            
                            t3a(b,a,c,i,j,k) = -t3a(a,b,c,i,j,k);
                            t3a(b,a,c,k,i,j) = -t3a(a,b,c,i,j,k);
                            t3a(b,a,c,j,k,i) = -t3a(a,b,c,i,j,k);
                            t3a(b,a,c,i,k,j) = t3a(a,b,c,i,j,k);
                            t3a(b,a,c,j,i,k) = t3a(a,b,c,i,j,k);
                            t3a(b,a,c,k,j,i) = t3a(a,b,c,i,j,k);
                            
                        end
                    end
                end
            end
        end
    end
    %T3A.PPpHHH = t3a;
                            
end

function [Vt3A] = get_t3a_intermediates(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys)

%     % h1A(me)
%     H1A.ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');
% 
%     % h1A(mi)
%     H1A.oo = sys.fa_oo ...
%              +einsum_kg(sys.fa_ov,t1a,'me,ei->mi')...
%              +einsum_kg(sys.vA_ooov,t1a,'mnif,fn->mi')...
%              +einsum_kg(sys.vB_ooov,t1b,'mnif,fn->mi')...
%              +0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efin->mi')...
%              +einsum_kg(sys.vB_oovv,t2b,'mnef,efin->mi')...
%              +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,ei->mi')...
%              +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,ei->mi');
%          
%     % h1A(ae)
%     H1A.vv = sys.fa_vv ...
%              -einsum_kg(sys.fa_ov,t1a,'me,am->ae')...
%              +einsum_kg(sys.vA_vovv,t1a,'amef,fm->ae')...
%              +einsum_kg(sys.vB_vovv,t1b,'anef,fn->ae')...
%              -0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,afmn->ae')...
%              -einsum_kg(sys.vB_oovv,t2b,'mnef,afmn->ae')...
%              -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,am->ae')...
%              -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,am->ae');
% 
%     % h2A(amij)
%     H2A.vooo    = sys.vA_vooo ...
%                   +einsum_kg(sys.vA_voov,t1a,'amie,ej->amij')...
% 	    			-einsum_kg(sys.vA_voov,t1a,'amje,ei->amij')...
%                   -einsum_kg(sys.vA_oooo,t1a,'nmij,an->amij')...
%                   +einsum_kg(sys.fa_ov,t2a,'me,aeij->amij')...
%                   +0.5*einsum_kg(sys.vA_vovv,t2a,'amef,efij->amij')...
%                   +einsum_kg(sys.vA_oovo,t2a,'nmej,aein->amij')...
% 	    			-einsum_kg(sys.vA_oovo,t2a,'nmei,aejn->amij')...
%                   +einsum_kg(sys.vB_ooov,t2b,'mnje,aein->amij')...
% 	    			-einsum_kg(sys.vB_ooov,t2b,'mnie,aejn->amij')...
%                   -einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmej,ei->nmij'),t1a,'nmij,an->amij')...
% 	    			+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmei,ej->nmij'),t1a,'nmij,an->amij')...
%                   +einsum_kg(einsum_kg(sys.vA_vovv,t1a,'amef,ei->amif'),t1a,'amif,fj->amij')...
%                   -0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,an->amef'),t2a,'amef,efij->amij')...
%                   +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ej->mnjf'),t2a,'mnjf,afin->amij')...
% 	    			-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t2a,'mnif,afjn->amij')...
%                   +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,aeij->amij')...
%                   +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t2b,'mnjf,afin->amij')...
% 	    			-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ei->mnif'),t2b,'mnif,afjn->amij')...
%                   +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,aeij->amij')...
%                   -einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,fj->nmej'),t1a,'nmej,an->amej'),t1a,'amej,ei->amij');
% 
%     % h(abie)
%     H2A.vvov  = sys.vA_vvov ...
% 	    	+einsum_kg(sys.vA_vvvv,t1a,'abfe,fi->abie')...
% 	    	-einsum_kg(sys.vA_ovov,t1a,'nbie,an->abie')...
% 	    			+einsum_kg(sys.vA_ovov,t1a,'naie,bn->abie')...
% 	    	-einsum_kg(sys.fa_ov,t2a,'me,abim->abie')...
% 	    	+einsum_kg(sys.vA_ovvv,t2a,'nbfe,afin->abie')...
% 	    			-einsum_kg(sys.vA_ovvv,t2a,'nafe,bfin->abie')...
% 	    	+0.5*einsum_kg(sys.vA_oovo,t2a,'mnei,abnm->abie')...
% 	    	+einsum_kg(sys.vB_vovv,t2b,'bnef,afin->abie')...
% 	    			-einsum_kg(sys.vB_vovv,t2b,'anef,bfin->abie')...
% 	    	+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'mnei,an->maei'),t1a,'maei,bm->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vA_vovv,t1a,'bnef,fi->bnei'),t1a,'bnei,an->abie')...
% 	    			+einsum_kg(einsum_kg(sys.vA_vovv,t1a,'anef,fi->anei'),t1a,'anei,bn->abie')...
% 	    	+0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fi->mnei'),t2a,'mnei,abnm->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t2a,'bnef,afin->abie')...
% 	    			+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,am->anef'),t2a,'anef,bfin->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,abim->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,bm->bnef'),t2b,'bnef,afin->abie')...
% 	    			+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,am->anef'),t2b,'anef,bfin->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,abim->abie')...
% 	    	+einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t1a,'bnef,an->baef'),t1a,'baef,fi->abie');
% 
%      % h2A(mnij)
%      H2A.oooo = sys.vA_oooo...
% 	     	+einsum_kg(sys.vA_oovo,t1a,'mnej,ei->mnij')...
% 	     			-einsum_kg(sys.vA_oovo,t1a,'mnei,ej->mnij')...
% 	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efij->mnij')...
% 	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t1a,'mnif,fj->mnij');
% 
%      % h2A(abef)
%      H2A.vvvv = sys.vA_vvvv...
% 	     	-einsum_kg(sys.vA_ovvv,t1a,'mbef,am->abef')...
% 	     			+einsum_kg(sys.vA_ovvv,t1a,'maef,bm->abef')...
% 	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,abmn->abef')...
% 	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bn->mbef'),t1a,'mbef,am->abef');
%         
%      % h2A(amie)
%      H2A.voov = sys.vA_voov ...
%                 -einsum_kg(sys.vA_ooov,t1a,'nmie,an->amie')...
%                 +einsum_kg(sys.vA_vovv,t1a,'amfe,fi->amie')...
%                 -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
%                 +einsum_kg(sys.vA_oovv,t2a,'nmfe,afin->amie')...
%                 +einsum_kg(sys.vB_oovv,t2b,'mnef,afin->amie');
%             
%     % h2B(amie)
%     H2B.voov = sys.vB_voov ...
%                -einsum_kg(sys.vB_ooov,t1a,'nmie,an->amie')...
%                +einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie')...
%                -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
%                +einsum_kg(sys.vB_oovv,t2a,'nmfe,afin->amie')...
%                +einsum_kg(sys.vC_oovv,t2b,'mnef,afin->amie');
%            
    % (VT3)_C 
    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;
    
    d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.PppHHh,'mnef,AefIJn->AmIJ')...
         +einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PPpHHh,'mnEf,AEfIJn->AmIJ')...
         +einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.PpPHHh,'mneF,AeFIJn->AmIJ')...
         +einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PPPHHh,'mnEF,AEFIJn->AmIJ')...
         +einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.PppHHH,'mNef,AefIJN->AmIJ')...
         +einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PPpHHH,'mNEf,AEfIJN->AmIJ')...
         +einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.PpPHHH,'mNeF,AeFIJN->AmIJ')...
         +einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PPPHHH,'mNEF,AEFIJN->AmIJ');

    d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.PpphHH,'mnef,AefnIJ->AmIJ')...
         -einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PPphHH,'mneF,AFenIJ->AmIJ')...
         +0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPPhHH,'mnEF,AEFnIJ->AmIJ')...
         +0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.PppHHH,'mNef,AefIJN->AmIJ')...
         -einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PPpHHH,'mNeF,AFeIJN->AmIJ')...
         +0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPPHHH,'mNEF,AEFIJN->AmIJ');

    Vt3A.PoHH = d1 + d2;

    d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.pppHHh,'mnef,aefIJn->amIJ')...
         -einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PppHHh,'mnEf,EafIJn->amIJ')...
         +einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.ppPHHh,'mneF,aeFIJn->amIJ')...
         -einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PpPHHh,'mnEF,EaFIJn->amIJ')...
         +einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.pppHHH,'mNef,aefIJN->amIJ')...
         -einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PppHHH,'mNEf,EafIJN->amIJ')...
         +einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.ppPHHH,'mNeF,aeFIJN->amIJ')...
         -einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PpPHHH,'mNEF,EaFIJN->amIJ');

    d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.ppphHH,'mnef,aefnIJ->amIJ')...
         +einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PpphHH,'mneF,FaenIJ->amIJ')...
         +0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPphHH,'mnEF,EFanIJ->amIJ')...
         +0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.pppHHH,'mNef,aefIJN->amIJ')...
         +einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PppHHH,'mNeF,FaeIJN->amIJ')...
         +0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPpHHH,'mNEF,EFaIJN->amIJ');

    Vt3A.poHH = d1 + d2;
    
    d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PPphHh,'mnef,ABfmIn->ABIe')...
    -einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PPPhHh,'mneF,ABFmIn->ABIe')...
    -einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PPphHH,'mNef,ABfmIN->ABIe')...
    -einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PPPhHH,'mNeF,ABFmIN->ABIe')...
    +einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PPpHHh,'Mnef,ABfIMn->ABIe')...
    +einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PPPHHh,'MneF,ABFIMn->ABIe')...
    +einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PPpHHH,'MNef,ABfIMN->ABIe')...
    +einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PPPHHH,'MNeF,ABFIMN->ABIe');

    d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PPphhH,'mnef,ABfmnI->ABIe')...
    +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPPhhH,'mneF,ABFmnI->ABIe')...
    +einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PPphHH,'Mnef,ABfnIM->ABIe')...
    +einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPPhHH,'MneF,ABFnIM->ABIe')...
    +0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PPpHHH,'MNef,ABfIMN->ABIe')...
    +0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPPHHH,'MNeF,ABFIMN->ABIe');

    Vt3A.PPHv = -d1 - d2;
    
    d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PpphHh,'mnef,AbfmIn->AbIe')...
    -einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PpPhHh,'mneF,AbFmIn->AbIe')...
    -einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PpphHH,'mNef,AbfmIN->AbIe')...
    -einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhHH,'mNeF,AbFmIN->AbIe')...
    +einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PppHHh,'Mnef,AbfIMn->AbIe')...
    +einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPHHh,'MneF,AbFIMn->AbIe')...
    +einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PppHHH,'MNef,AbfIMN->AbIe')...
    +einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPHHH,'MNeF,AbFIMN->AbIe');

    d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PpphhH,'mnef,AbfmnI->AbIe')...
    -0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPphhH,'mneF,AFbmnI->AbIe')...
    +einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PpphHH,'Mnef,AbfnIM->AbIe')...
    -einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphHH,'MneF,AFbnIM->AbIe')...
    +0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PppHHH,'MNef,AbfIMN->AbIe')...
    -0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPpHHH,'MNeF,AFbIMN->AbIe');

    Vt3A.PpHv = -d1 - d2;
end
