function [t3b] = update_t3b_proj4_ccsdt2_v2(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,HBar_t,sys,shift)

    % store active T3 as structs T3A,B,C,D,...
    % e.g. T3B.PPPHHH, etc.
    
    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;
    
    H1A = HBar_t.H1A; H1B = HBar_t.H1B;
    H2A = HBar_t.H2A; H2B = HBar_t.H2B; H2C = HBar_t.H2C;
    [Vt3A,Vt3B] = get_t3b_intermediates(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys);
    
    % MM23B + (V*T2*T3)_C    
    I2B_ovoo = H2B.ovoo - einsum_kg(H1A.ov,t2b,'me,ecjk->mcjk');
    I2B_vooo = H2B.vooo - einsum_kg(H1B.ov,t2b,'me,aeik->amik');
    I2A_vooo = H2A.vooo - einsum_kg(H1A.ov,t2a,'me,aeij->amij');
    
    M23_D4 = -einsum_kg(I2B_vooo(PA,:,HA,hB) + Vt3B.PoHh,t2b(PA,PB,HA,:),'AmIk,BCJm->ABCIJk');
    M23_D4 = M23_D4 - permute(M23_D4,[2,1,3,4,5,6]) - permute(M23_D4,[1,2,3,5,4,6]) + permute(M23_D4,[2,1,3,5,4,6]);

    M23_D6 = -einsum_kg(I2A_vooo(PA,:,HA,HA)+Vt3A.PoHH,t2b(PA,PB,:,hB),'BmJI,ACmk->ABCIJk');
    M23_D6 = M23_D6 - permute(M23_D6,[2,1,3,4,5,6]);
    
    M23_D2 = -einsum_kg(I2B_ovoo(:,PB,HA,hB) + Vt3B.oPHh,t2a(PA,PA,:,HA),'mCIk,ABmJ->ABCIJk');
    M23_D2 = M23_D2 - permute(M23_D2,[1,2,3,5,4,6]);
    
    M23_D5 = +einsum_kg(H2A.vvov(PA,PA,HA,:) + Vt3A.PPHv,t2b(:,PB,HA,hB),'BAJe,eCIk->ABCIJk');
    M23_D5 = M23_D5 - permute(M23_D5,[1,2,3,5,4,6]);
    
    M23_D1 = einsum_kg(H2B.vvvo(PA,PB,:,hB) + Vt3B.PPvh,t2a(:,PA,HA,HA),'ACek,eBIJ->ABCIJk');
    M23_D1 = M23_D1 - permute(M23_D1,[2,1,3,4,5,6]);
    
    M23_D3 = +einsum_kg(H2B.vvov(PA,PB,HA,:) + Vt3B.PPHv,t2b(PA,:,HA,hB),'ACIe,BeJk->ABCIJk');
    M23_D3 = M23_D3 - permute(M23_D3,[2,1,3,4,5,6]) - permute(M23_D3,[1,2,3,5,4,6]) + permute(M23_D3,[2,1,3,5,4,6]);
     
    D1 = -einsum_kg(H1A.oo(HA,HA),T3B.PPPHHh,'MI,ABCMJk->ABCIJk');
    D1 = D1 - permute(D1,[1,2,3,5,4,6]);
    
    D2 = -einsum_kg(H1B.oo(HB,hB),T3B.PPPHHH,'Mk,ABCIJM->ABCIJk')...
         -einsum_kg(H1B.oo(hB,hB),T3B.PPPHHh,'mk,ABCIJm->ABCIJk');
     
    D3 =  einsum_kg(H1A.vv(PA,PA),T3B.PPPHHh,'AE,EBCIJk->ABCIJk')...
         +einsum_kg(H1A.vv(PA,pA),T3B.PpPHHh,'Ae,BeCJIk->ABCIJk');
    D3 = D3 - permute(D3,[2,1,3,4,5,6]);
    
    D4 =  einsum_kg(H1B.vv(PB,PB),T3B.PPPHHh,'CE,ABEIJk->ABCIJk')...
         +einsum_kg(H1B.vv(PB,pB),T3B.PPpHHh,'Ce,ABeIJk->ABCIJk');
     
    D5 =  einsum_kg(H2A.voov(PA,HA,HA,PA),T3B.PPPHHh,'AMIE,EBCMJk->ABCIJk')...
         +einsum_kg(H2A.voov(PA,HA,HA,pA),T3B.PpPHHh,'AMIe,BeCJMk->ABCIJk');
    D5 = D5 - permute(D5,[2,1,3,4,5,6]) - permute(D5,[1,2,3,5,4,6]) + permute(D5,[2,1,3,5,4,6]);
    
    D6 =  einsum_kg(H2B.ovvo(HA,PB,PA,hB),T3A.PPPHHH,'MCEk,ABEIJM->ABCIJk')...
         +einsum_kg(H2B.ovvo(hA,PB,PA,hB),T3A.PPPhHH,'mCEk,EABmIJ->ABCIJk')...
         +einsum_kg(H2B.ovvo(HA,PB,pA,hB),T3A.PPpHHH,'MCek,ABeIJM->ABCIJk')...
         -einsum_kg(H2B.ovvo(hA,PB,pA,hB),T3A.PPphHH,'mCek,ABemJI->ABCIJk'); 
     
    D7 =  einsum_kg(H2C.voov(PB,HB,hB,PB),T3B.PPPHHH,'CMkE,ABEIJM->ABCIJk')...
         +einsum_kg(H2C.voov(PB,hB,hB,PB),T3B.PPPHHh,'CmkE,ABEIJm->ABCIJk')...
         +einsum_kg(H2C.voov(PB,HB,hB,pB),T3B.PPpHHH,'CMke,ABeIJM->ABCIJk')...
         +einsum_kg(H2C.voov(PB,hB,hB,pB),T3B.PPpHHh,'Cmke,ABeIJm->ABCIJk');
     
    D8 =  einsum_kg(H2B.voov(PA,HB,HA,PB),T3C.PPPHhH,'AMIE,BCEJkM->ABCIJk')...
         +einsum_kg(H2B.voov(PA,HB,HA,pB),T3C.PPpHhH,'AMIe,BCeJkM->ABCIJk');
    D8 = D8 - permute(D8,[2,1,3,4,5,6]) - permute(D8,[1,2,3,5,4,6]) + permute(D8,[2,1,3,5,4,6]);
    
    D9 = -einsum_kg(H2B.vovo(PA,HB,PA,hB),T3B.PPPHHH,'AMEk,BECJIM->ABCIJk')...
         -einsum_kg(H2B.vovo(PA,hB,PA,hB),T3B.PPPHHh,'AmEk,BECJIm->ABCIJk')...
         -einsum_kg(H2B.vovo(PA,HB,pA,hB),T3B.PpPHHH,'AMek,BeCJIM->ABCIJk')...
         -einsum_kg(H2B.vovo(PA,hB,pA,hB),T3B.PpPHHh,'Amek,BeCJIm->ABCIJk');
    D9 = D9 - permute(D9,[2,1,3,4,5,6]);
    
    D10 = -einsum_kg(H2B.ovov(HA,PB,HA,PB),T3B.PPPHHh,'MCIE,ABEMJk->ABCIJk')...
          -einsum_kg(H2B.ovov(HA,PB,HA,pB),T3B.PPpHHh,'MCIe,ABeMJk->ABCIJk');
    D10 = D10 - permute(D10,[1,2,3,5,4,6]);

    D11 =  0.5*einsum_kg(H2A.oooo(HA,HA,HA,HA),T3B.PPPHHh,'MNIJ,ABCMNk->ABCIJk');
      
    D12 =  einsum_kg(H2B.oooo(HA,HB,HA,hB),T3B.PPPHHH,'MNIk,ABCMJN->ABCIJk')...
          +einsum_kg(H2B.oooo(hA,HB,HA,hB),T3B.PPPhHH,'mNIk,ABCmJN->ABCIJk')...
          +einsum_kg(H2B.oooo(HA,hB,HA,hB),T3B.PPPHHh,'MnIk,ABCMJn->ABCIJk');
    D12 = D12 - permute(D12,[1,2,3,5,4,6]);
    
    D13 =  0.5*einsum_kg(H2A.vvvv(PA,PA,PA,PA),T3B.PPPHHh,'ABEF,EFCIJk->ABCIJk')...
          +einsum_kg(H2A.vvvv(PA,PA,PA,pA),T3B.PpPHHh,'ABEf,EfCIJk->ABCIJk');
      
    D14 =  einsum_kg(H2B.vvvv(PA,PB,PA,PB),T3B.PPPHHh,'ACEF,EBFIJk->ABCIJk')...
          +einsum_kg(H2B.vvvv(PA,PB,PA,pB),T3B.PPpHHh,'ACEf,EBfIJk->ABCIJk')...
          +einsum_kg(H2B.vvvv(PA,PB,pA,PB),T3B.PpPHHh,'ACeF,BeFJIk->ABCIJk');
    D14 = D14 - permute(D14,[2,1,3,4,5,6]);
          
    
    X3B_PPPHHh = D1+D2+D3+D4+D5+D6+D7+D8+D9+D10+D11+D12+D13+D14...
                +M23_D6+M23_D4+M23_D2+M23_D5+M23_D1+M23_D3;
    
    t3b = T3B.PPPHHh;
    for a = 1:sys.Nact_p_alpha
        for b = a+1:sys.Nact_p_alpha
            for c = 1:sys.Nact_p_beta
                for i = 1:sys.Nact_h_alpha
                    for j = i+1:sys.Nact_h_alpha
                        for k = 1:sys.Nunact_h_beta
                            denom=sys.fa_HH(i,i)+sys.fa_HH(j,j)+sys.fb_hh(k,k)-sys.fa_PP(a,a)-sys.fa_PP(b,b)-sys.fb_PP(c,c);
                            t3b(a,b,c,i,j,k) = t3b(a,b,c,i,j,k) + X3B_PPPHHh(a,b,c,i,j,k)/(denom-shift);
                            t3b(b,a,c,i,j,k) = -t3b(a,b,c,i,j,k);
                            t3b(a,b,c,j,i,k) = -t3b(a,b,c,i,j,k);
                            t3b(b,a,c,j,i,k) = t3b(a,b,c,i,j,k);
                        end
                    end
                end
            end
        end
    end
                       
    

end

function [Vt3A,Vt3B] = get_t3b_intermediates(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys)

%     % h1A(mi)
%     H1A.oo = sys.fa_oo ...
%              +einsum_kg(sys.fa_ov,t1a,'me,ei->mi')...
%              +einsum_kg(sys.vA_ooov,t1a,'mnif,fn->mi')...
%              +einsum_kg(sys.vB_ooov,t1b,'mnif,fn->mi')...
%              +0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efin->mi')...
%              +einsum_kg(sys.vB_oovv,t2b,'mnef,efin->mi')...
%              +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,ei->mi')...
%              +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,ei->mi');
%          
%     % h1A(ae)
%     H1A.vv = sys.fa_vv ...
%              -einsum_kg(sys.fa_ov,t1a,'me,am->ae')...
%              +einsum_kg(sys.vA_vovv,t1a,'amef,fm->ae')...
%              +einsum_kg(sys.vB_vovv,t1b,'anef,fn->ae')...
%              -0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,afmn->ae')...
%              -einsum_kg(sys.vB_oovv,t2b,'mnef,afmn->ae')...
%              -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,am->ae')...
%              -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,am->ae');
%          
%     % h1A(me)
%     H1A.ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');
% 
%     % h1B(mi)
%     H1B.oo = sys.fb_oo ...
%              +einsum_kg(sys.fb_ov,t1b,'me,ei->mi')...
%              +einsum_kg(sys.vB_oovo,t1a,'nmfi,fn->mi')...
%              +einsum_kg(sys.vC_ooov,t1b,'mnif,fn->mi')...
%              +einsum_kg(sys.vB_oovv,t2b,'nmfe,feni->mi')...
%              +0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,efin->mi')...
%              +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t1b,'me,ei->mi')...
%              +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t1b,'me,ei->mi');
%          
%     % h1B(ae)
%     H1B.vv = sys.fb_vv ...
%              -einsum_kg(sys.fb_ov,t1b,'me,am->ae')...
%              +einsum_kg(sys.vB_ovvv,t1a,'nafe,fn->ae')...
%              +einsum_kg(sys.vC_vovv,t1b,'anef,fn->ae')...
%              -einsum_kg(sys.vB_oovv,t2b,'nmfe,fanm->ae')...
%              -0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,afmn->ae')...
%              -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t1b,'me,am->ae')...
%              -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t1b,'me,am->ae');
%          
%     % h1B(me)
%     H1B.ov = sys.fb_ov + einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me') + einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me');
%     
%     % h2A(amij)
%     H2A.vooo    = sys.vA_vooo ...
%                   +einsum_kg(sys.vA_voov,t1a,'amie,ej->amij')...
% 	    			-einsum_kg(sys.vA_voov,t1a,'amje,ei->amij')...
%                   -einsum_kg(sys.vA_oooo,t1a,'nmij,an->amij')...
%                   +einsum_kg(sys.fa_ov,t2a,'me,aeij->amij')...
%                   +0.5*einsum_kg(sys.vA_vovv,t2a,'amef,efij->amij')...
%                   +einsum_kg(sys.vA_oovo,t2a,'nmej,aein->amij')...
% 	    			-einsum_kg(sys.vA_oovo,t2a,'nmei,aejn->amij')...
%                   +einsum_kg(sys.vB_ooov,t2b,'mnje,aein->amij')...
% 	    			-einsum_kg(sys.vB_ooov,t2b,'mnie,aejn->amij')...
%                   -einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmej,ei->nmij'),t1a,'nmij,an->amij')...
% 	    			+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmei,ej->nmij'),t1a,'nmij,an->amij')...
%                   +einsum_kg(einsum_kg(sys.vA_vovv,t1a,'amef,ei->amif'),t1a,'amif,fj->amij')...
%                   -0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,an->amef'),t2a,'amef,efij->amij')...
%                   +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ej->mnjf'),t2a,'mnjf,afin->amij')...
% 	    			-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t2a,'mnif,afjn->amij')...
%                   +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,aeij->amij')...
%                   +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t2b,'mnjf,afin->amij')...
% 	    			-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ei->mnif'),t2b,'mnif,afjn->amij')...
%                   +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,aeij->amij')...
%                   -einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,fj->nmej'),t1a,'nmej,an->amej'),t1a,'amej,ei->amij');
% 
%     % h(abie)
%     H2A.vvov  = sys.vA_vvov ...
% 	    	+einsum_kg(sys.vA_vvvv,t1a,'abfe,fi->abie')...
% 	    	-einsum_kg(sys.vA_ovov,t1a,'nbie,an->abie')...
% 	    			+einsum_kg(sys.vA_ovov,t1a,'naie,bn->abie')...
% 	    	-einsum_kg(sys.fa_ov,t2a,'me,abim->abie')...
% 	    	+einsum_kg(sys.vA_ovvv,t2a,'nbfe,afin->abie')...
% 	    			-einsum_kg(sys.vA_ovvv,t2a,'nafe,bfin->abie')...
% 	    	+0.5*einsum_kg(sys.vA_oovo,t2a,'mnei,abnm->abie')...
% 	    	+einsum_kg(sys.vB_vovv,t2b,'bnef,afin->abie')...
% 	    			-einsum_kg(sys.vB_vovv,t2b,'anef,bfin->abie')...
% 	    	+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'mnei,an->maei'),t1a,'maei,bm->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vA_vovv,t1a,'bnef,fi->bnei'),t1a,'bnei,an->abie')...
% 	    			+einsum_kg(einsum_kg(sys.vA_vovv,t1a,'anef,fi->anei'),t1a,'anei,bn->abie')...
% 	    	+0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fi->mnei'),t2a,'mnei,abnm->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t2a,'bnef,afin->abie')...
% 	    			+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,am->anef'),t2a,'anef,bfin->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,abim->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,bm->bnef'),t2b,'bnef,afin->abie')...
% 	    			+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,am->anef'),t2b,'anef,bfin->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,abim->abie')...
% 	    	+einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t1a,'bnef,an->baef'),t1a,'baef,fi->abie');
% 
%      % h2A(mnij)
%      H2A.oooo = sys.vA_oooo...
% 	     	+einsum_kg(sys.vA_oovo,t1a,'mnej,ei->mnij')...
% 	     			-einsum_kg(sys.vA_oovo,t1a,'mnei,ej->mnij')...
% 	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efij->mnij')...
% 	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t1a,'mnif,fj->mnij');
% 
%      % h2A(abef)
%      H2A.vvvv = sys.vA_vvvv...
% 	     	-einsum_kg(sys.vA_ovvv,t1a,'mbef,am->abef')...
% 	     			+einsum_kg(sys.vA_ovvv,t1a,'maef,bm->abef')...
% 	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,abmn->abef')...
% 	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bn->mbef'),t1a,'mbef,am->abef');
%         
%      % h2A(amie)
%      H2A.voov = sys.vA_voov ...
%                 -einsum_kg(sys.vA_ooov,t1a,'nmie,an->amie')...
%                 +einsum_kg(sys.vA_vovv,t1a,'amfe,fi->amie')...
%                 -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
%                 +einsum_kg(sys.vA_oovv,t2a,'nmfe,afin->amie')...
%                 +einsum_kg(sys.vB_oovv,t2b,'mnef,afin->amie');
%         
%      % h2B(amij)
%      H2B.vooo = sys.vB_vooo...
%                -einsum_kg(sys.vB_oooo,t1a,'nmij,an->amij')...
%                +einsum_kg(sys.vB_vovo,t1a,'amej,ei->amij')...
%                +einsum_kg(sys.vB_voov,t1b,'amie,ej->amij')...
%                +einsum_kg(sys.vB_oovo,t2a,'nmej,aein->amij')...
%                +einsum_kg(sys.vC_oovo,t2b,'nmej,aein->amij')...
%                +einsum_kg(sys.vB_vovv,t2b,'amef,efij->amij')...
%                -einsum_kg(sys.vB_ooov,t2b,'nmif,afnj->amij')...
%                +einsum_kg(sys.fb_ov,t2b,'me,aeij->amij')...
%                -einsum_kg(einsum_kg(sys.vB_oovo,t1a,'nmej,an->amej'),t1a,'amej,ei->amij')...
%                -einsum_kg(einsum_kg(sys.vB_ooov,t1b,'nmie,ej->nmij'),t1a,'nmij,an->amij')...
%                +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,ej->mnjf'),t2b,'mnjf,afin->amij')...
%                +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t2b,'me,aeij->amij')...
%                -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,an->amfe'),t2b,'amfe,feij->amij')...
%                -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t2b,'nmie,aenj->amij')...
%                +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t2b,'me,aeij->amij')...
%                +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,ej->nmfj'),t2a,'nmfj,afin->amij')...
%                -einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,ej->nmfj'),t1a,'nmfj,an->amfj'),t1a,'amfj,fi->amij')...
%                +einsum_kg(einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie'),t1b,'amie,ej->amij');
% 
%     % h2B(maji)
%     H2B.ovoo =  sys.vB_ovoo...
%                 +einsum_kg(sys.vB_ovvo,t1a,'maei,ej->maji')...
%                 -einsum_kg(sys.vB_oooo,t1b,'mnji,an->maji')...
%                 +einsum_kg(sys.vB_ovov,t1b,'majf,fi->maji')...
%                 +einsum_kg(sys.vB_ooov,t2c,'mnjf,afin->maji')...
%                 +einsum_kg(sys.vB_ovvv,t2b,'maef,efji->maji')...
%                 +einsum_kg(sys.vA_ooov,t2b,'mnjf,fani->maji')...
%                 -einsum_kg(sys.vB_oovo,t2b,'mnei,eajn->maji')...
%                 +einsum_kg(sys.fa_ov,t2b,'me,eaji->maji')...
%                 -einsum_kg(einsum_kg(sys.vB_ooov,t1b,'mnjf,an->majf'),t1b,'majf,fi->maji')...
%                 +einsum_kg(einsum_kg(sys.vB_ovvv,t1a,'maef,ej->majf'),t1b,'majf,fi->maji')...
%                 -einsum_kg(einsum_kg(sys.vB_oovo,t1a,'mnei,ej->mnji'),t1b,'mnji,an->maji')...
%                 +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t2c,'mnjf,afin->maji')...
%                 +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2b,'me,eaji->maji')...
%                 +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ej->mnjf'),t2b,'mnjf,fani->maji')...
%                 -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,an->maef'),t2b,'maef,efji->maji')...
%                 +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2b,'me,eaji->maji')...
%                 -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t2b,'mnei,eajn->maji')...
%                 -einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t1b,'mnjf,an->majf'),t1b,'majf,fi->maji');
% 
%     % h2B(abie)
%     H2B.vvov =  sys.vB_vvov...
% 	    	-einsum_kg(sys.vB_ovov,t1a,'nbie,an->abie')...
% 	    	+einsum_kg(sys.vB_vvvv,t1a,'abfe,fi->abie')...
% 	    	-einsum_kg(sys.vB_voov,t1b,'amie,bm->abie')...
% 	    	+einsum_kg(sys.vB_ovvv,t2a,'nbfe,afin->abie')...
% 	    	+einsum_kg(sys.vC_ovvv,t2b,'nbfe,afin->abie')...
% 	    	+einsum_kg(sys.vB_ooov,t2b,'nmie,abnm->abie')...
% 	    	-einsum_kg(sys.vB_vovv,t2b,'amfe,fbim->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vB_ovvv,t1a,'nbfe,an->abfe'),t1a,'abfe,fi->abie')...
% 	    	+einsum_kg(einsum_kg(sys.vB_ooov,t1a,'nmie,an->amie'),t1b,'amie,bm->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie'),t1b,'amie,bm->abie')...
% 	    	-einsum_kg(sys.fb_ov,t2b,'me,abim->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,bm->bnef'),t2b,'bnef,afin->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t2b,'me,abim->abie')...
% 	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t2b,'nmie,abnm->abie')...
% 	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,an->amfe'),t2b,'amfe,fbim->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t2b,'me,abim->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,bm->nbfe'),t2a,'nbfe,afin->abie')...
% 	    	+einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,an->amfe'),t1a,'amfe,fi->amie'),t1b,'amie,bm->abie');
% 
%     % h2B(baei)
%     H2B.vvvo =  sys.vB_vvvo...
% 	    	+einsum_kg(sys.vB_vvvv,t1b,'baef,fi->baei')...
% 	    	-einsum_kg(sys.vB_vovo,t1b,'bnei,an->baei')...
% 	    	-einsum_kg(sys.vB_ovvo,t1a,'maei,bm->baei')...
% 	    	+einsum_kg(sys.vB_vovv,t2c,'bnef,afin->baei')...
% 	    	+einsum_kg(sys.vB_oovo,t2b,'mnei,bamn->baei')...
% 	    	+einsum_kg(sys.vA_vovv,t2b,'bnef,fani->baei')...
% 	    	-einsum_kg(sys.vB_ovvv,t2b,'maef,bfmi->baei')...
% 	    	-einsum_kg(sys.fa_ov,t2b,'me,bami->baei')...
% 	    	-einsum_kg(einsum_kg(sys.vB_vovv,t1b,'bnef,fi->bnei'),t1b,'bnei,an->baei')...
% 	    	+einsum_kg(einsum_kg(sys.vB_oovo,t1b,'mnei,an->maei'),t1a,'maei,bm->baei')...
% 	    	-einsum_kg(einsum_kg(sys.vB_ovvv,t1b,'maef,fi->maei'),t1a,'maei,bm->baei')...
% 	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,bm->bnef'),t2c,'bnef,afin->baei')...
% 	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2b,'me,bami->baei')...
% 	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t2b,'bnef,fani->baei')...
% 	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t2b,'mnei,bamn->baei')...
% 	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2b,'me,bami->baei')...
% 	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,an->maef'),t2b,'maef,bfmi->baei')...
% 	    	+einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,an->maef'),t1b,'maef,fi->maei'),t1a,'maei,bm->baei');
% 
%     % h2B(mnij)
%     H2B.oooo =  sys.vB_oooo...
% 	    	+einsum_kg(sys.vB_oovo,t1a,'mnej,ei->mnij')...
% 	   	+einsum_kg(sys.vB_ooov,t1b,'mnif,fj->mnij')...
% 	   	+einsum_kg(sys.vB_oovv,t2b,'mnef,efij->mnij')...
% 	   	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ei->mnif'),t1b,'mnif,fj->mnij'); 
% 
%     % h2B(abef)
%     H2B.vvvv =  sys.vB_vvvv...
% 	    	-einsum_kg(sys.vB_ovvv,t1a,'mbef,am->abef')...
% 	    	-einsum_kg(sys.vB_vovv,t1b,'anef,bn->abef')...
% 	    	+einsum_kg(sys.vB_oovv,t2b,'mnef,abmn->abef')...
% 	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,am->anef'),t1b,'anef,bn->abef');
%         
%     % h2B(amie)
%     H2B.voov = sys.vB_voov ...
%                -einsum_kg(sys.vB_ooov,t1a,'nmie,an->amie')...
%                +einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie')...
%                -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
%                +einsum_kg(sys.vB_oovv,t2a,'nmfe,afin->amie')...
%                +einsum_kg(sys.vC_oovv,t2b,'mnef,afin->amie');
%           
%     % h2B(maie)
%     H2B.ovov = sys.vB_ovov ...
%                +einsum_kg(sys.vB_ovvv,t1a,'mafe,fi->maie')...
%                -einsum_kg(sys.vB_ooov,t1b,'mnie,an->maie')...
%                -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnfe,an->mafe'),t1a,'mafe,fi->maie')...
%                -einsum_kg(sys.vB_oovv,t2b,'mnfe,fain->maie');
%            
%     % h2B(amei)
%     H2B.vovo = sys.vB_vovo ...
%                -einsum_kg(sys.vB_oovo,t1a,'nmei,an->amei')...
%                +einsum_kg(sys.vB_vovv,t1b,'amef,fi->amei')...
%                -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmef,fi->nmei'),t1a,'nmei,an->amei')...
%                -einsum_kg(sys.vB_oovv,t2b,'nmef,afni->amei');
%            
%     % h2B(maei)
%     H2B.ovvo = sys.vB_ovvo ...
%                +einsum_kg(sys.vB_ovvv,t1b,'maef,fi->maei')...
%                -einsum_kg(sys.vB_oovo,t1b,'mnei,an->maei')...
%                -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->maei')...
%                +einsum_kg(sys.vB_oovv,t2c,'mnef,afin->maei')...
%                +einsum_kg(sys.vA_oovv,t2b,'mnef,fani->maei');
%    
%      % h2C(amie)
%      H2C.voov = sys.vC_voov ...
%                 -einsum_kg(sys.vC_oovo,t1b,'mnei,an->amie')...
%                 +einsum_kg(sys.vC_vovv,t1b,'amfe,fi->amie')...
%                 -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->amie')...
%                 +einsum_kg(sys.vC_oovv,t2c,'mnef,afin->amie')...
%                 +einsum_kg(sys.vB_oovv,t2b,'nmfe,fani->amie');

     % (Vt3)_C intermediates
     PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
     PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;
    
     d1 = 0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPPHHH,'mNEF,EFBINJ->BmJI')...
         +0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPPhHH,'mnEF,FEBnIJ->BmJI')...
         +einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PPpHHH,'mNeF,FBeNJI->BmJI')...
         +einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PPphHH,'mneF,FBenJI->BmJI');
             
     d2 =   einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PPPHHH,'mNEF,EBFIJN->BmJI')...
           +einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PPPHHh,'mnEF,EBFIJn->BmJI')...
           +einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.PpPHHH,'mNeF,BeFJIN->BmJI')...
           +einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PPpHHH,'mNEf,EBfIJN->BmJI')...
           +einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.PpPHHh,'mneF,BeFJIn->BmJI')...
           +einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PPpHHh,'mnEf,EBfIJn->BmJI');
             
     Vt3A.PoHH = d1 + d2;
     
     d1 = 0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPPHHH,'MNeF,ABFMJN->BAJe')...
           +einsum_kg(sys.vA_oovv(hA,HA,:,PA),T3A.PPPhHH,'mNeF,ABFmJN->BAJe')...
           +0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PPpHHH,'MNef,ABfMJN->BAJe')...
           +einsum_kg(sys.vA_oovv(hA,HA,:,pA),T3A.PPphHH,'mNef,ABfmJN->BAJe');
       
      d2 = einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PPPHHH,'MNeF,ABFMJN->BAJe')...
            +einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PPPhHH,'mNeF,ABFmJN->BAJe')...
            +einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PPPHHh,'MneF,ABFMJn->BAJe')...
            +einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PPpHHH,'MNef,ABfMJN->BAJe')...
            +einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PPphHH,'mNef,ABfmJN->BAJe')...
            +einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PPpHHh,'Mnef,ABfMJn->BAJe');
        
      Vt3A.PPHv = -d1 - d2;
     
     d1 =  einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PPPHHh,'NmFE,AFEINj->AmIj')...
          +einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.PpPHHh,'NmfE,AfEINj->AmIj')...
          +einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PPpHHh,'NmFe,AFeINj->AmIj');
      
     d2 =  0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3C.PPPHhH,'mNEF,AEFIjN->AmIj')...
          +einsum_kg(sys.vC_oovv(:,HB,PB,pB),T3C.PPpHhH,'mNEf,AEfIjN->AmIj');
             
     Vt3B.PoHh = d1 + d2;
     
     d1 = 0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3B.PPPHHh,'mNEF,EFBINj->mBIj')...
          +einsum_kg(sys.vA_oovv(:,HA,PA,pA),T3B.PpPHHh,'mNEf,EfBINj->mBIj');
      
     d2 = einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3C.PPPHhH,'mNEF,EBFIjN->mBIj')...
          +einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3C.pPPHhH,'mNeF,eBFIjN->mBIj')...
          +einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3C.PPpHhH,'mNEf,EBfIjN->mBIj');
      
      Vt3B.oPHh = d1 + d2;
      
      d1 = 0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3B.PPPHHh,'MNeF,AFBMNj->ABej')...
          +0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3B.PpPHHh,'MNef,AfBMNj->ABej');
      
      d2 = einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3C.PPPHhH,'MNeF,ABFMjN->ABej')...
          +einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3C.PPpHhH,'MNef,ABfMjN->ABej');
      
      Vt3B.PPvh = -d1 - d2;
      
      d1 = einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PPPHHH,'NMFe,AFBINM->ABIe')...
          +einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PPPHHh,'NmFe,AFBINm->ABIe')...
          +einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PPPhHH,'nMFe,FABnIM->ABIe')...
          +einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.PpPHHH,'NMfe,AfBINM->ABIe')...
          +einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.PpPHHh,'Nmfe,AfBINm->ABIe')...
          -einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.PpPhHH,'nMfe,AfBnIM->ABIe');
      
      d2 = 0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3C.PPPHHH,'MNeF,ABFIMN->ABIe')...
           +einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3C.PPPHhH,'MneF,AFBInM->ABIe')...
           +0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3C.PPpHHH,'MNef,ABfIMN->ABIe')...
           -einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3C.PPpHhH,'Mnef,ABfInM->ABIe');
       
       Vt3B.PPHv = -d1 - d2;

              
end