function [X1A] = update_t1a_proj1_ccsdt2(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys,shift)

    chi1A_vv = sys.fa_vv + einsum_kg(sys.vA_vovv,t1a,'anef,fn->ae') + einsum_kg(sys.vB_vovv,t1b,'anef,fn->ae');
    chi1A_oo = sys.fa_oo + einsum_kg(sys.vA_ooov,t1a,'mnif,fn->mi') + einsum_kg(sys.vB_ooov,t1b,'mnif,fn->mi');
    h1A_ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');
    h1B_ov = sys.fb_ov + einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me') + einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me');
    h1A_oo = chi1A_oo + einsum_kg(h1A_ov,t1a,'me,ei->mi');
       
    M11 = sys.fa_vo - einsum_kg(h1A_oo,t1a,'mi,am->ai') + einsum_kg(chi1A_vv,t1a,'ae,ei->ai')...
          +einsum_kg(sys.vA_voov,t1a,'anif,fn->ai') + einsum_kg(sys.vB_voov,t1b,'anif,fn->ai');
      
    h2A_ooov = sys.vA_ooov + einsum_kg(sys.vA_oovv,t1a,'mnfe,fi->mnie'); 
    h2B_ooov = sys.vB_ooov + einsum_kg(sys.vB_oovv,t1a,'mnfe,fi->mnie');
    h2A_vovv = sys.vA_vovv - einsum_kg(sys.vA_oovv,t1a,'mnfe,an->amef');
    h2B_vovv = sys.vB_vovv - einsum_kg(sys.vB_oovv,t1a,'nmef,an->amef');
      
    CCS_T2 = +einsum_kg(h1A_ov,t2a,'me,aeim->ai') + einsum_kg(h1B_ov,t2b,'me,aeim->ai')...
             -0.5*einsum_kg(h2A_ooov,t2a,'mnif,afmn->ai') - einsum_kg(h2B_ooov,t2b,'mnif,afmn->ai')...
             +0.5*einsum_kg(h2A_vovv,t2a,'anef,efin->ai') + einsum_kg(h2B_vovv,t2b,'anef,efin->ai');
       
    X1A = M11 + CCS_T2; 
    
    % CCSDT part
    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;

D1 = +0.25*einsum_kg(sys.vA_oovv(hA,hA,pA,pA),T3A.PpphhH,'mnef,AefmnI->AI')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,PA,pA),T3A.PPphhH,'mnEf,AEfmnI->AI')...
+0.25*einsum_kg(sys.vA_oovv(hA,hA,PA,PA),T3A.PPPhhH,'mnEF,AEFmnI->AI')...
+0.5*einsum_kg(sys.vA_oovv(HA,hA,pA,pA),T3A.PpphHH,'Mnef,AefnIM->AI')...
+1*einsum_kg(sys.vA_oovv(HA,hA,PA,pA),T3A.PPphHH,'MnEf,AEfnIM->AI')...
+0.5*einsum_kg(sys.vA_oovv(HA,hA,PA,PA),T3A.PPPhHH,'MnEF,AEFnIM->AI')...
+0.25*einsum_kg(sys.vA_oovv(HA,HA,pA,pA),T3A.PppHHH,'MNef,AefIMN->AI')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,PA,pA),T3A.PPpHHH,'MNEf,AEfIMN->AI')...
+0.25*einsum_kg(sys.vA_oovv(HA,HA,PA,PA),T3A.PPPHHH,'MNEF,AEFIMN->AI');

D2 = -1*einsum_kg(sys.vB_oovv(hA,hB,pA,pB),T3B.PpphHh,'mnef,AefmIn->AI')...
-1*einsum_kg(sys.vB_oovv(hA,hB,pA,PB),T3B.PpPhHh,'mneF,AeFmIn->AI')...
-1*einsum_kg(sys.vB_oovv(hA,hB,PA,pB),T3B.PPphHh,'mnEf,AEfmIn->AI')...
-1*einsum_kg(sys.vB_oovv(hA,hB,PA,PB),T3B.PPPhHh,'mnEF,AEFmIn->AI')...
-1*einsum_kg(sys.vB_oovv(hA,HB,pA,pB),T3B.PpphHH,'mNef,AefmIN->AI')...
-1*einsum_kg(sys.vB_oovv(hA,HB,pA,PB),T3B.PpPhHH,'mNeF,AeFmIN->AI')...
-1*einsum_kg(sys.vB_oovv(hA,HB,PA,pB),T3B.PPphHH,'mNEf,AEfmIN->AI')...
-1*einsum_kg(sys.vB_oovv(hA,HB,PA,PB),T3B.PPPhHH,'mNEF,AEFmIN->AI')...
+1*einsum_kg(sys.vB_oovv(HA,hB,pA,pB),T3B.PppHHh,'Mnef,AefIMn->AI')...
+1*einsum_kg(sys.vB_oovv(HA,hB,pA,PB),T3B.PpPHHh,'MneF,AeFIMn->AI')...
+1*einsum_kg(sys.vB_oovv(HA,hB,PA,pB),T3B.PPpHHh,'MnEf,AEfIMn->AI')...
+1*einsum_kg(sys.vB_oovv(HA,hB,PA,PB),T3B.PPPHHh,'MnEF,AEFIMn->AI')...
+1*einsum_kg(sys.vB_oovv(HA,HB,pA,pB),T3B.PppHHH,'MNef,AefIMN->AI')...
+1*einsum_kg(sys.vB_oovv(HA,HB,pA,PB),T3B.PpPHHH,'MNeF,AeFIMN->AI')...
+1*einsum_kg(sys.vB_oovv(HA,HB,PA,pB),T3B.PPpHHH,'MNEf,AEfIMN->AI')...
+1*einsum_kg(sys.vB_oovv(HA,HB,PA,PB),T3B.PPPHHH,'MNEF,AEFIMN->AI');

D3 = +0.25*einsum_kg(sys.vC_oovv(hB,hB,pB,pB),T3C.PppHhh,'mnef,AefImn->AI')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,pB),T3C.PPpHhh,'mnEf,AEfImn->AI')...
+0.25*einsum_kg(sys.vC_oovv(hB,hB,PB,PB),T3C.PPPHhh,'mnEF,AEFImn->AI')...
-0.5*einsum_kg(sys.vC_oovv(HB,hB,pB,pB),T3C.PppHhH,'Mnef,AefInM->AI')...
-1*einsum_kg(sys.vC_oovv(HB,hB,PB,pB),T3C.PPpHhH,'MnEf,AEfInM->AI')...
-0.5*einsum_kg(sys.vC_oovv(HB,hB,PB,PB),T3C.PPPHhH,'MnEF,AEFInM->AI')...
+0.25*einsum_kg(sys.vC_oovv(HB,HB,pB,pB),T3C.PppHHH,'MNef,AefIMN->AI')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,pB),T3C.PPpHHH,'MNEf,AEfIMN->AI')...
+0.25*einsum_kg(sys.vC_oovv(HB,HB,PB,PB),T3C.PPPHHH,'MNEF,AEFIMN->AI');


    X1A_PH = D1 + D2 + D3;

    %X1A(PA,HA) = X1A(PA,HA) + X1A_PH;
    
    for a = 1:sys.Nvir_alpha
        for i = 1:sys.Nocc_alpha
            denom = sys.fa_oo(i,i) - sys.fa_vv(a,a);
            t1a(a,i) = t1a(a,i) + X1A(a,i)/(denom-shift);
        end
    end
    
    for A = 1:sys.Nact_p_alpha
        for I = 1:sys.Nact_h_alpha
            denom = sys.fa_oo(HA(I),HA(I)) - sys.fa_vv(PA(A),PA(A));
            t1a(PA(A),HA(I)) = t1a(PA(A),HA(I)) + X1A_PH/(denom-shift);
        end
    end
            

end