function [X1B] = update_t1b_proj3(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys,shift)

    chi1B_vv = sys.fb_vv + einsum_kg(sys.vC_vovv,t1b,'anef,fn->ae') + einsum_kg(sys.vB_ovvv,t1a,'nafe,fn->ae');
    chi1B_oo = sys.fb_oo + einsum_kg(sys.vC_ooov,t1b,'mnif,fn->mi') + einsum_kg(sys.vB_oovo,t1b,'nmfi,fn->mi');
    h1A_ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');
    h1B_ov = sys.fb_ov + einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me') + einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me');
    h1B_oo = chi1B_oo + einsum_kg(h1B_ov,t1b,'me,ei->mi');
       
    M11 = sys.fb_vo - einsum_kg(h1B_oo,t1b,'mi,am->ai') + einsum_kg(chi1B_vv,t1b,'ae,ei->ai')...
          +einsum_kg(sys.vC_voov,t1b,'anif,fn->ai') + einsum_kg(sys.vB_ovvo,t1a,'nafi,fn->ai');
      
    h2C_ooov = sys.vC_ooov + einsum_kg(sys.vC_oovv,t1b,'mnfe,fi->mnie'); 
    h2B_oovo = sys.vB_oovo + einsum_kg(sys.vB_oovv,t1b,'nmef,fi->nmei');
    h2C_vovv = sys.vC_vovv - einsum_kg(sys.vC_oovv,t1b,'mnfe,an->amef');
    h2B_ovvv = sys.vB_ovvv - einsum_kg(sys.vB_oovv,t1b,'mnfe,an->mafe');
      
    CCS_T2 = +einsum_kg(h1A_ov,t2b,'me,eami->ai') + einsum_kg(h1B_ov,t2c,'me,aeim->ai')...
             -0.5*einsum_kg(h2C_ooov,t2c,'mnif,afmn->ai') - einsum_kg(h2B_oovo,t2b,'nmfi,fanm->ai')...
             +0.5*einsum_kg(h2C_vovv,t2c,'anef,efin->ai') + einsum_kg(h2B_ovvv,t2b,'nafe,feni->ai');
       
    X1B = M11 + CCS_T2; 
    
    % CCSDT part
    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;


D1 = +0.25*einsum_kg(sys.vC_oovv(hB,hB,pB,pB),T3D.Ppphhh,'mnef,Aefimn->Ai')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,pB),T3D.PPphhh,'mnEf,AEfimn->Ai')...
+0.25*einsum_kg(sys.vC_oovv(hB,hB,PB,PB),T3D.PPPhhh,'mnEF,AEFimn->Ai')...
-0.5*einsum_kg(sys.vC_oovv(HB,hB,pB,pB),T3D.PpphhH,'Mnef,AefinM->Ai')...
-1*einsum_kg(sys.vC_oovv(HB,hB,PB,pB),T3D.PPphhH,'MnEf,AEfinM->Ai')...
-0.5*einsum_kg(sys.vC_oovv(HB,hB,PB,PB),T3D.PPPhhH,'MnEF,AEFinM->Ai')...
+0.25*einsum_kg(sys.vC_oovv(HB,HB,pB,pB),T3D.PpphHH,'MNef,AefiMN->Ai')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,pB),T3D.PPphHH,'MNEf,AEfiMN->Ai')...
+0.25*einsum_kg(sys.vC_oovv(HB,HB,PB,PB),T3D.PPPhHH,'MNEF,AEFiMN->Ai');

D2 = -1*einsum_kg(sys.vB_oovv(hA,hB,pA,pB),T3C.pPphhh,'mnef,eAfmni->Ai')...
+1*einsum_kg(sys.vB_oovv(hA,hB,pA,PB),T3C.pPPhhh,'mneF,eFAmni->Ai')...
-1*einsum_kg(sys.vB_oovv(hA,hB,PA,pB),T3C.PPphhh,'mnEf,EAfmni->Ai')...
+1*einsum_kg(sys.vB_oovv(hA,hB,PA,PB),T3C.PPPhhh,'mnEF,EFAmni->Ai')...
+1*einsum_kg(sys.vB_oovv(hA,HB,pA,pB),T3C.pPphhH,'mNef,eAfmiN->Ai')...
-1*einsum_kg(sys.vB_oovv(hA,HB,pA,PB),T3C.pPPhhH,'mNeF,eFAmiN->Ai')...
+1*einsum_kg(sys.vB_oovv(hA,HB,PA,pB),T3C.PPphhH,'mNEf,EAfmiN->Ai')...
-1*einsum_kg(sys.vB_oovv(hA,HB,PA,PB),T3C.PPPhhH,'mNEF,EFAmiN->Ai')...
-1*einsum_kg(sys.vB_oovv(HA,hB,pA,pB),T3C.pPpHhh,'Mnef,eAfMni->Ai')...
+1*einsum_kg(sys.vB_oovv(HA,hB,pA,PB),T3C.pPPHhh,'MneF,eFAMni->Ai')...
-1*einsum_kg(sys.vB_oovv(HA,hB,PA,pB),T3C.PPpHhh,'MnEf,EAfMni->Ai')...
+1*einsum_kg(sys.vB_oovv(HA,hB,PA,PB),T3C.PPPHhh,'MnEF,EFAMni->Ai')...
+1*einsum_kg(sys.vB_oovv(HA,HB,pA,pB),T3C.pPpHhH,'MNef,eAfMiN->Ai')...
-1*einsum_kg(sys.vB_oovv(HA,HB,pA,PB),T3C.pPPHhH,'MNeF,eFAMiN->Ai')...
+1*einsum_kg(sys.vB_oovv(HA,HB,PA,pB),T3C.PPpHhH,'MNEf,EAfMiN->Ai')...
-1*einsum_kg(sys.vB_oovv(HA,HB,PA,PB),T3C.PPPHhH,'MNEF,EFAMiN->Ai');

D3 = +0.25*einsum_kg(sys.vA_oovv(hA,hA,pA,pA),T3B.ppPhhh,'mnef,efAmni->Ai')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,PA,pA),T3B.PpPhhh,'mnEf,EfAmni->Ai')...
+0.25*einsum_kg(sys.vA_oovv(hA,hA,PA,PA),T3B.PPPhhh,'mnEF,EFAmni->Ai')...
-0.5*einsum_kg(sys.vA_oovv(HA,hA,pA,pA),T3B.ppPhHh,'Mnef,efAnMi->Ai')...
-1*einsum_kg(sys.vA_oovv(HA,hA,PA,pA),T3B.PpPhHh,'MnEf,EfAnMi->Ai')...
-0.5*einsum_kg(sys.vA_oovv(HA,hA,PA,PA),T3B.PPPhHh,'MnEF,EFAnMi->Ai')...
+0.25*einsum_kg(sys.vA_oovv(HA,HA,pA,pA),T3B.ppPHHh,'MNef,efAMNi->Ai')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,PA,pA),T3B.PpPHHh,'MNEf,EfAMNi->Ai')...
+0.25*einsum_kg(sys.vA_oovv(HA,HA,PA,PA),T3B.PPPHHh,'MNEF,EFAMNi->Ai');
    
    X1B_Ph = D1 + D2 + D3;
    X1B(PB,hB) = X1B(PB,hB) + X1B_Ph;

end