function [X2C] = update_t2c_proj6(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys,shift)
   
    % H(CCS) intermediates          
    h1B_ov = sys.fb_ov...
             +einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me')...
             +einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me');
         
    h1B_oo = sys.fb_oo...
             +einsum_kg(h1B_ov,t1b,'me,ei->mi')...
             +einsum_kg(sys.vB_oovo,t1a,'nmfi,fn->mi')...
             +einsum_kg(sys.vC_ooov,t1b,'mnif,fn->mi');
         
    h1B_vv = sys.fb_vv...
             -einsum_kg(h1B_ov,t1b,'me,am->ae')...
             +einsum_kg(sys.vB_ovvv,t1a,'nafe,fn->ae')...
             +einsum_kg(sys.vC_vovv,t1b,'anef,fn->ae');
          
    h2C_oooo = sys.vC_oooo...
                +einsum_kg(sys.vC_ooov,t1b,'mnie,ej->mnij')...
	    			-einsum_kg(sys.vC_ooov,t1b,'mnje,ei->mnij')...
                +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,ei->mnif'),t1b,'mnif,fj->mnij'); 
            
    h2C_vvvv = sys.vC_vvvv...
                -einsum_kg(sys.vC_ovvv,t1b,'mbef,am->abef')...
	     			+einsum_kg(sys.vC_ovvv,t1b,'maef,bm->abef')...
                +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,bn->mbef'),t1b,'mbef,am->abef');
                
    h2B_ovvo = sys.vB_ovvo ...
               +einsum_kg(sys.vB_ovvv,t1b,'maef,fi->maei')...
               -einsum_kg(sys.vB_oovo,t1b,'mnei,an->maei')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->maei');
           
    h2C_voov = sys.vC_voov ...
               -einsum_kg(sys.vC_oovo,t1b,'mnei,an->amie')...
               +einsum_kg(sys.vC_vovv,t1b,'amfe,fi->amie')...
               -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->amie');
           
    % <ijab|H(CCS)|0> intermediates - need weights of 0.5 to compensate diagrams that do not have A(ij) or A(ab)
    I2C_ovoo = sys.vC_ovoo ...
               -0.5*einsum_kg(sys.vC_oooo,t1b,'mnij,bn->mbij')...
               +einsum_kg(einsum_kg(sys.vC_ovvv,t1b,'mbef,ei->mbif'),t1b,'mbif,fj->mbij')...
               -0.5*einsum_kg(einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fj->mnej'),t1b,'mnej,ei->mnij'),t1b,'mnij,bn->mbij')...
               +einsum_kg(sys.vC_ovov,t1b,'mbif,fj->mbij')...
                    -einsum_kg(sys.vC_ovov,t1b,'mbjf,fi->mbij');
                
    I2C_vvvo = sys.vC_vvvo...
               +0.5*einsum_kg(sys.vC_vvvv,t1b,'abef,fj->abej')...
               +einsum_kg(einsum_kg(sys.vC_oovo,t1b,'mnej,am->anej'),t1b,'anej,bn->abej');
             
    % VT2 intermediates - need weights of 0.5 to compensate diagrams that do not have A(ij) or A(ab)
    VT2_1B_oo = 0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,efin->mi') + einsum_kg(sys.vB_oovv,t2b,'nmfe,feni->mi');
    VT2_1B_vv = -0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,afmn->ae') - einsum_kg(sys.vB_oovv,t2b,'nmfe,fanm->ae');
    VT2_2C_oooo = 0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,efij->mnij');
    VT2_2B_ovvo = einsum_kg(sys.vB_oovv,t2c,'mnef,afin->maei') + 0.5*einsum_kg(sys.vA_oovv,t2b,'mnef,fani->maei');
    VT2_2C_voov = 0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,afin->amie');
    
    % contraction intermdiates
    I1B_oo = h1B_oo + VT2_1B_oo;
    I1B_vv = h1B_vv + VT2_1B_vv;
    I2C_voov = h2C_voov + VT2_2C_voov;
    I2B_ovvo = h2B_ovvo + VT2_2B_ovvo;
    I2C_oooo = h2C_oooo + VT2_2C_oooo;
    
    % <ijab| H(CCS) | 0> + <ijab| (H(CCS)T2)_C |0> + <ijab| 0.5*(H(CCS)T2^2)_C |0>
    D1 = -einsum_kg(I2C_ovoo,t1b,'mbij,am->abij'); 
    
    D2 = einsum_kg(I2C_vvvo,t1b,'abej,ei->abij');
    
    D3 = einsum_kg(I1B_vv,t2c,'ae,ebij->abij');
    
    D4 = -einsum_kg(I1B_oo,t2c,'mi,abmj->abij');
    
    D5 = einsum_kg(I2C_voov,t2c,'amie,ebmj->abij');
    
    D6 = einsum_kg(I2B_ovvo,t2b,'maei,ebmj->abij');
    
    D7 = 0.5*einsum_kg(h2C_vvvv,t2c,'abef,efij->abij');
    
    D8 = 0.5*einsum_kg(I2C_oooo,t2c,'mnij,abmn->abij');
    
    % diagrams that have A(ab)
    D13 = D1 + D3;
    D13 = D13 - permute(D13,[2,1,3,4]);
    
    % diagrams that have A(ij)
    D24 = D2 + D4;
    D24 = D24 - permute(D24,[1,2,4,3]);
        
    % diagrams that have A(ab)A(ij)
    D56 = D5 + D6;
    D56 = D56 - permute(D56,[2,1,3,4]) - permute(D56,[1,2,4,3]) + permute(D56,[2,1,4,3]);
    
    % total contribution
    X2C = sys.vC_vvoo + D13 + D24 + D56 + D7 + D8;
    
    % CCSDT part
    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;

    H1B.ov = h1B_ov;
    H1A.ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');
    H2C.vovv = sys.vC_vovv - einsum_kg(sys.vC_oovv,t1b,'mnfe,an->amef');
    H2C.ooov = sys.vC_ooov + einsum_kg(sys.vC_oovv,t1b,'mnfe,fi->mnie');
    H2B.ovvv = sys.vB_ovvv - einsum_kg(sys.vB_oovv,t1b,'mnfe,an->mafe');
    H2B.oovo = sys.vB_oovo + einsum_kg(sys.vB_oovv,t1b,'nmef,fi->nmei');
    

D1 = +einsum_kg(H1A.ov(hA,pA),T3C.ppphHH,'me,eabmIJ->abIJ')...
+einsum_kg(H1A.ov(hA,PA),T3C.PpphHH,'mE,EabmIJ->abIJ')...
+einsum_kg(H1A.ov(HA,pA),T3C.pppHHH,'Me,eabMIJ->abIJ')...
+einsum_kg(H1A.ov(HA,PA),T3C.PppHHH,'ME,EabMIJ->abIJ');

D2 = +einsum_kg(H1B.ov(hB,pB),T3D.ppphHH,'me,abemIJ->abIJ')...
+einsum_kg(H1B.ov(hB,PB),T3D.PpphHH,'mE,EabmIJ->abIJ')...
+einsum_kg(H1B.ov(HB,pB),T3D.pppHHH,'Me,abeIJM->abIJ')...
+einsum_kg(H1B.ov(HB,PB),T3D.PppHHH,'ME,EabIJM->abIJ');

D3 = +0.5*einsum_kg(H2C.vovv(pB,hB,pB,pB),T3D.ppphHH,'anef,ebfnIJ->abIJ')...
+einsum_kg(H2C.vovv(pB,hB,PB,pB),T3D.PpphHH,'anEf,EbfnIJ->abIJ')...
-0.5*einsum_kg(H2C.vovv(pB,hB,PB,PB),T3D.PPphHH,'anEF,EFbnIJ->abIJ')...
+0.5*einsum_kg(H2C.vovv(pB,HB,pB,pB),T3D.pppHHH,'aNef,ebfIJN->abIJ')...
+einsum_kg(H2C.vovv(pB,HB,PB,pB),T3D.PppHHH,'aNEf,EbfIJN->abIJ')...
-0.5*einsum_kg(H2C.vovv(pB,HB,PB,PB),T3D.PPpHHH,'aNEF,EFbIJN->abIJ');
D3 = D3 - permute(D3,[2,1,3,4]);

D4 = +einsum_kg(H2B.ovvv(hA,pB,pA,pB),T3C.ppphHH,'nafe,febnIJ->abIJ')...
+einsum_kg(H2B.ovvv(hA,pB,pA,PB),T3C.pPphHH,'nafE,fEbnIJ->abIJ')...
+einsum_kg(H2B.ovvv(hA,pB,PA,pB),T3C.PpphHH,'naFe,FebnIJ->abIJ')...
+einsum_kg(H2B.ovvv(hA,pB,PA,PB),T3C.PPphHH,'naFE,FEbnIJ->abIJ')...
+einsum_kg(H2B.ovvv(HA,pB,pA,pB),T3C.pppHHH,'Nafe,febNIJ->abIJ')...
+einsum_kg(H2B.ovvv(HA,pB,pA,PB),T3C.pPpHHH,'NafE,fEbNIJ->abIJ')...
+einsum_kg(H2B.ovvv(HA,pB,PA,pB),T3C.PppHHH,'NaFe,FebNIJ->abIJ')...
+einsum_kg(H2B.ovvv(HA,pB,PA,PB),T3C.PPpHHH,'NaFE,FEbNIJ->abIJ');
D4 = D4 - permute(D4,[2,1,3,4]);

D5 = +0.5*einsum_kg(H2C.ooov(hB,hB,HB,pB),T3D.ppphhH,'mnIf,abfmnJ->abIJ')...
+0.5*einsum_kg(H2C.ooov(hB,hB,HB,PB),T3D.PpphhH,'mnIF,FabmnJ->abIJ')...
-einsum_kg(H2C.ooov(HB,hB,HB,pB),T3D.ppphHH,'MnIf,abfnMJ->abIJ')...
-einsum_kg(H2C.ooov(HB,hB,HB,PB),T3D.PpphHH,'MnIF,FabnMJ->abIJ')...
-0.5*einsum_kg(H2C.ooov(HB,HB,HB,pB),T3D.pppHHH,'MNIf,abfMJN->abIJ')...
-0.5*einsum_kg(H2C.ooov(HB,HB,HB,PB),T3D.PppHHH,'MNIF,FabMJN->abIJ');
D5 = D5 - permute(D5,[1,2,4,3]);

D6 = -einsum_kg(H2B.oovo(hA,hB,pA,HB),T3C.ppphhH,'nmfI,fabnmJ->abIJ')...
-einsum_kg(H2B.oovo(hA,hB,PA,HB),T3C.PpphhH,'nmFI,FabnmJ->abIJ')...
-einsum_kg(H2B.oovo(hA,HB,pA,HB),T3C.ppphHH,'nMfI,fabnMJ->abIJ')...
-einsum_kg(H2B.oovo(hA,HB,PA,HB),T3C.PpphHH,'nMFI,FabnMJ->abIJ')...
-einsum_kg(H2B.oovo(HA,hB,pA,HB),T3C.pppHhH,'NmfI,fabNmJ->abIJ')...
-einsum_kg(H2B.oovo(HA,hB,PA,HB),T3C.PppHhH,'NmFI,FabNmJ->abIJ')...
-einsum_kg(H2B.oovo(HA,HB,pA,HB),T3C.pppHHH,'NMfI,fabNMJ->abIJ')...
-einsum_kg(H2B.oovo(HA,HB,PA,HB),T3C.PppHHH,'NMFI,FabNMJ->abIJ');
D6 = D6 - permute(D6,[1,2,4,3]);
    
    X2C_ppHH = (D1 + D2 + D3 + D4 + D5 + D6);
    X2C(pB,pB,HB,HB) = X2C(pB,pB,HB,HB) + X2C_ppHH;


end