function [X3B_PpPhHH] = update_t3b_proj8(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys,shift)

    % store active T3 as structs T3A,B,C,D,...
    % e.g. T3B.PPPHHH, etc.
    
    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;
    
    [H1A,H1B,H2A,H2B,H2C,Vt3A,Vt3B] = get_t3b_intermediates(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys);
    
    % MM23B + (V*T2*T3)_C    
    I2B_ovoo = H2B.ovoo - einsum_kg(H1A.ov,t2b,'me,ecjk->mcjk');
    I2B_vooo = H2B.vooo - einsum_kg(H1B.ov,t2b,'me,aeik->amik');
    I2A_vooo = H2A.vooo - einsum_kg(H1A.ov,t2a,'me,aeij->amij');   
    
    M23_D1 = +einsum_kg(H2B.vvvo(pA,PB,:,HB) + Vt3B.pPvH,t2a(PA,:,hA,HA),'bCeK,AeiJ->AbCiJK');
    M23_D2 = -einsum_kg(H2B.vvvo(PA,PB,:,HB) + Vt3B.PPvH,t2a(pA,:,hA,HA),'ACeK,beiJ->AbCiJK');
    
    M23_D3 = -einsum_kg(I2B_ovoo(:,PB,HA,HB) + Vt3B.oPHH,t2a(PA,pA,hA,:),'mCJK,Abim->AbCiJK');
    M23_D4 = +einsum_kg(I2B_ovoo(:,PB,hA,HB) + Vt3B.oPhH,t2a(PA,pA,HA,:),'mCiK,AbJm->AbCiJK');
    
    M23_D5 = +einsum_kg(H2B.vvov(PA,PB,hA,:) + Vt3B.PPhv,t2b(pA,:,HA,HB),'ACie,beJK->AbCiJK');
    M23_D6 = -einsum_kg(H2B.vvov(pA,PB,hA,:) + Vt3B.pPhv,t2b(PA,:,HA,HB),'bCie,AeJK->AbCiJK');
    M23_D7 = -einsum_kg(H2B.vvov(PA,PB,HA,:) + Vt3B.PPHv,t2b(pA,:,hA,HB),'ACJe,beiK->AbCiJK');
    M23_D8 = +einsum_kg(H2B.vvov(pA,PB,HA,:) + Vt3B.pPHv,t2b(PA,:,hA,HB),'bCJe,AeiK->AbCiJK');
    
    M23_D9 = -einsum_kg(I2B_vooo(PA,:,hA,HB) + Vt3B.PohH,t2b(pA,PB,HA,:),'AmiK,bCJm->AbCiJK');
    M23_D10 = +einsum_kg(I2B_vooo(pA,:,hA,HB) + Vt3B.pohH,t2b(PA,PB,HA,:),'bmiK,ACJm->AbCiJK');
    M23_D11 = +einsum_kg(I2B_vooo(PA,:,HA,HB) + Vt3B.PoHH,t2b(pA,PB,hA,:),'AmJK,bCim->AbCiJK');
    M23_D12 = -einsum_kg(I2B_vooo(pA,:,HA,HB) + Vt3B.poHH,t2b(PA,PB,hA,:),'bmJK,ACim->AbCiJK');
    
    M23_D13 = +einsum_kg(H2A.vvov(PA,pA,hA,:) + Vt3A.Pphv,t2b(:,PB,HA,HB),'Abie,eCJK->AbCiJK');
    M23_D14 = -einsum_kg(H2A.vvov(PA,pA,HA,:) + Vt3A.PpHv,t2b(:,PB,hA,HB),'AbJe,eCiK->AbCiJK');
    
    M23_D15 = -einsum_kg(I2A_vooo(PA,:,hA,HA) + Vt3A.PohH,t2b(pA,PB,:,HB),'AmiJ,bCmK->AbCiJK');
    M23_D16 = +einsum_kg(I2A_vooo(pA,:,hA,HA) + Vt3A.pohH,t2b(PA,PB,:,HB),'bmiJ,ACmK->AbCiJK');
    
    MM23B = M23_D1 + M23_D2 + M23_D3 + M23_D4 + M23_D5 + M23_D6 + M23_D7 + ...
            M23_D8 + M23_D9 + M23_D10 + M23_D11 + M23_D12 + M23_D13 + M23_D14 + ...
            M23_D15 + M23_D16;
  
    %%%%%
    
D1 = -einsum_kg(H1A.oo(hA,hA),T3B.PpPhHH,'mi,AbCmJK->AbCiJK')...
-einsum_kg(H1A.oo(HA,hA),T3B.PpPHHH,'Mi,AbCMJK->AbCiJK')...
+einsum_kg(H1A.oo(hA,HA),T3B.PpPhhH,'mJ,AbCmiK->AbCiJK')...
-einsum_kg(H1A.oo(HA,HA),T3B.PpPhHH,'MJ,AbCiMK->AbCiJK');

D2 = -einsum_kg(H1B.oo(hB,HB),T3B.PpPhHh,'mK,AbCiJm->AbCiJK')...
-einsum_kg(H1B.oo(HB,HB),T3B.PpPhHH,'MK,AbCiJM->AbCiJK');

D3 = +einsum_kg(H1A.vv(PA,pA),T3B.ppPhHH,'Ae,ebCiJK->AbCiJK')...
+einsum_kg(H1A.vv(PA,PA),T3B.PpPhHH,'AE,EbCiJK->AbCiJK')...
+einsum_kg(H1A.vv(pA,pA),T3B.PpPhHH,'be,AeCiJK->AbCiJK')...
-einsum_kg(H1A.vv(pA,PA),T3B.PPPhHH,'bE,EACiJK->AbCiJK');

D4 = +einsum_kg(H1B.vv(PB,pB),T3B.PpphHH,'Ce,AbeiJK->AbCiJK')...
+einsum_kg(H1B.vv(PB,PB),T3B.PpPhHH,'CE,AbEiJK->AbCiJK');

D5 = +0.5*einsum_kg(H2A.oooo(hA,hA,hA,HA),T3B.PpPhhH,'mniJ,AbCmnK->AbCiJK')...
-einsum_kg(H2A.oooo(HA,hA,hA,HA),T3B.PpPhHH,'MniJ,AbCnMK->AbCiJK')...
+0.5*einsum_kg(H2A.oooo(HA,HA,hA,HA),T3B.PpPHHH,'MNiJ,AbCMNK->AbCiJK');

D6 = +einsum_kg(H2B.oooo(hA,hB,HA,HB),T3B.PpPhhh,'mnJK,AbCimn->AbCiJK')...
+einsum_kg(H2B.oooo(hA,HB,HA,HB),T3B.PpPhhH,'mNJK,AbCimN->AbCiJK')...
+einsum_kg(H2B.oooo(HA,hB,HA,HB),T3B.PpPhHh,'MnJK,AbCiMn->AbCiJK')...
+einsum_kg(H2B.oooo(HA,HB,HA,HB),T3B.PpPhHH,'MNJK,AbCiMN->AbCiJK')...
+einsum_kg(H2B.oooo(hA,hB,hA,HB),T3B.PpPhHh,'mniK,AbCmJn->AbCiJK')...
+einsum_kg(H2B.oooo(hA,HB,hA,HB),T3B.PpPhHH,'mNiK,AbCmJN->AbCiJK')...
-einsum_kg(H2B.oooo(HA,hB,hA,HB),T3B.PpPHHh,'MniK,AbCJMn->AbCiJK')...
-einsum_kg(H2B.oooo(HA,HB,hA,HB),T3B.PpPHHH,'MNiK,AbCJMN->AbCiJK');

D7 = +0.5*einsum_kg(H2A.vvvv(PA,pA,pA,pA),T3B.ppPhHH,'Abef,efCiJK->AbCiJK')...
+einsum_kg(H2A.vvvv(PA,pA,PA,pA),T3B.PpPhHH,'AbEf,EfCiJK->AbCiJK')...
+0.5*einsum_kg(H2A.vvvv(PA,pA,PA,PA),T3B.PPPhHH,'AbEF,EFCiJK->AbCiJK');

D8 = +einsum_kg(H2B.vvvv(pA,PB,pA,pB),T3B.PpphHH,'bCef,AefiJK->AbCiJK')...
+einsum_kg(H2B.vvvv(pA,PB,pA,PB),T3B.PpPhHH,'bCeF,AeFiJK->AbCiJK')...
+einsum_kg(H2B.vvvv(pA,PB,PA,pB),T3B.PPphHH,'bCEf,AEfiJK->AbCiJK')...
+einsum_kg(H2B.vvvv(pA,PB,PA,PB),T3B.PPPhHH,'bCEF,AEFiJK->AbCiJK')...
-einsum_kg(H2B.vvvv(PA,PB,pA,pB),T3B.ppphHH,'ACef,befiJK->AbCiJK')...
-einsum_kg(H2B.vvvv(PA,PB,pA,PB),T3B.ppPhHH,'ACeF,beFiJK->AbCiJK')...
+einsum_kg(H2B.vvvv(PA,PB,PA,pB),T3B.PpphHH,'ACEf,EbfiJK->AbCiJK')...
+einsum_kg(H2B.vvvv(PA,PB,PA,PB),T3B.PpPhHH,'ACEF,EbFiJK->AbCiJK');

D9 = +einsum_kg(H2A.voov(PA,hA,hA,pA),T3B.ppPhHH,'Amie,ebCmJK->AbCiJK')...
+einsum_kg(H2A.voov(PA,hA,hA,PA),T3B.PpPhHH,'AmiE,EbCmJK->AbCiJK')...
+einsum_kg(H2A.voov(PA,HA,hA,pA),T3B.ppPHHH,'AMie,ebCMJK->AbCiJK')...
+einsum_kg(H2A.voov(PA,HA,hA,PA),T3B.PpPHHH,'AMiE,EbCMJK->AbCiJK')...
+einsum_kg(H2A.voov(pA,hA,hA,pA),T3B.PpPhHH,'bmie,AeCmJK->AbCiJK')...
-einsum_kg(H2A.voov(pA,hA,hA,PA),T3B.PPPhHH,'bmiE,EACmJK->AbCiJK')...
+einsum_kg(H2A.voov(pA,HA,hA,pA),T3B.PpPHHH,'bMie,AeCMJK->AbCiJK')...
-einsum_kg(H2A.voov(pA,HA,hA,PA),T3B.PPPHHH,'bMiE,EACMJK->AbCiJK')...
-einsum_kg(H2A.voov(PA,hA,HA,pA),T3B.ppPhhH,'AmJe,ebCmiK->AbCiJK')...
-einsum_kg(H2A.voov(PA,hA,HA,PA),T3B.PpPhhH,'AmJE,EbCmiK->AbCiJK')...
+einsum_kg(H2A.voov(PA,HA,HA,pA),T3B.ppPhHH,'AMJe,ebCiMK->AbCiJK')...
+einsum_kg(H2A.voov(PA,HA,HA,PA),T3B.PpPhHH,'AMJE,EbCiMK->AbCiJK')...
-einsum_kg(H2A.voov(pA,hA,HA,pA),T3B.PpPhhH,'bmJe,AeCmiK->AbCiJK')...
+einsum_kg(H2A.voov(pA,hA,HA,PA),T3B.PPPhhH,'bmJE,EACmiK->AbCiJK')...
+einsum_kg(H2A.voov(pA,HA,HA,pA),T3B.PpPhHH,'bMJe,AeCiMK->AbCiJK')...
-einsum_kg(H2A.voov(pA,HA,HA,PA),T3B.PPPhHH,'bMJE,EACiMK->AbCiJK');

D10 = -einsum_kg(H2B.voov(PA,hB,hA,pB),T3C.pPpHhH,'Amie,bCeJmK->AbCiJK')...
-einsum_kg(H2B.voov(PA,hB,hA,PB),T3C.pPPHhH,'AmiE,bCEJmK->AbCiJK')...
+einsum_kg(H2B.voov(PA,HB,hA,pB),T3C.pPpHHH,'AMie,bCeJKM->AbCiJK')...
+einsum_kg(H2B.voov(PA,HB,hA,PB),T3C.pPPHHH,'AMiE,bCEJKM->AbCiJK')...
+einsum_kg(H2B.voov(pA,hB,hA,pB),T3C.PPpHhH,'bmie,ACeJmK->AbCiJK')...
+einsum_kg(H2B.voov(pA,hB,hA,PB),T3C.PPPHhH,'bmiE,ACEJmK->AbCiJK')...
-einsum_kg(H2B.voov(pA,HB,hA,pB),T3C.PPpHHH,'bMie,ACeJKM->AbCiJK')...
-einsum_kg(H2B.voov(pA,HB,hA,PB),T3C.PPPHHH,'bMiE,ACEJKM->AbCiJK')...
+einsum_kg(H2B.voov(PA,hB,HA,pB),T3C.pPphhH,'AmJe,bCeimK->AbCiJK')...
+einsum_kg(H2B.voov(PA,hB,HA,PB),T3C.pPPhhH,'AmJE,bCEimK->AbCiJK')...
-einsum_kg(H2B.voov(PA,HB,HA,pB),T3C.pPphHH,'AMJe,bCeiKM->AbCiJK')...
-einsum_kg(H2B.voov(PA,HB,HA,PB),T3C.pPPhHH,'AMJE,bCEiKM->AbCiJK')...
-einsum_kg(H2B.voov(pA,hB,HA,pB),T3C.PPphhH,'bmJe,ACeimK->AbCiJK')...
-einsum_kg(H2B.voov(pA,hB,HA,PB),T3C.PPPhhH,'bmJE,ACEimK->AbCiJK')...
+einsum_kg(H2B.voov(pA,HB,HA,pB),T3C.PPphHH,'bMJe,ACeiKM->AbCiJK')...
+einsum_kg(H2B.voov(pA,HB,HA,PB),T3C.PPPhHH,'bMJE,ACEiKM->AbCiJK');

D11 = -einsum_kg(H2B.ovvo(hA,PB,pA,HB),T3A.PpphhH,'mCeK,AbeimJ->AbCiJK')...
+einsum_kg(H2B.ovvo(hA,PB,PA,HB),T3A.PPphhH,'mCEK,AEbimJ->AbCiJK')...
+einsum_kg(H2B.ovvo(HA,PB,pA,HB),T3A.PpphHH,'MCeK,AbeiJM->AbCiJK')...
-einsum_kg(H2B.ovvo(HA,PB,PA,HB),T3A.PPphHH,'MCEK,AEbiJM->AbCiJK');

D12 = +einsum_kg(H2C.voov(PB,hB,HB,pB),T3B.PpphHh,'CmKe,AbeiJm->AbCiJK')...
+einsum_kg(H2C.voov(PB,hB,HB,PB),T3B.PpPhHh,'CmKE,AbEiJm->AbCiJK')...
+einsum_kg(H2C.voov(PB,HB,HB,pB),T3B.PpphHH,'CMKe,AbeiJM->AbCiJK')...
+einsum_kg(H2C.voov(PB,HB,HB,PB),T3B.PpPhHH,'CMKE,AbEiJM->AbCiJK');

D13 = -einsum_kg(H2B.vovo(PA,hB,pA,HB),T3B.ppPhHh,'AmeK,ebCiJm->AbCiJK')...
-einsum_kg(H2B.vovo(PA,hB,PA,HB),T3B.PpPhHh,'AmEK,EbCiJm->AbCiJK')...
-einsum_kg(H2B.vovo(PA,HB,pA,HB),T3B.ppPhHH,'AMeK,ebCiJM->AbCiJK')...
-einsum_kg(H2B.vovo(PA,HB,PA,HB),T3B.PpPhHH,'AMEK,EbCiJM->AbCiJK')...
-einsum_kg(H2B.vovo(pA,hB,pA,HB),T3B.PpPhHh,'bmeK,AeCiJm->AbCiJK')...
+einsum_kg(H2B.vovo(pA,hB,PA,HB),T3B.PPPhHh,'bmEK,EACiJm->AbCiJK')...
-einsum_kg(H2B.vovo(pA,HB,pA,HB),T3B.PpPhHH,'bMeK,AeCiJM->AbCiJK')...
+einsum_kg(H2B.vovo(pA,HB,PA,HB),T3B.PPPhHH,'bMEK,EACiJM->AbCiJK');

D14 = -einsum_kg(H2B.ovov(hA,PB,hA,pB),T3B.PpphHH,'mCie,AbemJK->AbCiJK')...
-einsum_kg(H2B.ovov(hA,PB,hA,PB),T3B.PpPhHH,'mCiE,AbEmJK->AbCiJK')...
-einsum_kg(H2B.ovov(HA,PB,hA,pB),T3B.PppHHH,'MCie,AbeMJK->AbCiJK')...
-einsum_kg(H2B.ovov(HA,PB,hA,PB),T3B.PpPHHH,'MCiE,AbEMJK->AbCiJK')...
+einsum_kg(H2B.ovov(hA,PB,HA,pB),T3B.PpphhH,'mCJe,AbemiK->AbCiJK')...
+einsum_kg(H2B.ovov(hA,PB,HA,PB),T3B.PpPhhH,'mCJE,AbEmiK->AbCiJK')...
-einsum_kg(H2B.ovov(HA,PB,HA,pB),T3B.PpphHH,'MCJe,AbeiMK->AbCiJK')...
-einsum_kg(H2B.ovov(HA,PB,HA,PB),T3B.PpPhHH,'MCJE,AbEiMK->AbCiJK');

    X3B_PpPhHH = MM23B + D1 + D2 + D3 + D4 + D5 + D6 + D7 + D8 + D9 + D10 + D11 + D12 + D13 + D14;

end

function [H1A,H1B,H2A,H2B,H2C,Vt3A,Vt3B] = get_t3b_intermediates(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys)

    % h1A(mi)
    H1A.oo = sys.fa_oo ...
             +einsum_kg(sys.fa_ov,t1a,'me,ei->mi')...
             +einsum_kg(sys.vA_ooov,t1a,'mnif,fn->mi')...
             +einsum_kg(sys.vB_ooov,t1b,'mnif,fn->mi')...
             +0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efin->mi')...
             +einsum_kg(sys.vB_oovv,t2b,'mnef,efin->mi')...
             +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,ei->mi')...
             +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,ei->mi');
         
    % h1A(ae)
    H1A.vv = sys.fa_vv ...
             -einsum_kg(sys.fa_ov,t1a,'me,am->ae')...
             +einsum_kg(sys.vA_vovv,t1a,'amef,fm->ae')...
             +einsum_kg(sys.vB_vovv,t1b,'anef,fn->ae')...
             -0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,afmn->ae')...
             -einsum_kg(sys.vB_oovv,t2b,'mnef,afmn->ae')...
             -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,am->ae')...
             -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,am->ae');
         
    % h1A(me)
    H1A.ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');

    % h1B(mi)
    H1B.oo = sys.fb_oo ...
             +einsum_kg(sys.fb_ov,t1b,'me,ei->mi')...
             +einsum_kg(sys.vB_oovo,t1a,'nmfi,fn->mi')...
             +einsum_kg(sys.vC_ooov,t1b,'mnif,fn->mi')...
             +einsum_kg(sys.vB_oovv,t2b,'nmfe,feni->mi')...
             +0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,efin->mi')...
             +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t1b,'me,ei->mi')...
             +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t1b,'me,ei->mi');
         
    % h1B(ae)
    H1B.vv = sys.fb_vv ...
             -einsum_kg(sys.fb_ov,t1b,'me,am->ae')...
             +einsum_kg(sys.vB_ovvv,t1a,'nafe,fn->ae')...
             +einsum_kg(sys.vC_vovv,t1b,'anef,fn->ae')...
             -einsum_kg(sys.vB_oovv,t2b,'nmfe,fanm->ae')...
             -0.5*einsum_kg(sys.vC_oovv,t2c,'mnef,afmn->ae')...
             -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t1b,'me,am->ae')...
             -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t1b,'me,am->ae');
         
    % h1B(me)
    H1B.ov = sys.fb_ov + einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me') + einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me');
    
    % h2A(amij)
    H2A.vooo    = sys.vA_vooo ...
                  +einsum_kg(sys.vA_voov,t1a,'amie,ej->amij')...
	    			-einsum_kg(sys.vA_voov,t1a,'amje,ei->amij')...
                  -einsum_kg(sys.vA_oooo,t1a,'nmij,an->amij')...
                  +einsum_kg(sys.fa_ov,t2a,'me,aeij->amij')...
                  +0.5*einsum_kg(sys.vA_vovv,t2a,'amef,efij->amij')...
                  +einsum_kg(sys.vA_oovo,t2a,'nmej,aein->amij')...
	    			-einsum_kg(sys.vA_oovo,t2a,'nmei,aejn->amij')...
                  +einsum_kg(sys.vB_ooov,t2b,'mnje,aein->amij')...
	    			-einsum_kg(sys.vB_ooov,t2b,'mnie,aejn->amij')...
                  -einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmej,ei->nmij'),t1a,'nmij,an->amij')...
	    			+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmei,ej->nmij'),t1a,'nmij,an->amij')...
                  +einsum_kg(einsum_kg(sys.vA_vovv,t1a,'amef,ei->amif'),t1a,'amif,fj->amij')...
                  -0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,an->amef'),t2a,'amef,efij->amij')...
                  +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ej->mnjf'),t2a,'mnjf,afin->amij')...
	    			-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t2a,'mnif,afjn->amij')...
                  +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,aeij->amij')...
                  +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t2b,'mnjf,afin->amij')...
	    			-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ei->mnif'),t2b,'mnif,afjn->amij')...
                  +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,aeij->amij')...
                  -einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,fj->nmej'),t1a,'nmej,an->amej'),t1a,'amej,ei->amij');

    % h(abie)
    H2A.vvov  = sys.vA_vvov ...
	    	+einsum_kg(sys.vA_vvvv,t1a,'abfe,fi->abie')...
	    	-einsum_kg(sys.vA_ovov,t1a,'nbie,an->abie')...
	    			+einsum_kg(sys.vA_ovov,t1a,'naie,bn->abie')...
	    	-einsum_kg(sys.fa_ov,t2a,'me,abim->abie')...
	    	+einsum_kg(sys.vA_ovvv,t2a,'nbfe,afin->abie')...
	    			-einsum_kg(sys.vA_ovvv,t2a,'nafe,bfin->abie')...
	    	+0.5*einsum_kg(sys.vA_oovo,t2a,'mnei,abnm->abie')...
	    	+einsum_kg(sys.vB_vovv,t2b,'bnef,afin->abie')...
	    			-einsum_kg(sys.vB_vovv,t2b,'anef,bfin->abie')...
	    	+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'mnei,an->maei'),t1a,'maei,bm->abie')...
	    	-einsum_kg(einsum_kg(sys.vA_vovv,t1a,'bnef,fi->bnei'),t1a,'bnei,an->abie')...
	    			+einsum_kg(einsum_kg(sys.vA_vovv,t1a,'anef,fi->anei'),t1a,'anei,bn->abie')...
	    	+0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fi->mnei'),t2a,'mnei,abnm->abie')...
	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t2a,'bnef,afin->abie')...
	    			+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,am->anef'),t2a,'anef,bfin->abie')...
	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,abim->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,bm->bnef'),t2b,'bnef,afin->abie')...
	    			+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,am->anef'),t2b,'anef,bfin->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,abim->abie')...
	    	+einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t1a,'bnef,an->baef'),t1a,'baef,fi->abie');

     % h2A(mnij)
     H2A.oooo = sys.vA_oooo...
	     	+einsum_kg(sys.vA_oovo,t1a,'mnej,ei->mnij')...
	     			-einsum_kg(sys.vA_oovo,t1a,'mnei,ej->mnij')...
	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efij->mnij')...
	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t1a,'mnif,fj->mnij');

     % h2A(abef)
     H2A.vvvv = sys.vA_vvvv...
	     	-einsum_kg(sys.vA_ovvv,t1a,'mbef,am->abef')...
	     			+einsum_kg(sys.vA_ovvv,t1a,'maef,bm->abef')...
	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,abmn->abef')...
	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bn->mbef'),t1a,'mbef,am->abef');
        
     % h2A(amie)
     H2A.voov = sys.vA_voov ...
                -einsum_kg(sys.vA_ooov,t1a,'nmie,an->amie')...
                +einsum_kg(sys.vA_vovv,t1a,'amfe,fi->amie')...
                -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
                +einsum_kg(sys.vA_oovv,t2a,'nmfe,afin->amie')...
                +einsum_kg(sys.vB_oovv,t2b,'mnef,afin->amie');
        
     % h2B(amij)
     H2B.vooo = sys.vB_vooo...
               -einsum_kg(sys.vB_oooo,t1a,'nmij,an->amij')...
               +einsum_kg(sys.vB_vovo,t1a,'amej,ei->amij')...
               +einsum_kg(sys.vB_voov,t1b,'amie,ej->amij')...
               +einsum_kg(sys.vB_oovo,t2a,'nmej,aein->amij')...
               +einsum_kg(sys.vC_oovo,t2b,'nmej,aein->amij')...
               +einsum_kg(sys.vB_vovv,t2b,'amef,efij->amij')...
               -einsum_kg(sys.vB_ooov,t2b,'nmif,afnj->amij')...
               +einsum_kg(sys.fb_ov,t2b,'me,aeij->amij')...
               -einsum_kg(einsum_kg(sys.vB_oovo,t1a,'nmej,an->amej'),t1a,'amej,ei->amij')...
               -einsum_kg(einsum_kg(sys.vB_ooov,t1b,'nmie,ej->nmij'),t1a,'nmij,an->amij')...
               +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,ej->mnjf'),t2b,'mnjf,afin->amij')...
               +einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t2b,'me,aeij->amij')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,an->amfe'),t2b,'amfe,feij->amij')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t2b,'nmie,aenj->amij')...
               +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t2b,'me,aeij->amij')...
               +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,ej->nmfj'),t2a,'nmfj,afin->amij')...
               -einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,ej->nmfj'),t1a,'nmfj,an->amfj'),t1a,'amfj,fi->amij')...
               +einsum_kg(einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie'),t1b,'amie,ej->amij');

    % h2B(maji)
    H2B.ovoo =  sys.vB_ovoo...
                +einsum_kg(sys.vB_ovvo,t1a,'maei,ej->maji')...
                -einsum_kg(sys.vB_oooo,t1b,'mnji,an->maji')...
                +einsum_kg(sys.vB_ovov,t1b,'majf,fi->maji')...
                +einsum_kg(sys.vB_ooov,t2c,'mnjf,afin->maji')...
                +einsum_kg(sys.vB_ovvv,t2b,'maef,efji->maji')...
                +einsum_kg(sys.vA_ooov,t2b,'mnjf,fani->maji')...
                -einsum_kg(sys.vB_oovo,t2b,'mnei,eajn->maji')...
                +einsum_kg(sys.fa_ov,t2b,'me,eaji->maji')...
                -einsum_kg(einsum_kg(sys.vB_ooov,t1b,'mnjf,an->majf'),t1b,'majf,fi->maji')...
                +einsum_kg(einsum_kg(sys.vB_ovvv,t1a,'maef,ej->majf'),t1b,'majf,fi->maji')...
                -einsum_kg(einsum_kg(sys.vB_oovo,t1a,'mnei,ej->mnji'),t1b,'mnji,an->maji')...
                +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t2c,'mnjf,afin->maji')...
                +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2b,'me,eaji->maji')...
                +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ej->mnjf'),t2b,'mnjf,fani->maji')...
                -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,an->maef'),t2b,'maef,efji->maji')...
                +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2b,'me,eaji->maji')...
                -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t2b,'mnei,eajn->maji')...
                -einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t1b,'mnjf,an->majf'),t1b,'majf,fi->maji');

    % h2B(abie)
    H2B.vvov =  sys.vB_vvov...
	    	-einsum_kg(sys.vB_ovov,t1a,'nbie,an->abie')...
	    	+einsum_kg(sys.vB_vvvv,t1a,'abfe,fi->abie')...
	    	-einsum_kg(sys.vB_voov,t1b,'amie,bm->abie')...
	    	+einsum_kg(sys.vB_ovvv,t2a,'nbfe,afin->abie')...
	    	+einsum_kg(sys.vC_ovvv,t2b,'nbfe,afin->abie')...
	    	+einsum_kg(sys.vB_ooov,t2b,'nmie,abnm->abie')...
	    	-einsum_kg(sys.vB_vovv,t2b,'amfe,fbim->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_ovvv,t1a,'nbfe,an->abfe'),t1a,'abfe,fi->abie')...
	    	+einsum_kg(einsum_kg(sys.vB_ooov,t1a,'nmie,an->amie'),t1b,'amie,bm->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie'),t1b,'amie,bm->abie')...
	    	-einsum_kg(sys.fb_ov,t2b,'me,abim->abie')...
	    	-einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,bm->bnef'),t2b,'bnef,afin->abie')...
	    	-einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fn->me'),t2b,'me,abim->abie')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t2b,'nmie,abnm->abie')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,an->amfe'),t2b,'amfe,fbim->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fn->me'),t2b,'me,abim->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmfe,bm->nbfe'),t2a,'nbfe,afin->abie')...
	    	+einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,an->amfe'),t1a,'amfe,fi->amie'),t1b,'amie,bm->abie');

    % h2B(baei)
    H2B.vvvo =  sys.vB_vvvo...
	    	+einsum_kg(sys.vB_vvvv,t1b,'baef,fi->baei')...
	    	-einsum_kg(sys.vB_vovo,t1b,'bnei,an->baei')...
	    	-einsum_kg(sys.vB_ovvo,t1a,'maei,bm->baei')...
	    	+einsum_kg(sys.vB_vovv,t2c,'bnef,afin->baei')...
	    	+einsum_kg(sys.vB_oovo,t2b,'mnei,bamn->baei')...
	    	+einsum_kg(sys.vA_vovv,t2b,'bnef,fani->baei')...
	    	-einsum_kg(sys.vB_ovvv,t2b,'maef,bfmi->baei')...
	    	-einsum_kg(sys.fa_ov,t2b,'me,bami->baei')...
	    	-einsum_kg(einsum_kg(sys.vB_vovv,t1b,'bnef,fi->bnei'),t1b,'bnei,an->baei')...
	    	+einsum_kg(einsum_kg(sys.vB_oovo,t1b,'mnei,an->maei'),t1a,'maei,bm->baei')...
	    	-einsum_kg(einsum_kg(sys.vB_ovvv,t1b,'maef,fi->maei'),t1a,'maei,bm->baei')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,bm->bnef'),t2c,'bnef,afin->baei')...
	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2b,'me,bami->baei')...
	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t2b,'bnef,fani->baei')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t2b,'mnei,bamn->baei')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2b,'me,bami->baei')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,an->maef'),t2b,'maef,bfmi->baei')...
	    	+einsum_kg(einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,an->maef'),t1b,'maef,fi->maei'),t1a,'maei,bm->baei');

    % h2B(mnij)
    H2B.oooo =  sys.vB_oooo...
	    	+einsum_kg(sys.vB_oovo,t1a,'mnej,ei->mnij')...
	   	+einsum_kg(sys.vB_ooov,t1b,'mnif,fj->mnij')...
	   	+einsum_kg(sys.vB_oovv,t2b,'mnef,efij->mnij')...
	   	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ei->mnif'),t1b,'mnif,fj->mnij'); 

    % h2B(abef)
    H2B.vvvv =  sys.vB_vvvv...
	    	-einsum_kg(sys.vB_ovvv,t1a,'mbef,am->abef')...
	    	-einsum_kg(sys.vB_vovv,t1b,'anef,bn->abef')...
	    	+einsum_kg(sys.vB_oovv,t2b,'mnef,abmn->abef')...
	    	+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,am->anef'),t1b,'anef,bn->abef');
        
    % h2B(amie)
    H2B.voov = sys.vB_voov ...
               -einsum_kg(sys.vB_ooov,t1a,'nmie,an->amie')...
               +einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
               +einsum_kg(sys.vB_oovv,t2a,'nmfe,afin->amie')...
               +einsum_kg(sys.vC_oovv,t2b,'mnef,afin->amie');
          
    % h2B(maie)
    H2B.ovov = sys.vB_ovov ...
               +einsum_kg(sys.vB_ovvv,t1a,'mafe,fi->maie')...
               -einsum_kg(sys.vB_ooov,t1b,'mnie,an->maie')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnfe,an->mafe'),t1a,'mafe,fi->maie')...
               -einsum_kg(sys.vB_oovv,t2b,'mnfe,fain->maie');
           
    % h2B(amei)
    H2B.vovo = sys.vB_vovo ...
               -einsum_kg(sys.vB_oovo,t1a,'nmei,an->amei')...
               +einsum_kg(sys.vB_vovv,t1b,'amef,fi->amei')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'nmef,fi->nmei'),t1a,'nmei,an->amei')...
               -einsum_kg(sys.vB_oovv,t2b,'nmef,afni->amei');
           
    % h2B(maei)
    H2B.ovvo = sys.vB_ovvo ...
               +einsum_kg(sys.vB_ovvv,t1b,'maef,fi->maei')...
               -einsum_kg(sys.vB_oovo,t1b,'mnei,an->maei')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->maei')...
               +einsum_kg(sys.vB_oovv,t2c,'mnef,afin->maei')...
               +einsum_kg(sys.vA_oovv,t2b,'mnef,fani->maei');
   
     % h2C(amie)
     H2C.voov = sys.vC_voov ...
                -einsum_kg(sys.vC_oovo,t1b,'mnei,an->amie')...
                +einsum_kg(sys.vC_vovv,t1b,'amfe,fi->amie')...
                -einsum_kg(einsum_kg(sys.vC_oovv,t1b,'mnef,fi->mnei'),t1b,'mnei,an->amie')...
                +einsum_kg(sys.vC_oovv,t2c,'mnef,afin->amie')...
                +einsum_kg(sys.vB_oovv,t2b,'nmfe,fani->amie');

     % (Vt3)_C intermediates
     PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
     PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;
    
d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3C.pPphhH,'mnef,aBfmnJ->aBeJ')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3C.pPPhhH,'mneF,aFBmnJ->aBeJ')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3C.pPphHH,'mNef,aBfmNJ->aBeJ')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3C.pPPhHH,'mNeF,aFBmNJ->aBeJ')...
-einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3C.pPpHhH,'Mnef,aBfMnJ->aBeJ')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3C.pPPHhH,'MneF,aFBMnJ->aBeJ')...
-einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3C.pPpHHH,'MNef,aBfMNJ->aBeJ')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3C.pPPHHH,'MNeF,aFBMNJ->aBeJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3B.ppPhhH,'mnef,afBmnJ->aBeJ')...
-0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3B.PpPhhH,'mneF,FaBmnJ->aBeJ')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3B.ppPhHH,'Mnef,afBnMJ->aBeJ')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3B.PpPhHH,'MneF,FaBnMJ->aBeJ')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3B.ppPHHH,'MNef,afBMNJ->aBeJ')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3B.PpPHHH,'MNeF,FaBMNJ->aBeJ');

Vt3B.pPvH = -d1 - d2;

d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3C.PPphhH,'mnef,ABfmnJ->ABeJ')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3C.PPPhhH,'mneF,AFBmnJ->ABeJ')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3C.PPphHH,'mNef,ABfmNJ->ABeJ')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3C.PPPhHH,'mNeF,AFBmNJ->ABeJ')...
-einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3C.PPpHhH,'Mnef,ABfMnJ->ABeJ')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3C.PPPHhH,'MneF,AFBMnJ->ABeJ')...
-einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3C.PPpHHH,'MNef,ABfMNJ->ABeJ')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3C.PPPHHH,'MNeF,AFBMNJ->ABeJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3B.PpPhhH,'mnef,AfBmnJ->ABeJ')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3B.PPPhhH,'mneF,AFBmnJ->ABeJ')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3B.PpPhHH,'Mnef,AfBnMJ->ABeJ')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3B.PPPhHH,'MneF,AFBnMJ->ABeJ')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3B.PpPHHH,'MNef,AfBMNJ->ABeJ')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3B.PPPHHH,'MNeF,AFBMNJ->ABeJ');

Vt3B.PPvH = -d1 - d2;

d1 = -einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3C.pPpHhH,'mnef,eBfInJ->mBIJ')...
-einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3C.PPpHhH,'mnEf,EBfInJ->mBIJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3C.pPPHhH,'mneF,eFBInJ->mBIJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3C.PPPHhH,'mnEF,EFBInJ->mBIJ')...
-einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3C.pPpHHH,'mNef,eBfINJ->mBIJ')...
-einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3C.PPpHHH,'mNEf,EBfINJ->mBIJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3C.pPPHHH,'mNeF,eFBINJ->mBIJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3C.PPPHHH,'mNEF,EFBINJ->mBIJ');

d2 = -0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3B.ppPhHH,'mnef,efBnIJ->mBIJ')...
+einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3B.PpPhHH,'mneF,FeBnIJ->mBIJ')...
-0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3B.PPPhHH,'mnEF,EFBnIJ->mBIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3B.ppPHHH,'mNef,efBINJ->mBIJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3B.PpPHHH,'mNeF,FeBINJ->mBIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3B.PPPHHH,'mNEF,EFBINJ->mBIJ');

Vt3B.oPHH = d1 + d2;

d1 = -einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3C.pPphhH,'mnef,eBfinJ->mBiJ')...
-einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3C.PPphhH,'mnEf,EBfinJ->mBiJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3C.pPPhhH,'mneF,eFBinJ->mBiJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3C.PPPhhH,'mnEF,EFBinJ->mBiJ')...
-einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3C.pPphHH,'mNef,eBfiNJ->mBiJ')...
-einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3C.PPphHH,'mNEf,EBfiNJ->mBiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3C.pPPhHH,'mNeF,eFBiNJ->mBiJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3C.PPPhHH,'mNEF,EFBiNJ->mBiJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3B.ppPhhH,'mnef,efBinJ->mBiJ')...
-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3B.PpPhhH,'mneF,FeBinJ->mBiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3B.PPPhhH,'mnEF,EFBinJ->mBiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3B.ppPhHH,'mNef,efBiNJ->mBiJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3B.PpPhHH,'mNeF,FeBiNJ->mBiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3B.PPPhHH,'mNEF,EFBiNJ->mBiJ');

Vt3B.oPhH = d1 + d2;

d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.PpPhhh,'nmfe,AfBinm->ABie')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.PPPhhh,'nmFe,AFBinm->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.PpPhHh,'Nmfe,AfBiNm->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PPPhHh,'NmFe,AFBiNm->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.PpPhhH,'nMfe,AfBinM->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PPPhhH,'nMFe,AFBinM->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.PpPhHH,'NMfe,AfBiNM->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PPPhHH,'NMFe,AFBiNM->ABie');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.PPphhh,'nmfe,ABfinm->ABie')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.PPPhhh,'nmFe,AFBinm->ABie')...
-einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.PPphhH,'nMfe,ABfinM->ABie')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.PPPhhH,'nMFe,AFBinM->ABie')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.PPphHH,'NMfe,ABfiNM->ABie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.PPPhHH,'NMFe,AFBiNM->ABie');

Vt3B.PPhv = -d1 - d2;

d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.ppPhhh,'nmfe,afBinm->aBie')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.PpPhhh,'nmFe,FaBinm->aBie')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.ppPhHh,'Nmfe,afBiNm->aBie')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PpPhHh,'NmFe,FaBiNm->aBie')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.ppPhhH,'nMfe,afBinM->aBie')...
-einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PpPhhH,'nMFe,FaBinM->aBie')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.ppPhHH,'NMfe,afBiNM->aBie')...
-einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PpPhHH,'NMFe,FaBiNM->aBie');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.pPphhh,'nmfe,aBfinm->aBie')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.pPPhhh,'nmFe,aFBinm->aBie')...
-einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.pPphhH,'nMfe,aBfinM->aBie')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.pPPhhH,'nMFe,aFBinM->aBie')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.pPphHH,'NMfe,aBfiNM->aBie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.pPPhHH,'NMFe,aFBiNM->aBie');

Vt3B.pPhv = -d1 - d2;

d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.PpPhHh,'nmfe,AfBnIm->ABIe')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.PPPhHh,'nmFe,AFBnIm->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.PpPHHh,'Nmfe,AfBINm->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PPPHHh,'NmFe,AFBINm->ABIe')...
-einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.PpPhHH,'nMfe,AfBnIM->ABIe')...
-einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PPPhHH,'nMFe,AFBnIM->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.PpPHHH,'NMfe,AfBINM->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PPPHHH,'NMFe,AFBINM->ABIe');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.PPpHhh,'nmfe,ABfInm->ABIe')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.PPPHhh,'nmFe,AFBInm->ABIe')...
-einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.PPpHhH,'nMfe,ABfInM->ABIe')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.PPPHhH,'nMFe,AFBInM->ABIe')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.PPpHHH,'NMfe,ABfINM->ABIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.PPPHHH,'NMFe,AFBINM->ABIe');

Vt3B.PPHv = -d1 - d2;

d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.ppPhHh,'nmfe,afBnIm->aBIe')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.PpPhHh,'nmFe,FaBnIm->aBIe')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.ppPHHh,'Nmfe,afBINm->aBIe')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PpPHHh,'NmFe,FaBINm->aBIe')...
-einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.ppPhHH,'nMfe,afBnIM->aBIe')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PpPhHH,'nMFe,FaBnIM->aBIe')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.ppPHHH,'NMfe,afBINM->aBIe')...
-einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PpPHHH,'NMFe,FaBINM->aBIe');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.pPpHhh,'nmfe,aBfInm->aBIe')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.pPPHhh,'nmFe,aFBInm->aBIe')...
-einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.pPpHhH,'nMfe,aBfInM->aBIe')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.pPPHhH,'nMFe,aFBInM->aBIe')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.pPpHHH,'NMfe,aBfINM->aBIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.pPPHHH,'NMFe,aFBINM->aBIe');

Vt3B.pPHv = -d1 - d2;

d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.PpphhH,'nmfe,AfeinJ->AmiJ')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.PpPhhH,'nmfE,AfEinJ->AmiJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.PPphhH,'nmFe,AFeinJ->AmiJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PPPhhH,'nmFE,AFEinJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.PpphHH,'Nmfe,AfeiNJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.PpPhHH,'NmfE,AfEiNJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PPphHH,'NmFe,AFeiNJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PPPhHH,'NmFE,AFEiNJ->AmiJ');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.PpphhH,'nmfe,AfeinJ->AmiJ')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.PPphhH,'nmFe,AFeinJ->AmiJ')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.PPPhhH,'nmFE,AFEinJ->AmiJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.PpphHH,'Nmfe,AfeiNJ->AmiJ')...
+einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.PPphHH,'NmFe,AFeiNJ->AmiJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.PPPhHH,'NmFE,AFEiNJ->AmiJ');

Vt3B.PohH = d1 + d2;

d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.ppphhH,'nmfe,afeinJ->amiJ')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.ppPhhH,'nmfE,afEinJ->amiJ')...
-einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.PpphhH,'nmFe,FaeinJ->amiJ')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PpPhhH,'nmFE,FaEinJ->amiJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.ppphHH,'Nmfe,afeiNJ->amiJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.ppPhHH,'NmfE,afEiNJ->amiJ')...
-einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PpphHH,'NmFe,FaeiNJ->amiJ')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PpPhHH,'NmFE,FaEiNJ->amiJ');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.ppphhH,'nmfe,afeinJ->amiJ')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.pPphhH,'nmFe,aFeinJ->amiJ')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.pPPhhH,'nmFE,aFEinJ->amiJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.ppphHH,'Nmfe,afeiNJ->amiJ')...
+einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.pPphHH,'NmFe,aFeiNJ->amiJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.pPPhHH,'NmFE,aFEiNJ->amiJ');

Vt3B.pohH = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.PpphHH,'nmfe,AfenIJ->AmIJ')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.PpPhHH,'nmfE,AfEnIJ->AmIJ')...
-einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.PPphHH,'nmFe,AFenIJ->AmIJ')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PPPhHH,'nmFE,AFEnIJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.PppHHH,'Nmfe,AfeINJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.PpPHHH,'NmfE,AfEINJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PPpHHH,'NmFe,AFeINJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PPPHHH,'NmFE,AFEINJ->AmIJ');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.PppHhH,'nmfe,AfeInJ->AmIJ')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.PPpHhH,'nmFe,AFeInJ->AmIJ')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.PPPHhH,'nmFE,AFEInJ->AmIJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.PppHHH,'Nmfe,AfeINJ->AmIJ')...
+einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.PPpHHH,'NmFe,AFeINJ->AmIJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.PPPHHH,'NmFE,AFEINJ->AmIJ');

Vt3B.PoHH = d1 + d2;

d1 = -einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.ppphHH,'nmfe,afenIJ->amIJ')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.ppPhHH,'nmfE,afEnIJ->amIJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.PpphHH,'nmFe,FaenIJ->amIJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PpPhHH,'nmFE,FaEnIJ->amIJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.pppHHH,'Nmfe,afeINJ->amIJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.ppPHHH,'NmfE,afEINJ->amIJ')...
-einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PppHHH,'NmFe,FaeINJ->amIJ')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PpPHHH,'NmFE,FaEINJ->amIJ');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.pppHhH,'nmfe,afeInJ->amIJ')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.pPpHhH,'nmFe,aFeInJ->amIJ')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.pPPHhH,'nmFE,aFEInJ->amIJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.pppHHH,'Nmfe,afeINJ->amIJ')...
+einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.pPpHHH,'NmFe,aFeINJ->amIJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.pPPHHH,'NmFE,aFEINJ->amIJ');

Vt3B.poHH = d1 + d2;

d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.Ppphhh,'mnef,Abfimn->Abie')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PpPhhh,'mneF,AbFimn->Abie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PpphhH,'mNef,AbfimN->Abie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhhH,'mNeF,AbFimN->Abie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PpphHh,'Mnef,AbfiMn->Abie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPhHh,'MneF,AbFiMn->Abie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PpphHH,'MNef,AbfiMN->Abie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPhHH,'MNeF,AbFiMN->Abie');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.Ppphhh,'mnef,Abfimn->Abie')...
-0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPphhh,'mneF,AFbimn->Abie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PpphhH,'Mnef,AbfinM->Abie')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphhH,'MneF,AFbinM->Abie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PpphHH,'MNef,AbfiMN->Abie')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPphHH,'MNeF,AFbiMN->Abie');

Vt3A.Pphv = -d1 - d2;

d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PpphHh,'mnef,AbfmIn->AbIe')...
-einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PpPhHh,'mneF,AbFmIn->AbIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PpphHH,'mNef,AbfmIN->AbIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhHH,'mNeF,AbFmIN->AbIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PppHHh,'Mnef,AbfIMn->AbIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPHHh,'MneF,AbFIMn->AbIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PppHHH,'MNef,AbfIMN->AbIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPHHH,'MNeF,AbFIMN->AbIe');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PpphhH,'mnef,AbfmnI->AbIe')...
-0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPphhH,'mneF,AFbmnI->AbIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PpphHH,'Mnef,AbfnIM->AbIe')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphHH,'MneF,AFbnIM->AbIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PppHHH,'MNef,AbfIMN->AbIe')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPpHHH,'MNeF,AFbIMN->AbIe');

Vt3A.PpHv = -d1 - d2;

d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.PpphHh,'mnef,AefiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PPphHh,'mnEf,AEfiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.PpPhHh,'mneF,AeFiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PPPhHh,'mnEF,AEFiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.PpphHH,'mNef,AefiJN->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PPphHH,'mNEf,AEfiJN->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.PpPhHH,'mNeF,AeFiJN->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PPPhHH,'mNEF,AEFiJN->AmiJ');

d2 = -0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.PpphhH,'mnef,AefinJ->AmiJ')...
+einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PPphhH,'mneF,AFeinJ->AmiJ')...
-0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPPhhH,'mnEF,AEFinJ->AmiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.PpphHH,'mNef,AefiJN->AmiJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PPphHH,'mNeF,AFeiJN->AmiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPPhHH,'mNEF,AEFiJN->AmiJ');

Vt3A.PohH = d1 + d2;

d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.ppphHh,'mnef,aefiJn->amiJ')...
-einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PpphHh,'mnEf,EafiJn->amiJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.ppPhHh,'mneF,aeFiJn->amiJ')...
-einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PpPhHh,'mnEF,EaFiJn->amiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.ppphHH,'mNef,aefiJN->amiJ')...
-einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PpphHH,'mNEf,EafiJN->amiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.ppPhHH,'mNeF,aeFiJN->amiJ')...
-einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PpPhHH,'mNEF,EaFiJN->amiJ');

d2 = -0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.ppphhH,'mnef,aefinJ->amiJ')...
-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PpphhH,'mneF,FaeinJ->amiJ')...
-0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPphhH,'mnEF,EFainJ->amiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.ppphHH,'mNef,aefiJN->amiJ')...
+einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PpphHH,'mNeF,FaeiJN->amiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPphHH,'mNEF,EFaiJN->amiJ');

Vt3A.pohH = d1 + d2;

              
end