function [t3a] = update_t3a_proj3_ccsdt2(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,HBar_t,sys,shift)

    PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;

    H1A = HBar_t.H1A; H2A = HBar_t.H2A; H2B = HBar_t.H2B;
    [Vt3A] = get_t3a_intermediates(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys);

    I2A_vvov = H2A.vvov+einsum_kg(H1A.ov,t2a,'me,abim->abie');
    
    % MM23A + (V*T2*T3)_C
    M23_D1 = -einsum_kg(H2A.vooo(PA,:,hA,HA) + Vt3A.PohH,t2a(PA,PA,:,HA),'AmiJ,BCmK->ABCiJK');
    M23_D1 = M23_D1 - permute(M23_D1,[1,2,3,4,6,5]);
    M23_D2 = +einsum_kg(H2A.vooo(PA,:,HA,HA) + Vt3A.PoHH,t2a(PA,PA,:,hA),'AmKJ,BCmi->ABCiJK');
    M23_D12 = M23_D1 + M23_D2;
    M23_D12 = M23_D12 - permute(M23_D12,[2,1,3,4,5,6]) - permute(M23_D12,[3,2,1,4,5,6]);

    M23_D3 = +einsum_kg(I2A_vvov(PA,PA,hA,:) + Vt3A.PPhv,t2a(:,PA,HA,HA),'ABie,eCJK->ABCiJK');
    M23_D4 = -einsum_kg(I2A_vvov(PA,PA,HA,:) + Vt3A.PPHv,t2a(:,PA,hA,HA),'ABJe,eCiK->ABCiJK');
    M23_D4 = M23_D4 - permute(M23_D4,[1,2,3,4,6,5]);
    M23_D34 = M23_D3 + M23_D4;
    M23_D34 = M23_D34 - permute(M23_D34,[1,3,2,4,5,6]) - permute(M23_D34,[3,2,1,4,5,6]);

    MM23A = M23_D12 + M23_D34;
              
    % (HBar*T3)_C    

D1 = +einsum_kg(H1A.oo(hA,HA),T3A.PPPhhH,'mK,ABCimJ->ABCiJK')...
-einsum_kg(H1A.oo(HA,HA),T3A.PPPhHH,'MK,ABCiJM->ABCiJK');
D1 = D1 - permute(D1,[1,2,3,4,6,5]);

D2 = +einsum_kg(H1A.oo(hA,hA),T3A.PPPhHH,'mi,ABCmKJ->ABCiJK')...
+einsum_kg(H1A.oo(HA,hA),T3A.PPPHHH,'Mi,ABCKJM->ABCiJK');

D3 = +einsum_kg(H1A.vv(PA,pA),T3A.PPphHH,'Ce,ABeiJK->ABCiJK')...
+einsum_kg(H1A.vv(PA,PA),T3A.PPPhHH,'CE,ABEiJK->ABCiJK');
D3 = D3 - permute(D3,[3,2,1,4,5,6]) - permute(D3,[1,3,2,4,5,6]);

D4 = +0.5*einsum_kg(H2A.oooo(hA,hA,hA,HA),T3A.PPPhhH,'mniJ,ABCmnK->ABCiJK')...
-einsum_kg(H2A.oooo(HA,hA,hA,HA),T3A.PPPhHH,'MniJ,ABCnMK->ABCiJK')...
+0.5*einsum_kg(H2A.oooo(HA,HA,hA,HA),T3A.PPPHHH,'MNiJ,ABCMNK->ABCiJK');
D4 = D4 - permute(D4,[1,2,3,4,6,5]);

D5 = -0.5*einsum_kg(H2A.oooo(hA,hA,HA,HA),T3A.PPPhhh,'mnKJ,ABCmni->ABCiJK')...
-einsum_kg(H2A.oooo(HA,hA,HA,HA),T3A.PPPhhH,'MnKJ,ABCniM->ABCiJK')...
-0.5*einsum_kg(H2A.oooo(HA,HA,HA,HA),T3A.PPPhHH,'MNKJ,ABCiMN->ABCiJK');

D6 = +0.5*einsum_kg(H2A.vvvv(PA,PA,pA,pA),T3A.PpphHH,'ABef,CefiJK->ABCiJK')...
-einsum_kg(H2A.vvvv(PA,PA,PA,pA),T3A.PPphHH,'ABEf,ECfiJK->ABCiJK')...
+0.5*einsum_kg(H2A.vvvv(PA,PA,PA,PA),T3A.PPPhHH,'ABEF,EFCiJK->ABCiJK');
D6 = D6 - permute(D6,[3,2,1,4,5,6]) - permute(D6,[1,3,2,4,5,6]);

D7 = -einsum_kg(H2A.voov(PA,hA,HA,pA),T3A.PPphhH,'CmKe,ABeimJ->ABCiJK')...
-einsum_kg(H2A.voov(PA,hA,HA,PA),T3A.PPPhhH,'CmKE,ABEimJ->ABCiJK')...
+einsum_kg(H2A.voov(PA,HA,HA,pA),T3A.PPphHH,'CMKe,ABeiJM->ABCiJK')...
+einsum_kg(H2A.voov(PA,HA,HA,PA),T3A.PPPhHH,'CMKE,ABEiJM->ABCiJK');
D7 = D7 - permute(D7,[1,2,3,4,6,5]);

D8 = -einsum_kg(H2A.voov(PA,hA,hA,pA),T3A.PPphHH,'Cmie,ABemKJ->ABCiJK')...
-einsum_kg(H2A.voov(PA,hA,hA,PA),T3A.PPPhHH,'CmiE,ABEmKJ->ABCiJK')...
-einsum_kg(H2A.voov(PA,HA,hA,pA),T3A.PPpHHH,'CMie,ABeKJM->ABCiJK')...
-einsum_kg(H2A.voov(PA,HA,hA,PA),T3A.PPPHHH,'CMiE,ABEKJM->ABCiJK');

D78 = D7 + D8;
D78 = D78 - permute(D78,[3,2,1,4,5,6]) - permute(D78,[1,3,2,4,5,6]);

D9 = +einsum_kg(H2B.voov(PA,hB,HA,pB),T3B.PPphHh,'CmKe,ABeiJm->ABCiJK')...
+einsum_kg(H2B.voov(PA,hB,HA,PB),T3B.PPPhHh,'CmKE,ABEiJm->ABCiJK')...
+einsum_kg(H2B.voov(PA,HB,HA,pB),T3B.PPphHH,'CMKe,ABeiJM->ABCiJK')...
+einsum_kg(H2B.voov(PA,HB,HA,PB),T3B.PPPhHH,'CMKE,ABEiJM->ABCiJK');
D9 = D9 - permute(D9,[1,2,3,4,6,5]);

D10 = -einsum_kg(H2B.voov(PA,hB,hA,pB),T3B.PPpHHh,'Cmie,ABeKJm->ABCiJK')...
-einsum_kg(H2B.voov(PA,hB,hA,PB),T3B.PPPHHh,'CmiE,ABEKJm->ABCiJK')...
-einsum_kg(H2B.voov(PA,HB,hA,pB),T3B.PPpHHH,'CMie,ABeKJM->ABCiJK')...
-einsum_kg(H2B.voov(PA,HB,hA,PB),T3B.PPPHHH,'CMiE,ABEKJM->ABCiJK');

D910 = D9 + D10;
D910 = D910 - permute(D910,[3,2,1,4,5,6]) - permute(D910,[1,3,2,4,5,6]);

        
    X3A_PPPhHH = D1 + D2 + D3 + D4 + D5 + D6 + D78 + D910 + MM23A;
    
    t3a = T3A.PPPhHH;
    for a = 1:sys.Nact_p_alpha
        for b = a+1:sys.Nact_p_alpha
            for c = b+1:sys.Nact_p_alpha
                for i = 1:sys.Nunact_h_alpha
                    for j = 1:sys.Nact_h_alpha
                        for k = j+1:sys.Nact_h_alpha
                            
                            denom = sys.fa_hh(i,i) + sys.fa_HH(j,j) + sys.fa_HH(k,k) - sys.fa_PP(a,a) - sys.fa_PP(b,b) - sys.fa_PP(c,c);
                            
                            t3a(a,b,c,i,j,k) = t3a(a,b,c,i,j,k) + X3A_PPPhHH(a,b,c,i,j,k)/(denom-shift);   
                            t3a(a,b,c,i,k,j) = -t3a(a,b,c,i,j,k);
                            
                            t3a(b,a,c,i,j,k) = -t3a(a,b,c,i,j,k);
                            t3a(b,a,c,i,k,j) = t3a(a,b,c,i,j,k);

                            t3a(a,c,b,i,j,k) = -t3a(a,b,c,i,j,k);
                            t3a(a,c,b,i,k,j) = t3a(a,b,c,i,j,k);
                            
                            t3a(c,b,a,i,j,k) = -t3a(a,b,c,i,j,k);
                            t3a(c,b,a,i,k,j) = t3a(a,b,c,i,j,k);

                            t3a(b,c,a,i,j,k) = t3a(a,b,c,i,j,k);
                            t3a(b,c,a,i,k,j) = -t3a(a,b,c,i,j,k);
                            
                            t3a(c,a,b,i,j,k) = t3a(a,b,c,i,j,k);
                            t3a(c,a,b,i,k,j) = -t3a(a,b,c,i,j,k);
                        end
                    end
                end
            end
        end
    end
    %T3A.PPPhHH = t3a;


end

function [Vt3A] = get_t3a_intermediates(t1a,t1b,t2a,t2b,t2c,T3A,T3B,T3C,T3D,sys)

%     % h1A(me)
%     H1A.ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');
% 
%     % h1A(mi)
%     H1A.oo = sys.fa_oo ...
%              +einsum_kg(sys.fa_ov,t1a,'me,ei->mi')...
%              +einsum_kg(sys.vA_ooov,t1a,'mnif,fn->mi')...
%              +einsum_kg(sys.vB_ooov,t1b,'mnif,fn->mi')...
%              +0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efin->mi')...
%              +einsum_kg(sys.vB_oovv,t2b,'mnef,efin->mi')...
%              +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,ei->mi')...
%              +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,ei->mi');
%          
%     % h1A(ae)
%     H1A.vv = sys.fa_vv ...
%              -einsum_kg(sys.fa_ov,t1a,'me,am->ae')...
%              +einsum_kg(sys.vA_vovv,t1a,'amef,fm->ae')...
%              +einsum_kg(sys.vB_vovv,t1b,'anef,fn->ae')...
%              -0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,afmn->ae')...
%              -einsum_kg(sys.vB_oovv,t2b,'mnef,afmn->ae')...
%              -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,am->ae')...
%              -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,am->ae');
% 
%     % h2A(amij)
%     H2A.vooo    = sys.vA_vooo ...
%                   +einsum_kg(sys.vA_voov,t1a,'amie,ej->amij')...
% 	    			-einsum_kg(sys.vA_voov,t1a,'amje,ei->amij')...
%                   -einsum_kg(sys.vA_oooo,t1a,'nmij,an->amij')...
%                   +einsum_kg(sys.fa_ov,t2a,'me,aeij->amij')...
%                   +0.5*einsum_kg(sys.vA_vovv,t2a,'amef,efij->amij')...
%                   +einsum_kg(sys.vA_oovo,t2a,'nmej,aein->amij')...
% 	    			-einsum_kg(sys.vA_oovo,t2a,'nmei,aejn->amij')...
%                   +einsum_kg(sys.vB_ooov,t2b,'mnje,aein->amij')...
% 	    			-einsum_kg(sys.vB_ooov,t2b,'mnie,aejn->amij')...
%                   -einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmej,ei->nmij'),t1a,'nmij,an->amij')...
% 	    			+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmei,ej->nmij'),t1a,'nmij,an->amij')...
%                   +einsum_kg(einsum_kg(sys.vA_vovv,t1a,'amef,ei->amif'),t1a,'amif,fj->amij')...
%                   -0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,an->amef'),t2a,'amef,efij->amij')...
%                   +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ej->mnjf'),t2a,'mnjf,afin->amij')...
% 	    			-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t2a,'mnif,afjn->amij')...
%                   +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,aeij->amij')...
%                   +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t2b,'mnjf,afin->amij')...
% 	    			-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ei->mnif'),t2b,'mnif,afjn->amij')...
%                   +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,aeij->amij')...
%                   -einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,fj->nmej'),t1a,'nmej,an->amej'),t1a,'amej,ei->amij');
% 
%     % h(abie)
%     H2A.vvov  = sys.vA_vvov ...
% 	    	+einsum_kg(sys.vA_vvvv,t1a,'abfe,fi->abie')...
% 	    	-einsum_kg(sys.vA_ovov,t1a,'nbie,an->abie')...
% 	    			+einsum_kg(sys.vA_ovov,t1a,'naie,bn->abie')...
% 	    	-einsum_kg(sys.fa_ov,t2a,'me,abim->abie')...
% 	    	+einsum_kg(sys.vA_ovvv,t2a,'nbfe,afin->abie')...
% 	    			-einsum_kg(sys.vA_ovvv,t2a,'nafe,bfin->abie')...
% 	    	+0.5*einsum_kg(sys.vA_oovo,t2a,'mnei,abnm->abie')...
% 	    	+einsum_kg(sys.vB_vovv,t2b,'bnef,afin->abie')...
% 	    			-einsum_kg(sys.vB_vovv,t2b,'anef,bfin->abie')...
% 	    	+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'mnei,an->maei'),t1a,'maei,bm->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vA_vovv,t1a,'bnef,fi->bnei'),t1a,'bnei,an->abie')...
% 	    			+einsum_kg(einsum_kg(sys.vA_vovv,t1a,'anef,fi->anei'),t1a,'anei,bn->abie')...
% 	    	+0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fi->mnei'),t2a,'mnei,abnm->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t2a,'bnef,afin->abie')...
% 	    			+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,am->anef'),t2a,'anef,bfin->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,abim->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,bm->bnef'),t2b,'bnef,afin->abie')...
% 	    			+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,am->anef'),t2b,'anef,bfin->abie')...
% 	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,abim->abie')...
% 	    	+einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t1a,'bnef,an->baef'),t1a,'baef,fi->abie');
% 
%      % h2A(mnij)
%      H2A.oooo = sys.vA_oooo...
% 	     	+einsum_kg(sys.vA_oovo,t1a,'mnej,ei->mnij')...
% 	     			-einsum_kg(sys.vA_oovo,t1a,'mnei,ej->mnij')...
% 	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efij->mnij')...
% 	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t1a,'mnif,fj->mnij');
% 
%      % h2A(abef)
%      H2A.vvvv = sys.vA_vvvv...
% 	     	-einsum_kg(sys.vA_ovvv,t1a,'mbef,am->abef')...
% 	     			+einsum_kg(sys.vA_ovvv,t1a,'maef,bm->abef')...
% 	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,abmn->abef')...
% 	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bn->mbef'),t1a,'mbef,am->abef');
%         
%      % h2A(amie)
%      H2A.voov = sys.vA_voov ...
%                 -einsum_kg(sys.vA_ooov,t1a,'nmie,an->amie')...
%                 +einsum_kg(sys.vA_vovv,t1a,'amfe,fi->amie')...
%                 -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
%                 +einsum_kg(sys.vA_oovv,t2a,'nmfe,afin->amie')...
%                 +einsum_kg(sys.vB_oovv,t2b,'mnef,afin->amie');
%             
%     % h2B(amie)
%     H2B.voov = sys.vB_voov ...
%                -einsum_kg(sys.vB_ooov,t1a,'nmie,an->amie')...
%                +einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie')...
%                -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
%                +einsum_kg(sys.vB_oovv,t2a,'nmfe,afin->amie')...
%                +einsum_kg(sys.vC_oovv,t2b,'mnef,afin->amie');
           
    % (VT3)_C 
        PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
    PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;
    
    d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PPphHh,'mnef,ABfmIn->ABIe')...
-einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PPPhHh,'mneF,ABFmIn->ABIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PPphHH,'mNef,ABfmIN->ABIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PPPhHH,'mNeF,ABFmIN->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PPpHHh,'Mnef,ABfIMn->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PPPHHh,'MneF,ABFIMn->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PPpHHH,'MNef,ABfIMN->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PPPHHH,'MNeF,ABFIMN->ABIe');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PPphhH,'mnef,ABfmnI->ABIe')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPPhhH,'mneF,ABFmnI->ABIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PPphHH,'Mnef,ABfnIM->ABIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPPhHH,'MneF,ABFnIM->ABIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PPpHHH,'MNef,ABfIMN->ABIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPPHHH,'MNeF,ABFIMN->ABIe');

Vt3A.PPHv = -d1 - d2;

d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PPphhh,'mnef,ABfimn->ABie')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PPPhhh,'mneF,ABFimn->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PPphhH,'mNef,ABfimN->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PPPhhH,'mNeF,ABFimN->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PPphHh,'Mnef,ABfiMn->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PPPhHh,'MneF,ABFiMn->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PPphHH,'MNef,ABfiMN->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PPPhHH,'MNeF,ABFiMN->ABie');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PPphhh,'mnef,ABfimn->ABie')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPPhhh,'mneF,ABFimn->ABie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PPphhH,'Mnef,ABfinM->ABie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPPhhH,'MneF,ABFinM->ABie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PPphHH,'MNef,ABfiMN->ABie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPPhHH,'MNeF,ABFiMN->ABie');

Vt3A.PPhv = -d1 - d2;

d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.PppHHh,'mnef,AefIJn->AmIJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PPpHHh,'mnEf,AEfIJn->AmIJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.PpPHHh,'mneF,AeFIJn->AmIJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PPPHHh,'mnEF,AEFIJn->AmIJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.PppHHH,'mNef,AefIJN->AmIJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PPpHHH,'mNEf,AEfIJN->AmIJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.PpPHHH,'mNeF,AeFIJN->AmIJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PPPHHH,'mNEF,AEFIJN->AmIJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.PpphHH,'mnef,AefnIJ->AmIJ')...
-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PPphHH,'mneF,AFenIJ->AmIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPPhHH,'mnEF,AEFnIJ->AmIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.PppHHH,'mNef,AefIJN->AmIJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PPpHHH,'mNeF,AFeIJN->AmIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPPHHH,'mNEF,AEFIJN->AmIJ');

Vt3A.PoHH = d1 + d2;

d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.PpphHh,'mnef,AefiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PPphHh,'mnEf,AEfiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.PpPhHh,'mneF,AeFiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PPPhHh,'mnEF,AEFiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.PpphHH,'mNef,AefiJN->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PPphHH,'mNEf,AEfiJN->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.PpPhHH,'mNeF,AeFiJN->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PPPhHH,'mNEF,AEFiJN->AmiJ');

d2 = -0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.PpphhH,'mnef,AefinJ->AmiJ')...
+einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PPphhH,'mneF,AFeinJ->AmiJ')...
-0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPPhhH,'mnEF,AEFinJ->AmiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.PpphHH,'mNef,AefiJN->AmiJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PPphHH,'mNeF,AFeiJN->AmiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPPhHH,'mNEF,AEFiJN->AmiJ');

Vt3A.PohH = d1 + d2;

end
