function [t3a] = update_t3a_proj1(t1a, t1b, t2a, t2b, t2c, t3a, t3b, t3c, t3d, sys, shift)

    [H1A, H2A, H2B, VTA] = get_t3a_intermediates(t1a,t1b,t2a,t2b,t2c,t3a,t3b,t3c,t3d,sys);
    
    PA = sys.PA; PB  = sys.PB; HA = sys.HA; HB = sys.HB;

    I2A_vvov = H2A.vvov+einsum_kg(H1A.ov,t2a,'me,abim->abie');
    
    % MM23A + (V*T2*T3)_C
    M23_D1 =   -einsum_kg(H2A.vooo(PA,:,HA,HA) + VTA.vooo,t2a(PA,PA,:,HA),'AmIJ,BCmK->ABCIJK'); 
    M23_D1 = M23_D1 - permute(M23_D1,[1,2,3,6,5,4]) - permute(M23_D1,[1,2,3,4,6,5]) - permute(M23_D1,[3,2,1,4,5,6])...
                    - permute(M23_D1,[2,1,3,4,5,6]) + permute(M23_D1,[2,1,3,6,5,4]) + permute(M23_D1,[3,2,1,6,5,4]) ...
                    + permute(M23_D1,[2,1,3,4,6,5]) + permute(M23_D1,[3,2,1,4,6,5]);

         
    M23_D2 =   +einsum_kg(I2A_vvov(PA,PA,HA,:) + VTA.vvov,t2a(:,PA,HA,HA),'ABIe,eCJK->ABCIJK');
    M23_D2 = M23_D2 - permute(M23_D2,[1,2,3,5,4,6]) - permute(M23_D2,[1,2,3,6,5,4]) ...
                    - permute(M23_D2,[3,2,1,4,5,6]) - permute(M23_D2,[1,3,2,4,5,6]) + permute(M23_D2,[3,2,1,5,4,6]) ...
                    + permute(M23_D2,[1,3,2,5,4,6]) + permute(M23_D2,[3,2,1,6,5,4]) + permute(M23_D2,[1,3,2,6,5,4]);
                
    MM23A = M23_D1 + M23_D2;
                
%     VT_1 = -0.5*einsum_kg(einsum_kg(sys.vA_oovv,t3a,'mnef,afcmnk->acek'),t2a,'acek,ebij->abcijk');
%     VT_2 = -einsum_kg(einsum_kg(sys.vB_oovv,t3b,'mnef,acfmkn->acek'),t2a,'acek,ebij->abcijk');
%     VT_12 = VT_1+VT_2;
%     VT_12 = VT_12 - permute(VT_12,[1,2,3,6,5,4]) - permute(VT_12,[1,2,3,4,6,5]) ...
%                  - permute(VT_12,[2,1,3,4,5,6]) - permute(VT_12,[1,3,2,4,5,6]) ...
%                  + permute(VT_12,[2,1,3,6,5,4]) + permute(VT_12,[2,1,3,4,6,5]) ...
%                  + permute(VT_12,[1,3,2,6,5,4]) + permute(VT_12,[1,3,2,4,6,5]);
%              
%     VT_3 = -0.5*einsum_kg(einsum_kg(sys.vA_oovv,t3a,'mnef,efcink->cmki'),t2a,'cmki,abmj->abcijk');
%     VT_4 = -einsum_kg(einsum_kg(sys.vB_oovv,t3b,'mnef,ecfikn->cmki'),t2a,'cmki,abmj->abcijk');
%     VT_34 = VT_3+VT_4;
%     VT_34 = VT_34 - permute(VT_34,[1,2,3,5,4,6]) - permute(VT_34,[1,2,3,4,6,5]) ...
%                   - permute(VT_34,[3,2,1,4,5,6]) - permute(VT_34,[1,3,2,4,5,6]) ...
%                   + permute(VT_34,[3,2,1,5,4,6]) + permute(VT_34,[3,2,1,4,6,5]) ...
%                   + permute(VT_34,[1,3,2,5,4,6]) + permute(VT_34,[1,3,2,4,6,5]);
%               
%     MM23A = MM23A + VT_12 + VT_34;

    % (HBar*T3)_C    
    D1 = -einsum_kg(H1A.oo(HA,HA),t3a,'mk,abcijm->abcijk');
    D2 = einsum_kg(H1A.vv(PA,PA),t3a,'ce,abeijk->abcijk');
    D3 = 0.5*einsum_kg(H2A.oooo(HA,HA,HA,HA),t3a,'mnij,abcmnk->abcijk'); 
    D4 = 0.5*einsum_kg(H2A.vvvv(PA,PA,PA,PA),t3a,'abef,efcijk->abcijk');
    D5 = einsum_kg(H2A.voov(PA,HA,HA,PA),t3a,'cmke,abeijm->abcijk');
    D6 = einsum_kg(H2B.voov(PA,HB,HA,PB),t3b,'cmke,abeijm->abcijk');
    
    % A(k/ij)
    D13 = D1 + D3;
    D13 = D13 - permute(D13,[1,2,3,6,5,4]) - permute(D13,[1,2,3,4,6,5]);
    
    % A(c/ab)
    D24 = D2 + D4;
    D24 = D24 - permute(D24,[3,2,1,4,5,6]) - permute(D24,[1,3,2,4,5,6]);
   
    % A(k/ij)A(c/ab)
    D56 = D5 + D6;
    D56 = D56 - permute(D56,[1,2,3,6,5,4]) - permute(D56,[1,2,3,4,6,5])...
              - permute(D56,[3,2,1,4,5,6]) - permute(D56,[1,3,2,4,5,6]) ...
              + permute(D56,[3,2,1,6,5,4]) + permute(D56,[3,2,1,4,6,5]) ...
              + permute(D56,[1,3,2,6,5,4]) + permute(D56,[1,3,2,4,6,5]);    
     
     X3A_abcijk = MM23A + D13 + D24 + D56;

    
%      D1 = -einsum_kg(H1A.oo-diag(diag(sys.fa_oo)),t3a,'mi,abcmjk->abcijk');
%      D1 = D1 - permute(D1,[1,2,3,6,5,4]) - permute(D1,[1,2,3,5,4,6]);
%      
%      D2 = einsum_kg(H1A.vv-diag(diag(sys.fa_vv)),t3a,'ae,ebcijk->abcijk');
%      D2 = D2 - permute(D2,[2,1,3,4,5,6]) - permute(D2,[3,2,1,4,5,6]);
%      
%      D3 = 0.5*einsum_kg(H2A.oooo,t3a,'mnij,abcmnk->abcijk');
%      D3 = D3 - permute(D3,[1,2,3,6,5,4]) - permute(D3,[1,2,3,4,6,5]);
%      
%      D4 = 0.5*einsum_kg(H2A.vvvv,t3a,'abef,efcijk->abcijk');
%      D4 = D4 - permute(D4,[3,2,1,4,5,6]) - permute(D4,[1,3,2,4,5,6]);
%      
%      D5 = einsum_kg(H2A.voov,t3a,'cmke,abeijm->abcijk');
%      D5 = D5 - permute(D5,[3,2,1,4,5,6]) - permute(D5,[1,3,2,4,5,6]) ...
%              - permute(D5,[1,2,3,6,5,4]) - permute(D5,[1,2,3,4,6,5]) ...
%              + permute(D5,[3,2,1,6,5,4]) + permute(D5,[3,2,1,4,6,5]) ...
%              + permute(D5,[1,3,2,6,5,4]) + permute(D5,[1,3,2,4,6,5]);
%          
%      D6 = einsum_kg(H2B.voov,t3b,'cmke,abeijm->abcijk');
%      D6 = D6 - permute(D6,[3,2,1,4,5,6]) - permute(D6,[1,3,2,4,5,6]) ...
%          - permute(D6,[1,2,3,6,5,4]) - permute(D6,[1,2,3,4,6,5]) ...
%          + permute(D6,[3,2,1,6,5,4]) + permute(D6,[3,2,1,4,6,5]) ...
%          + permute(D6,[1,3,2,6,5,4]) + permute(D6,[1,3,2,4,6,5]);
%      
%      X3A_abcijk = MM23A + D1 + D2 + D3 + D4 + D5 + D6;
     
     for a = 1:sys.Nact_p_alpha
        for b = a+1:sys.Nact_p_alpha
            for c = b+1:sys.Nact_p_alpha
                for i = 1:sys.Nact_h_alpha
                    for j = i+1:sys.Nact_h_alpha
                        for k = j+1:sys.Nact_h_alpha
                            
                            % (1)/[(1),(ki)(ij),(ki)(kj),(kj),(ij),(ki)]
                            t3a(a,b,c,i,j,k) = X3A_abcijk(a,b,c,i,j,k)/...
                                (sys.fa_HH(i,i)+sys.fa_HH(j,j)+sys.fa_HH(k,k)-sys.fa_PP(a,a)-sys.fa_PP(b,b)-sys.fa_PP(c,c)-shift);    
                            t3a(a,b,c,k,i,j) = t3a(a,b,c,i,j,k);
                            t3a(a,b,c,j,k,i) = t3a(a,b,c,i,j,k);
                            t3a(a,b,c,i,k,j) = -t3a(a,b,c,i,j,k);
                            t3a(a,b,c,j,i,k) = -t3a(a,b,c,i,j,k);
                            t3a(a,b,c,k,j,i) = -t3a(a,b,c,i,j,k);
                            
                            % (ab)/[(1),(ki)(ij),(ki)(kj),(kj),(ij),(ki)]
                            t3a(b,a,c,i,j,k) = -t3a(a,b,c,i,j,k);
                            t3a(b,a,c,k,i,j) = -t3a(a,b,c,i,j,k);
                            t3a(b,a,c,j,k,i) = -t3a(a,b,c,i,j,k);
                            t3a(b,a,c,i,k,j) = t3a(a,b,c,i,j,k);
                            t3a(b,a,c,j,i,k) = t3a(a,b,c,i,j,k);
                            t3a(b,a,c,k,j,i) = t3a(a,b,c,i,j,k);
                            
                            % (bc)/[(1),(ki)(ij),(ki)(kj),(kj),(ij),(ki)]
                            t3a(a,c,b,i,j,k) = -t3a(a,b,c,i,j,k);
                            t3a(a,c,b,k,i,j) = -t3a(a,b,c,i,j,k);
                            t3a(a,c,b,j,k,i) = -t3a(a,b,c,i,j,k);
                            t3a(a,c,b,i,k,j) = t3a(a,b,c,i,j,k);
                            t3a(a,c,b,j,i,k) = t3a(a,b,c,i,j,k);
                            t3a(a,c,b,k,j,i) = t3a(a,b,c,i,j,k);
                            
                            % (ac)/[(1),(ki)(ij),(ki)(kj),(kj),(ij),(ki)]
                            t3a(c,b,a,i,j,k) = -t3a(a,b,c,i,j,k);
                            t3a(c,b,a,k,i,j) = -t3a(a,b,c,i,j,k);
                            t3a(c,b,a,j,k,i) = -t3a(a,b,c,i,j,k);
                            t3a(c,b,a,i,k,j) = t3a(a,b,c,i,j,k);
                            t3a(c,b,a,j,i,k) = t3a(a,b,c,i,j,k);
                            t3a(c,b,a,k,j,i) = t3a(a,b,c,i,j,k);
                            
                            % (ac)(bc)/[(1),(ki)(ij),(ki)(kj),(kj),(ij),(ki)]
                            t3a(b,c,a,i,j,k) = t3a(a,b,c,i,j,k);
                            t3a(b,c,a,k,i,j) = t3a(a,b,c,i,j,k);
                            t3a(b,c,a,j,k,i) = t3a(a,b,c,i,j,k);
                            t3a(b,c,a,i,k,j) = -t3a(a,b,c,i,j,k);
                            t3a(b,c,a,j,i,k) = -t3a(a,b,c,i,j,k);
                            t3a(b,c,a,k,j,i) = -t3a(a,b,c,i,j,k);
                            
                            % (ac)(ab)/[(1),(ki)(ij),(ki)(kj),(kj),(ij),(ki)]
                            t3a(c,a,b,i,j,k) = t3a(a,b,c,i,j,k);
                            t3a(c,a,b,k,i,j) = t3a(a,b,c,i,j,k);
                            t3a(c,a,b,j,k,i) = t3a(a,b,c,i,j,k);
                            t3a(c,a,b,i,k,j) = -t3a(a,b,c,i,j,k);
                            t3a(c,a,b,j,i,k) = -t3a(a,b,c,i,j,k);
                            t3a(c,a,b,k,j,i) = -t3a(a,b,c,i,j,k);
                        end
                    end
                end
            end
        end
    end
       

end

function [H1A,H2A,H2B,VTA] = get_t3a_intermediates(t1a,t1b,t2a,t2b,t2c,t3a,t3b,t3c,t3d,sys)

    % h1A(me)
    H1A.ov = sys.fa_ov + einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me') + einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me');

    % h1A(mi)
    H1A.oo = sys.fa_oo_masked ...
             +einsum_kg(sys.fa_ov,t1a,'me,ei->mi')...
             +einsum_kg(sys.vA_ooov,t1a,'mnif,fn->mi')...
             +einsum_kg(sys.vB_ooov,t1b,'mnif,fn->mi')...
             +0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efin->mi')...
             +einsum_kg(sys.vB_oovv,t2b,'mnef,efin->mi')...
             +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,ei->mi')...
             +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,ei->mi');
         
    % h1A(ae)
    H1A.vv = sys.fa_vv_masked ...
             -einsum_kg(sys.fa_ov,t1a,'me,am->ae')...
             +einsum_kg(sys.vA_vovv,t1a,'amef,fm->ae')...
             +einsum_kg(sys.vB_vovv,t1b,'anef,fn->ae')...
             -0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,afmn->ae')...
             -einsum_kg(sys.vB_oovv,t2b,'mnef,afmn->ae')...
             -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t1a,'me,am->ae')...
             -einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t1a,'me,am->ae');

    % h2A(amij)
    H2A.vooo    = sys.vA_vooo ...
                  +einsum_kg(sys.vA_voov,t1a,'amie,ej->amij')...
	    			-einsum_kg(sys.vA_voov,t1a,'amje,ei->amij')...
                  -einsum_kg(sys.vA_oooo,t1a,'nmij,an->amij')...
                  +einsum_kg(sys.fa_ov,t2a,'me,aeij->amij')...
                  +0.5*einsum_kg(sys.vA_vovv,t2a,'amef,efij->amij')...
                  +einsum_kg(sys.vA_oovo,t2a,'nmej,aein->amij')...
	    			-einsum_kg(sys.vA_oovo,t2a,'nmei,aejn->amij')...
                  +einsum_kg(sys.vB_ooov,t2b,'mnje,aein->amij')...
	    			-einsum_kg(sys.vB_ooov,t2b,'mnie,aejn->amij')...
                  -einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmej,ei->nmij'),t1a,'nmij,an->amij')...
	    			+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'nmei,ej->nmij'),t1a,'nmij,an->amij')...
                  +einsum_kg(einsum_kg(sys.vA_vovv,t1a,'amef,ei->amif'),t1a,'amif,fj->amij')...
                  -0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,an->amef'),t2a,'amef,efij->amij')...
                  +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ej->mnjf'),t2a,'mnjf,afin->amij')...
	    			-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t2a,'mnif,afjn->amij')...
                  +einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,aeij->amij')...
                  +einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ej->mnjf'),t2b,'mnjf,afin->amij')...
	    			-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,ei->mnif'),t2b,'mnif,afjn->amij')...
                  +einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,aeij->amij')...
                  -einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmef,fj->nmej'),t1a,'nmej,an->amej'),t1a,'amej,ei->amij');

    % h(abie)
    H2A.vvov  = sys.vA_vvov ...
	    	+einsum_kg(sys.vA_vvvv,t1a,'abfe,fi->abie')...
	    	-einsum_kg(sys.vA_ovov,t1a,'nbie,an->abie')...
	    			+einsum_kg(sys.vA_ovov,t1a,'naie,bn->abie')...
	    	-einsum_kg(sys.fa_ov,t2a,'me,abim->abie')...
	    	+einsum_kg(sys.vA_ovvv,t2a,'nbfe,afin->abie')...
	    			-einsum_kg(sys.vA_ovvv,t2a,'nafe,bfin->abie')...
	    	+0.5*einsum_kg(sys.vA_oovo,t2a,'mnei,abnm->abie')...
	    	+einsum_kg(sys.vB_vovv,t2b,'bnef,afin->abie')...
	    			-einsum_kg(sys.vB_vovv,t2b,'anef,bfin->abie')...
	    	+einsum_kg(einsum_kg(sys.vA_oovo,t1a,'mnei,an->maei'),t1a,'maei,bm->abie')...
	    	-einsum_kg(einsum_kg(sys.vA_vovv,t1a,'bnef,fi->bnei'),t1a,'bnei,an->abie')...
	    			+einsum_kg(einsum_kg(sys.vA_vovv,t1a,'anef,fi->anei'),t1a,'anei,bn->abie')...
	    	+0.5*einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fi->mnei'),t2a,'mnei,abnm->abie')...
	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t2a,'bnef,afin->abie')...
	    			+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,am->anef'),t2a,'anef,bfin->abie')...
	    	-einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,fn->me'),t2a,'me,abim->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,bm->bnef'),t2b,'bnef,afin->abie')...
	    			+einsum_kg(einsum_kg(sys.vB_oovv,t1a,'mnef,am->anef'),t2b,'anef,bfin->abie')...
	    	-einsum_kg(einsum_kg(sys.vB_oovv,t1b,'mnef,fn->me'),t2a,'me,abim->abie')...
	    	+einsum_kg(einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bm->bnef'),t1a,'bnef,an->baef'),t1a,'baef,fi->abie');

     % h2A(mnij)
     H2A.oooo = sys.vA_oooo...
	     	+einsum_kg(sys.vA_oovo,t1a,'mnej,ei->mnij')...
	     			-einsum_kg(sys.vA_oovo,t1a,'mnei,ej->mnij')...
	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,efij->mnij')...
	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,ei->mnif'),t1a,'mnif,fj->mnij');

     % h2A(abef)
     H2A.vvvv = sys.vA_vvvv...
	     	-einsum_kg(sys.vA_ovvv,t1a,'mbef,am->abef')...
	     			+einsum_kg(sys.vA_ovvv,t1a,'maef,bm->abef')...
	     	+0.5*einsum_kg(sys.vA_oovv,t2a,'mnef,abmn->abef')...
	     	+einsum_kg(einsum_kg(sys.vA_oovv,t1a,'mnef,bn->mbef'),t1a,'mbef,am->abef');
        
     % h2A(amie)
     H2A.voov = sys.vA_voov ...
                -einsum_kg(sys.vA_ooov,t1a,'nmie,an->amie')...
                +einsum_kg(sys.vA_vovv,t1a,'amfe,fi->amie')...
                -einsum_kg(einsum_kg(sys.vA_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
                +einsum_kg(sys.vA_oovv,t2a,'nmfe,afin->amie')...
                +einsum_kg(sys.vB_oovv,t2b,'mnef,afin->amie');
            
    % h2B(amie)
    H2B.voov = sys.vB_voov ...
               -einsum_kg(sys.vB_ooov,t1a,'nmie,an->amie')...
               +einsum_kg(sys.vB_vovv,t1a,'amfe,fi->amie')...
               -einsum_kg(einsum_kg(sys.vB_oovv,t1a,'nmfe,fi->nmie'),t1a,'nmie,an->amie')...
               +einsum_kg(sys.vB_oovv,t2a,'nmfe,afin->amie')...
               +einsum_kg(sys.vC_oovv,t2b,'mnef,afin->amie');
           
    % (VT3)_C 
    PA = sys.PA; PB  = sys.PB; HA = sys.HA; HB = sys.HB;
        
    VTA.vvov = -0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),t3a,'MNeF,ABFIMN->ABIe')...
                   -einsum_kg(sys.vB_oovv(HA,HB,:,PB),t3b,'MNeF,ABFIMN->ABIe');
             
    VTA.vooo = 0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),t3a,'mNEF,AEFIJN->AmIJ')...
                  +einsum_kg(sys.vB_oovv(:,HB,PA,PB),t3b,'mNEF,AEFIJN->AmIJ');
     
end
