%%                              %% VVOV (A) %%%%
d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.ppphhh,'mnef,abfimn->abie')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.ppPhhh,'mneF,abFimn->abie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.ppphhH,'mNef,abfimN->abie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.ppPhhH,'mNeF,abFimN->abie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.ppphHh,'Mnef,abfiMn->abie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.ppPhHh,'MneF,abFiMn->abie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.ppphHH,'MNef,abfiMN->abie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.ppPhHH,'MNeF,abFiMN->abie');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.ppphhh,'mnef,abfimn->abie')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.Ppphhh,'mneF,Fabimn->abie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.ppphhH,'Mnef,abfinM->abie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PpphhH,'MneF,FabinM->abie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.ppphHH,'MNef,abfiMN->abie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PpphHH,'MNeF,FabiMN->abie');

Vt3A.pphv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.ppphHh,'mnef,abfmIn->abIe')...
-einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.ppPhHh,'mneF,abFmIn->abIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.ppphHH,'mNef,abfmIN->abIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.ppPhHH,'mNeF,abFmIN->abIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.pppHHh,'Mnef,abfIMn->abIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.ppPHHh,'MneF,abFIMn->abIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.pppHHH,'MNef,abfIMN->abIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.ppPHHH,'MNeF,abFIMN->abIe');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.ppphhH,'mnef,abfmnI->abIe')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PpphhH,'mneF,FabmnI->abIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.ppphHH,'Mnef,abfnIM->abIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PpphHH,'MneF,FabnIM->abIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.pppHHH,'MNef,abfIMN->abIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PppHHH,'MNeF,FabIMN->abIe');

Vt3A.ppHv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.Ppphhh,'mnef,Bafimn->aBie')...
-einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PpPhhh,'mneF,BaFimn->aBie')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PpphhH,'mNef,BafimN->aBie')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhhH,'mNeF,BaFimN->aBie')...
-einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PpphHh,'Mnef,BafiMn->aBie')...
-einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPhHh,'MneF,BaFiMn->aBie')...
-einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PpphHH,'MNef,BafiMN->aBie')...
-einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPhHH,'MNeF,BaFiMN->aBie');

d2 = -0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.Ppphhh,'mnef,Bafimn->aBie')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPphhh,'mneF,BFaimn->aBie')...
+einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PpphhH,'Mnef,BafinM->aBie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphhH,'MneF,BFainM->aBie')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PpphHH,'MNef,BafiMN->aBie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPphHH,'MNeF,BFaiMN->aBie');

Vt3A.pPhv = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PpphHh,'mnef,BafmIn->aBIe')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PpPhHh,'mneF,BaFmIn->aBIe')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PpphHH,'mNef,BafmIN->aBIe')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhHH,'mNeF,BaFmIN->aBIe')...
-einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PppHHh,'Mnef,BafIMn->aBIe')...
-einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPHHh,'MneF,BaFIMn->aBIe')...
-einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PppHHH,'MNef,BafIMN->aBIe')...
-einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPHHH,'MNeF,BaFIMN->aBIe');

d2 = -0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PpphhH,'mnef,BafmnI->aBIe')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPphhH,'mneF,BFamnI->aBIe')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PpphHH,'Mnef,BafnIM->aBIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphHH,'MneF,BFanIM->aBIe')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PppHHH,'MNef,BafIMN->aBIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPpHHH,'MNeF,BFaIMN->aBIe');

Vt3A.pPHv = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.Ppphhh,'mnef,Abfimn->Abie')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PpPhhh,'mneF,AbFimn->Abie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PpphhH,'mNef,AbfimN->Abie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhhH,'mNeF,AbFimN->Abie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PpphHh,'Mnef,AbfiMn->Abie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPhHh,'MneF,AbFiMn->Abie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PpphHH,'MNef,AbfiMN->Abie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPhHH,'MNeF,AbFiMN->Abie');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.Ppphhh,'mnef,Abfimn->Abie')...
-0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPphhh,'mneF,AFbimn->Abie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PpphhH,'Mnef,AbfinM->Abie')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphhH,'MneF,AFbinM->Abie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PpphHH,'MNef,AbfiMN->Abie')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPphHH,'MNeF,AFbiMN->Abie');

Vt3A.Pphv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PpphHh,'mnef,AbfmIn->AbIe')...
-einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PpPhHh,'mneF,AbFmIn->AbIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PpphHH,'mNef,AbfmIN->AbIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhHH,'mNeF,AbFmIN->AbIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PppHHh,'Mnef,AbfIMn->AbIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPHHh,'MneF,AbFIMn->AbIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PppHHH,'MNef,AbfIMN->AbIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPHHH,'MNeF,AbFIMN->AbIe');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PpphhH,'mnef,AbfmnI->AbIe')...
-0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPphhH,'mneF,AFbmnI->AbIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PpphHH,'Mnef,AbfnIM->AbIe')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphHH,'MneF,AFbnIM->AbIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PppHHH,'MNef,AbfIMN->AbIe')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPpHHH,'MNeF,AFbIMN->AbIe');

Vt3A.PpHv = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PPphhh,'mnef,ABfimn->ABie')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PPPhhh,'mneF,ABFimn->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PPphhH,'mNef,ABfimN->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PPPhhH,'mNeF,ABFimN->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PPphHh,'Mnef,ABfiMn->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PPPhHh,'MneF,ABFiMn->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PPphHH,'MNef,ABfiMN->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PPPhHH,'MNeF,ABFiMN->ABie');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PPphhh,'mnef,ABfimn->ABie')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPPhhh,'mneF,ABFimn->ABie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PPphhH,'Mnef,ABfinM->ABie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPPhhH,'MneF,ABFinM->ABie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PPphHH,'MNef,ABfiMN->ABie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPPhHH,'MNeF,ABFiMN->ABie');

Vt3A.PPhv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PPphHh,'mnef,ABfmIn->ABIe')...
-einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PPPhHh,'mneF,ABFmIn->ABIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PPphHH,'mNef,ABfmIN->ABIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PPPhHH,'mNeF,ABFmIN->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PPpHHh,'Mnef,ABfIMn->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PPPHHh,'MneF,ABFIMn->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PPpHHH,'MNef,ABfIMN->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PPPHHH,'MNeF,ABFIMN->ABIe');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PPphhH,'mnef,ABfmnI->ABIe')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPPhhH,'mneF,ABFmnI->ABIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PPphHH,'Mnef,ABfnIM->ABIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPPhHH,'MneF,ABFnIM->ABIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PPpHHH,'MNef,ABfIMN->ABIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPPHHH,'MNeF,ABFIMN->ABIe');

Vt3A.PPHv = -d1 - d2;

%%                              %% VOOO (A) %%%%

d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.ppphhh,'mnef,aefijn->amij')...
-einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.Ppphhh,'mnEf,Eafijn->amij')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.ppPhhh,'mneF,aeFijn->amij')...
-einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PpPhhh,'mnEF,EaFijn->amij')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.ppphhH,'mNef,aefijN->amij')...
-einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PpphhH,'mNEf,EafijN->amij')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.ppPhhH,'mNeF,aeFijN->amij')...
-einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PpPhhH,'mNEF,EaFijN->amij');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.ppphhh,'mnef,aefijn->amij')...
+einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.Ppphhh,'mneF,Faeijn->amij')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPphhh,'mnEF,EFaijn->amij')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.ppphhH,'mNef,aefijN->amij')...
+einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PpphhH,'mNeF,FaeijN->amij')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPphhH,'mNEF,EFaijN->amij');

Vt3A.pohh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.ppphHh,'mnef,aefiJn->amiJ')...
-einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PpphHh,'mnEf,EafiJn->amiJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.ppPhHh,'mneF,aeFiJn->amiJ')...
-einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PpPhHh,'mnEF,EaFiJn->amiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.ppphHH,'mNef,aefiJN->amiJ')...
-einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PpphHH,'mNEf,EafiJN->amiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.ppPhHH,'mNeF,aeFiJN->amiJ')...
-einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PpPhHH,'mNEF,EaFiJN->amiJ');

d2 = -0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.ppphhH,'mnef,aefinJ->amiJ')...
-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PpphhH,'mneF,FaeinJ->amiJ')...
-0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPphhH,'mnEF,EFainJ->amiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.ppphHH,'mNef,aefiJN->amiJ')...
+einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PpphHH,'mNeF,FaeiJN->amiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPphHH,'mNEF,EFaiJN->amiJ');

Vt3A.pohH = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.ppphHh,'mnef,aefjIn->amIj')...
+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PpphHh,'mnEf,EafjIn->amIj')...
-einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.ppPhHh,'mneF,aeFjIn->amIj')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PpPhHh,'mnEF,EaFjIn->amIj')...
-einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.ppphHH,'mNef,aefjIN->amIj')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PpphHH,'mNEf,EafjIN->amIj')...
-einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.ppPhHH,'mNeF,aeFjIN->amIj')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PpPhHH,'mNEF,EaFjIN->amIj');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.ppphhH,'mnef,aefjnI->amIj')...
+einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PpphhH,'mneF,FaejnI->amIj')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPphhH,'mnEF,EFajnI->amIj')...
-0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.ppphHH,'mNef,aefjIN->amIj')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PpphHH,'mNeF,FaejIN->amIj')...
-0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPphHH,'mNEF,EFajIN->amIj');

Vt3A.poHh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.pppHHh,'mnef,aefIJn->amIJ')...
-einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PppHHh,'mnEf,EafIJn->amIJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.ppPHHh,'mneF,aeFIJn->amIJ')...
-einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PpPHHh,'mnEF,EaFIJn->amIJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.pppHHH,'mNef,aefIJN->amIJ')...
-einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PppHHH,'mNEf,EafIJN->amIJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.ppPHHH,'mNeF,aeFIJN->amIJ')...
-einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PpPHHH,'mNEF,EaFIJN->amIJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.ppphHH,'mnef,aefnIJ->amIJ')...
+einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PpphHH,'mneF,FaenIJ->amIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPphHH,'mnEF,EFanIJ->amIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.pppHHH,'mNef,aefIJN->amIJ')...
+einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PppHHH,'mNeF,FaeIJN->amIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPpHHH,'mNEF,EFaIJN->amIJ');

Vt3A.poHH = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.Ppphhh,'mnef,Aefijn->Amij')...
+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PPphhh,'mnEf,AEfijn->Amij')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.PpPhhh,'mneF,AeFijn->Amij')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PPPhhh,'mnEF,AEFijn->Amij')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.PpphhH,'mNef,AefijN->Amij')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PPphhH,'mNEf,AEfijN->Amij')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.PpPhhH,'mNeF,AeFijN->Amij')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PPPhhH,'mNEF,AEFijN->Amij');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.Ppphhh,'mnef,Aefijn->Amij')...
-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PPphhh,'mneF,AFeijn->Amij')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPPhhh,'mnEF,AEFijn->Amij')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.PpphhH,'mNef,AefijN->Amij')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PPphhH,'mNeF,AFeijN->Amij')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPPhhH,'mNEF,AEFijN->Amij');

Vt3A.Pohh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.PpphHh,'mnef,AefiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PPphHh,'mnEf,AEfiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.PpPhHh,'mneF,AeFiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PPPhHh,'mnEF,AEFiJn->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.PpphHH,'mNef,AefiJN->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PPphHH,'mNEf,AEfiJN->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.PpPhHH,'mNeF,AeFiJN->AmiJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PPPhHH,'mNEF,AEFiJN->AmiJ');

d2 = -0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.PpphhH,'mnef,AefinJ->AmiJ')...
+einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PPphhH,'mneF,AFeinJ->AmiJ')...
-0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPPhhH,'mnEF,AEFinJ->AmiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.PpphHH,'mNef,AefiJN->AmiJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PPphHH,'mNeF,AFeiJN->AmiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPPhHH,'mNEF,AEFiJN->AmiJ');

Vt3A.PohH = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.PpphHh,'mnef,AefjIn->AmIj')...
-einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PPphHh,'mnEf,AEfjIn->AmIj')...
-einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.PpPhHh,'mneF,AeFjIn->AmIj')...
-einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PPPhHh,'mnEF,AEFjIn->AmIj')...
-einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.PpphHH,'mNef,AefjIN->AmIj')...
-einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PPphHH,'mNEf,AEfjIN->AmIj')...
-einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.PpPhHH,'mNeF,AeFjIN->AmIj')...
-einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PPPhHH,'mNEF,AEFjIN->AmIj');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.PpphhH,'mnef,AefjnI->AmIj')...
-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PPphhH,'mneF,AFejnI->AmIj')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPPhhH,'mnEF,AEFjnI->AmIj')...
-0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.PpphHH,'mNef,AefjIN->AmIj')...
+einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PPphHH,'mNeF,AFejIN->AmIj')...
-0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPPhHH,'mNEF,AEFjIN->AmIj');

Vt3A.PoHh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3B.PppHHh,'mnef,AefIJn->AmIJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3B.PPpHHh,'mnEf,AEfIJn->AmIJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3B.PpPHHh,'mneF,AeFIJn->AmIJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3B.PPPHHh,'mnEF,AEFIJn->AmIJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3B.PppHHH,'mNef,AefIJN->AmIJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3B.PPpHHH,'mNEf,AEfIJN->AmIJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3B.PpPHHH,'mNeF,AeFIJN->AmIJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3B.PPPHHH,'mNEF,AEFIJN->AmIJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3A.PpphHH,'mnef,AefnIJ->AmIJ')...
-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3A.PPphHH,'mneF,AFenIJ->AmIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3A.PPPhHH,'mnEF,AEFnIJ->AmIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3A.PppHHH,'mNef,AefIJN->AmIJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3A.PPpHHH,'mNeF,AFeIJN->AmIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3A.PPPHHH,'mNEF,AEFIJN->AmIJ');

Vt3A.PoHH = d1 + d2;

%%                              %% OVOO (B) %%%%

d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3C.ppphhh,'mnef,efbinj->mbij')...
+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3C.Ppphhh,'mnEf,Efbinj->mbij')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3C.pPphhh,'mneF,eFbinj->mbij')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3C.PPphhh,'mnEF,EFbinj->mbij')...
-einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3C.ppphhH,'mNef,efbijN->mbij')...
-einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3C.PpphhH,'mNEf,EfbijN->mbij')...
-einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3C.pPphhH,'mNeF,eFbijN->mbij')...
-einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3C.PPphhH,'mNEF,EFbijN->mbij');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3B.ppphhh,'mnef,efbinj->mbij')...
-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3B.Ppphhh,'mneF,Febinj->mbij')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3B.PPphhh,'mnEF,EFbinj->mbij')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3B.ppphHh,'mNef,efbiNj->mbij')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3B.PpphHh,'mNeF,FebiNj->mbij')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3B.PPphHh,'mNEF,EFbiNj->mbij');

Vt3B.ophh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3C.ppphhH,'mnef,efbinJ->mbiJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3C.PpphhH,'mnEf,EfbinJ->mbiJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3C.pPphhH,'mneF,eFbinJ->mbiJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3C.PPphhH,'mnEF,EFbinJ->mbiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3C.ppphHH,'mNef,efbiNJ->mbiJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3C.PpphHH,'mNEf,EfbiNJ->mbiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3C.pPphHH,'mNeF,eFbiNJ->mbiJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3C.PPphHH,'mNEF,EFbiNJ->mbiJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3B.ppphhH,'mnef,efbinJ->mbiJ')...
-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3B.PpphhH,'mneF,FebinJ->mbiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3B.PPphhH,'mnEF,EFbinJ->mbiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3B.ppphHH,'mNef,efbiNJ->mbiJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3B.PpphHH,'mNeF,FebiNJ->mbiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3B.PPphHH,'mNEF,EFbiNJ->mbiJ');

Vt3B.ophH = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3C.pppHhh,'mnef,efbInj->mbIj')...
+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3C.PppHhh,'mnEf,EfbInj->mbIj')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3C.pPpHhh,'mneF,eFbInj->mbIj')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3C.PPpHhh,'mnEF,EFbInj->mbIj')...
-einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3C.pppHhH,'mNef,efbIjN->mbIj')...
-einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3C.PppHhH,'mNEf,EfbIjN->mbIj')...
-einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3C.pPpHhH,'mNeF,eFbIjN->mbIj')...
-einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3C.PPpHhH,'mNEF,EFbIjN->mbIj');

d2 = -0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3B.ppphHh,'mnef,efbnIj->mbIj')...
+einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3B.PpphHh,'mneF,FebnIj->mbIj')...
-0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3B.PPphHh,'mnEF,EFbnIj->mbIj')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3B.pppHHh,'mNef,efbINj->mbIj')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3B.PppHHh,'mNeF,FebINj->mbIj')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3B.PPpHHh,'mNEF,EFbINj->mbIj');

Vt3B.opHh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3C.pppHhH,'mnef,efbInJ->mbIJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3C.PppHhH,'mnEf,EfbInJ->mbIJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3C.pPpHhH,'mneF,eFbInJ->mbIJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3C.PPpHhH,'mnEF,EFbInJ->mbIJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3C.pppHHH,'mNef,efbINJ->mbIJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3C.PppHHH,'mNEf,EfbINJ->mbIJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3C.pPpHHH,'mNeF,eFbINJ->mbIJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3C.PPpHHH,'mNEF,EFbINJ->mbIJ');

d2 = -0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3B.ppphHH,'mnef,efbnIJ->mbIJ')...
+einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3B.PpphHH,'mneF,FebnIJ->mbIJ')...
-0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3B.PPphHH,'mnEF,EFbnIJ->mbIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3B.pppHHH,'mNef,efbINJ->mbIJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3B.PppHHH,'mNeF,FebINJ->mbIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3B.PPpHHH,'mNEF,EFbINJ->mbIJ');

Vt3B.opHH = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3C.pPphhh,'mnef,eBfinj->mBij')...
-einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3C.PPphhh,'mnEf,EBfinj->mBij')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3C.pPPhhh,'mneF,eFBinj->mBij')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3C.PPPhhh,'mnEF,EFBinj->mBij')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3C.pPphhH,'mNef,eBfijN->mBij')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3C.PPphhH,'mNEf,EBfijN->mBij')...
-einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3C.pPPhhH,'mNeF,eFBijN->mBij')...
-einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3C.PPPhhH,'mNEF,EFBijN->mBij');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3B.ppPhhh,'mnef,efBinj->mBij')...
-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3B.PpPhhh,'mneF,FeBinj->mBij')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3B.PPPhhh,'mnEF,EFBinj->mBij')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3B.ppPhHh,'mNef,efBiNj->mBij')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3B.PpPhHh,'mNeF,FeBiNj->mBij')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3B.PPPhHh,'mNEF,EFBiNj->mBij');

Vt3B.oPhh = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3C.pPphhH,'mnef,eBfinJ->mBiJ')...
-einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3C.PPphhH,'mnEf,EBfinJ->mBiJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3C.pPPhhH,'mneF,eFBinJ->mBiJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3C.PPPhhH,'mnEF,EFBinJ->mBiJ')...
-einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3C.pPphHH,'mNef,eBfiNJ->mBiJ')...
-einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3C.PPphHH,'mNEf,EBfiNJ->mBiJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3C.pPPhHH,'mNeF,eFBiNJ->mBiJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3C.PPPhHH,'mNEF,EFBiNJ->mBiJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3B.ppPhhH,'mnef,efBinJ->mBiJ')...
-einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3B.PpPhhH,'mneF,FeBinJ->mBiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3B.PPPhhH,'mnEF,EFBinJ->mBiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3B.ppPhHH,'mNef,efBiNJ->mBiJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3B.PpPhHH,'mNeF,FeBiNJ->mBiJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3B.PPPhHH,'mNEF,EFBiNJ->mBiJ');

Vt3B.oPhH = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3C.pPpHhh,'mnef,eBfInj->mBIj')...
-einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3C.PPpHhh,'mnEf,EBfInj->mBIj')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3C.pPPHhh,'mneF,eFBInj->mBIj')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3C.PPPHhh,'mnEF,EFBInj->mBIj')...
+einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3C.pPpHhH,'mNef,eBfIjN->mBIj')...
+einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3C.PPpHhH,'mNEf,EBfIjN->mBIj')...
-einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3C.pPPHhH,'mNeF,eFBIjN->mBIj')...
-einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3C.PPPHhH,'mNEF,EFBIjN->mBIj');

d2 = -0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3B.ppPhHh,'mnef,efBnIj->mBIj')...
+einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3B.PpPhHh,'mneF,FeBnIj->mBIj')...
-0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3B.PPPhHh,'mnEF,EFBnIj->mBIj')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3B.ppPHHh,'mNef,efBINj->mBIj')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3B.PpPHHh,'mNeF,FeBINj->mBIj')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3B.PPPHHh,'mNEF,EFBINj->mBIj');

Vt3B.oPHh = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(:,hB,pA,pB),T3C.pPpHhH,'mnef,eBfInJ->mBIJ')...
-einsum_kg(sys.vB_oovv(:,hB,PA,pB),T3C.PPpHhH,'mnEf,EBfInJ->mBIJ')...
+einsum_kg(sys.vB_oovv(:,hB,pA,PB),T3C.pPPHhH,'mneF,eFBInJ->mBIJ')...
+einsum_kg(sys.vB_oovv(:,hB,PA,PB),T3C.PPPHhH,'mnEF,EFBInJ->mBIJ')...
-einsum_kg(sys.vB_oovv(:,HB,pA,pB),T3C.pPpHHH,'mNef,eBfINJ->mBIJ')...
-einsum_kg(sys.vB_oovv(:,HB,PA,pB),T3C.PPpHHH,'mNEf,EBfINJ->mBIJ')...
+einsum_kg(sys.vB_oovv(:,HB,pA,PB),T3C.pPPHHH,'mNeF,eFBINJ->mBIJ')...
+einsum_kg(sys.vB_oovv(:,HB,PA,PB),T3C.PPPHHH,'mNEF,EFBINJ->mBIJ');

d2 = -0.5*einsum_kg(sys.vA_oovv(:,hA,pA,pA),T3B.ppPhHH,'mnef,efBnIJ->mBIJ')...
+einsum_kg(sys.vA_oovv(:,hA,pA,PA),T3B.PpPhHH,'mneF,FeBnIJ->mBIJ')...
-0.5*einsum_kg(sys.vA_oovv(:,hA,PA,PA),T3B.PPPhHH,'mnEF,EFBnIJ->mBIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,pA,pA),T3B.ppPHHH,'mNef,efBINJ->mBIJ')...
-einsum_kg(sys.vA_oovv(:,HA,pA,PA),T3B.PpPHHH,'mNeF,FeBINJ->mBIJ')...
+0.5*einsum_kg(sys.vA_oovv(:,HA,PA,PA),T3B.PPPHHH,'mNEF,EFBINJ->mBIJ');

Vt3B.oPHH = d1 + d2;

%%                              %% VOOO (B) %%%%

d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.ppphhh,'nmfe,afeinj->amij')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.ppPhhh,'nmfE,afEinj->amij')...
-einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.Ppphhh,'nmFe,Faeinj->amij')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PpPhhh,'nmFE,FaEinj->amij')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.ppphHh,'Nmfe,afeiNj->amij')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.ppPhHh,'NmfE,afEiNj->amij')...
-einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PpphHh,'NmFe,FaeiNj->amij')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PpPhHh,'NmFE,FaEiNj->amij');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.ppphhh,'nmfe,afeinj->amij')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.pPphhh,'nmFe,aFeinj->amij')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.pPPhhh,'nmFE,aFEinj->amij')...
-0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.ppphhH,'Nmfe,afeijN->amij')...
-einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.pPphhH,'NmFe,aFeijN->amij')...
-0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.pPPhhH,'NmFE,aFEijN->amij');

Vt3B.pohh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.ppphhH,'nmfe,afeinJ->amiJ')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.ppPhhH,'nmfE,afEinJ->amiJ')...
-einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.PpphhH,'nmFe,FaeinJ->amiJ')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PpPhhH,'nmFE,FaEinJ->amiJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.ppphHH,'Nmfe,afeiNJ->amiJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.ppPhHH,'NmfE,afEiNJ->amiJ')...
-einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PpphHH,'NmFe,FaeiNJ->amiJ')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PpPhHH,'NmFE,FaEiNJ->amiJ');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.ppphhH,'nmfe,afeinJ->amiJ')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.pPphhH,'nmFe,aFeinJ->amiJ')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.pPPhhH,'nmFE,aFEinJ->amiJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.ppphHH,'Nmfe,afeiNJ->amiJ')...
+einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.pPphHH,'NmFe,aFeiNJ->amiJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.pPPhHH,'NmFE,aFEiNJ->amiJ');

Vt3B.pohH = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.ppphHh,'nmfe,afenIj->amIj')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.ppPhHh,'nmfE,afEnIj->amIj')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.PpphHh,'nmFe,FaenIj->amIj')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PpPhHh,'nmFE,FaEnIj->amIj')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.pppHHh,'Nmfe,afeINj->amIj')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.ppPHHh,'NmfE,afEINj->amIj')...
-einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PppHHh,'NmFe,FaeINj->amIj')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PpPHHh,'NmFE,FaEINj->amIj');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.pppHhh,'nmfe,afeInj->amIj')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.pPpHhh,'nmFe,aFeInj->amIj')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.pPPHhh,'nmFE,aFEInj->amIj')...
-0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.pppHhH,'Nmfe,afeIjN->amIj')...
-einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.pPpHhH,'NmFe,aFeIjN->amIj')...
-0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.pPPHhH,'NmFE,aFEIjN->amIj');

Vt3B.poHh = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.ppphHH,'nmfe,afenIJ->amIJ')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.ppPhHH,'nmfE,afEnIJ->amIJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.PpphHH,'nmFe,FaenIJ->amIJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PpPhHH,'nmFE,FaEnIJ->amIJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.pppHHH,'Nmfe,afeINJ->amIJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.ppPHHH,'NmfE,afEINJ->amIJ')...
-einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PppHHH,'NmFe,FaeINJ->amIJ')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PpPHHH,'NmFE,FaEINJ->amIJ');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.pppHhH,'nmfe,afeInJ->amIJ')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.pPpHhH,'nmFe,aFeInJ->amIJ')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.pPPHhH,'nmFE,aFEInJ->amIJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.pppHHH,'Nmfe,afeINJ->amIJ')...
+einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.pPpHHH,'NmFe,aFeINJ->amIJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.pPPHHH,'NmFE,aFEINJ->amIJ');

Vt3B.poHH = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.Ppphhh,'nmfe,Afeinj->Amij')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.PpPhhh,'nmfE,AfEinj->Amij')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.PPphhh,'nmFe,AFeinj->Amij')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PPPhhh,'nmFE,AFEinj->Amij')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.PpphHh,'Nmfe,AfeiNj->Amij')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.PpPhHh,'NmfE,AfEiNj->Amij')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PPphHh,'NmFe,AFeiNj->Amij')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PPPhHh,'NmFE,AFEiNj->Amij');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.Ppphhh,'nmfe,Afeinj->Amij')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.PPphhh,'nmFe,AFeinj->Amij')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.PPPhhh,'nmFE,AFEinj->Amij')...
-0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.PpphhH,'Nmfe,AfeijN->Amij')...
-einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.PPphhH,'NmFe,AFeijN->Amij')...
-0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.PPPhhH,'NmFE,AFEijN->Amij');

Vt3B.Pohh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.PpphhH,'nmfe,AfeinJ->AmiJ')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.PpPhhH,'nmfE,AfEinJ->AmiJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.PPphhH,'nmFe,AFeinJ->AmiJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PPPhhH,'nmFE,AFEinJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.PpphHH,'Nmfe,AfeiNJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.PpPhHH,'NmfE,AfEiNJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PPphHH,'NmFe,AFeiNJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PPPhHH,'NmFE,AFEiNJ->AmiJ');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.PpphhH,'nmfe,AfeinJ->AmiJ')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.PPphhH,'nmFe,AFeinJ->AmiJ')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.PPPhhH,'nmFE,AFEinJ->AmiJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.PpphHH,'Nmfe,AfeiNJ->AmiJ')...
+einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.PPphHH,'NmFe,AFeiNJ->AmiJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.PPPhHH,'NmFE,AFEiNJ->AmiJ');

Vt3B.PohH = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.PpphHh,'nmfe,AfenIj->AmIj')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.PpPhHh,'nmfE,AfEnIj->AmIj')...
-einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.PPphHh,'nmFe,AFenIj->AmIj')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PPPhHh,'nmFE,AFEnIj->AmIj')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.PppHHh,'Nmfe,AfeINj->AmIj')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.PpPHHh,'NmfE,AfEINj->AmIj')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PPpHHh,'NmFe,AFeINj->AmIj')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PPPHHh,'NmFE,AFEINj->AmIj');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.PppHhh,'nmfe,AfeInj->AmIj')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.PPpHhh,'nmFe,AFeInj->AmIj')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.PPPHhh,'nmFE,AFEInj->AmIj')...
-0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.PppHhH,'Nmfe,AfeIjN->AmIj')...
-einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.PPpHhH,'NmFe,AFeIjN->AmIj')...
-0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.PPPHhH,'NmFE,AFEIjN->AmIj');

Vt3B.PoHh = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3B.PpphHH,'nmfe,AfenIJ->AmIJ')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3B.PpPhHH,'nmfE,AfEnIJ->AmIJ')...
-einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3B.PPphHH,'nmFe,AFenIJ->AmIJ')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3B.PPPhHH,'nmFE,AFEnIJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3B.PppHHH,'Nmfe,AfeINJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3B.PpPHHH,'NmfE,AfEINJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3B.PPpHHH,'NmFe,AFeINJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3B.PPPHHH,'NmFE,AFEINJ->AmIJ');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,:,pB,pB),T3C.PppHhH,'nmfe,AfeInJ->AmIJ')...
+einsum_kg(sys.vC_oovv(hB,:,PB,pB),T3C.PPpHhH,'nmFe,AFeInJ->AmIJ')...
+0.5*einsum_kg(sys.vC_oovv(hB,:,PB,PB),T3C.PPPHhH,'nmFE,AFEInJ->AmIJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,pB,pB),T3C.PppHHH,'Nmfe,AfeINJ->AmIJ')...
+einsum_kg(sys.vC_oovv(HB,:,PB,pB),T3C.PPpHHH,'NmFe,AFeINJ->AmIJ')...
+0.5*einsum_kg(sys.vC_oovv(HB,:,PB,PB),T3C.PPPHHH,'NmFE,AFEINJ->AmIJ');

Vt3B.PoHH = d1 + d2;

%%                              %% VVOV (B) %%%%

d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.ppphhh,'nmfe,afbinm->abie')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.Ppphhh,'nmFe,Fabinm->abie')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.ppphHh,'Nmfe,afbiNm->abie')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PpphHh,'NmFe,FabiNm->abie')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.ppphhH,'nMfe,afbinM->abie')...
-einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PpphhH,'nMFe,FabinM->abie')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.ppphHH,'NMfe,afbiNM->abie')...
-einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PpphHH,'NMFe,FabiNM->abie');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.ppphhh,'nmfe,afbinm->abie')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.pPphhh,'nmFe,aFbinm->abie')...
+einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.ppphhH,'nMfe,afbinM->abie')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.pPphhH,'nMFe,aFbinM->abie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.ppphHH,'NMfe,afbiNM->abie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.pPphHH,'NMFe,aFbiNM->abie');

Vt3B.pphv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.ppphHh,'nmfe,afbnIm->abIe')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.PpphHh,'nmFe,FabnIm->abIe')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.pppHHh,'Nmfe,afbINm->abIe')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PppHHh,'NmFe,FabINm->abIe')...
-einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.ppphHH,'nMfe,afbnIM->abIe')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PpphHH,'nMFe,FabnIM->abIe')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.pppHHH,'NMfe,afbINM->abIe')...
-einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PppHHH,'NMFe,FabINM->abIe');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.pppHhh,'nmfe,afbInm->abIe')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.pPpHhh,'nmFe,aFbInm->abIe')...
+einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.pppHhH,'nMfe,afbInM->abIe')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.pPpHhH,'nMFe,aFbInM->abIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.pppHHH,'NMfe,afbINM->abIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.pPpHHH,'NMFe,aFbINM->abIe');

Vt3B.ppHv = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.ppPhhh,'nmfe,afBinm->aBie')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.PpPhhh,'nmFe,FaBinm->aBie')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.ppPhHh,'Nmfe,afBiNm->aBie')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PpPhHh,'NmFe,FaBiNm->aBie')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.ppPhhH,'nMfe,afBinM->aBie')...
-einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PpPhhH,'nMFe,FaBinM->aBie')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.ppPhHH,'NMfe,afBiNM->aBie')...
-einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PpPhHH,'NMFe,FaBiNM->aBie');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.pPphhh,'nmfe,aBfinm->aBie')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.pPPhhh,'nmFe,aFBinm->aBie')...
-einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.pPphhH,'nMfe,aBfinM->aBie')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.pPPhhH,'nMFe,aFBinM->aBie')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.pPphHH,'NMfe,aBfiNM->aBie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.pPPhHH,'NMFe,aFBiNM->aBie');

Vt3B.pPhv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.ppPhHh,'nmfe,afBnIm->aBIe')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.PpPhHh,'nmFe,FaBnIm->aBIe')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.ppPHHh,'Nmfe,afBINm->aBIe')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PpPHHh,'NmFe,FaBINm->aBIe')...
-einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.ppPhHH,'nMfe,afBnIM->aBIe')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PpPhHH,'nMFe,FaBnIM->aBIe')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.ppPHHH,'NMfe,afBINM->aBIe')...
-einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PpPHHH,'NMFe,FaBINM->aBIe');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.pPpHhh,'nmfe,aBfInm->aBIe')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.pPPHhh,'nmFe,aFBInm->aBIe')...
-einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.pPpHhH,'nMfe,aBfInM->aBIe')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.pPPHhH,'nMFe,aFBInM->aBIe')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.pPpHHH,'NMfe,aBfINM->aBIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.pPPHHH,'NMFe,aFBINM->aBIe');

Vt3B.pPHv = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.Ppphhh,'nmfe,Afbinm->Abie')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.PPphhh,'nmFe,AFbinm->Abie')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.PpphHh,'Nmfe,AfbiNm->Abie')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PPphHh,'NmFe,AFbiNm->Abie')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.PpphhH,'nMfe,AfbinM->Abie')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PPphhH,'nMFe,AFbinM->Abie')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.PpphHH,'NMfe,AfbiNM->Abie')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PPphHH,'NMFe,AFbiNM->Abie');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.Ppphhh,'nmfe,Afbinm->Abie')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.PPphhh,'nmFe,AFbinm->Abie')...
+einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.PpphhH,'nMfe,AfbinM->Abie')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.PPphhH,'nMFe,AFbinM->Abie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.PpphHH,'NMfe,AfbiNM->Abie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.PPphHH,'NMFe,AFbiNM->Abie');

Vt3B.Pphv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.PpphHh,'nmfe,AfbnIm->AbIe')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.PPphHh,'nmFe,AFbnIm->AbIe')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.PppHHh,'Nmfe,AfbINm->AbIe')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PPpHHh,'NmFe,AFbINm->AbIe')...
-einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.PpphHH,'nMfe,AfbnIM->AbIe')...
-einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PPphHH,'nMFe,AFbnIM->AbIe')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.PppHHH,'NMfe,AfbINM->AbIe')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PPpHHH,'NMFe,AFbINM->AbIe');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.PppHhh,'nmfe,AfbInm->AbIe')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.PPpHhh,'nmFe,AFbInm->AbIe')...
+einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.PppHhH,'nMfe,AfbInM->AbIe')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.PPpHhH,'nMFe,AFbInM->AbIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.PppHHH,'NMfe,AfbINM->AbIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.PPpHHH,'NMFe,AFbINM->AbIe');

Vt3B.PpHv = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.PpPhhh,'nmfe,AfBinm->ABie')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.PPPhhh,'nmFe,AFBinm->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.PpPhHh,'Nmfe,AfBiNm->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PPPhHh,'NmFe,AFBiNm->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.PpPhhH,'nMfe,AfBinM->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PPPhhH,'nMFe,AFBinM->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.PpPhHH,'NMfe,AfBiNM->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PPPhHH,'NMFe,AFBiNM->ABie');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.PPphhh,'nmfe,ABfinm->ABie')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.PPPhhh,'nmFe,AFBinm->ABie')...
-einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.PPphhH,'nMfe,ABfinM->ABie')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.PPPhhH,'nMFe,AFBinM->ABie')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.PPphHH,'NMfe,ABfiNM->ABie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.PPPhHH,'NMFe,AFBiNM->ABie');

Vt3B.PPhv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3B.PpPhHh,'nmfe,AfBnIm->ABIe')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3B.PPPhHh,'nmFe,AFBnIm->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3B.PpPHHh,'Nmfe,AfBINm->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3B.PPPHHh,'NmFe,AFBINm->ABIe')...
-einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3B.PpPhHH,'nMfe,AfBnIM->ABIe')...
-einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3B.PPPhHH,'nMFe,AFBnIM->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3B.PpPHHH,'NMfe,AfBINM->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3B.PPPHHH,'NMFe,AFBINM->ABIe');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,pB,:),T3C.PPpHhh,'nmfe,ABfInm->ABIe')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,PB,:),T3C.PPPHhh,'nmFe,AFBInm->ABIe')...
-einsum_kg(sys.vC_oovv(hB,HB,pB,:),T3C.PPpHhH,'nMfe,ABfInM->ABIe')...
+einsum_kg(sys.vC_oovv(hB,HB,PB,:),T3C.PPPHhH,'nMFe,AFBInM->ABIe')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,pB,:),T3C.PPpHHH,'NMfe,ABfINM->ABIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,PB,:),T3C.PPPHHH,'NMFe,AFBINM->ABIe');

Vt3B.PPHv = -d1 - d2;

%%                              %% VVVO (B) %%%%

d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3C.ppphhh,'mnef,afbmnj->abej')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3C.pPphhh,'mneF,aFbmnj->abej')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3C.ppphhH,'mNef,afbmjN->abej')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3C.pPphhH,'mNeF,aFbmjN->abej')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3C.pppHhh,'Mnef,afbMnj->abej')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3C.pPpHhh,'MneF,aFbMnj->abej')...
-einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3C.pppHhH,'MNef,afbMjN->abej')...
-einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3C.pPpHhH,'MNeF,aFbMjN->abej');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3B.ppphhh,'mnef,afbmnj->abej')...
-0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3B.Ppphhh,'mneF,Fabmnj->abej')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3B.ppphHh,'Mnef,afbnMj->abej')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3B.PpphHh,'MneF,FabnMj->abej')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3B.pppHHh,'MNef,afbMNj->abej')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3B.PppHHh,'MNeF,FabMNj->abej');

Vt3B.ppvh = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3C.ppphhH,'mnef,afbmnJ->abeJ')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3C.pPphhH,'mneF,aFbmnJ->abeJ')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3C.ppphHH,'mNef,afbmNJ->abeJ')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3C.pPphHH,'mNeF,aFbmNJ->abeJ')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3C.pppHhH,'Mnef,afbMnJ->abeJ')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3C.pPpHhH,'MneF,aFbMnJ->abeJ')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3C.pppHHH,'MNef,afbMNJ->abeJ')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3C.pPpHHH,'MNeF,aFbMNJ->abeJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3B.ppphhH,'mnef,afbmnJ->abeJ')...
-0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3B.PpphhH,'mneF,FabmnJ->abeJ')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3B.ppphHH,'Mnef,afbnMJ->abeJ')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3B.PpphHH,'MneF,FabnMJ->abeJ')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3B.pppHHH,'MNef,afbMNJ->abeJ')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3B.PppHHH,'MNeF,FabMNJ->abeJ');

Vt3B.ppvH = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3C.pPphhh,'mnef,aBfmnj->aBej')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3C.pPPhhh,'mneF,aFBmnj->aBej')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3C.pPphhH,'mNef,aBfmjN->aBej')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3C.pPPhhH,'mNeF,aFBmjN->aBej')...
-einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3C.pPpHhh,'Mnef,aBfMnj->aBej')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3C.pPPHhh,'MneF,aFBMnj->aBej')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3C.pPpHhH,'MNef,aBfMjN->aBej')...
-einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3C.pPPHhH,'MNeF,aFBMjN->aBej');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3B.ppPhhh,'mnef,afBmnj->aBej')...
-0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3B.PpPhhh,'mneF,FaBmnj->aBej')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3B.ppPhHh,'Mnef,afBnMj->aBej')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3B.PpPhHh,'MneF,FaBnMj->aBej')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3B.ppPHHh,'MNef,afBMNj->aBej')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3B.PpPHHh,'MNeF,FaBMNj->aBej');

Vt3B.pPvh = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3C.pPphhH,'mnef,aBfmnJ->aBeJ')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3C.pPPhhH,'mneF,aFBmnJ->aBeJ')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3C.pPphHH,'mNef,aBfmNJ->aBeJ')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3C.pPPhHH,'mNeF,aFBmNJ->aBeJ')...
-einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3C.pPpHhH,'Mnef,aBfMnJ->aBeJ')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3C.pPPHhH,'MneF,aFBMnJ->aBeJ')...
-einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3C.pPpHHH,'MNef,aBfMNJ->aBeJ')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3C.pPPHHH,'MNeF,aFBMNJ->aBeJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3B.ppPhhH,'mnef,afBmnJ->aBeJ')...
-0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3B.PpPhhH,'mneF,FaBmnJ->aBeJ')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3B.ppPhHH,'Mnef,afBnMJ->aBeJ')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3B.PpPhHH,'MneF,FaBnMJ->aBeJ')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3B.ppPHHH,'MNef,afBMNJ->aBeJ')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3B.PpPHHH,'MNeF,FaBMNJ->aBeJ');

Vt3B.pPvH = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3C.Ppphhh,'mnef,Afbmnj->Abej')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3C.PPphhh,'mneF,AFbmnj->Abej')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3C.PpphhH,'mNef,AfbmjN->Abej')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3C.PPphhH,'mNeF,AFbmjN->Abej')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3C.PppHhh,'Mnef,AfbMnj->Abej')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3C.PPpHhh,'MneF,AFbMnj->Abej')...
-einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3C.PppHhH,'MNef,AfbMjN->Abej')...
-einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3C.PPpHhH,'MNeF,AFbMjN->Abej');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3B.Ppphhh,'mnef,Afbmnj->Abej')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3B.PPphhh,'mneF,AFbmnj->Abej')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3B.PpphHh,'Mnef,AfbnMj->Abej')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3B.PPphHh,'MneF,AFbnMj->Abej')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3B.PppHHh,'MNef,AfbMNj->Abej')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3B.PPpHHh,'MNeF,AFbMNj->Abej');

Vt3B.Ppvh = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3C.PpphhH,'mnef,AfbmnJ->AbeJ')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3C.PPphhH,'mneF,AFbmnJ->AbeJ')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3C.PpphHH,'mNef,AfbmNJ->AbeJ')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3C.PPphHH,'mNeF,AFbmNJ->AbeJ')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3C.PppHhH,'Mnef,AfbMnJ->AbeJ')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3C.PPpHhH,'MneF,AFbMnJ->AbeJ')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3C.PppHHH,'MNef,AfbMNJ->AbeJ')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3C.PPpHHH,'MNeF,AFbMNJ->AbeJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3B.PpphhH,'mnef,AfbmnJ->AbeJ')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3B.PPphhH,'mneF,AFbmnJ->AbeJ')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3B.PpphHH,'Mnef,AfbnMJ->AbeJ')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3B.PPphHH,'MneF,AFbnMJ->AbeJ')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3B.PppHHH,'MNef,AfbMNJ->AbeJ')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3B.PPpHHH,'MNeF,AFbMNJ->AbeJ');

Vt3B.PpvH = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3C.PPphhh,'mnef,ABfmnj->ABej')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3C.PPPhhh,'mneF,AFBmnj->ABej')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3C.PPphhH,'mNef,ABfmjN->ABej')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3C.PPPhhH,'mNeF,AFBmjN->ABej')...
-einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3C.PPpHhh,'Mnef,ABfMnj->ABej')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3C.PPPHhh,'MneF,AFBMnj->ABej')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3C.PPpHhH,'MNef,ABfMjN->ABej')...
-einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3C.PPPHhH,'MNeF,AFBMjN->ABej');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3B.PpPhhh,'mnef,AfBmnj->ABej')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3B.PPPhhh,'mneF,AFBmnj->ABej')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3B.PpPhHh,'Mnef,AfBnMj->ABej')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3B.PPPhHh,'MneF,AFBnMj->ABej')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3B.PpPHHh,'MNef,AfBMNj->ABej')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3B.PPPHHh,'MNeF,AFBMNj->ABej');

Vt3B.PPvh = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3C.PPphhH,'mnef,ABfmnJ->ABeJ')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3C.PPPhhH,'mneF,AFBmnJ->ABeJ')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3C.PPphHH,'mNef,ABfmNJ->ABeJ')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3C.PPPhHH,'mNeF,AFBmNJ->ABeJ')...
-einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3C.PPpHhH,'Mnef,ABfMnJ->ABeJ')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3C.PPPHhH,'MneF,AFBMnJ->ABeJ')...
-einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3C.PPpHHH,'MNef,ABfMNJ->ABeJ')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3C.PPPHHH,'MNeF,AFBMNJ->ABeJ');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3B.PpPhhH,'mnef,AfBmnJ->ABeJ')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3B.PPPhhH,'mneF,AFBmnJ->ABeJ')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3B.PpPhHH,'Mnef,AfBnMJ->ABeJ')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3B.PPPhHH,'MneF,AFBnMJ->ABeJ')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3B.PpPHHH,'MNef,AfBMNJ->ABeJ')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3B.PPPHHH,'MNeF,AFBMNJ->ABeJ');

Vt3B.PPvH = -d1 - d2;

%%                              %% VVVO (C) %%%%

d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.ppphhh,'nmfe,fabnim->baei')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.Ppphhh,'nmFe,Fabnim->baei')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pppHhh,'Nmfe,fabNim->baei')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PppHhh,'NmFe,FabNim->baei')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.ppphhH,'nMfe,fabniM->baei')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PpphhH,'nMFe,FabniM->baei')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pppHhH,'NMfe,fabNiM->baei')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PppHhH,'NMFe,FabNiM->baei');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.ppphhh,'mnef,abfimn->baei')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.Ppphhh,'mneF,Fabimn->baei')...
-einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.ppphhH,'Mnef,abfinM->baei')...
-einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PpphhH,'MneF,FabinM->baei')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.ppphHH,'MNef,abfiMN->baei')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PpphHH,'MNeF,FabiMN->baei');

Vt3C.ppvh = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.ppphhH,'nmfe,fabnmI->baeI')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PpphhH,'nmFe,FabnmI->baeI')...
-einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pppHhH,'Nmfe,fabNmI->baeI')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PppHhH,'NmFe,FabNmI->baeI')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.ppphHH,'nMfe,fabnIM->baeI')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PpphHH,'nMFe,FabnIM->baeI')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pppHHH,'NMfe,fabNIM->baeI')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PppHHH,'NMFe,FabNIM->baeI');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.ppphhH,'mnef,abfmnI->baeI')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PpphhH,'mneF,FabmnI->baeI')...
+einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.ppphHH,'Mnef,abfnIM->baeI')...
+einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PpphHH,'MneF,FabnIM->baeI')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.pppHHH,'MNef,abfIMN->baeI')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PppHHH,'MNeF,FabIMN->baeI');

Vt3C.ppvH = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPphhh,'nmfe,fBanim->Baei')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPphhh,'nmFe,FBanim->Baei')...
-einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPpHhh,'Nmfe,fBaNim->Baei')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPpHhh,'NmFe,FBaNim->Baei')...
-einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPphhH,'nMfe,fBaniM->Baei')...
-einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPphhH,'nMFe,FBaniM->Baei')...
-einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPpHhH,'NMfe,fBaNiM->Baei')...
-einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPpHhH,'NMFe,FBaNiM->Baei');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.Ppphhh,'mnef,Bafimn->Baei')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPphhh,'mneF,BFaimn->Baei')...
+einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PpphhH,'Mnef,BafinM->Baei')...
-einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPphhH,'MneF,BFainM->Baei')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PpphHH,'MNef,BafiMN->Baei')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPphHH,'MNeF,BFaiMN->Baei');

Vt3C.Ppvh = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPphhH,'nmfe,fBanmI->BaeI')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPphhH,'nmFe,FBanmI->BaeI')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPpHhH,'Nmfe,fBaNmI->BaeI')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPpHhH,'NmFe,FBaNmI->BaeI')...
-einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPphHH,'nMfe,fBanIM->BaeI')...
-einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPphHH,'nMFe,FBanIM->BaeI')...
-einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPpHHH,'NMfe,fBaNIM->BaeI')...
-einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPpHHH,'NMFe,FBaNIM->BaeI');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.PpphhH,'mnef,BafmnI->BaeI')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPphhH,'mneF,BFamnI->BaeI')...
-einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PpphHH,'Mnef,BafnIM->BaeI')...
+einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPphHH,'MneF,BFanIM->BaeI')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PppHHH,'MNef,BafIMN->BaeI')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPpHHH,'MNeF,BFaIMN->BaeI');

Vt3C.PpvH = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPphhh,'nmfe,fAbnim->bAei')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPphhh,'nmFe,FAbnim->bAei')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPpHhh,'Nmfe,fAbNim->bAei')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPpHhh,'NmFe,FAbNim->bAei')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPphhH,'nMfe,fAbniM->bAei')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPphhH,'nMFe,FAbniM->bAei')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPpHhH,'NMfe,fAbNiM->bAei')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPpHhH,'NMFe,FAbNiM->bAei');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.Ppphhh,'mnef,Abfimn->bAei')...
-0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPphhh,'mneF,AFbimn->bAei')...
-einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PpphhH,'Mnef,AbfinM->bAei')...
+einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPphhH,'MneF,AFbinM->bAei')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PpphHH,'MNef,AbfiMN->bAei')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPphHH,'MNeF,AFbiMN->bAei');

Vt3C.pPvh = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPphhH,'nmfe,fAbnmI->bAeI')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPphhH,'nmFe,FAbnmI->bAeI')...
-einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPpHhH,'Nmfe,fAbNmI->bAeI')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPpHhH,'NmFe,FAbNmI->bAeI')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPphHH,'nMfe,fAbnIM->bAeI')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPphHH,'nMFe,FAbnIM->bAeI')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPpHHH,'NMfe,fAbNIM->bAeI')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPpHHH,'NMFe,FAbNIM->bAeI');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.PpphhH,'mnef,AbfmnI->bAeI')...
-0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPphhH,'mneF,AFbmnI->bAeI')...
+einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PpphHH,'Mnef,AbfnIM->bAeI')...
-einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPphHH,'MneF,AFbnIM->bAeI')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PppHHH,'MNef,AbfIMN->bAeI')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPpHHH,'MNeF,AFbIMN->bAeI');

Vt3C.pPvH = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPPhhh,'nmfe,fABnim->BAei')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPPhhh,'nmFe,FABnim->BAei')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPPHhh,'Nmfe,fABNim->BAei')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPPHhh,'NmFe,FABNim->BAei')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPPhhH,'nMfe,fABniM->BAei')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPPhhH,'nMFe,FABniM->BAei')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPPHhH,'NMfe,fABNiM->BAei')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPPHhH,'NMFe,FABNiM->BAei');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.PPphhh,'mnef,ABfimn->BAei')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPPhhh,'mneF,ABFimn->BAei')...
-einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PPphhH,'Mnef,ABfinM->BAei')...
-einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPPhhH,'MneF,ABFinM->BAei')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PPphHH,'MNef,ABfiMN->BAei')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPPhHH,'MNeF,ABFiMN->BAei');

Vt3C.PPvh = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPPhhH,'nmfe,fABnmI->BAeI')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPPhhH,'nmFe,FABnmI->BAeI')...
-einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPPHhH,'Nmfe,fABNmI->BAeI')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPPHhH,'NmFe,FABNmI->BAeI')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPPhHH,'nMfe,fABnIM->BAeI')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPPhHH,'nMFe,FABnIM->BAeI')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPPHHH,'NMfe,fABNIM->BAeI')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPPHHH,'NMFe,FABNIM->BAeI');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.PPphhH,'mnef,ABfmnI->BAeI')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPPhhH,'mneF,ABFmnI->BAeI')...
+einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PPphHH,'Mnef,ABfnIM->BAeI')...
+einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPPhHH,'MneF,ABFnIM->BAeI')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PPpHHH,'MNef,ABfIMN->BAeI')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPPHHH,'MNeF,ABFIMN->BAeI');

Vt3C.PPvH = -d1 - d2;

%%                              %% OVOO (C) %%%%

d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.ppphhh,'nmfe,faenij->maji')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPphhh,'nmfE,fEanij->maji')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.Ppphhh,'nmFe,Faenij->maji')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPphhh,'nmFE,FEanij->maji')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pppHhh,'Nmfe,faeNij->maji')...
-einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPpHhh,'NmfE,fEaNij->maji')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PppHhh,'NmFe,FaeNij->maji')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPpHhh,'NmFE,FEaNij->maji');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.ppphhh,'mnef,aefijn->maji')...
+einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.Ppphhh,'mneF,Faeijn->maji')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPphhh,'mnEF,EFaijn->maji')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.ppphhH,'mNef,aefijN->maji')...
+einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PpphhH,'mNeF,FaeijN->maji')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPphhH,'mNEF,EFaijN->maji');

Vt3C.ophh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.ppphhH,'nmfe,faeniJ->maJi')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPphhH,'nmfE,fEaniJ->maJi')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PpphhH,'nmFe,FaeniJ->maJi')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPphhH,'nmFE,FEaniJ->maJi')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pppHhH,'Nmfe,faeNiJ->maJi')...
-einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPpHhH,'NmfE,fEaNiJ->maJi')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PppHhH,'NmFe,FaeNiJ->maJi')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPpHhH,'NmFE,FEaNiJ->maJi');

d2 = -0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.ppphhH,'mnef,aefinJ->maJi')...
-einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PpphhH,'mneF,FaeinJ->maJi')...
-0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPphhH,'mnEF,EFainJ->maJi')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.ppphHH,'mNef,aefiJN->maJi')...
+einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PpphHH,'mNeF,FaeiJN->maJi')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPphHH,'mNEF,EFaiJN->maJi');

Vt3C.opHh = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.ppphhH,'nmfe,faenjI->majI')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPphhH,'nmfE,fEanjI->majI')...
-einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PpphhH,'nmFe,FaenjI->majI')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPphhH,'nmFE,FEanjI->majI')...
-einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pppHhH,'Nmfe,faeNjI->majI')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPpHhH,'NmfE,fEaNjI->majI')...
-einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PppHhH,'NmFe,FaeNjI->majI')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPpHhH,'NmFE,FEaNjI->majI');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.ppphhH,'mnef,aefjnI->majI')...
+einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PpphhH,'mneF,FaejnI->majI')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPphhH,'mnEF,EFajnI->majI')...
-0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.ppphHH,'mNef,aefjIN->majI')...
-einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PpphHH,'mNeF,FaejIN->majI')...
-0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPphHH,'mNEF,EFajIN->majI');

Vt3C.ophH = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.ppphHH,'nmfe,faenIJ->maJI')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPphHH,'nmfE,fEanIJ->maJI')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PpphHH,'nmFe,FaenIJ->maJI')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPphHH,'nmFE,FEanIJ->maJI')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pppHHH,'Nmfe,faeNIJ->maJI')...
-einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPpHHH,'NmfE,fEaNIJ->maJI')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PppHHH,'NmFe,FaeNIJ->maJI')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPpHHH,'NmFE,FEaNIJ->maJI');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.ppphHH,'mnef,aefnIJ->maJI')...
+einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PpphHH,'mneF,FaenIJ->maJI')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPphHH,'mnEF,EFanIJ->maJI')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.pppHHH,'mNef,aefIJN->maJI')...
+einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PppHHH,'mNeF,FaeIJN->maJI')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPpHHH,'mNEF,EFaIJN->maJI');

Vt3C.opHH = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.pPphhh,'nmfe,fAenij->mAji')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPPhhh,'nmfE,fAEnij->mAji')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PPphhh,'nmFe,FAenij->mAji')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPPhhh,'nmFE,FAEnij->mAji')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pPpHhh,'Nmfe,fAeNij->mAji')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPPHhh,'NmfE,fAENij->mAji')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PPpHhh,'NmFe,FAeNij->mAji')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPPHhh,'NmFE,FAENij->mAji');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.Ppphhh,'mnef,Aefijn->mAji')...
-einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PPphhh,'mneF,AFeijn->mAji')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPPhhh,'mnEF,AEFijn->mAji')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.PpphhH,'mNef,AefijN->mAji')...
-einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PPphhH,'mNeF,AFeijN->mAji')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPPhhH,'mNEF,AEFijN->mAji');

Vt3C.oPhh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.pPphhH,'nmfe,fAeniJ->mAJi')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPPhhH,'nmfE,fAEniJ->mAJi')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PPphhH,'nmFe,FAeniJ->mAJi')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPPhhH,'nmFE,FAEniJ->mAJi')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pPpHhH,'Nmfe,fAeNiJ->mAJi')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPPHhH,'NmfE,fAENiJ->mAJi')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PPpHhH,'NmFe,FAeNiJ->mAJi')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPPHhH,'NmFE,FAENiJ->mAJi');

d2 = -0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.PpphhH,'mnef,AefinJ->mAJi')...
+einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PPphhH,'mneF,AFeinJ->mAJi')...
-0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPPhhH,'mnEF,AEFinJ->mAJi')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.PpphHH,'mNef,AefiJN->mAJi')...
-einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PPphHH,'mNeF,AFeiJN->mAJi')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPPhHH,'mNEF,AEFiJN->mAJi');

Vt3C.oPHh = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.pPphhH,'nmfe,fAenjI->mAjI')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPPhhH,'nmfE,fAEnjI->mAjI')...
-einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PPphhH,'nmFe,FAenjI->mAjI')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPPhhH,'nmFE,FAEnjI->mAjI')...
-einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pPpHhH,'Nmfe,fAeNjI->mAjI')...
-einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPPHhH,'NmfE,fAENjI->mAjI')...
-einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PPpHhH,'NmFe,FAeNjI->mAjI')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPPHhH,'NmFE,FAENjI->mAjI');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.PpphhH,'mnef,AefjnI->mAjI')...
-einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PPphhH,'mneF,AFejnI->mAjI')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPPhhH,'mnEF,AEFjnI->mAjI')...
-0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.PpphHH,'mNef,AefjIN->mAjI')...
+einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PPphHH,'mNeF,AFejIN->mAjI')...
-0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPPhHH,'mNEF,AEFjIN->mAjI');

Vt3C.oPhH = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.pPphHH,'nmfe,fAenIJ->mAJI')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPPhHH,'nmfE,fAEnIJ->mAJI')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PPphHH,'nmFe,FAenIJ->mAJI')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPPhHH,'nmFE,FAEnIJ->mAJI')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pPpHHH,'Nmfe,fAeNIJ->mAJI')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPPHHH,'NmfE,fAENIJ->mAJI')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PPpHHH,'NmFe,FAeNIJ->mAJI')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPPHHH,'NmFE,FAENIJ->mAJI');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.PpphHH,'mnef,AefnIJ->mAJI')...
-einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PPphHH,'mneF,AFenIJ->mAJI')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPPhHH,'mnEF,AEFnIJ->mAJI')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.PppHHH,'mNef,AefIJN->mAJI')...
-einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PPpHHH,'mNeF,AFeIJN->mAJI')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPPHHH,'mNEF,AEFIJN->mAJI');

Vt3C.oPHH = d1 + d2;

%%                              %% VOOO (C) %%%%


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.ppphhh,'nmfe,faenij->amij')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPphhh,'nmfE,fEanij->amij')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.Ppphhh,'nmFe,Faenij->amij')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPphhh,'nmFE,FEanij->amij')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pppHhh,'Nmfe,faeNij->amij')...
-einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPpHhh,'NmfE,fEaNij->amij')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PppHhh,'NmFe,FaeNij->amij')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPpHhh,'NmFE,FEaNij->amij');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.ppphhh,'mnef,aefijn->amij')...
+einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.Ppphhh,'mneF,Faeijn->amij')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPphhh,'mnEF,EFaijn->amij')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.ppphhH,'mNef,aefijN->amij')...
+einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PpphhH,'mNeF,FaeijN->amij')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPphhH,'mNEF,EFaijN->amij');

Vt3C.pohh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.ppphhH,'nmfe,faeniJ->amiJ')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPphhH,'nmfE,fEaniJ->amiJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PpphhH,'nmFe,FaeniJ->amiJ')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPphhH,'nmFE,FEaniJ->amiJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pppHhH,'Nmfe,faeNiJ->amiJ')...
-einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPpHhH,'NmfE,fEaNiJ->amiJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PppHhH,'NmFe,FaeNiJ->amiJ')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPpHhH,'NmFE,FEaNiJ->amiJ');

d2 = -0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.ppphhH,'mnef,aefinJ->amiJ')...
-einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PpphhH,'mneF,FaeinJ->amiJ')...
-0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPphhH,'mnEF,EFainJ->amiJ')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.ppphHH,'mNef,aefiJN->amiJ')...
+einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PpphHH,'mNeF,FaeiJN->amiJ')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPphHH,'mNEF,EFaiJN->amiJ');

Vt3C.pohH = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.ppphhH,'nmfe,faenjI->amIj')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPphhH,'nmfE,fEanjI->amIj')...
-einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PpphhH,'nmFe,FaenjI->amIj')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPphhH,'nmFE,FEanjI->amIj')...
-einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pppHhH,'Nmfe,faeNjI->amIj')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPpHhH,'NmfE,fEaNjI->amIj')...
-einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PppHhH,'NmFe,FaeNjI->amIj')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPpHhH,'NmFE,FEaNjI->amIj');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.ppphhH,'mnef,aefjnI->amIj')...
+einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PpphhH,'mneF,FaejnI->amIj')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPphhH,'mnEF,EFajnI->amIj')...
-0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.ppphHH,'mNef,aefjIN->amIj')...
-einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PpphHH,'mNeF,FaejIN->amIj')...
-0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPphHH,'mNEF,EFajIN->amIj');

Vt3C.poHh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.ppphHH,'nmfe,faenIJ->amIJ')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPphHH,'nmfE,fEanIJ->amIJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PpphHH,'nmFe,FaenIJ->amIJ')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPphHH,'nmFE,FEanIJ->amIJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pppHHH,'Nmfe,faeNIJ->amIJ')...
-einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPpHHH,'NmfE,fEaNIJ->amIJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PppHHH,'NmFe,FaeNIJ->amIJ')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPpHHH,'NmFE,FEaNIJ->amIJ');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.ppphHH,'mnef,aefnIJ->amIJ')...
+einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PpphHH,'mneF,FaenIJ->amIJ')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPphHH,'mnEF,EFanIJ->amIJ')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.pppHHH,'mNef,aefIJN->amIJ')...
+einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PppHHH,'mNeF,FaeIJN->amIJ')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPpHHH,'mNEF,EFaIJN->amIJ');

Vt3C.poHH = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.pPphhh,'nmfe,fAenij->Amij')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPPhhh,'nmfE,fAEnij->Amij')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PPphhh,'nmFe,FAenij->Amij')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPPhhh,'nmFE,FAEnij->Amij')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pPpHhh,'Nmfe,fAeNij->Amij')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPPHhh,'NmfE,fAENij->Amij')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PPpHhh,'NmFe,FAeNij->Amij')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPPHhh,'NmFE,FAENij->Amij');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.Ppphhh,'mnef,Aefijn->Amij')...
-einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PPphhh,'mneF,AFeijn->Amij')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPPhhh,'mnEF,AEFijn->Amij')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.PpphhH,'mNef,AefijN->Amij')...
-einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PPphhH,'mNeF,AFeijN->Amij')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPPhhH,'mNEF,AEFijN->Amij');

Vt3C.Pohh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.pPphhH,'nmfe,fAeniJ->AmiJ')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPPhhH,'nmfE,fAEniJ->AmiJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PPphhH,'nmFe,FAeniJ->AmiJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPPhhH,'nmFE,FAEniJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pPpHhH,'Nmfe,fAeNiJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPPHhH,'NmfE,fAENiJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PPpHhH,'NmFe,FAeNiJ->AmiJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPPHhH,'NmFE,FAENiJ->AmiJ');

d2 = -0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.PpphhH,'mnef,AefinJ->AmiJ')...
+einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PPphhH,'mneF,AFeinJ->AmiJ')...
-0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPPhhH,'mnEF,AEFinJ->AmiJ')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.PpphHH,'mNef,AefiJN->AmiJ')...
-einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PPphHH,'mNeF,AFeiJN->AmiJ')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPPhHH,'mNEF,AEFiJN->AmiJ');

Vt3C.PohH = d1 + d2;


d1 = -einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.pPphhH,'nmfe,fAenjI->AmIj')...
-einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPPhhH,'nmfE,fAEnjI->AmIj')...
-einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PPphhH,'nmFe,FAenjI->AmIj')...
-einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPPhhH,'nmFE,FAEnjI->AmIj')...
-einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pPpHhH,'Nmfe,fAeNjI->AmIj')...
-einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPPHhH,'NmfE,fAENjI->AmIj')...
-einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PPpHhH,'NmFe,FAeNjI->AmIj')...
-einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPPHhH,'NmFE,FAENjI->AmIj');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.PpphhH,'mnef,AefjnI->AmIj')...
-einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PPphhH,'mneF,AFejnI->AmIj')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPPhhH,'mnEF,AEFjnI->AmIj')...
-0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.PpphHH,'mNef,AefjIN->AmIj')...
+einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PPphHH,'mNeF,AFejIN->AmIj')...
-0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPPhHH,'mNEF,AEFjIN->AmIj');

Vt3C.PoHh = d1 + d2;


d1 = +einsum_kg(sys.vB_oovv(hA,:,pA,pB),T3C.pPphHH,'nmfe,fAenIJ->AmIJ')...
+einsum_kg(sys.vB_oovv(hA,:,pA,PB),T3C.pPPhHH,'nmfE,fAEnIJ->AmIJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,pB),T3C.PPphHH,'nmFe,FAenIJ->AmIJ')...
+einsum_kg(sys.vB_oovv(hA,:,PA,PB),T3C.PPPhHH,'nmFE,FAEnIJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,pB),T3C.pPpHHH,'Nmfe,fAeNIJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,pA,PB),T3C.pPPHHH,'NmfE,fAENIJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,pB),T3C.PPpHHH,'NmFe,FAeNIJ->AmIJ')...
+einsum_kg(sys.vB_oovv(HA,:,PA,PB),T3C.PPPHHH,'NmFE,FAENIJ->AmIJ');

d2 = +0.5*einsum_kg(sys.vC_oovv(:,hB,pB,pB),T3D.PpphHH,'mnef,AefnIJ->AmIJ')...
-einsum_kg(sys.vC_oovv(:,hB,pB,PB),T3D.PPphHH,'mneF,AFenIJ->AmIJ')...
+0.5*einsum_kg(sys.vC_oovv(:,hB,PB,PB),T3D.PPPhHH,'mnEF,AEFnIJ->AmIJ')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,pB,pB),T3D.PppHHH,'mNef,AefIJN->AmIJ')...
-einsum_kg(sys.vC_oovv(:,HB,pB,PB),T3D.PPpHHH,'mNeF,AFeIJN->AmIJ')...
+0.5*einsum_kg(sys.vC_oovv(:,HB,PB,PB),T3D.PPPHHH,'mNEF,AEFIJN->AmIJ');

Vt3C.PoHH = d1 + d2;
%%                              %% VVOV (C) %%%%


d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.ppphhh,'nmfe,fabnim->abie')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.Ppphhh,'nmFe,Fabnim->abie')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pppHhh,'Nmfe,fabNim->abie')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PppHhh,'NmFe,FabNim->abie')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.ppphhH,'nMfe,fabniM->abie')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PpphhH,'nMFe,FabniM->abie')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pppHhH,'NMfe,fabNiM->abie')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PppHhH,'NMFe,FabNiM->abie');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.ppphhh,'mnef,abfimn->abie')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.Ppphhh,'mneF,Fabimn->abie')...
-einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.ppphhH,'Mnef,abfinM->abie')...
-einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PpphhH,'MneF,FabinM->abie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.ppphHH,'MNef,abfiMN->abie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PpphHH,'MNeF,FabiMN->abie');

Vt3C.pphv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.ppphhH,'nmfe,fabnmI->abIe')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PpphhH,'nmFe,FabnmI->abIe')...
-einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pppHhH,'Nmfe,fabNmI->abIe')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PppHhH,'NmFe,FabNmI->abIe')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.ppphHH,'nMfe,fabnIM->abIe')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PpphHH,'nMFe,FabnIM->abIe')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pppHHH,'NMfe,fabNIM->abIe')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PppHHH,'NMFe,FabNIM->abIe');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.ppphhH,'mnef,abfmnI->abIe')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PpphhH,'mneF,FabmnI->abIe')...
+einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.ppphHH,'Mnef,abfnIM->abIe')...
+einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PpphHH,'MneF,FabnIM->abIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.pppHHH,'MNef,abfIMN->abIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PppHHH,'MNeF,FabIMN->abIe');

Vt3C.ppHv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPphhh,'nmfe,fBanim->aBie')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPphhh,'nmFe,FBanim->aBie')...
-einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPpHhh,'Nmfe,fBaNim->aBie')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPpHhh,'NmFe,FBaNim->aBie')...
-einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPphhH,'nMfe,fBaniM->aBie')...
-einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPphhH,'nMFe,FBaniM->aBie')...
-einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPpHhH,'NMfe,fBaNiM->aBie')...
-einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPpHhH,'NMFe,FBaNiM->aBie');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.Ppphhh,'mnef,Bafimn->aBie')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPphhh,'mneF,BFaimn->aBie')...
+einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PpphhH,'Mnef,BafinM->aBie')...
-einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPphhH,'MneF,BFainM->aBie')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PpphHH,'MNef,BafiMN->aBie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPphHH,'MNeF,BFaiMN->aBie');

Vt3C.pPhv = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPphhH,'nmfe,fBanmI->aBIe')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPphhH,'nmFe,FBanmI->aBIe')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPpHhH,'Nmfe,fBaNmI->aBIe')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPpHhH,'NmFe,FBaNmI->aBIe')...
-einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPphHH,'nMfe,fBanIM->aBIe')...
-einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPphHH,'nMFe,FBanIM->aBIe')...
-einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPpHHH,'NMfe,fBaNIM->aBIe')...
-einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPpHHH,'NMFe,FBaNIM->aBIe');

d2 = -0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.PpphhH,'mnef,BafmnI->aBIe')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPphhH,'mneF,BFamnI->aBIe')...
-einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PpphHH,'Mnef,BafnIM->aBIe')...
+einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPphHH,'MneF,BFanIM->aBIe')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PppHHH,'MNef,BafIMN->aBIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPpHHH,'MNeF,BFaIMN->aBIe');

Vt3C.pPHv = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPphhh,'nmfe,fAbnim->Abie')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPphhh,'nmFe,FAbnim->Abie')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPpHhh,'Nmfe,fAbNim->Abie')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPpHhh,'NmFe,FAbNim->Abie')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPphhH,'nMfe,fAbniM->Abie')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPphhH,'nMFe,FAbniM->Abie')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPpHhH,'NMfe,fAbNiM->Abie')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPpHhH,'NMFe,FAbNiM->Abie');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.Ppphhh,'mnef,Abfimn->Abie')...
-0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPphhh,'mneF,AFbimn->Abie')...
-einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PpphhH,'Mnef,AbfinM->Abie')...
+einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPphhH,'MneF,AFbinM->Abie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PpphHH,'MNef,AbfiMN->Abie')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPphHH,'MNeF,AFbiMN->Abie');

Vt3C.Pphv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPphhH,'nmfe,fAbnmI->AbIe')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPphhH,'nmFe,FAbnmI->AbIe')...
-einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPpHhH,'Nmfe,fAbNmI->AbIe')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPpHhH,'NmFe,FAbNmI->AbIe')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPphHH,'nMfe,fAbnIM->AbIe')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPphHH,'nMFe,FAbnIM->AbIe')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPpHHH,'NMfe,fAbNIM->AbIe')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPpHHH,'NMFe,FAbNIM->AbIe');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.PpphhH,'mnef,AbfmnI->AbIe')...
-0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPphhH,'mneF,AFbmnI->AbIe')...
+einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PpphHH,'Mnef,AbfnIM->AbIe')...
-einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPphHH,'MneF,AFbnIM->AbIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PppHHH,'MNef,AbfIMN->AbIe')...
-0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPpHHH,'MNeF,AFbIMN->AbIe');

Vt3C.PpHv = -d1 - d2;


d1 = +einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPPhhh,'nmfe,fABnim->ABie')...
+einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPPhhh,'nmFe,FABnim->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPPHhh,'Nmfe,fABNim->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPPHhh,'NmFe,FABNim->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPPhhH,'nMfe,fABniM->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPPhhH,'nMFe,FABniM->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPPHhH,'NMfe,fABNiM->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPPHhH,'NMFe,FABNiM->ABie');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.PPphhh,'mnef,ABfimn->ABie')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPPhhh,'mneF,ABFimn->ABie')...
-einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PPphhH,'Mnef,ABfinM->ABie')...
-einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPPhhH,'MneF,ABFinM->ABie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PPphHH,'MNef,ABfiMN->ABie')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPPhHH,'MNeF,ABFiMN->ABie');

Vt3C.PPhv = -d1 - d2;


d1 = -einsum_kg(sys.vB_oovv(hA,hB,pA,:),T3C.pPPhhH,'nmfe,fABnmI->ABIe')...
-einsum_kg(sys.vB_oovv(hA,hB,PA,:),T3C.PPPhhH,'nmFe,FABnmI->ABIe')...
-einsum_kg(sys.vB_oovv(HA,hB,pA,:),T3C.pPPHhH,'Nmfe,fABNmI->ABIe')...
-einsum_kg(sys.vB_oovv(HA,hB,PA,:),T3C.PPPHhH,'NmFe,FABNmI->ABIe')...
+einsum_kg(sys.vB_oovv(hA,HB,pA,:),T3C.pPPhHH,'nMfe,fABnIM->ABIe')...
+einsum_kg(sys.vB_oovv(hA,HB,PA,:),T3C.PPPhHH,'nMFe,FABnIM->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,pA,:),T3C.pPPHHH,'NMfe,fABNIM->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,PA,:),T3C.PPPHHH,'NMFe,FABNIM->ABIe');

d2 = +0.5*einsum_kg(sys.vC_oovv(hB,hB,:,pB),T3D.PPphhH,'mnef,ABfmnI->ABIe')...
+0.5*einsum_kg(sys.vC_oovv(hB,hB,:,PB),T3D.PPPhhH,'mneF,ABFmnI->ABIe')...
+einsum_kg(sys.vC_oovv(HB,hB,:,pB),T3D.PPphHH,'Mnef,ABfnIM->ABIe')...
+einsum_kg(sys.vC_oovv(HB,hB,:,PB),T3D.PPPhHH,'MneF,ABFnIM->ABIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,pB),T3D.PPpHHH,'MNef,ABfIMN->ABIe')...
+0.5*einsum_kg(sys.vC_oovv(HB,HB,:,PB),T3D.PPPHHH,'MNeF,ABFIMN->ABIe');

Vt3C.PPHv = -d1 - d2;
%%
ccsdt_act_VT3_writer('vvov','C')