clear all
clc
close all

ccsdt_act_VT3_writer('vvov','A')
%%

format long

addpath(genpath('/Users/karthik/Dropbox/Hartree Fock/hartree_fock/v4/CC_matlab'));
addpath(genpath('/Users/karthik/Desktop/CC_matlab_tests'));

load h2o-631g-stretched
%load f2-2.0-pvdz.mat % NEEDS NFZC = 2

%% Set up problem

nfzc = 0; nfzv = 0; 
nact_h = 2; nact_p = 3; % BE CAREFUL ABOUT SINGLETON DIMENSIONS!
nact_h_alpha = nact_h; nact_h_beta = nact_h; nact_p_alpha = nact_p; nact_p_beta = nact_p;
flag_act_scheme = 0;

sys = build_system_ucc(e1int,e2int,Vnuc,Nocc_a,Nocc_b,nfzc,...
                           nact_h_alpha,nact_p_alpha,nact_h_beta,nact_p_beta,flag_act_scheme);
                       
PA = sys.PA; pA = sys.pA; HA = sys.HA; hA = sys.hA;
PB = sys.PB; pB = sys.pB; HB = sys.HB; hB = sys.hB;


                       
%% Full CCSDT

ccopts.diis_size = 5;
ccopts.maxit = 100;
ccopts.tol = 1e-10;
ccopts.shift = 0;

[cc_t,Ecorr_uccsdt] = uccsdt(sys,ccopts);

% HBar
flag_build_3body = true;
[HBar_t] = build_ucc_HBar( cc_t, sys, flag_build_3body);

%%
[t3a, VTA] = build_t3a(cc_t.t1a, cc_t.t1b, cc_t.t2a, cc_t.t2b, cc_t.t2c, cc_t.t3a, cc_t.t3b, cc_t.t3c, cc_t.t3d, sys, 0.0);

%%
[T3A,T3B,T3C,T3D] = make_t3_act_struct(cc_t,sys);

%%
clc

d1 = '-h1a(mI),t3b(ABcmJK)'; 
[D1] = ccsdt_act_HBarT3_simple(d1)

d2 = 'h2a(Abef),t3b(efCIJk)';
[D2] = ccsdt_act_HBarT3_simple(d2)

d3 = 'h2a(bmJe),t3b(AeCImk)'
[D3] = ccsdt_act_HBarT3_simple(d3)


%%
clc


d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.ppphhh,'mnef,abfimn->abie')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.ppPhhh,'mneF,abFimn->abie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.ppphhH,'mNef,abfimN->abie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.ppPhhH,'mNeF,abFimN->abie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.ppphHh,'Mnef,abfiMn->abie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.ppPhHh,'MneF,abFiMn->abie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.ppphHH,'MNef,abfiMN->abie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.ppPhHH,'MNeF,abFiMN->abie');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.ppphhh,'mnef,abfimn->abie')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.Ppphhh,'mneF,Fabimn->abie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.ppphhH,'Mnef,abfinM->abie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PpphhH,'MneF,FabinM->abie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.ppphHH,'MNef,abfiMN->abie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PpphHH,'MNeF,FabiMN->abie');

Vt3a.pphv = -d1 - d2;

get_error(Vt3a.pphv,VTA.vvov(pA,pA,hA,:))


d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.ppphHh,'mnef,abfmIn->abIe')...
-einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.ppPhHh,'mneF,abFmIn->abIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.ppphHH,'mNef,abfmIN->abIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.ppPhHH,'mNeF,abFmIN->abIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.pppHHh,'Mnef,abfIMn->abIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.ppPHHh,'MneF,abFIMn->abIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.pppHHH,'MNef,abfIMN->abIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.ppPHHH,'MNeF,abFIMN->abIe');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.ppphhH,'mnef,abfmnI->abIe')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PpphhH,'mneF,FabmnI->abIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.ppphHH,'Mnef,abfnIM->abIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PpphHH,'MneF,FabnIM->abIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.pppHHH,'MNef,abfIMN->abIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PppHHH,'MNeF,FabIMN->abIe');

Vt3a.ppHv = -d1 - d2;

get_error(Vt3a.ppHv,VTA.vvov(pA,pA,HA,:))


d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.Ppphhh,'mnef,Bafimn->aBie')...
-einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PpPhhh,'mneF,BaFimn->aBie')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PpphhH,'mNef,BafimN->aBie')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhhH,'mNeF,BaFimN->aBie')...
-einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PpphHh,'Mnef,BafiMn->aBie')...
-einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPhHh,'MneF,BaFiMn->aBie')...
-einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PpphHH,'MNef,BafiMN->aBie')...
-einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPhHH,'MNeF,BaFiMN->aBie');

d2 = -0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.Ppphhh,'mnef,Bafimn->aBie')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPphhh,'mneF,BFaimn->aBie')...
+einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PpphhH,'Mnef,BafinM->aBie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphhH,'MneF,BFainM->aBie')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PpphHH,'MNef,BafiMN->aBie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPphHH,'MNeF,BFaiMN->aBie');

Vt3a.pPhv = -d1 - d2;
get_error(Vt3a.pPhv,VTA.vvov(pA,PA,hA,:))


d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PpphHh,'mnef,BafmIn->aBIe')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PpPhHh,'mneF,BaFmIn->aBIe')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PpphHH,'mNef,BafmIN->aBIe')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhHH,'mNeF,BaFmIN->aBIe')...
-einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PppHHh,'Mnef,BafIMn->aBIe')...
-einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPHHh,'MneF,BaFIMn->aBIe')...
-einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PppHHH,'MNef,BafIMN->aBIe')...
-einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPHHH,'MNeF,BaFIMN->aBIe');

d2 = -0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PpphhH,'mnef,BafmnI->aBIe')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPphhH,'mneF,BFamnI->aBIe')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PpphHH,'Mnef,BafnIM->aBIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphHH,'MneF,BFanIM->aBIe')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PppHHH,'MNef,BafIMN->aBIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPpHHH,'MNeF,BFaIMN->aBIe');

Vt3a.pPHv = -d1 - d2;
get_error(Vt3a.pPHv,VTA.vvov(pA,PA,HA,:))

d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.Ppphhh,'mnef,Abfimn->Abie')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PpPhhh,'mneF,AbFimn->Abie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PpphhH,'mNef,AbfimN->Abie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhhH,'mNeF,AbFimN->Abie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PpphHh,'Mnef,AbfiMn->Abie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPhHh,'MneF,AbFiMn->Abie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PpphHH,'MNef,AbfiMN->Abie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPhHH,'MNeF,AbFiMN->Abie');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.Ppphhh,'mnef,Abfimn->Abie')...
-0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPphhh,'mneF,AFbimn->Abie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PpphhH,'Mnef,AbfinM->Abie')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphhH,'MneF,AFbinM->Abie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PpphHH,'MNef,AbfiMN->Abie')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPphHH,'MNeF,AFbiMN->Abie');

Vt3a.Pphv = -d1 - d2;
get_error(Vt3a.Pphv,VTA.vvov(PA,pA,hA,:))

d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PpphHh,'mnef,AbfmIn->AbIe')...
-einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PpPhHh,'mneF,AbFmIn->AbIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PpphHH,'mNef,AbfmIN->AbIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PpPhHH,'mNeF,AbFmIN->AbIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PppHHh,'Mnef,AbfIMn->AbIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PpPHHh,'MneF,AbFIMn->AbIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PppHHH,'MNef,AbfIMN->AbIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PpPHHH,'MNeF,AbFIMN->AbIe');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PpphhH,'mnef,AbfmnI->AbIe')...
-0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPphhH,'mneF,AFbmnI->AbIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PpphHH,'Mnef,AbfnIM->AbIe')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPphHH,'MneF,AFbnIM->AbIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PppHHH,'MNef,AbfIMN->AbIe')...
-0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPpHHH,'MNeF,AFbIMN->AbIe');

Vt3a.PpHv = -d1 - d2;
get_error(Vt3a.PpHv,VTA.vvov(PA,pA,HA,:))

d1 = +einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PPphhh,'mnef,ABfimn->ABie')...
+einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PPPhhh,'mneF,ABFimn->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PPphhH,'mNef,ABfimN->ABie')...
+einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PPPhhH,'mNeF,ABFimN->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PPphHh,'Mnef,ABfiMn->ABie')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PPPhHh,'MneF,ABFiMn->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PPphHH,'MNef,ABfiMN->ABie')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PPPhHH,'MNeF,ABFiMN->ABie');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PPphhh,'mnef,ABfimn->ABie')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPPhhh,'mneF,ABFimn->ABie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PPphhH,'Mnef,ABfinM->ABie')...
-einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPPhhH,'MneF,ABFinM->ABie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PPphHH,'MNef,ABfiMN->ABie')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPPhHH,'MNeF,ABFiMN->ABie');

Vt3a.PPhv = -d1 - d2;
get_error(Vt3a.PPhv,VTA.vvov(PA,PA,hA,:))

d1 = -einsum_kg(sys.vB_oovv(hA,hB,:,pB),T3B.PPphHh,'mnef,ABfmIn->ABIe')...
-einsum_kg(sys.vB_oovv(hA,hB,:,PB),T3B.PPPhHh,'mneF,ABFmIn->ABIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,pB),T3B.PPphHH,'mNef,ABfmIN->ABIe')...
-einsum_kg(sys.vB_oovv(hA,HB,:,PB),T3B.PPPhHH,'mNeF,ABFmIN->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,pB),T3B.PPpHHh,'Mnef,ABfIMn->ABIe')...
+einsum_kg(sys.vB_oovv(HA,hB,:,PB),T3B.PPPHHh,'MneF,ABFIMn->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,pB),T3B.PPpHHH,'MNef,ABfIMN->ABIe')...
+einsum_kg(sys.vB_oovv(HA,HB,:,PB),T3B.PPPHHH,'MNeF,ABFIMN->ABIe');

d2 = +0.5*einsum_kg(sys.vA_oovv(hA,hA,:,pA),T3A.PPphhH,'mnef,ABfmnI->ABIe')...
+0.5*einsum_kg(sys.vA_oovv(hA,hA,:,PA),T3A.PPPhhH,'mneF,ABFmnI->ABIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,pA),T3A.PPphHH,'Mnef,ABfnIM->ABIe')...
+einsum_kg(sys.vA_oovv(HA,hA,:,PA),T3A.PPPhHH,'MneF,ABFnIM->ABIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,pA),T3A.PPpHHH,'MNef,ABfIMN->ABIe')...
+0.5*einsum_kg(sys.vA_oovv(HA,HA,:,PA),T3A.PPPHHH,'MNeF,ABFIMN->ABIe');

Vt3a.PPHv = -d1 - d2;
get_error(Vt3a.PPHv,VTA.vvov(PA,PA,HA,:))