function [L3C] = build_L3C_approx(cc_t,HBar_t,sys,nroot)

    fprintf('Approximate L3C construction...')

    tic
    
    if nroot == 0
        nroot = 1;
    else
        nroot = nroot + 1;
    end

    l1a = cc_t.l1a{nroot}; l1b = cc_t.l1b{nroot}; 
    l2a = cc_t.l2a{nroot}; l2b = cc_t.l2b{nroot}; l2c = cc_t.l2c{nroot};
    
    H1A = HBar_t.H1A; H1B = HBar_t.H1B;
    H2A = HBar_t.H2A; H2B = HBar_t.H2B; H2C = HBar_t.H2C;
    
    % permute L1 and L2 into ijab
    l1a = permute(l1a,[2,1]); l1b = permute(l1b,[2,1]); 
    l2a = permute(l2a,[3,4,1,2]); l2b = permute(l2b,[3,4,1,2]); l2c = permute(l2c,[3,4,1,2]);   

    DC1 = einsum_kg(l1b,H2B.oovv,'kc,ijab->ijkabc')...
          -einsum_kg(l1b,H2B.oovv,'kb,ijac->ijkabc')...
          -einsum_kg(l1b,H2B.oovv,'jc,ikab->ijkabc')...
          +einsum_kg(l1b,H2B.oovv,'jb,ikac->ijkabc')...
          +einsum_kg(l1a,H2C.oovv,'ia,jkbc->ijkabc');
    
    DC2 =  einsum_kg(H1B.ov,l2b,'kc,ijab->ijkabc')...
          -einsum_kg(H1B.ov,l2b,'kb,ijac->ijkabc')...
          -einsum_kg(H1B.ov,l2b,'jc,ikab->ijkabc')...
          +einsum_kg(H1B.ov,l2b,'jb,ikac->ijkabc')...
          +einsum_kg(H1A.ov,l2c,'ia,jkbc->ijkabc');

    D1 = einsum_kg(H2B.ovvv,l2c,'ieab,jkec->ijkabc')...
        -einsum_kg(H2B.ovvv,l2c,'ieac,jkeb->ijkabc')...
        +einsum_kg(H2C.vovv,l2b,'ekbc,ijae->ijkabc')...
        -einsum_kg(H2C.vovv,l2b,'ejbc,ikae->ijkabc')...
        +einsum_kg(H2B.vovv,l2b,'ejab,ikec->ijkabc')...
        -einsum_kg(H2B.vovv,l2b,'ekab,ijec->ijkabc')...
        -einsum_kg(H2B.vovv,l2b,'ejac,ikeb->ijkabc')...
        +einsum_kg(H2B.vovv,l2b,'ekac,ijeb->ijkabc');

    D2 = einsum_kg(H2B.oovo,l2c,'ijam,mkbc->ijkabc')...
        -einsum_kg(H2B.oovo,l2c,'ikam,mjbc->ijkabc')...
        +einsum_kg(H2C.ooov,l2b,'jkmc,imab->ijkabc')...
        -einsum_kg(H2C.ooov,l2b,'jkmb,imac->ijkabc')...
        +einsum_kg(H2B.ooov,l2b,'ijmb,mkac->ijkabc')...
        -einsum_kg(H2B.ooov,l2b,'ikmb,mjac->ijkabc')...
        -einsum_kg(H2B.ooov,l2b,'ijmc,mkab->ijkabc')...
        +einsum_kg(H2B.ooov,l2b,'ikmc,mjab->ijkabc');

    L3C = DC1 + DC2 + D1 - D2;

    fprintf(' finished in %4.2f s\n',toc)
end