function [L3B] = build_L3B_approx(cc_t,HBar_t,sys,nroot)

    fprintf('Approximate L3B construction...')

    tic
    
    if nroot == 0
        nroot = 1;
    else
        nroot = nroot + 1;
    end

    l1a = cc_t.l1a{nroot}; l1b = cc_t.l1b{nroot}; 
    l2a = cc_t.l2a{nroot}; l2b = cc_t.l2b{nroot}; 
    
    H1A = HBar_t.H1A; H1B = HBar_t.H1B;
    H2A = HBar_t.H2A; H2B = HBar_t.H2B; 
    
    % permute L1 and L2 into ijab
    l1a = permute(l1a,[2,1]); l1b = permute(l1b,[2,1]); 
    l2a = permute(l2a,[3,4,1,2]); l2b = permute(l2b,[3,4,1,2]);   

    % Errors in disconnected piece...
    DC1 =   einsum_kg(l1a,H2B.oovv,'ia,jkbc->ijkabc')...
           -einsum_kg(l1a,H2B.oovv,'ja,ikbc->ijkabc')...
           -einsum_kg(l1a,H2B.oovv,'ib,jkac->ijkabc')...
           +einsum_kg(l1a,H2B.oovv,'jb,ikac->ijkabc')...
           +einsum_kg(l1b,H2A.oovv,'kc,ijab->ijkabc');

    DC2 =  einsum_kg(l2b,H1A.ov,'jkbc,ia->ijkabc')...
          -einsum_kg(l2b,H1A.ov,'ikbc,ja->ijkabc')...
          -einsum_kg(l2b,H1A.ov,'jkac,ib->ijkabc')...
          +einsum_kg(l2b,H1A.ov,'ikac,jb->ijkabc')...
          +einsum_kg(l2a,H1B.ov,'ijab,kc->ijkabc');


    % these are fine
    D1 =    einsum_kg(H2B.vovv,l2a,'ekbc,ijae->ijkabc')...
           -einsum_kg(H2B.vovv,l2a,'ekac,ijbe->ijkabc')...
           +einsum_kg(H2A.vovv,l2b,'eiba,jkec->ijkabc')...
           -einsum_kg(H2A.vovv,l2b,'ejba,ikec->ijkabc')...
           +einsum_kg(H2B.ovvv,l2b,'ieac,jkbe->ijkabc')...
           -einsum_kg(H2B.ovvv,l2b,'jeac,ikbe->ijkabc')...
           -einsum_kg(H2B.ovvv,l2b,'iebc,jkae->ijkabc')...
           +einsum_kg(H2B.ovvv,l2b,'jebc,ikae->ijkabc');

    D2 =   einsum_kg(H2B.ooov,l2a,'jkmc,imab->ijkabc')...
          -einsum_kg(H2B.ooov,l2a,'ikmc,jmab->ijkabc')...
          +einsum_kg(H2A.oovo,l2b,'ijam,mkbc->ijkabc')...
          -einsum_kg(H2A.oovo,l2b,'ijbm,mkac->ijkabc')...
          +einsum_kg(H2B.oovo,l2b,'ikam,jmbc->ijkabc')...
          -einsum_kg(H2B.oovo,l2b,'jkam,imbc->ijkabc')...
          -einsum_kg(H2B.oovo,l2b,'ikbm,jmac->ijkabc')...
          +einsum_kg(H2B.oovo,l2b,'jkbm,imac->ijkabc');

    L3B = DC1 + DC2 + D1 - D2;

    fprintf(' finished in %4.2f s\n',toc)
end
