function [MM23C] = build_MM23C(cc_t,HBar_t,sys)

    fprintf('MMCC(2,3)C construction... ')
    
    tic

    h_abie = HBar_t.H2B.vvov;
    h_amij = HBar_t.H2B.vooo;
    h_bcek = HBar_t.H2C.vvvo;
    h_mcjk = HBar_t.H2C.ovoo;
    h_abej = HBar_t.H2B.vvvo;
    h_mbij = HBar_t.H2B.ovoo;
    
    h1A_me = HBar_t.H1A.ov;
    h1B_me = HBar_t.H1B.ov;
    
    t2b = cc_t.t2b; t2c = cc_t.t2c;
    
    I1 = h_amij + einsum_kg(h1B_me,t2b,'me,aeij->amij');
    I2 = h_mcjk + einsum_kg(h1B_me,t2c,'me,ecjk->mcjk');
    I3 = h_mbij + einsum_kg(h1A_me,t2b,'me,ebij->mbij');
    
    MM23C = einsum_kg(h_abie,t2c,'abie,ecjk->abcijk')...
            - einsum_kg(h_abie,t2c,'acie,ebjk->abcijk')...
            - einsum_kg(I1,t2c,'amij,bcmk->abcijk')...
            + einsum_kg(I1,t2c,'amik,bcmj->abcijk');
        
    MM23C = MM23C...
            + einsum_kg(h_bcek,t2b,'bcek,aeij->abcijk')...
            - einsum_kg(h_bcek,t2b,'bcej,aeik->abcijk')...
            - einsum_kg(I2,t2b,'mcjk,abim->abcijk')...
            + einsum_kg(I2,t2b,'mbjk,acim->abcijk');
        
    MM23C = MM23C...
            + einsum_kg(h_abej,t2b,'abej,ecik->abcijk')...
            - einsum_kg(h_abej,t2b,'acej,ebik->abcijk')...
            - einsum_kg(h_abej,t2b,'abek,ecij->abcijk')...
            + einsum_kg(h_abej,t2b,'acek,ebij->abcijk')...
            - einsum_kg(I3,t2b,'mbij,acmk->abcijk')...
            + einsum_kg(I3,t2b,'mcij,abmk->abcijk')...
            + einsum_kg(I3,t2b,'mbik,acmj->abcijk')...
            - einsum_kg(I3,t2b,'mcik,abmj->abcijk');
    
    fprintf(' finished in %4.2f s\n',toc)
end

